import Link from "next/link";
import { DiscoverySummary } from "@/components/techint/discovery-summary";
import { NodeGlobalView } from "@/components/techint/node-global-view";
import { globalRangeSchema } from "@/lib/baykush-node/range";
import { getNodeChanges,getNodeComparisons,getNodeDiscoverySummary,getNodeMeasurements,getNodeRoutingMeasurements,getNodeRoutingStatus,getNodeSourceStatus } from "@/lib/baykush-node/queries";
import { requireUser } from "@/lib/auth";

function latestGeneratedAt(...values:(string|undefined)[]){return values.filter((value):value is string=>Boolean(value)).sort().at(-1)??new Date().toISOString();}

export default async function Page({searchParams}:{searchParams:Promise<{range?:string}>}){await requireUser();const query=await searchParams;const range=globalRangeSchema.catch('24h').parse(query.range);const [status,measurements,routingMeasurements,changes,comparisons,routingStatus,discovery]=await Promise.allSettled([getNodeSourceStatus(range),getNodeMeasurements(range),getNodeRoutingMeasurements(range),getNodeChanges(range),getNodeComparisons(range),getNodeRoutingStatus(),getNodeDiscoverySummary(range)]);if(status.status==='rejected'&&measurements.status==='rejected')return <section className="space-y-5"><header className="citem-page-header"><div><p className="citem-eyebrow">BAYKUSH Intelligence Node</p><h1 className="citem-title">Global View unavailable</h1><p className="citem-subtitle">The Node cannot be reached safely. Private CİTEM investigations and evidence remain available; legacy collection stays paused.</p></div></header><RangeLinks range={range}/></section>;const series=measurements.status==='fulfilled'?measurements.value.data:[];const routingSeries=routingMeasurements.status==='fulfilled'?routingMeasurements.value.data:[];return <><RangeLinks range={range}/><NodeGlobalView generatedAt={latestGeneratedAt(measurements.status==='fulfilled'?measurements.value.generatedAt:undefined,routingMeasurements.status==='fulfilled'?routingMeasurements.value.generatedAt:undefined,status.status==='fulfilled'?status.value.generatedAt:undefined)} range={range} sources={status.status==='fulfilled'?status.value.data:[]} comparisons={comparisons.status==='fulfilled'?comparisons.value:[]} vulnerability={series.filter(item=>item.measurement.measurementKey.startsWith('vulnerability.')||item.measurement.measurementKey.startsWith('exploitation.'))} malwareIoc={series.filter(item=>item.measurement.measurementKey.startsWith('ioc.')||item.measurement.measurementKey.startsWith('malware.'))} routing={routingSeries} routingStatus={routingStatus.status==='fulfilled'?routingStatus.value.data:undefined} routingStatusUnavailable={routingStatus.status==='rejected'} routingMeasurementsUnavailable={routingMeasurements.status==='rejected'}/><DiscoverySummary range={range} data={discovery.status==='fulfilled'?discovery.value.data:undefined} unavailable={discovery.status==='rejected'}/><section className="card panel-corners mt-5"><div className="flex justify-between"><h2 className="citem-section-title">What changed</h2><Link href={`/techint/global/changes?range=${range}`} className="text-sm text-amber-300">Full feed</Link></div>{changes.status==='rejected'?<p className="mt-3 text-sm text-stone-500">Change feed unavailable; measurements remain visible.</p>:<ul className="mt-3 space-y-2 text-sm text-stone-400">{changes.value.data.slice(0,10).map((item,index)=><li key={item.fact_revision_id??index}>{item.measurement_key??item.measurementKey??'Factual source change'} · {item.event_time??item.event_date??'time unavailable'}</li>)}</ul>}</section></>}
function RangeLinks({range}:{range:'24h'|'7d'|'30d'}){return <nav className="mb-4 flex gap-2" aria-label="Global history range">{(['24h','7d','30d'] as const).map(value=><Link key={value} href={`/techint/global?range=${value}`} className={value===range?'citem-button':'citem-button-ghost'}>{value.toUpperCase()}</Link>)}</nav>}
