"use client";

import { useActionState, useState, useTransition } from "react";
import { archiveResearchFeed, createResearchFeed, fetchResearchFeedNow, restoreResearchFeed, setResearchFeedEnabled, updateResearchFeed, type FeedActionState } from "@/app/projects/[id]/research-feed-actions";

type Feed = { id:string;name:string;description:string;configured_url:string;display_url:string;enabled:boolean;archived_at:string|null;detected_feed_type:string;health_status:string;consecutive_failures:number;last_checked_at:string|null;last_success_at:string|null;last_error_message:string|null;research_feed_item_observations?:Array<{count:number}> };
type Run = { id:string;feed_source_id:string;status:string;http_status:number|null;items_seen:number;items_changed?:number;completed_at:string|null };
type Item = { id:string;feed_source_id:string;title:string|null;published_at:string|null;first_seen_at:string;last_seen_at:string;canonical_url:string|null };

export function ResearchFeedsWorkspace({projectId,feeds,runs,items}:{projectId:string;feeds:Feed[];runs:Run[];items:Item[]}) {
  const [state,action,pending]=useActionState(createResearchFeed.bind(null,projectId),{} as FeedActionState);
  const [busy,start]=useTransition();const [editing,setEditing]=useState<string|null>(null);
  return <div className="mt-6 space-y-6"><header><h2 className="text-2xl font-semibold text-white">Research Feeds</h2><p className="text-sm text-slate-400">External collected material is untrusted and never becomes Evidence or an analytical Source automatically.</p></header>
    <form action={action} className="card grid gap-3 md:grid-cols-2"><input name="name" required maxLength={240} placeholder="Feed name"/><input name="configured_url" required maxLength={4096} placeholder="https://example.org/feed.xml"/><textarea name="description" maxLength={10000} placeholder="Description"/><label><input type="checkbox" name="enabled" defaultChecked/> Enabled</label><button disabled={pending} className="button">{pending?"Creating…":"Create feed"}</button>{(state.error||state.success)&&<p>{state.error??state.success}</p>}</form>
    <div className="space-y-4">{feeds.map(feed=><article className="card" key={feed.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold text-white">{feed.name}</h3><p className="text-sm text-slate-400">{feed.display_url}</p><p className="text-sm">{feed.archived_at?"Archived":feed.enabled?"Enabled":"Paused"} · {feed.detected_feed_type} · {feed.health_status} · failures {feed.consecutive_failures}</p><p className="text-xs text-slate-400">Checked {feed.last_checked_at??"never"}; successful {feed.last_success_at??"never"}; {feed.research_feed_item_observations?.[0]?.count??0} items</p>{feed.last_error_message&&<p className="text-sm text-red-300">{feed.last_error_message}</p>}</div>
      <div className="flex gap-2">{feed.archived_at?<button className="button" disabled={busy} onClick={()=>start(async()=>{await restoreResearchFeed(projectId,feed.id)})}>Restore</button>:<><button className="button" disabled={busy||!feed.enabled} onClick={()=>start(async()=>{await fetchResearchFeedNow(projectId,feed.id)})}>{busy?"Working…":"Fetch now"}</button><button className="button" disabled={busy} onClick={()=>start(async()=>{await setResearchFeedEnabled(projectId,feed.id,!feed.enabled)})}>{feed.enabled?"Pause":"Enable"}</button><button className="button" onClick={()=>setEditing(editing===feed.id?null:feed.id)}>Edit</button><button className="button" disabled={busy} onClick={()=>start(async()=>{await archiveResearchFeed(projectId,feed.id)})}>Archive</button></>}</div></div>
      {editing===feed.id&&!feed.archived_at&&<Edit projectId={projectId} feed={feed}/>}<details className="mt-3"><summary>Recent runs and normalized items</summary><ul>{runs.filter(run=>run.feed_source_id===feed.id).map(run=><li key={run.id}>{run.status} · {run.http_status??"—"} · {run.items_seen} seen · {run.items_changed??0} changed · {run.completed_at??"running"}</li>)}</ul><ul>{items.filter(item=>item.feed_source_id===feed.id).map(item=><li key={item.id}>{item.title??"Untitled"} · {item.published_at??"date unknown"} · first {item.first_seen_at} · last {item.last_seen_at}{item.canonical_url&&<> · <a rel="noreferrer" target="_blank" href={item.canonical_url}>Open item</a></>}</li>)}</ul></details></article>)}</div></div>;
}
function Edit({projectId,feed}:{projectId:string;feed:Feed}){const [state,action,pending]=useActionState(updateResearchFeed.bind(null,projectId,feed.id),{} as FeedActionState);return <form action={action} className="mt-3 grid gap-2"><input name="name" defaultValue={feed.name}/><input name="configured_url" defaultValue={feed.configured_url}/><textarea name="description" defaultValue={feed.description}/><label><input name="enabled" type="checkbox" defaultChecked={feed.enabled}/> Enabled</label><button className="button" disabled={pending}>Save</button>{(state.error||state.success)&&<p>{state.error??state.success}</p>}</form>}
