"use client";
import Link from "next/link";
import { useState } from "react";
import { addReportReference,unlinkReportReference } from "@/app/projects/[id]/reports/version-actions";
import { buildReferencePath,compareReference,referenceTypes } from "@/lib/reports/versioning";
type Row=Record<string,unknown>; type Candidates=Record<string,Row[]>;
const targetColumns:Record<string,string>={SOURCE:"source_id",EVIDENCE:"evidence_id",INDICATOR:"indicator_id",ENRICHMENT_RESULT:"enrichment_result_id",INFRASTRUCTURE_CLUSTER:"infrastructure_cluster_id",TIMELINE_EVENT:"timeline_event_id",CAMPAIGN:"campaign_id",THREAT_ACTOR:"threat_actor_id",MALWARE:"malware_id",CVE:"cve_id",MITRE_TECHNIQUE:"mitre_technique_id",ATTRIBUTION_HYPOTHESIS:"attribution_hypothesis_id",ATTRIBUTION_ASSESSMENT:"attribution_assessment_id"};
function targetId(r:Row){return String(r[targetColumns[String(r.reference_type)]]??"");}
export function AnalyticalReferences({projectId,reportId,references,snapshots,candidates}:{projectId:string;reportId:string;references:Row[];snapshots:Row[];candidates:Candidates}){
 const [message,setMessage]=useState(""); const act=(p:Promise<{error?:string;success?:string}>)=>p.then(x=>setMessage(x.error??x.success??""));
 const current=new Map(references.map(r=>[`${r.reference_type}:${targetId(r)}`,r])); const frozen=new Map(snapshots.map(r=>[`${r.reference_type}:${targetId(r)}`,r]));
 const status=(r:Row)=>{const key=`${r.reference_type}:${targetId(r)}`,snap=frozen.get(key),live=(candidates[String(r.reference_type)]??[]).find(x=>String(x.id)===targetId(r));return compareReference(snap,live);};
 return <section className="card"><h2 className="text-xl font-semibold">Analytical references</h2><p className="text-sm text-slate-400">Selectors contain only records from this Investigation. Labels, state, and timestamps are resolved by PostgreSQL; Source links remain internal.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{referenceTypes.map(type=><form className="rounded border border-slate-700 p-3" key={type} action={fd=>act(addReportReference(projectId,reportId,{},fd))}><input type="hidden" name="referenceType" value={type}/><label className="text-sm">{type.replaceAll("_"," ")}<select required className="field mt-1" name="targetId" defaultValue=""><option value="" disabled>Select a record</option>{(candidates[type]??[]).map(x=><option key={String(x.id)} value={String(x.id)}>{String(x.label)}</option>)}</select></label><button className="mt-2 rounded border border-cyan-500 px-3 py-1 text-sm">Add reference</button></form>)}</div><div className="mt-5 space-y-2">{references.map(r=>{const type=String(r.reference_type) as (typeof referenceTypes)[number],live=(candidates[type]??[]).find(x=>String(x.id)===targetId(r)),path=buildReferencePath(projectId,type,targetId(r),live?.routeContext as {indicatorId?:string;campaignId?:string}|undefined);return <div className="flex flex-wrap items-center justify-between gap-2 rounded border border-slate-700 p-3" key={String(r.id)}><div>{path?<Link className="text-cyan-300" href={path}>{type} · {String(r.label)}</Link>:<span>{type} · {String(r.label)} (internal destination unavailable)</span>}<p className="text-xs text-slate-400">{status(r)} · updated {String(r.source_updated_at)}</p></div><button type="button" className="rounded border border-red-700 px-3 py-1 text-sm" onClick={()=>act(unlinkReportReference(projectId,reportId,String(r.id)))}>Unlink</button></div>})}{snapshots.filter(s=>!current.has(`${s.reference_type}:${targetId(s)}`)).map(s=><div className="rounded border border-slate-700 p-3" key={String(s.id)}>{String(s.reference_type)} · {String(s.label_snapshot)}<p className="text-xs text-slate-400">REMOVED_FROM_CURRENT_DRAFT</p></div>)}</div><p aria-live="polite" className="mt-2 text-sm text-cyan-200">{message}</p></section>;
}
