import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { TimelineEdit } from "@/components/workspace-forms";
import { EntityLinkForm, EventMembershipForm, SupportLinkForm } from "@/components/reconstruction/forms";
type Row=Record<string,unknown>; const s=(v:unknown)=>String(v??"");
export default async function TimelineEventPage({params}:{params:Promise<{id:string;eventId:string}>}){const{id,eventId}=await params;const c=await requireUser();const project=await c.supabase.from("projects").select("id,owner_id").eq("id",id).maybeSingle();if(!project.data||project.data.owner_id!==c.user.id)notFound();const event=await c.supabase.from("timeline_events").select("*").eq("project_id",id).eq("id",eventId).maybeSingle();if(!event.data)notFound();const [members,entities,support,campaigns,indicators,clusters,malware,cves,mitre,sources,evidence,enrichment]=await Promise.all([
c.supabase.from("campaign_timeline_events").select("*,campaigns(name)").eq("project_id",id).eq("timeline_event_id",eventId),c.supabase.from("timeline_event_entities").select("*").eq("project_id",id).eq("timeline_event_id",eventId),c.supabase.from("timeline_event_support").select("*").eq("project_id",id).eq("timeline_event_id",eventId),c.supabase.from("campaigns").select("id,name").eq("project_id",id),c.supabase.from("indicators").select("id,value").eq("project_id",id),c.supabase.from("infrastructure_clusters").select("id,name").eq("project_id",id),c.supabase.from("malware").select("id,name").eq("project_id",id),c.supabase.from("cves").select("id,cve_id").eq("project_id",id),c.supabase.from("mitre_techniques").select("id,technique_id").eq("project_id",id),c.supabase.from("sources").select("id,title").eq("project_id",id),c.supabase.from("evidence").select("id,title").eq("project_id",id),c.supabase.from("enrichment_results").select("id,category,queried_at").eq("project_id",id)]);
return <main className="space-y-5"><Link className="text-cyan-200" href={`/projects/${id}?tab=timeline`}>← Timeline</Link><section className="card"><p className="citem-label">Structured attack event</p><h1 className="text-2xl font-semibold">{s(event.data.event_name)}</h1><div className="mt-2 flex gap-2"><span className="citem-badge">{s(event.data.basis)}</span><span className="citem-badge">{s(event.data.activity_phase)}</span><span className="citem-badge">{s(event.data.assessment_status)}</span><span className="citem-badge">{s(event.data.confidence)}</span></div><p className="mt-3">Observed means supported by directly recorded material. Inferred means analyst judgement derived from other observations; it does not mean false.</p><TimelineEdit projectId={id} event={event.data as Row}/></section>
<section className="card"><h2 className="text-lg font-semibold">Campaign Membership</h2><ul className="mt-3">{(members.data??[]).map((x:Row)=><li key={s(x.id)}>{s((x.campaigns as Row)?.name)} — <strong>{s(x.status)}</strong> / {s(x.confidence)} — {s(x.rationale)} <Link className="text-cyan-200" href={`/projects/${id}/campaigns/${s(x.campaign_id)}`}>Open Campaign</Link></li>)}</ul><EventMembershipForm projectId={id} eventId={eventId} campaigns={(campaigns.data??[]) as Row[]}/></section>
<section className="card"><h2 className="text-lg font-semibold">Technical Entities</h2><p className="text-sm text-stone-500">Only existing same-Investigation records can be linked. Threat Actors are intentionally excluded.</p><ul>{(entities.data??[]).map((x:Row)=><li key={s(x.id)}>{s(x.role)} — {s(x.indicator_id||x.infrastructure_cluster_id||x.malware_id||x.cve_id||x.mitre_technique_id)} — {s(x.analyst_note)}</li>)}</ul><EntityLinkForm projectId={id} eventId={eventId} options={{indicator:(indicators.data??[]) as Row[],infrastructure_cluster:(clusters.data??[]) as Row[],malware:(malware.data??[]) as Row[],cve:(cves.data??[]) as Row[],mitre_technique:(mitre.data??[]) as Row[]}}/></section>
<section className="card"><h2 className="text-lg font-semibold">Supporting Material</h2><p className="text-sm text-stone-500">Sources open only through internal records; CİTEM never visits their external URLs.</p><ul>{(support.data??[]).map((x:Row)=><li key={s(x.id)}>{x.source_id?"Source":x.evidence_id?"Evidence":"Enrichment"} — {s(x.source_id||x.evidence_id||x.enrichment_result_id)} — {s(x.analyst_note)}</li>)}</ul><SupportLinkForm projectId={id} eventId={eventId} options={{source:(sources.data??[]) as Row[],evidence:(evidence.data??[]) as Row[],enrichment_result:(enrichment.data??[]) as Row[]}}/></section>
<section className="card"><h2 className="text-lg font-semibold">Assessment prompts</h2><p>What happened? What was observed or inferred? Which technical elements participated? What supports the event? What remains uncertain? Which Campaign may it belong to, and how does it change the reconstruction?</p></section></main>}
