"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { acceptIocCandidate, changeIocConnectionState, connectThreatFox, disconnectThreatFox, ensureSyntheticIocConnection, saveThreatFoxSettings, syncIocProviderConnection, triageIocCandidate, type IocActionResult } from "@/app/osint/ioc-actions";
import { defangCandidate } from "@/lib/ioc-connectors/normalize";
import type { IocInboxFilters } from "@/lib/ioc-connectors/schema";
import type { IocCandidateType } from "@/lib/ioc-connectors/types";

export type IocCandidateRow = { id: string; candidate_type: IocCandidateType; normalized_value: string; network_port: number | null; status: string; first_seen_at: string | null; last_seen_at: string | null; highest_confidence: number | null; provider_count: number; source_count: number; latest_provider: string | null; threat_types: string[]; malware_families: string[]; tags: string[]; acceptance_count: number; sort_value: string };
export type IocConnection = { id: string; provider_key: string; display_name: string; enabled: boolean; scheduler_enabled: boolean; sync_interval_minutes:number; next_scheduled_sync_at:string|null; health_status: string; last_checked_at: string | null; last_success_at: string | null; last_error_message: string | null; archived_at: string | null };
export type IocSourceRow = { id: string; provider_display_name: string; provider_item_id: string; original_value: string; provider_reference_url: string | null; threat_type: string | null; malware_family: string | null; confidence_score: number | null; provider_first_seen: string | null; provider_last_seen: string | null; first_observed_at: string; last_observed_at: string; observation_count: number; tags: string[]; metadata_summary: Record<string, unknown> };
type Project = { id: string; name: string };
type Run = { id: string; provider_connection_id: string; status: string; trigger_type: string; started_at: string; completed_at: string | null; candidate_count: number; source_observation_count: number; created_count: number; updated_count: number; skipped_count: number; deduplicated_count: number; error_message: string | null };

export function IocInbox({ rows, projects, connections, runs, sources, filters, nextHref, syntheticEnabled }: { rows: IocCandidateRow[]; projects: Project[]; connections: IocConnection[]; runs: Run[]; sources: Record<string, IocSourceRow[]>; filters: IocInboxFilters; nextHref: string | null; syntheticEnabled: boolean }) {
  const router = useRouter();
  const [selected, setSelected] = useState<IocCandidateRow | null>(null);
  const [notice, setNotice] = useState<IocActionResult>({});
  const [pending, startTransition] = useTransition();
  const run = (work: () => Promise<IocActionResult>) => startTransition(async () => { const result = await work(); setNotice(result); router.refresh(); });
  const synthetic = connections.find(connection => connection.provider_key === "TEST_SYNTHETIC");
  const threatfox = connections.find(connection => connection.provider_key === "THREATFOX");
  const latestRun = synthetic ? runs.find(item => item.provider_connection_id === synthetic.id) : undefined;

  return <section className="space-y-4">
    <header className="card"><h1 className="text-2xl font-bold">IOC Inbox</h1><p className="text-sm text-slate-400">Provider claims remain untrusted candidates until explicitly accepted into an Investigation.</p>
      <div className="mt-3 space-y-3 rounded border border-cyan-500/50 p-3"><strong>ThreatFox Community API</strong><p className="text-sm text-slate-300" role="note">Automatic provider synchronization is not enabled in this deployment. Use Sync now to check for new observations.</p><p className="text-sm">IOC data is supplied by an external community provider. Provider confidence is not CİTEM’s analytical judgement; accepting a candidate remains an explicit analyst action.</p><a className="text-cyan-300 underline" href="https://threatfox.abuse.ch/api/" target="_blank" rel="noopener noreferrer">Provider terms and fair-use information</a>
      {!threatfox?<form action={form=>run(()=>connectThreatFox(form))} className="grid gap-2 md:grid-cols-4"><input type="password" autoComplete="off" name="auth_key" maxLength={512} required placeholder="Auth-Key"/><input type="number" name="lookback_days" min="1" max="7" defaultValue="1"/><input type="number" name="sync_interval_minutes" min="30" max="1440" defaultValue="60"/><label><input type="checkbox" name="scheduler_enabled"/> Enable scheduled sync</label><button disabled={pending} className="button">{pending?"Testing credential…":"Test and connect"}</button></form>:<><div className="grid gap-1 text-sm"><span>{threatfox.enabled?"Credential configured":"Credential missing"}</span><span>Connection health: {threatfox.health_status}</span><span>Last tested: {threatfox.last_checked_at??"Never"}</span><span>Last successful sync: {threatfox.last_success_at??"Never"}</span><span>Next scheduled sync: {threatfox.next_scheduled_sync_at??"Paused"}</span>{threatfox.last_error_message&&<span className="text-red-300">{threatfox.last_error_message}</span>}</div>{threatfox.enabled?<><form action={form=>run(()=>saveThreatFoxSettings(threatfox.id,form))} className="flex flex-wrap gap-2"><input type="number" name="lookback_days" min="1" max="7" defaultValue="1" aria-label="ThreatFox lookback days"/><input type="number" name="sync_interval_minutes" min="30" max="1440" defaultValue={threatfox.sync_interval_minutes}/><label><input type="checkbox" name="scheduler_enabled" defaultChecked={threatfox.scheduler_enabled}/> Scheduled</label><button className="button">Save settings</button></form><div className="flex flex-wrap gap-2"><button disabled={pending} className="button" onClick={()=>run(()=>syncIocProviderConnection(threatfox.id))}>Sync now</button><button disabled={pending} className="button" onClick={()=>run(()=>changeIocConnectionState(threatfox.id,!threatfox.enabled))}>Pause connection</button><button disabled={pending} className="button" onClick={()=>run(()=>disconnectThreatFox(threatfox.id))}>Disconnect credential</button></div><details><summary>Rotate Auth-Key</summary><form action={form=>run(()=>connectThreatFox(form))} className="grid gap-2 md:grid-cols-4"><input type="password" autoComplete="off" name="auth_key" maxLength={512} required placeholder="New Auth-Key"/><input type="number" name="lookback_days" min="1" max="7" defaultValue="1"/><input type="number" name="sync_interval_minutes" min="30" max="1440" defaultValue={threatfox.sync_interval_minutes}/><button className="button">Test and rotate</button></form></details></>:<form action={form=>run(()=>connectThreatFox(form))} className="flex gap-2"><input type="password" autoComplete="off" name="auth_key" maxLength={512} required placeholder="Auth-Key"/><input type="hidden" name="lookback_days" value="1"/><input type="hidden" name="sync_interval_minutes" value="60"/><button className="button">Reconnect ThreatFox</button></form>}</>}</div>
      {syntheticEnabled && <div className="mt-3 space-y-3 rounded border border-amber-500/50 p-3"><strong>TEST / SYNTHETIC</strong><p>This result is local and deterministic. It is not live intelligence.</p>
        {!synthetic ? <button disabled={pending} className="button" onClick={() => run(ensureSyntheticIocConnection)}>Enable test provider</button> : <><div className="grid gap-1 text-sm"><span>State: {synthetic.enabled ? "Enabled" : "Paused"}</span><span>Health: {synthetic.health_status}</span><span>Last checked: {synthetic.last_checked_at ?? "Never"}</span><span>Last successful sync: {synthetic.last_success_at ?? "Never"}</span>{synthetic.last_error_message && <span className="text-red-300">Last safe error: {synthetic.last_error_message}</span>}{latestRun && <span>Latest {latestRun.trigger_type} run: {latestRun.status} · {latestRun.candidate_count} candidates · {latestRun.deduplicated_count} deduplicated · {latestRun.skipped_count} skipped</span>}</div><div className="flex gap-2"><button disabled={pending || !synthetic.enabled} className="button" onClick={() => run(() => syncIocProviderConnection(synthetic.id))}>{pending ? "Synchronizing…" : "Sync test provider now"}</button><button disabled={pending} className="button" onClick={() => run(() => changeIocConnectionState(synthetic.id, !synthetic.enabled))}>{synthetic.enabled ? "Pause test provider" : "Enable test provider"}</button></div></>}
      </div>}
    </header>
    {notice.error && <p role="alert" className="card text-red-300">{notice.error}</p>}{notice.success && <p role="status" className="card text-emerald-300">{notice.success}</p>}
    <form className="card grid gap-2 md:grid-cols-4"><input type="hidden" name="view" value="iocs"/><input name="ioc_q" defaultValue={filters.ioc_q} maxLength={200} placeholder="Search IOC candidates" aria-label="Search IOC candidates"/><select name="ioc_status" defaultValue={filters.ioc_status} aria-label="Status"><option value="">All statuses</option>{["NEW","REVIEWED","ACCEPTED","DISMISSED","EXPIRED"].map(value => <option key={value}>{value}</option>)}</select><select name="ioc_type" defaultValue={filters.ioc_type} aria-label="Type"><option value="">All types</option>{["IPV4","IPV6","CIDR","DOMAIN","HOSTNAME","URL","MD5","SHA1","SHA256","CVE"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Provider" name="ioc_provider" defaultValue={filters.ioc_provider}><option value="">All providers</option>{connections.map(connection => <option value={connection.id} key={connection.id}>{connection.display_name}</option>)}</select><select aria-label="Sort" name="ioc_sort" defaultValue={filters.ioc_sort}><option value="last">Last observed</option><option value="first">First observed</option><option value="confidence">Confidence</option></select><input name="ioc_min_confidence" defaultValue={filters.ioc_min_confidence} type="number" min="0" max="100" placeholder="Minimum confidence"/><input name="ioc_max_confidence" defaultValue={filters.ioc_max_confidence} type="number" min="0" max="100" placeholder="Maximum confidence"/><select name="ioc_port" defaultValue={filters.ioc_port} aria-label="Port"><option value="">Any port state</option><option value="present">Port present</option><option value="absent">No port</option></select><select name="ioc_project" defaultValue={filters.ioc_project} aria-label="Accepted Investigation"><option value="">Any acceptance</option>{projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select><button className="button">Apply filters</button></form>
    <p>{rows.length} results on this page</p>
    <div className="space-y-3">{rows.map(row => <article className="card space-y-2" key={row.id}><button className="text-left font-mono text-cyan-200" onClick={() => setSelected(row)}>{defangCandidate(row.candidate_type,row.normalized_value)}{row.network_port ? ` : ${row.network_port}` : ""}</button><div className="flex flex-wrap gap-2 text-xs"><span>{row.candidate_type}</span><span>{row.status}</span><span>Confidence {row.highest_confidence ?? "—"}</span><span>{row.provider_count} provider(s)</span><span>{row.source_count} source(s)</span><span>{row.acceptance_count} Investigation(s)</span></div><p className="text-xs text-slate-400">Latest: {row.latest_provider ?? "Unknown"} · First seen: {row.first_seen_at ?? "Unknown"} · Last seen: {row.last_seen_at ?? "Unknown"}</p><p>{row.threat_types?.join(" · ")} {row.malware_families?.join(" · ")}</p><div>{row.tags?.map(tag => <span key={tag} className="mr-2 text-xs text-cyan-300">#{tag}</span>)}</div></article>)}{!rows.length && <div className="card">No IOC candidates match these filters.</div>}</div>
    {nextHref && <Link className="button inline-block" href={nextHref}>Load more</Link>}
    {selected && <div className="fixed inset-0 z-50 bg-black/60"><aside role="dialog" aria-modal="true" aria-labelledby="ioc-detail-title" className="ml-auto h-full max-w-xl overflow-y-auto bg-slate-950 p-6"><button className="button float-right" onClick={() => setSelected(null)}>Close</button><h2 id="ioc-detail-title" className="text-xl font-bold">Candidate detail</h2><p className="mt-6 font-mono">{defangCandidate(selected.candidate_type,selected.normalized_value)}</p><div className="my-3 flex gap-2"><button className="button" onClick={() => navigator.clipboard.writeText(defangCandidate(selected.candidate_type,selected.normalized_value))}>Copy defanged</button><button className="button" onClick={() => navigator.clipboard.writeText(selected.normalized_value)}>Copy canonical</button></div><h3 className="font-semibold">Provider observations</h3><div className="space-y-3">{(sources[selected.id] ?? []).map(source => <article className="card text-sm" key={source.id}><strong>{source.provider_display_name}</strong><p>Provider item: {source.provider_item_id}</p><p>Original observation: <span className="font-mono">{defangCandidate(selected.candidate_type,source.original_value)}</span></p><p>Threat type: {source.threat_type ?? "—"} · Malware family: {source.malware_family ?? "—"}</p><p>Confidence: {source.confidence_score ?? "—"} · Observations: {source.observation_count}</p><p>Provider seen: {source.provider_first_seen ?? "—"} → {source.provider_last_seen ?? "—"}</p><p>CİTEM observed: {source.first_observed_at} → {source.last_observed_at}</p><p>{source.tags.map(tag => `#${tag}`).join(" ")}</p>{source.provider_reference_url && <a className="button mt-2 inline-block" href={source.provider_reference_url} target="_blank" rel="noopener noreferrer">Open provider reference</a>}</article>)}</div><div className="my-4 flex gap-2"><button disabled={pending} className="button" onClick={() => run(() => triageIocCandidate(selected.id,"REVIEW"))}>Mark reviewed</button><button disabled={pending} className="button" onClick={() => run(() => triageIocCandidate(selected.id,"DISMISS"))}>Dismiss</button><button disabled={pending} className="button" onClick={() => run(() => triageIocCandidate(selected.id,"RESTORE"))}>Restore</button></div><form action={form => run(() => acceptIocCandidate(selected.id,form))} className="space-y-3"><h3>Accept to Investigation</h3><select name="project_id" required><option value="">Choose an owned Investigation</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select>{selected.candidate_type === "CVE" && <select name="severity" required><option value="">Confirm severity</option>{["LOW","MEDIUM","HIGH","CRITICAL"].map(value => <option key={value}>{value}</option>)}</select>}<textarea name="note" maxLength={5000} placeholder="Analyst note"/><button disabled={pending} className="button">Accept explicitly</button></form></aside></div>}
  </section>;
}
