import {act,render,screen} from "@testing-library/react";
import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {IocInboxPoller} from "./ioc-inbox-poller";
const refresh=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({refresh})}));
const visible=(value:"visible"|"hidden")=>Object.defineProperty(document,"visibilityState",{configurable:true,value});
const online=(value:boolean)=>Object.defineProperty(navigator,"onLine",{configurable:true,value});
describe("IOC Inbox bounded polling",()=>{beforeEach(()=>{vi.useFakeTimers();refresh.mockReset();visible("visible");online(true);global.fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({token:"same",new_count:2})}) as never;});afterEach(()=>{vi.useRealTimers();vi.restoreAllMocks()});
 it("does not poll while hidden",async()=>{visible("hidden");render(<IocInboxPoller initialToken="same" initialNewCount={2}/>);await act(()=>vi.advanceTimersByTimeAsync(46_000));expect(fetch).not.toHaveBeenCalled();});
 it("resumes when visible and pauses offline",async()=>{visible("hidden");render(<IocInboxPoller initialToken="same" initialNewCount={2}/>);visible("visible");online(false);document.dispatchEvent(new Event("visibilitychange"));expect(fetch).not.toHaveBeenCalled();online(true);window.dispatchEvent(new Event("online"));await act(()=>Promise.resolve());expect(fetch).toHaveBeenCalledOnce();});
 it("does not refresh for an unchanged token",async()=>{render(<IocInboxPoller initialToken="same" initialNewCount={2}/>);await act(()=>vi.advanceTimersByTimeAsync(46_000));expect(refresh).not.toHaveBeenCalled();});
 it("refreshes once and announces a changed token",async()=>{vi.mocked(fetch).mockResolvedValue({ok:true,json:async()=>({token:"next",new_count:9})} as Response);render(<IocInboxPoller initialToken="same" initialNewCount={2}/>);await act(()=>vi.advanceTimersByTimeAsync(46_000));expect(refresh).toHaveBeenCalledOnce();expect(screen.getByRole("status")).toHaveTextContent("7 new IOC observations received");});
 it("cleans up timers and backs off after failures",async()=>{vi.mocked(fetch).mockRejectedValue(new Error("offline"));const {unmount}=render(<IocInboxPoller initialToken="same" initialNewCount={2}/>);await act(()=>vi.advanceTimersByTimeAsync(46_000));expect(fetch).toHaveBeenCalledOnce();await act(()=>vi.advanceTimersByTimeAsync(50_000));expect(fetch).toHaveBeenCalledOnce();unmount();await act(()=>vi.runOnlyPendingTimersAsync());expect(fetch).toHaveBeenCalledOnce();});
});
