import {fireEvent,render,screen,within} from "@testing-library/react";import {afterEach,describe,expect,it,vi} from "vitest";import {IocInbox,type IocCandidateRow,type IocConnection,type IocSourceRow} from "./ioc-inbox";
const actions=vi.hoisted(()=>({connectOtx:vi.fn(),disconnectOtx:vi.fn(),saveOtxSettings:vi.fn(),sync:vi.fn()}));
vi.mock("next/navigation",()=>({useRouter:()=>({refresh:vi.fn()})}));vi.mock("@/app/osint/ioc-actions",()=>({acceptIocCandidate:vi.fn(),changeIocConnectionState:vi.fn(),connectOtx:actions.connectOtx,connectThreatFox:vi.fn(),disconnectOtx:actions.disconnectOtx,disconnectThreatFox:vi.fn(),ensureSyntheticIocConnection:vi.fn(),saveOtxSettings:actions.saveOtxSettings,saveThreatFoxSettings:vi.fn(),syncIocProviderConnection:actions.sync,triageIocCandidate:vi.fn()}));
const filters={view:"iocs" as const,ioc_q:"",ioc_status:"" as const,ioc_type:"" as const,ioc_provider:"",ioc_sort:"last" as const,ioc_min_confidence:"" as const,ioc_max_confidence:"" as const,ioc_port:"" as const,ioc_project:"",ioc_cursor:""};
const connection=(enabled=true):IocConnection=>({id:"otx",provider_key:"ALIENVAULT_OTX",display_name:"AlienVault OTX",enabled,scheduler_enabled:false,sync_interval_minutes:15,next_scheduled_sync_at:null,health_status:"HEALTHY",last_checked_at:null,last_success_at:null,last_error_message:null,archived_at:null});
const props=(connections:IocConnection[]=[])=>({rows:[] as IocCandidateRow[],projects:[],connections,runs:[],sources:{},filters,nextHref:null,syntheticEnabled:false});
afterEach(()=>{vi.clearAllMocks();vi.restoreAllMocks()});
describe("AlienVault OTX IOC Inbox",()=>{
 it("renders a password connection form with exact look-backs and no scheduler",()=>{render(<IocInbox {...props()}/>);const heading=screen.getByText("AlienVault OTX");const panel=heading.parentElement!;const key=within(panel).getByLabelText("OTX API Key");expect(key).toHaveAttribute("type","password");const select=within(panel).getByLabelText("Bootstrap look-back") as HTMLSelectElement;expect([...select.options].map(o=>o.value)).toEqual(["30","90","180","365"]);expect(select.value).toBe("30");expect(within(panel).getByText(/obsolete or noisy community indicators/)).toBeVisible();expect(within(panel).queryByText(/scheduled/i)).not.toBeInTheDocument();expect(within(panel).getByRole("button",{name:"Test and connect"})).toBeEnabled()});
 it("never starts browser OTX requests or polling",()=>{const fetchSpy=vi.spyOn(globalThis,"fetch"),timeout=vi.spyOn(globalThis,"setTimeout"),interval=vi.spyOn(globalThis,"setInterval");render(<IocInbox {...props()}/>);expect(fetchSpy).not.toHaveBeenCalled();expect(timeout).not.toHaveBeenCalled();expect(interval).not.toHaveBeenCalled();expect(document.body.textContent).not.toMatch(/automatic OTX synchronization is enabled/i)});
 it("configured state does not redisplay a key and exposes manual lifecycle",()=>{render(<IocInbox {...props([connection()])}/>);expect(screen.queryByDisplayValue(/key|secret/i)).not.toBeInTheDocument();expect(screen.getByText("Rotate API key")).toBeVisible();expect(screen.getByRole("button",{name:"Sync now"})).toBeEnabled();expect(screen.getByRole("button",{name:"Disconnect"})).toBeEnabled();expect(screen.getByText(/Disconnect removes only the encrypted credential/)).toBeVisible()});
 it("wires Test and connect",()=>{actions.connectOtx.mockResolvedValue({success:"ok"});render(<IocInbox {...props()}/>);const panel=screen.getByText("AlienVault OTX").parentElement!;fireEvent.submit(within(panel).getByRole("button",{name:"Test and connect"}).closest("form")!);expect(actions.connectOtx).toHaveBeenCalledTimes(1)});
 it("renders two bounded Pulse contexts as plain text with safe links",()=>{const row:IocCandidateRow={id:"candidate",candidate_type:"DOMAIN",normalized_value:"example.com",network_port:null,status:"NEW",first_seen_at:null,last_seen_at:null,highest_confidence:null,provider_count:1,source_count:2,latest_provider:"AlienVault OTX",threat_types:[],malware_families:[],tags:[],acceptance_count:0,sort_value:"x"};const source=(id:string,reference:string):IocSourceRow=>({id,provider_display_name:"AlienVault OTX",provider_item_id:id,original_value:"example.com",provider_reference_url:reference,threat_type:null,malware_family:null,confidence_score:null,provider_first_seen:null,provider_last_seen:null,first_observed_at:"2026-08-01",last_observed_at:"2026-08-01",observation_count:1,tags:[],metadata_summary:{otx_pulse:{id,name:`Pulse ${id}`,description:"<script>alert(1)</script>",author_name:"author",tlp:"amber",created:"2026-08-01",modified:"2026-08-01",tags:[],references:["https://example.com/good","http://example.com/good","javascript:alert(1)","data:text/plain,x","https://u:p@example.com/x","not-url"],targeted_countries:[],industries:[],malware_families:[],attack_ids:[]},otx_indicator:{type:"domain"}}});render(<IocInbox {...props([connection()])} rows={[row]} sources={{candidate:[source("0123456789abcdef01234567","https://otx.alienvault.com/pulse/0123456789abcdef01234567"),source("1123456789abcdef01234567","javascript:alert(1)")]}}/>);fireEvent.click(screen.getByText("example[.]com"));expect(screen.getAllByLabelText("OTX Pulse context")).toHaveLength(2);expect(screen.getAllByText(/TLP: AMBER/)).toHaveLength(2);expect(screen.getAllByText("External community intelligence — analyst validation required.")).toHaveLength(3);expect(screen.getAllByText("<script>alert(1)</script>")).toHaveLength(2);expect(document.querySelector("script")).toBeNull();const links=screen.getAllByRole("link").filter(a=>a.textContent==="External reference");expect(links).toHaveLength(4);for(const link of links){expect(link).toHaveAttribute("target","_blank");expect(link).toHaveAttribute("rel","noopener noreferrer");expect(link.getAttribute("href")).toMatch(/^https?:\/\//)}expect(document.querySelector('a[href^="javascript:"],a[href^="data:"],a[href*="u:p@"]')).toBeNull()});
});
