"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";

type State={read_at:string|null;saved_at:string|null;dismissed_at:string|null};
type Item={id:string;title:string|null;summary_text:string|null;canonical_url:string|null;published_at:string|null;first_seen_at:string;categories:string[];osint_item_states:State[];research_feed_item_observations:Array<{feed_source_id:string;research_feed_sources:{name:string}|Array<{name:string}>}>};
type Feed={id:string;name:string;description:string;enabled:boolean;scheduler_enabled:boolean;fetch_interval_minutes:number;next_scheduled_fetch_at:string|null;detected_feed_type:string;health_status:string;last_checked_at:string|null;last_success_at:string|null;last_error_message:string|null;archived_at:string|null};
type Project={id:string;name:string};
const stamp=(i:Item)=>i.published_at??i.first_seen_at;
function sources(i:Item){return [...new Set(i.research_feed_item_observations.map(o=>Array.isArray(o.research_feed_sources)?o.research_feed_sources[0]?.name:o.research_feed_sources?.name).filter(Boolean))] as string[];}

export function OsintWorkspace({initialItems,feeds,projects,mode,search}:{initialItems:Item[];feeds:Feed[];projects:Project[];mode:string;search:string}){
 const router=useRouter(),settingsButton=useRef<HTMLButtonElement>(null);const [settings,setSettings]=useState(false),[linkItem,setLinkItem]=useState<Item|null>(null);
 useEffect(()=>{if(!settings&&!linkItem)return;const previous=document.activeElement as HTMLElement;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSettings(false);setLinkItem(null)};if(e.key==="Tab"){const root=document.querySelector<HTMLElement>("[role=dialog]");const focus=[...(root?.querySelectorAll<HTMLElement>('button,a,input,select,textarea')??[])].filter(x=>!x.hasAttribute("disabled"));if(!focus.length)return;const first=focus[0],last=focus.at(-1)!;if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",onKey);document.body.style.overflow="hidden";requestAnimationFrame(()=>document.querySelector<HTMLElement>("[role=dialog] button")?.focus());return()=>{document.removeEventListener("keydown",onKey);document.body.style.overflow="";previous?.focus()};},[settings,linkItem]);
 const visible=initialItems.filter(i=>{const s=i.osint_item_states[0];if(mode==="dismissed")return !!s?.dismissed_at;if(s?.dismissed_at)return false;if(mode==="unread")return !s?.read_at;if(mode==="saved")return !!s?.saved_at;return true});
 return <main className="mx-auto max-w-6xl space-y-6"><header className="flex items-center justify-between"><div><p className="eyebrow">GLOBAL COLLECTION</p><h1 className="text-3xl font-bold text-white">OSINT Intelligence Feed</h1><p className="text-sm text-slate-400">Untrusted external material remains separate until you explicitly link it.</p></div><button ref={settingsButton} className="button" onClick={()=>setSettings(true)}>Settings</button></header>
 <form className="card flex flex-wrap gap-3" method="get"><input name="q" defaultValue={search} maxLength={200} aria-label="Search intelligence" placeholder="Search intelligence"/><select name="source" aria-label="Source"><option value="">All sources</option>{feeds.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><input name="from" type="date" aria-label="From date"/><input name="to" type="date" aria-label="To date"/><button className="button">Apply filters</button></form>
 <nav className="flex gap-2" aria-label="Feed mode">{["all","unread","saved","dismissed"].map(m=><Link className={`button ${mode===m?"border-cyan-400 text-cyan-200":""}`} href={`/osint?mode=${m}`} key={m}>{m[0].toUpperCase()+m.slice(1)}</Link>)}</nav>
 <section className="space-y-3" aria-label="Unified intelligence stream">{visible.map(item=>{const state=item.osint_item_states[0],provenance=sources(item);return <article key={item.id} className="card space-y-3"><div className="flex justify-between text-xs text-slate-400"><span>{provenance[0]??"Unknown source"}{provenance.length>1?` · +${provenance.length-1} sources`:""}</span><time dateTime={stamp(item)}>{new Date(stamp(item)).toLocaleString()}</time></div><h2 className="text-lg font-semibold text-white">{item.title??"Untitled intelligence item"}</h2><p className="line-clamp-3 text-sm text-slate-300">{item.summary_text??"No summary supplied by the feed."}</p><div className="text-xs text-cyan-300">{item.categories.slice(0,5).join(" · ")}</div><div className="flex flex-wrap gap-2">{item.canonical_url&&<a className="button" href={item.canonical_url} target="_blank" rel="noopener noreferrer">Open original</a>}<button className="button" aria-label={state?.read_at?"Mark unread":"Mark read"}>{state?.read_at?"Mark unread":"Mark read"}</button><button className="button">{state?.saved_at?"Unsave":"Save"}</button><button className="button">{state?.dismissed_at?"Restore":"Dismiss"}</button><button className="button" onClick={()=>setLinkItem(item)}>Send to Investigation</button></div></article>})}{!visible.length&&<div className="card text-slate-400">No intelligence items match these filters.</div>}</section>
 {settings&&<div className="fixed inset-0 z-50 bg-black/60" onMouseDown={e=>{if(e.target===e.currentTarget)setSettings(false)}}><aside role="dialog" aria-modal="true" aria-label="OSINT feed settings" className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-slate-950 p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-bold">Feed settings</h2><button className="button" onClick={()=>setSettings(false)} aria-label="Close settings">Close</button></div><form className="card mt-5 space-y-3"><h3>Add RSS or Atom feed</h3><input aria-label="Source name" placeholder="Source name"/><textarea aria-label="Description" placeholder="Description"/><input aria-label="Feed URL" type="url" placeholder="https://example.com/feed.xml"/><select aria-label="Automatic fetch interval" defaultValue="15"><option value="15">Every 15 minutes</option><option value="30">Every 30 minutes</option><option value="60">Hourly</option><option value="360">Every 6 hours</option><option value="1440">Daily</option></select><button className="button" type="submit">Add feed</button></form>{feeds.map(f=><section className="card mt-3" key={f.id}><div className="flex justify-between"><strong>{f.name}</strong><span>{f.health_status}</span></div><p className="text-sm text-slate-400">{f.description}</p><dl className="mt-2 grid grid-cols-2 text-xs"><dt>Type</dt><dd>{f.detected_feed_type}</dd><dt>Next scheduled</dt><dd>{f.next_scheduled_fetch_at??"Not scheduled"}</dd><dt>Last check</dt><dd>{f.last_checked_at??"Never"}</dd><dt>Last success</dt><dd>{f.last_success_at??"Never"}</dd></dl>{f.last_error_message&&<p role="alert" className="text-red-300">{f.last_error_message}</p>}<div className="mt-3 flex gap-2"><button className="button">{f.enabled?"Pause":"Enable"}</button><button className="button">{f.scheduler_enabled?"Disable automatic":"Enable automatic"}</button><button className="button">{f.archived_at?"Restore":"Archive"}</button><button className="button">Fetch now</button></div></section>)}</aside></div>}
 {linkItem&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60"><div role="dialog" aria-modal="true" aria-label="Send item to Investigation" className="card w-[min(32rem,calc(100%-2rem))]"><h2 className="text-xl font-bold">Send to Investigation</h2><form className="mt-4 space-y-3"><select aria-label="Investigation" required><option value="">Choose an Investigation</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><textarea aria-label="Analyst note" maxLength={2000}/><div className="flex gap-2"><button className="button">Link item</button><button className="button" type="button" onClick={()=>setLinkItem(null)}>Cancel</button></div></form></div></div>}
 </main>;
}
