import {afterEach,describe,expect,it,vi} from "vitest";
import {buildOtxResult,otxAdapter} from "./adapter";import {serializeOtxCursor} from "./cursor";
const a="0123456789abcdef01234567",b="1123456789abcdef01234567",old="2026-08-01T09:00:00.000Z",boundary="2026-08-01T10:00:00.000Z",newer="2026-08-01T11:00:00.000Z";
const pulse=(id=a,modified=boundary,indicators:unknown[]=[{id:"one",indicator:"example.com",type:"domain"}])=>({id,name:`Pulse ${id}`,description:"plain",created:old,modified,tags:[],references:[],targeted_countries:[],industries:[],malware_families:[],attack_ids:[],indicators});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()});
describe("OTX incremental adapter",()=>{
 it("uses a 30-day bootstrap look-back",async()=>{vi.setSystemTime(new Date("2026-08-01T12:00:00.000Z"));vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[],next:null,previous:null,count:0}))));await otxAdapter.sync({ownerId:"o",connectionId:"c",cursor:null,settings:{bootstrap_lookback_days:30},credential:"key"});expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("modified_since=2026-07-02T12%3A00%3A00.000Z")});
 it("uses a one-minute overlap",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[],next:null,previous:null,count:0}))));await otxAdapter.sync({ownerId:"o",connectionId:"c",cursor:serializeOtxCursor(boundary,[a]),settings:{},credential:"key"});expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("modified_since=2026-08-01T09%3A59%3A00.000Z")});
 it("treats older and known boundary Pulses as seen",()=>{const r=buildOtxResult([pulse(a,old),pulse(a,boundary)],serializeOtxCursor(boundary,[a]),false);expect(r.status).toBe("NOT_MODIFIED");expect(r.items).toEqual([])});
 it("accepts an unseen boundary Pulse",()=>expect(buildOtxResult([pulse(b,boundary)],serializeOtxCursor(boundary,[a]),false).status).toBe("SUCCEEDED"));
 it("accepts a known Pulse modified later",()=>expect(buildOtxResult([pulse(a,newer)],serializeOtxCursor(boundary,[a]),false).status).toBe("SUCCEEDED"));
 it("returns NOT_MODIFIED for an identical second response without replay",()=>{const r=buildOtxResult([pulse()],serializeOtxCursor(boundary,[a]),false);expect(r).toMatchObject({status:"NOT_MODIFIED",items:[],diagnostics:{mapped_count:0,mapping_skipped_count:0}})});
 it("modified Pulse can add new indicator and preserves existing fingerprint",()=>{const first=buildOtxResult([pulse()],null);const changed=buildOtxResult([pulse(a,newer,[{id:"one",indicator:"example.com",type:"domain"},{id:"two",indicator:"sub.example.com",type:"domain"}])],serializeOtxCursor(boundary,[a]),false);expect(changed.items).toHaveLength(2);expect("source_fingerprint" in first.items[0]&&"source_fingerprint" in changed.items[0]&&changed.items[0].source_fingerprint).toBe(first.items[0].source_fingerprint)});
 it("incremental all-invalid succeeds with bounded skips",()=>expect(buildOtxResult([pulse(a,newer,[{id:"x",indicator:"x",type:"email"}])],serializeOtxCursor(boundary,[a]),false)).toMatchObject({status:"SUCCEEDED",items:[{provider_skip_reason:"UNSUPPORTED_IOC_TYPE"}]}));
 it("bootstrap all-invalid fails",()=>expect(()=>buildOtxResult([pulse(a,boundary,[{id:"x",indicator:"x",type:"email"}])],null)).toThrow("OTX_MAPPING_FAILED"));
 it("unexpected malformed Pulse fails and leaves supplied cursor unchanged",()=>{const cursor=serializeOtxCursor(boundary,[a]);expect(()=>buildOtxResult([{unexpected:"raw"}],cursor,false)).toThrow();expect(cursor).toBe(serializeOtxCursor(boundary,[a]))});
});
