import "server-only";
import {createHash} from "node:crypto";
import type {IocProviderAdapter,NormalizedCandidate,ProviderSkipReason} from "../../types";
import {fetchSubscribedPulses,testOtxConnection,OTX_MAX_INDICATORS} from "./client";
import {isPulseEligible,parseOtxCursor,serializeOtxState,type OtxCommitted,type OtxCursor} from "./cursor";
import {OtxError} from "./errors";
import {mapOtxIndicator,OtxMappingError,parseOtxPulse,type ParsedOtxPulse,type PulseContextCategory,type PulseNormalizationDiagnostics} from "./mapping";
import {OTX_DEFAULT_BOOTSTRAP_LOOKBACK_DAYS} from "./settings";
const OVERLAP=60_000;
type Outcome={pulse:ParsedOtxPulse;raw:unknown;modified:string;itemKey:string};
const iso=(value:string)=>new Date(value).toISOString();
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function rawIdentity(raw:unknown){if(!raw||typeof raw!=="object"||Array.isArray(raw))return String(raw).slice(0,8000);const record=raw as Record<string,unknown>;return["id","type","indicator","created","modified","is_active","active"].map(key=>`${key}=${typeof record[key]==="string"||typeof record[key]==="number"||typeof record[key]==="boolean"?String(record[key]).slice(0,8000):""}`).join("\0")}
function outcomes(pulses:ParsedOtxPulse[]){const base=pulses.flatMap(pulse=>pulse.indicators.map(raw=>({pulse,raw,modified:iso(pulse.modified),baseKey:hash(`ALIENVAULT_OTX\0${pulse.id}\0${iso(pulse.modified)}\0${rawIdentity(raw)}`)}))).sort((a,b)=>a.modified.localeCompare(b.modified)||a.pulse.id.localeCompare(b.pulse.id)||a.baseKey.localeCompare(b.baseKey));const seen=new Map<string,number>();return base.map(item=>{const group=`${item.modified}\0${item.pulse.id}\0${item.baseKey}`,ordinal=seen.get(group)??0;seen.set(group,ordinal+1);return{pulse:item.pulse,raw:item.raw,modified:item.modified,itemKey:hash(`${item.baseKey}\0${ordinal}`)}}).sort((a,b)=>a.modified.localeCompare(b.modified)||a.pulse.id.localeCompare(b.pulse.id)||a.itemKey.localeCompare(b.itemKey))}
function afterResume(item:Outcome,cursor:OtxCursor|null){const resume=cursor?.continuation?.resume_after;if(!resume)return true;return item.modified>resume.pulse_modified||(item.modified===resume.pulse_modified&&(item.pulse.id>resume.pulse_id||(item.pulse.id===resume.pulse_id&&item.itemKey>resume.item_key)))}
function nextCommitted(pulses:ParsedOtxPulse[],previous:OtxCommitted|null){const greatest=pulses.map(pulse=>iso(pulse.modified)).sort().at(-1);if(!greatest||previous&&previous.last_modified>greatest)return previous;const ids=Array.from(new Set(pulses.filter(pulse=>iso(pulse.modified)===greatest).map(pulse=>pulse.id))).sort();if(previous&&previous.last_modified===greatest)for(const id of previous.pulse_ids_at_boundary)if(!ids.includes(id))ids.push(id);ids.sort();return{last_modified:greatest,pulse_ids_at_boundary:ids}}
function aggregateNormalization(pulses:ParsedOtxPulse[]):PulseNormalizationDiagnostics{const result:PulseNormalizationDiagnostics={pulse_context_fields_dropped:{},pulse_context_items_dropped:0,invalid_identity_pulse_count:0};for(const pulse of pulses){result.pulse_context_items_dropped+=pulse.normalization.pulse_context_items_dropped;for(const[key,count]of Object.entries(pulse.normalization.pulse_context_fields_dropped)as[PulseContextCategory,number][])result.pulse_context_fields_dropped[key]=(result.pulse_context_fields_dropped[key]??0)+count}return result}
export function buildOtxResult(raw:unknown[],cursorValue:string|null,options:{now?:Date;lookbackDays?:number;scope?:"SEARCH_PULSE";pulseId?:string}={}){
 const cursor=parseOtxCursor(cursorValue),now=(options.now??new Date()).toISOString(),mode=cursor?.continuation?.mode??(cursor?.committed?"INCREMENTAL":"BOOTSTRAP"),windowStart=cursor?.continuation?.window_start??(cursor?.committed?new Date(Date.parse(cursor.committed.last_modified)-OVERLAP).toISOString():new Date(Date.parse(now)-(options.lookbackDays??OTX_DEFAULT_BOOTSTRAP_LOOKBACK_DAYS)*86400000).toISOString()),windowEnd=cursor?.continuation?.window_end??now;
 const parsedPulses=raw.map(parseOtxPulse),normalization=aggregateNormalization(parsedPulses),snapshot=parsedPulses.filter(pulse=>{const modified=iso(pulse.modified);return modified>=windowStart&&modified<=windowEnd&&(!options.pulseId||pulse.id===options.pulseId)}).sort((a,b)=>iso(a.modified).localeCompare(iso(b.modified))||a.id.localeCompare(b.id)),all=outcomes(snapshot),searchScope=options.scope==="SEARCH_PULSE"||cursor?.continuation?.scope==="SEARCH_PULSE",eligiblePulse=(pulse:ParsedOtxPulse)=>searchScope||isPulseEligible(iso(pulse.modified),pulse.id,cursor),covered=all.filter(item=>!eligiblePulse(item.pulse)||!afterResume(item,cursor)),remaining=all.filter(item=>eligiblePulse(item.pulse)&&afterResume(item,cursor)),selected=remaining.slice(0,OTX_MAX_INDICATORS),deferred=remaining.length-selected.length,mapped:NormalizedCandidate[]=[],skipped:{provider_skip_reason:ProviderSkipReason}[]=[],counts:Partial<Record<ProviderSkipReason,number>>={};
 for(const item of selected)try{mapped.push(mapOtxIndicator(item.pulse,item.raw))}catch(error){if(!(error instanceof OtxMappingError))throw error;skipped.push({provider_skip_reason:error.reason});counts[error.reason]=(counts[error.reason]??0)+1}
 if(mode==="BOOTSTRAP"&&all.length>0&&!cursor?.continuation&&selected.length>0&&!mapped.length&&deferred===0)throw new OtxError("OTX_MAPPING_FAILED",false,undefined,{received_count:all.length,mapping_skipped_count:skipped.length,skip_reason_counts:counts,...normalization});
 const hasMore=deferred>0;let nextCursor:string;if(hasMore){const last=selected.at(-1);if(!last)throw new OtxError("OTX_MAPPING_FAILED");nextCursor=serializeOtxState({committed:cursor?.committed??null,continuation:{mode,scope:searchScope?"SEARCH_PULSE":"LEGACY_BULK",...(searchScope?{pulse_id:options.pulseId??cursor?.continuation?.pulse_id}:{}),window_start:windowStart,window_end:windowEnd,resume_after:{pulse_modified:last.modified,pulse_id:last.pulse.id,item_key:last.itemKey},processed_count:(cursor?.continuation?.processed_count??0)+selected.length}})}else nextCursor=serializeOtxState({committed:searchScope?cursor?.committed??null:nextCommitted(snapshot.filter(eligiblePulse),cursor?.committed??null),continuation:null});
 const diagnostics={received_count:all.length,already_seen_count:covered.length,eligible_count:selected.length,deferred_count:deferred,mapped_count:mapped.length,mapping_skipped_count:skipped.length,skip_reason_counts:counts,has_more:hasMore,...normalization};
 if(!selected.length)return{status:"NOT_MODIFIED" as const,items:[] as [],nextCursor,diagnostics};return{status:"SUCCEEDED" as const,items:[...mapped,...skipped],nextCursor,diagnostics};
}
export const otxAdapter:IocProviderAdapter={key:"ALIENVAULT_OTX",displayName:"AlienVault OTX",credentialRequired:true,supportedTypes:["IPV4","IPV6","CIDR","DOMAIN","HOSTNAME","URL","MD5","SHA1","SHA256","CVE"],supportsScheduling:false,testConnection:testOtxConnection,async sync({credential,cursor,settings,signal}){try{if(!credential)throw new OtxError("OTX_CREDENTIAL_REQUIRED");const parsed=parseOtxCursor(cursor),now=new Date(),lookback=Number(settings.bootstrap_lookback_days??OTX_DEFAULT_BOOTSTRAP_LOOKBACK_DAYS),since=parsed?.continuation?.window_start??(parsed?.committed?new Date(Date.parse(parsed.committed.last_modified)-OVERLAP).toISOString():new Date(now.valueOf()-lookback*86400000).toISOString());return buildOtxResult(await fetchSubscribedPulses(credential,since,signal),cursor,{now,lookbackDays:lookback})}catch(error){if(error instanceof OtxMappingError)throw new OtxError("OTX_MAPPING_FAILED");throw error}}};
