import "server-only";
import type {IocProviderAdapter,NormalizedCandidate,ProviderSkipReason} from "../../types";
import {fetchSubscribedPulses,testOtxConnection} from "./client";
import {isPulseEligible,parseOtxCursor,serializeOtxCursor} from "./cursor";
import {OtxError} from "./errors";
import {mapOtxIndicator,OtxMappingError,parseOtxPulse} from "./mapping";
const OVERLAP=60_000;
export function buildOtxResult(raw:unknown[],cursorValue:string|null,bootstrap=true){const cursor=parseOtxCursor(cursorValue);const pulses=raw.map(parseOtxPulse);const eligible=pulses.filter(p=>isPulseEligible(new Date(p.modified).toISOString(),p.id,cursor));const greatest=pulses.map(p=>new Date(p.modified).toISOString()).sort().at(-1);const ids=greatest?pulses.filter(p=>new Date(p.modified).toISOString()===greatest).map(p=>p.id):[];const next=greatest?serializeOtxCursor(greatest,ids):(cursorValue??undefined);if(!eligible.length)return{status:"NOT_MODIFIED" as const,items:[] as [],...(next?{nextCursor:next}:{}),diagnostics:{received_count:pulses.reduce((n,p)=>n+p.indicators.length,0),eligible_count:0,already_seen_count:pulses.reduce((n,p)=>n+p.indicators.length,0),mapped_count:0,mapping_skipped_count:0,skip_reason_counts:{}}};const mapped:NormalizedCandidate[]=[],skipped:{provider_skip_reason:ProviderSkipReason}[]=[],counts:Partial<Record<ProviderSkipReason,number>>={};for(const p of eligible)for(const i of p.indicators)try{mapped.push(mapOtxIndicator(p,i))}catch(e){if(!(e instanceof OtxMappingError))throw e;skipped.push({provider_skip_reason:e.reason});counts[e.reason]=(counts[e.reason]??0)+1}const total=pulses.reduce((n,p)=>n+p.indicators.length,0),eligibleCount=eligible.reduce((n,p)=>n+p.indicators.length,0);if(bootstrap&&eligibleCount>0&&!mapped.length)throw new OtxError("OTX_MAPPING_FAILED",false,undefined,{received_count:total,mapping_skipped_count:skipped.length,skip_reason_counts:counts});return{status:"SUCCEEDED" as const,items:[...mapped,...skipped],nextCursor:next!,diagnostics:{received_count:total,eligible_count:eligibleCount,already_seen_count:total-eligibleCount,mapped_count:mapped.length,mapping_skipped_count:skipped.length,skip_reason_counts:counts}}}
export const otxAdapter:IocProviderAdapter={key:"ALIENVAULT_OTX",displayName:"AlienVault OTX",credentialRequired:true,supportedTypes:["IPV4","IPV6","CIDR","DOMAIN","HOSTNAME","URL","MD5","SHA1","SHA256","CVE"],supportsScheduling:false,testConnection:testOtxConnection,async sync({credential,cursor,settings,signal}){if(!credential)throw new OtxError("OTX_CREDENTIAL_REQUIRED");const parsed=parseOtxCursor(cursor);const since=parsed?new Date(Date.parse(parsed.last_modified)-OVERLAP).toISOString():new Date(Date.now()-Number(settings.bootstrap_lookback_days??30)*86400000).toISOString();return buildOtxResult(await fetchSubscribedPulses(credential,since,signal),cursor,!parsed)}};
