import {describe,expect,it} from "vitest";import {buildOtxResult} from "./adapter";import {parseOtxCursor} from "./cursor";
const id="0123456789abcdef01234567",modified="2026-08-01T10:00:00.000Z",now=new Date("2026-08-01T12:00:00.000Z");
const indicators=(count:number)=>Array.from({length:count},(_,i)=>({id:`indicator-${String(i).padStart(5,"0")}`,indicator:`i${String(i).padStart(5,"0")}.example.com`,type:"domain"}));
const pulse=(items:unknown[],pulseId=id,pulseModified=modified)=>({id:pulseId,name:"Bounded Pulse",description:"",created:modified,modified:pulseModified,tags:[],references:[],targeted_countries:[],industries:[],malware_families:[],attack_ids:[],indicators:items});
const run=(items:unknown[],cursor:string|null=null)=>buildOtxResult([pulse(items)],cursor,{now,lookbackDays:1});
describe("resumable deterministic OTX batches",()=>{
 it("completes exactly 1000 outcomes in one batch",()=>{const result=run(indicators(1000));expect(result).toMatchObject({status:"SUCCEEDED",diagnostics:{eligible_count:1000,deferred_count:0,has_more:false}});expect(result.items).toHaveLength(1000);expect(parseOtxCursor(result.nextCursor)?.continuation).toBeNull()});
 it("processes 1001 as 1000 then one then NOT_MODIFIED",()=>{const raw=indicators(1001),first=run(raw);expect(first).toMatchObject({status:"SUCCEEDED",diagnostics:{eligible_count:1000,deferred_count:1,has_more:true}});expect(parseOtxCursor(first.nextCursor)?.continuation?.processed_count).toBe(1000);const second=run(raw,first.nextCursor);expect(second).toMatchObject({status:"SUCCEEDED",diagnostics:{eligible_count:1,deferred_count:0,has_more:false}});expect(second.items).toHaveLength(1);const third=run(raw,second.nextCursor);expect(third).toMatchObject({status:"NOT_MODIFIED",items:[],diagnostics:{deferred_count:0,has_more:false}})});
 it("drains one 2500-indicator Pulse as 1000, 1000 and 500",()=>{const raw=indicators(2500),one=run(raw),two=run(raw,one.nextCursor),three=run(raw,two.nextCursor);expect([one.items.length,two.items.length,three.items.length]).toEqual([1000,1000,500]);expect([one.diagnostics.deferred_count,two.diagnostics.deferred_count,three.diagnostics.deferred_count]).toEqual([1500,500,0]);expect(three.diagnostics.has_more).toBe(false)});
 it("unsupported and inactive outcomes consume positions and are not replayed",()=>{const raw=[{id:"a",indicator:"x",type:"email"},{id:"b",indicator:"example.com",type:"domain",active:false},...indicators(999)],first=run(raw);expect(first.items.filter(i=>"provider_skip_reason" in i)).toHaveLength(2);const second=run(raw,first.nextCursor);expect(second.items).toHaveLength(1);expect(second.items.filter(i=>"provider_skip_reason" in i)).toHaveLength(0)});
 it("selects the same batch for the same response and cursor",()=>{const raw=indicators(1001),a=run(raw),b=run([...raw].reverse());expect(a.nextCursor).toBe(b.nextCursor);expect(a.items.map(i=>"source_fingerprint" in i?i.source_fingerprint:i.provider_skip_reason)).toEqual(b.items.map(i=>"source_fingerprint" in i?i.source_fingerprint:i.provider_skip_reason))});
 it("retry after completion failure reselects the same current batch",()=>{const raw=indicators(1001),previous:string|null=null,a=run(raw,previous),retry=run(raw,previous);expect(retry.nextCursor).toBe(a.nextCursor);expect(retry.items).toEqual(a.items)});
 it("excludes Pulses modified after the fixed window end",()=>{const first=run(indicators(1001)),future=pulse(indicators(2),"1123456789abcdef01234567","2026-08-01T13:00:00.000Z"),continued=buildOtxResult([pulse(indicators(1001)),future],first.nextCursor,{now:new Date("2026-08-01T14:00:00.000Z"),lookbackDays:1});expect(continued.items).toHaveLength(1);expect(continued.items.every(i=>!("provider_item_id" in i)||!i.provider_item_id.startsWith("112345"))).toBe(true)});
 it("defers a known Pulse modified beyond the snapshot to the next cycle",()=>{const first=run(indicators(1001)),changed=buildOtxResult([pulse(indicators(1100),id,"2026-08-01T13:00:00.000Z")],first.nextCursor,{now:new Date("2026-08-01T14:00:00.000Z"),lookbackDays:1});expect(changed).toMatchObject({status:"NOT_MODIFIED",items:[],diagnostics:{eligible_count:0,deferred_count:0}})});
 it("keeps fingerprints idempotent and distinct across Pulses",()=>{const item={id:"stable",indicator:"example.com",type:"domain"},a=buildOtxResult([pulse([item])],null,{now}),b=buildOtxResult([pulse([item],"1123456789abcdef01234567")],null,{now});if(!("source_fingerprint" in a.items[0])||!("source_fingerprint" in b.items[0]))throw new Error("candidate expected");expect(a.items[0].normalized_value).toBe(b.items[0].normalized_value);expect(a.items[0].source_fingerprint).not.toBe(b.items[0].source_fingerprint);expect(run([item]).items).toEqual(run([item]).items)});
 it("never returns more than 1000 outcomes",()=>expect(run(indicators(5000)).items.length).toBeLessThanOrEqual(1000));
});
