import "server-only";
import {OtxError} from "./errors";
import {envelopeSchema,searchEnvelopeSchema} from "./schema";
export const OTX_ORIGIN="https://otx.alienvault.com",OTX_PATH="/api/v1/pulses/subscribed",OTX_PAGE_SIZE=50,OTX_MAX_PAGES=5,OTX_MAX_PULSES=250,OTX_MAX_INDICATORS=1000;
const PAGE_BYTES=8*1024*1024,TOTAL_BYTES=16*1024*1024;
function queryUrl(page:number,modifiedSince?:string,limit=OTX_PAGE_SIZE){const u=new URL(OTX_PATH,OTX_ORIGIN);u.searchParams.set("limit",String(limit));u.searchParams.set("page",String(page));if(modifiedSince)u.searchParams.set("modified_since",modifiedSince);return u}
export function validateNext(value:string,modifiedSince?:string){let u:URL;try{u=new URL(value)}catch{throw new OtxError("OTX_PAGINATION_INVALID")};if(u.protocol!=="https:"||u.hostname!=="otx.alienvault.com"||u.port||u.username||u.password||u.hash||u.pathname!==OTX_PATH||u.search.length>1000)throw new OtxError("OTX_PAGINATION_INVALID");for(const k of u.searchParams.keys())if(!["page","limit","modified_since"].includes(k))throw new OtxError("OTX_PAGINATION_INVALID");const page=Number(u.searchParams.get("page"));if(!Number.isInteger(page)||page<1||page>OTX_MAX_PAGES||Number(u.searchParams.get("limit"))!==OTX_PAGE_SIZE||(modifiedSince&&u.searchParams.get("modified_since")!==modifiedSince))throw new OtxError("OTX_PAGINATION_INVALID");return page}
async function request(url:URL,key:string,signal?:AbortSignal){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000),abort=()=>c.abort();signal?.addEventListener("abort",abort,{once:true});try{const r=await fetch(url,{method:"GET",headers:{"X-OTX-API-KEY":key,Accept:"application/json"},cache:"no-store",redirect:"error",signal:c.signal});if(r.status===401||r.status===403)throw new OtxError("OTX_AUTH_FAILED");if(r.status===429)throw new OtxError("OTX_RATE_LIMITED",true,1800);if(r.status>=500)throw new OtxError("OTX_NETWORK_FAILURE",true);if(!r.ok)throw new OtxError("OTX_QUERY_FAILED");const l=Number(r.headers.get("content-length"));if(l>PAGE_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");const text=await r.text();if(Buffer.byteLength(text)>PAGE_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");let json:unknown;try{json=JSON.parse(text)}catch{throw new OtxError("OTX_INVALID_RESPONSE")};return{text,json}}catch(e){if(e instanceof OtxError)throw e;if(c.signal.aborted)throw new OtxError("OTX_TIMEOUT",true);if(e instanceof TypeError&&/redirect/i.test(e.message))throw new OtxError("OTX_REDIRECT_FORBIDDEN");throw new OtxError("OTX_NETWORK_FAILURE",true)}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort)}}
export async function testOtxConnection(key:string,signal?:AbortSignal){if(!key)throw new OtxError("OTX_CREDENTIAL_REQUIRED");const {json}=await request(queryUrl(1,undefined,1),key,signal);if(!json||typeof json!=="object")throw new OtxError("OTX_INVALID_RESPONSE")}
export async function fetchSubscribedPulses(key:string,modifiedSince:string,signal?:AbortSignal){if(!key)throw new OtxError("OTX_CREDENTIAL_REQUIRED");let page=1,total=0;const results:unknown[]=[];const visited=new Set<number>();while(page){if(visited.has(page))throw new OtxError("OTX_PAGINATION_LOOP");if(visited.size>=OTX_MAX_PAGES)throw new OtxError("OTX_ITEM_LIMIT");visited.add(page);const response=await request(queryUrl(page,modifiedSince),key,signal);total+=Buffer.byteLength(response.text);if(total>TOTAL_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");const parsed=envelopeSchema.safeParse(response.json);if(!parsed.success)throw new OtxError("OTX_INVALID_RESPONSE");results.push(...parsed.data.results);if(results.length>OTX_MAX_PULSES)throw new OtxError("OTX_PULSE_LIMIT",false,undefined,{observed_count:results.length,configured_limit:OTX_MAX_PULSES,limit_category:"PULSES"});page=parsed.data.next?validateNext(parsed.data.next,modifiedSince):0}return results}

const SEARCH_PATH="/api/v1/search/pulses",PULSE_ID=/^[0-9a-f]{24}$/;
export type OtxPulseSearchSummary={id:string;name:string;description:string;modified:string;author_name:string|null;tlp:string;indicator_count:number;tags:string[];reference_url:string};
function searchSummary(raw:unknown):OtxPulseSearchSummary|null{if(!raw||typeof raw!=="object"||Array.isArray(raw))return null;const value=raw as Record<string,unknown>,id=typeof value.id==="string"&&PULSE_ID.test(value.id)?value.id:null,modified=typeof value.modified==="string"&&!Number.isNaN(new Date(value.modified).valueOf())?new Date(value.modified).toISOString():null;if(!id||!modified)return null;const author=typeof value.author_name==="string"?value.author_name:typeof value.author==="string"?value.author:null;return{id,name:typeof value.name==="string"?value.name.slice(0,300):"Unnamed OTX Pulse",description:typeof value.description==="string"?value.description.slice(0,500):"",modified,author_name:author?.slice(0,200)??null,tlp:typeof value.TLP==="string"?value.TLP.slice(0,20):"unknown",indicator_count:Number.isInteger(value.indicator_count)&&Number(value.indicator_count)>=0?Math.min(Number(value.indicator_count),10_000_000):0,tags:Array.isArray(value.tags)?Array.from(new Set(value.tags.filter((tag):tag is string=>typeof tag==="string"&&tag.length<=200))).slice(0,20):[],reference_url:`${OTX_ORIGIN}/pulse/${id}`}}
export async function searchOtxPulses(key:string,query:string,signal?:AbortSignal){if(query.length<2||query.length>120)throw new OtxError("OTX_QUERY_FAILED");const url=new URL(SEARCH_PATH,OTX_ORIGIN);url.searchParams.set("q",query);url.searchParams.set("page","1");url.searchParams.set("limit","25");const response=await request(url,key,signal);const parsed=searchEnvelopeSchema.safeParse(response.json);if(!parsed.success)throw new OtxError("OTX_INVALID_RESPONSE");return parsed.data.results.map(searchSummary).filter((value):value is OtxPulseSearchSummary=>value!==null).slice(0,25)}
export async function fetchOtxPulse(key:string,pulseId:string,signal?:AbortSignal){if(!PULSE_ID.test(pulseId))throw new OtxError("OTX_INVALID_RESPONSE");const detail=await request(new URL(`/api/v1/pulses/${pulseId}`,OTX_ORIGIN),key,signal),indicators=await request(new URL(`/api/v1/pulses/${pulseId}/indicators`,OTX_ORIGIN),key,signal);if(!detail.json||typeof detail.json!=="object"||Array.isArray(detail.json))throw new OtxError("OTX_INVALID_RESPONSE");const indicatorBody=indicators.json as Record<string,unknown>,items=Array.isArray(indicatorBody.results)?indicatorBody.results:Array.isArray(indicatorBody.indicators)?indicatorBody.indicators:null;if(!items||items.length>100000)throw new OtxError("OTX_INVALID_RESPONSE");return{...(detail.json as Record<string,unknown>),id:pulseId,indicators:items}}
