import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {fetchSubscribedPulses,testOtxConnection,validateNext,OTX_MAX_PAGES} from "./client";
const key="synthetic-test-key", modified="2026-08-01T10:00:00.000Z";
const envelope=(results:unknown[]=[],next:string|null=null)=>({results,next,previous:null,count:results.length});
const response=(body:unknown,status=200,headers:Record<string,string>={})=>new Response(typeof body==="string"?body:JSON.stringify(body),{status,headers});
function next(page:number,extra=""){return `https://otx.alienvault.com/api/v1/pulses/subscribed?limit=50&page=${page}&modified_since=${encodeURIComponent(modified)}${extra}`}
beforeEach(()=>vi.stubGlobal("fetch",vi.fn()));afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks()});
describe("OTX fixed read-only client",()=>{
 it("uses exact GET origin, path, key header and fixed test limit",async()=>{vi.mocked(fetch).mockResolvedValue(response(envelope()));await testOtxConnection(key);const [url,init]=vi.mocked(fetch).mock.calls[0];const u=new URL(String(url));expect([u.protocol,u.host,u.pathname,u.searchParams.get("limit")]).toEqual(["https:","otx.alienvault.com","/api/v1/pulses/subscribed","1"]);expect(init).toMatchObject({method:"GET",redirect:"error"});expect(new Headers(init?.headers).get("X-OTX-API-KEY")).toBe(key)});
 it("encodes modified_since itself",async()=>{vi.mocked(fetch).mockResolvedValue(response(envelope()));await fetchSubscribedPulses(key,modified);expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("modified_since=2026-08-01T10%3A00%3A00.000Z")});
 it("aborts at fifteen seconds",async()=>{vi.useFakeTimers();vi.mocked(fetch).mockImplementation((_u,init)=>new Promise((_r,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")))));const assertion=expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_TIMEOUT"});await vi.advanceTimersByTimeAsync(15000);await assertion});
 it("classifies redirect refusal without leaking data",async()=>{vi.mocked(fetch).mockRejectedValue(new TypeError("redirect mode is set to error"));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_REDIRECT_FORBIDDEN"})});
 it.each(["http://otx.alienvault.com/api/v1/pulses/subscribed?limit=50&page=2","https://evil.example/api/v1/pulses/subscribed?limit=50&page=2","https://u:p@otx.alienvault.com/api/v1/pulses/subscribed?limit=50&page=2","https://otx.alienvault.com/api/v1/pulses/subscribed?limit=50&page=2#x","https://otx.alienvault.com/api/v1/pulses/subscribed?limit=50&page=2&evil=1"])("rejects hostile pagination %s",url=>expect(()=>validateNext(url)).toThrow("OTX_PAGINATION_INVALID"));
 it("rejects pagination loops",async()=>{vi.mocked(fetch).mockResolvedValue(response(envelope([],next(1))));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_PAGINATION_LOOP"})});
 it("accepts five pages but rejects a sixth",async()=>{for(let page=1;page<=OTX_MAX_PAGES;page++)vi.mocked(fetch).mockResolvedValueOnce(response(envelope([],next(page+1))));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_PAGINATION_INVALID"});expect(fetch).toHaveBeenCalledTimes(5)});
 it("accepts exactly 250 Pulses",async()=>{for(let page=1;page<=5;page++)vi.mocked(fetch).mockResolvedValueOnce(response(envelope(Array.from({length:50},()=>({indicators:[]})),page<5?next(page+1):null)));await expect(fetchSubscribedPulses(key,modified)).resolves.toHaveLength(250)});
 it("classifies more than 250 Pulses",async()=>{for(let page=1;page<=5;page++)vi.mocked(fetch).mockResolvedValueOnce(response(envelope(Array.from({length:page===1?51:50},()=>({indicators:[]})),page<5?next(page+1):null)));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_PULSE_LIMIT",diagnostics:{observed_count:251,configured_limit:250,limit_category:"PULSES"}})});
 it("accepts exactly 1000 indicators",async()=>{const results=[{indicators:Array.from({length:1000})}];vi.mocked(fetch).mockResolvedValue(response(envelope(results)));const accepted=await fetchSubscribedPulses(key,modified);expect((accepted[0] as {indicators:unknown[]}).indicators).toHaveLength(1000)});
 it("accepts aggregate responses above the per-completion workload bound",async()=>{const results=[{indicators:Array.from({length:2500},(_,i)=>({indicator:`i${i}.example.com`}))}];vi.mocked(fetch).mockResolvedValue(response(envelope(results)));const accepted=await fetchSubscribedPulses(key,modified);expect((accepted[0] as {indicators:unknown[]}).indicators).toHaveLength(2500)});
 it("rejects declared per-page size",async()=>{vi.mocked(fetch).mockResolvedValue(response("{}",200,{"content-length":String(8*1024*1024+1)}));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_RESPONSE_TOO_LARGE"})});
 it("rejects measured per-page size",async()=>{vi.mocked(fetch).mockResolvedValue(response("x".repeat(8*1024*1024+1)));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_RESPONSE_TOO_LARGE"})});
 it("rejects total response size",async()=>{const body=JSON.stringify(envelope([],next(2)))+" ".repeat(6*1024*1024);const body2=JSON.stringify(envelope([],next(3)))+" ".repeat(6*1024*1024);const body3=JSON.stringify(envelope([]))+" ".repeat(6*1024*1024);vi.mocked(fetch).mockResolvedValueOnce(response(body)).mockResolvedValueOnce(response(body2)).mockResolvedValueOnce(response(body3));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_RESPONSE_TOO_LARGE"})});
 it.each([401,403])("classifies %s authentication",async status=>{vi.mocked(fetch).mockResolvedValue(response("secret raw body",status));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_AUTH_FAILED"})});
 it("classifies 429",async()=>{vi.mocked(fetch).mockResolvedValue(response({},429));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_RATE_LIMITED",transient:true})});
 it("classifies transient 5xx",async()=>{vi.mocked(fetch).mockResolvedValue(response({},503));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_NETWORK_FAILURE",transient:true})});
 it("rejects malformed JSON",async()=>{vi.mocked(fetch).mockResolvedValue(response("raw-provider-secret"));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_INVALID_RESPONSE"})});
 it("rejects invalid envelope",async()=>{vi.mocked(fetch).mockResolvedValue(response({results:"wrong"}));await expect(fetchSubscribedPulses(key,modified)).rejects.toMatchObject({code:"OTX_INVALID_RESPONSE"})});
 it("never leaks key or response body",async()=>{vi.mocked(fetch).mockResolvedValue(response("raw-provider-secret",403));try{await fetchSubscribedPulses(key,modified)}catch(error){const visible=error instanceof Error?`${error.message} ${JSON.stringify(error)}`:String(error);expect(visible).not.toContain(key);expect(visible).not.toContain("raw-provider-secret")}});
});
