import "server-only";
import {OtxError} from "./errors";
import {envelopeSchema} from "./schema";
export const OTX_ORIGIN="https://otx.alienvault.com",OTX_PATH="/api/v1/pulses/subscribed",OTX_PAGE_SIZE=50,OTX_MAX_PAGES=5,OTX_MAX_PULSES=250,OTX_MAX_INDICATORS=1000;
const PAGE_BYTES=8*1024*1024,TOTAL_BYTES=16*1024*1024;
function queryUrl(page:number,modifiedSince?:string,limit=OTX_PAGE_SIZE){const u=new URL(OTX_PATH,OTX_ORIGIN);u.searchParams.set("limit",String(limit));u.searchParams.set("page",String(page));if(modifiedSince)u.searchParams.set("modified_since",modifiedSince);return u}
export function validateNext(value:string,modifiedSince?:string){let u:URL;try{u=new URL(value)}catch{throw new OtxError("OTX_PAGINATION_INVALID")};if(u.protocol!=="https:"||u.hostname!=="otx.alienvault.com"||u.port||u.username||u.password||u.hash||u.pathname!==OTX_PATH||u.search.length>1000)throw new OtxError("OTX_PAGINATION_INVALID");for(const k of u.searchParams.keys())if(!["page","limit","modified_since"].includes(k))throw new OtxError("OTX_PAGINATION_INVALID");const page=Number(u.searchParams.get("page"));if(!Number.isInteger(page)||page<1||page>OTX_MAX_PAGES||Number(u.searchParams.get("limit"))!==OTX_PAGE_SIZE||(modifiedSince&&u.searchParams.get("modified_since")!==modifiedSince))throw new OtxError("OTX_PAGINATION_INVALID");return page}
async function request(url:URL,key:string,signal?:AbortSignal){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000),abort=()=>c.abort();signal?.addEventListener("abort",abort,{once:true});try{const r=await fetch(url,{method:"GET",headers:{"X-OTX-API-KEY":key,Accept:"application/json"},cache:"no-store",redirect:"error",signal:c.signal});if(r.status===401||r.status===403)throw new OtxError("OTX_AUTH_FAILED");if(r.status===429)throw new OtxError("OTX_RATE_LIMITED",true,1800);if(r.status>=500)throw new OtxError("OTX_NETWORK_FAILURE",true);if(!r.ok)throw new OtxError("OTX_QUERY_FAILED");const l=Number(r.headers.get("content-length"));if(l>PAGE_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");const text=await r.text();if(Buffer.byteLength(text)>PAGE_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");let json:unknown;try{json=JSON.parse(text)}catch{throw new OtxError("OTX_INVALID_RESPONSE")};return{text,json}}catch(e){if(e instanceof OtxError)throw e;if(c.signal.aborted)throw new OtxError("OTX_TIMEOUT",true);if(e instanceof TypeError&&/redirect/i.test(e.message))throw new OtxError("OTX_REDIRECT_FORBIDDEN");throw new OtxError("OTX_NETWORK_FAILURE",true)}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort)}}
export async function testOtxConnection(key:string,signal?:AbortSignal){if(!key)throw new OtxError("OTX_CREDENTIAL_REQUIRED");const {json}=await request(queryUrl(1,undefined,1),key,signal);if(!json||typeof json!=="object")throw new OtxError("OTX_INVALID_RESPONSE")}
export async function fetchSubscribedPulses(key:string,modifiedSince:string,signal?:AbortSignal){if(!key)throw new OtxError("OTX_CREDENTIAL_REQUIRED");let page=1,total=0,indicators=0;const results:unknown[]=[];const visited=new Set<number>();while(page){if(visited.has(page))throw new OtxError("OTX_PAGINATION_LOOP");if(visited.size>=OTX_MAX_PAGES)throw new OtxError("OTX_ITEM_LIMIT");visited.add(page);const response=await request(queryUrl(page,modifiedSince),key,signal);total+=Buffer.byteLength(response.text);if(total>TOTAL_BYTES)throw new OtxError("OTX_RESPONSE_TOO_LARGE");const parsed=envelopeSchema.safeParse(response.json);if(!parsed.success)throw new OtxError("OTX_INVALID_RESPONSE");results.push(...parsed.data.results);if(results.length>OTX_MAX_PULSES)throw new OtxError("OTX_ITEM_LIMIT");for(const p of parsed.data.results)if(p&&typeof p==="object"&&Array.isArray((p as {indicators?:unknown}).indicators))indicators+=(p as {indicators:unknown[]}).indicators.length;if(indicators>OTX_MAX_INDICATORS)throw new OtxError("OTX_ITEM_LIMIT");page=parsed.data.next?validateNext(parsed.data.next,modifiedSince):0}return results}
