import {createHash} from "node:crypto";
import {ZodError} from "zod";
import {normalizeProviderItem} from "../../normalize";
import type {IocCandidateType,ProviderSkipReason} from "../../types";
import {pulseSchema} from "./schema";
export class OtxMappingError extends Error{constructor(public reason:ProviderSkipReason){super(reason)}}
const types:Record<string,IocCandidateType>={IPv4:"IPV4",ipv4:"IPV4",IPv6:"IPV6",ipv6:"IPV6",CIDR:"CIDR",cidr:"CIDR",domain:"DOMAIN",Domain:"DOMAIN",hostname:"HOSTNAME",Hostname:"HOSTNAME",URL:"URL",url:"URL","FileHash-MD5":"MD5","FileHash-SHA1":"SHA1","FileHash-SHA256":"SHA256",CVE:"CVE",cve:"CVE"};
function date(v:string|null|undefined){if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(v))throw new OtxMappingError("INVALID_DATE");const d=new Date(v);if(Number.isNaN(d.valueOf()))throw new OtxMappingError("INVALID_DATE");return d.toISOString()}
const safeReferences=(a:string[])=>a.filter(v=>{try{return ["http:","https:"].includes(new URL(v).protocol)}catch{return false}});
export function parseOtxPulse(raw:unknown){try{return pulseSchema.parse(raw)}catch(e){if(e instanceof ZodError)throw new OtxMappingError("INVALID_PROVIDER_RECORD");throw e}}
export function mapOtxIndicator(pulse:ReturnType<typeof parseOtxPulse>,indicator:ReturnType<typeof parseOtxPulse>["indicators"][number]){if(indicator.is_active===false||indicator.active===false)throw new OtxMappingError("INACTIVE_PROVIDER_RECORD");const type=types[indicator.type];if(!type)throw new OtxMappingError("UNSUPPORTED_IOC_TYPE");const first=date(indicator.created),last=date(indicator.modified);if(first&&last&&last<first)throw new OtxMappingError("INVALID_DATE_ORDER");const iid=indicator.id?String(indicator.id):null;const provenance=`ALIENVAULT_OTX\0${pulse.id}\0${iid??indicator.type}\0${iid?indicator.type:indicator.indicator}`;try{const item=normalizeProviderItem({providerKey:"ALIENVAULT_OTX",providerItemId:`${pulse.id}:${iid??createHash("sha256").update(`${indicator.type}\0${indicator.indicator}`).digest("hex")}`,type,value:indicator.indicator,provider_reference_url:`https://otx.alienvault.com/pulse/${pulse.id}`,confidence_score:null,first_seen_at:first,last_seen_at:last,tags:["ALIENVAULT_OTX",...pulse.tags.slice(0,49)],metadata:{otx_pulse:{id:pulse.id,name:pulse.name,description:pulse.description,author_name:pulse.author_name??(typeof pulse.author==="string"?pulse.author:pulse.author?.username)??null,tlp:["white","green","amber","red"].includes((pulse.TLP??"").toLowerCase())?(pulse.TLP??"").toLowerCase():"unknown",created:date(pulse.created),modified:date(pulse.modified),tags:pulse.tags,references:safeReferences(pulse.references),adversary:pulse.adversary??null,targeted_countries:pulse.targeted_countries,industries:pulse.industries,malware_families:pulse.malware_families,attack_ids:pulse.attack_ids},otx_indicator:{id:iid,type:indicator.type,created:first,modified:last}}});return{...item,source_fingerprint:createHash("sha256").update(provenance).digest("hex")}}catch(e){if(e instanceof OtxMappingError)throw e;if(e instanceof Error&&e.message==="INVALID_CANDIDATE_VALUE")throw new OtxMappingError("INVALID_IOC");throw e}}
