import {createHash} from "node:crypto";
import {ZodError} from "zod";
import {normalizeProviderItem} from "../../normalize";
import type {IocCandidateType,ProviderSkipReason} from "../../types";
import {OtxError} from "./errors";
import {otxIndicatorSchema,pulseContextObjectSchema,pulseIdentitySchema} from "./schema";
export class OtxMappingError extends Error{constructor(public reason:ProviderSkipReason){super(reason)}}
const types:Record<string,IocCandidateType>={IPv4:"IPV4",ipv4:"IPV4",IPv6:"IPV6",ipv6:"IPV6",CIDR:"CIDR",cidr:"CIDR",domain:"DOMAIN",Domain:"DOMAIN",hostname:"HOSTNAME",Hostname:"HOSTNAME",URL:"URL",url:"URL","FileHash-MD5":"MD5","FileHash-SHA1":"SHA1","FileHash-SHA256":"SHA256",CVE:"CVE",cve:"CVE"};
export const pulseContextCategories=["name","description","author","tlp","tags","references","adversary","targeted_countries","industries","malware_families","attack_ids"] as const;
export type PulseContextCategory=typeof pulseContextCategories[number];
export type PulseNormalizationDiagnostics={pulse_context_fields_dropped:Partial<Record<PulseContextCategory,number>>;pulse_context_items_dropped:number;invalid_identity_pulse_count:number};
type ParsedPulseIdentity=ReturnType<typeof pulseIdentitySchema.parse>;
export type ParsedOtxPulse=ParsedPulseIdentity&{name:string;description:string;author_name?:string;TLP?:string;tags:string[];references:string[];adversary:string|null;targeted_countries:string[];industries:string[];malware_families:string[];attack_ids:string[];normalization:PulseNormalizationDiagnostics};
function date(v:string|null|undefined){if(!v)return null;if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(v))throw new OtxMappingError("INVALID_DATE");const d=new Date(v);if(Number.isNaN(d.valueOf()))throw new OtxMappingError("INVALID_DATE");return d.toISOString()}
const record=(raw:unknown):Record<string,unknown>=>raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};
function normalizePulseContext(raw:unknown,identity:ParsedPulseIdentity):ParsedOtxPulse{
 const source=record(raw),dropped:Partial<Record<PulseContextCategory,number>>={},diagnostics:PulseNormalizationDiagnostics={pulse_context_fields_dropped:dropped,pulse_context_items_dropped:0,invalid_identity_pulse_count:0};
 const fieldDrop=(category:PulseContextCategory)=>{dropped[category]=(dropped[category]??0)+1};
 const scalar=(category:PulseContextCategory,value:unknown,max:number,fallback="")=>{if(value==null)return fallback;if(typeof value==="string"&&value.length<=max&&(category!=="name"||value.length>0))return value;fieldDrop(category);return fallback};
 const objectValue=(value:unknown,priority:("display_name"|"name"|"id"|"username")[])=>{if(typeof value==="string"&&value.length<=200)return value;const parsed=pulseContextObjectSchema.safeParse(value);if(!parsed.success)return null;for(const key of priority){const selected=parsed.data[key];if(selected)return selected}return null};
 const list=(category:PulseContextCategory,max:number,format:(value:unknown)=>string|null)=>{const value=source[category];if(value==null)return[];if(!Array.isArray(value)){fieldDrop(category);return[]}const output:string[]=[];for(const item of value){const normalized=format(item);if(!normalized||output.includes(normalized)||output.length>=max){diagnostics.pulse_context_items_dropped++;continue}output.push(normalized)}return output};
 const ordinary=(value:unknown)=>objectValue(value,["display_name","name","id"]);
 const references=list("references",25,value=>{if(typeof value!=="string"||value.length>4096)return null;try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)&&!url.username&&!url.password?url.toString():null}catch{return null}});
 const attack=list("attack_ids",100,value=>{if(typeof value==="string"&&value.length<=200)return value;const parsed=pulseContextObjectSchema.safeParse(value);if(!parsed.success)return null;const id=parsed.data.id,label=parsed.data.display_name??parsed.data.name;if(id&&label&&id!==label)return`${id} — ${label}`;return id??label??null});
 const author=objectValue(source.author_name??source.author,["display_name","name","username","id"]);
 if((source.author_name??source.author)!=null&&!author)fieldDrop("author");
 const tlp=scalar("tlp",source.TLP,20);
 return{...identity,created:identity.created?new Date(identity.created).toISOString():identity.created,modified:new Date(identity.modified).toISOString(),name:scalar("name",source.name,300,"Unnamed OTX Pulse"),description:scalar("description",source.description,4000),author_name:author??undefined,TLP:tlp||undefined,tags:list("tags",50,ordinary),references,adversary:source.adversary==null?null:(ordinary(source.adversary)??(fieldDrop("adversary"),null)),targeted_countries:list("targeted_countries",50,ordinary),industries:list("industries",50,ordinary),malware_families:list("malware_families",50,value=>objectValue(value,["display_name","name","id"])),attack_ids:attack,normalization:diagnostics};
}
export function parseOtxPulse(raw:unknown):ParsedOtxPulse{const identity=pulseIdentitySchema.safeParse(raw);if(!identity.success)throw new OtxError("OTX_INVALID_RESPONSE",false,undefined,{pulse_context_fields_dropped:{},pulse_context_items_dropped:0,invalid_identity_pulse_count:1});return normalizePulseContext(raw,identity.data)}
export function mapOtxIndicator(pulse:ParsedOtxPulse,raw:unknown){let indicator;try{indicator=otxIndicatorSchema.parse(raw)}catch(e){if(e instanceof ZodError)throw new OtxMappingError("INVALID_PROVIDER_RECORD");throw e}if(indicator.is_active===false||indicator.active===false)throw new OtxMappingError("INACTIVE_PROVIDER_RECORD");const type=types[indicator.type];if(!type)throw new OtxMappingError("UNSUPPORTED_IOC_TYPE");const first=date(indicator.created),last=date(indicator.modified);if(first&&last&&last<first)throw new OtxMappingError("INVALID_DATE_ORDER");const iid=indicator.id?String(indicator.id):null;const provenance=`ALIENVAULT_OTX\0${pulse.id}\0${iid??indicator.type}\0${iid?indicator.type:indicator.indicator}`;try{const item=normalizeProviderItem({providerKey:"ALIENVAULT_OTX",providerItemId:`${pulse.id}:${iid??createHash("sha256").update(`${indicator.type}\0${indicator.indicator}`).digest("hex")}`,type,value:indicator.indicator,provider_reference_url:`https://otx.alienvault.com/pulse/${pulse.id}`,confidence_score:null,first_seen_at:first,last_seen_at:last,tags:["ALIENVAULT_OTX",...pulse.tags.slice(0,49)],metadata:{otx_pulse:{id:pulse.id,name:pulse.name,description:pulse.description,author_name:pulse.author_name??null,tlp:["white","green","amber","red"].includes((pulse.TLP??"").toLowerCase())?(pulse.TLP??"").toLowerCase():"unknown",created:date(pulse.created),modified:date(pulse.modified),tags:pulse.tags,references:pulse.references,adversary:pulse.adversary,targeted_countries:pulse.targeted_countries,industries:pulse.industries,malware_families:pulse.malware_families,attack_ids:pulse.attack_ids},otx_indicator:{id:iid,type:indicator.type,created:first,modified:last}}});return{...item,source_fingerprint:createHash("sha256").update(provenance).digest("hex")}}catch(e){if(e instanceof OtxMappingError)throw e;if(e instanceof Error&&e.message==="INVALID_CANDIDATE_VALUE")throw new OtxMappingError("INVALID_IOC");throw e}}
