import {describe,expect,it} from "vitest";
import {buildOtxResult} from "./adapter";
import {OtxError} from "./errors";
import {mapOtxIndicator,parseOtxPulse} from "./mapping";
const id="0123456789abcdef01234567",modified="2026-08-01T10:00:00.000Z",indicator={id:"stable",type:"domain",indicator:"example.com"};
const pulse=(context:Record<string,unknown>={})=>({id,created:modified,modified,indicators:[indicator],...context});
const metadata=(context:Record<string,unknown>)=>mapOtxIndicator(parseOtxPulse(pulse(context)),indicator).metadata.otx_pulse as Record<string,unknown>;
describe("real OTX Pulse context normalization",()=>{
 it("accepts malware family strings",()=>expect(metadata({malware_families:["Alpha","Beta"]}).malware_families).toEqual(["Alpha","Beta"]));
 it("normalizes malware family objects by display_name, name, then id",()=>expect(metadata({malware_families:[{id:"m1",name:"Name",display_name:"Display"},{id:"m2",name:"Second"},{id:"m3"}]}).malware_families).toEqual(["Display","Second","m3"]));
 it("accepts ATT&CK strings and renders bounded objects readably",()=>expect(metadata({attack_ids:["T1001",{id:"T1002",display_name:"Data Compressed"},{id:"T1003",name:"Credential Dumping"},{name:"Name only"}]}).attack_ids).toEqual(["T1001","T1002 — Data Compressed","T1003 — Credential Dumping","Name only"]));
 it("handles mixed string, object, and null context",()=>{const parsed=parseOtxPulse(pulse({tags:["tag",null,{display_name:"object tag"}],industries:[null,"Finance",{name:"Technology"}],targeted_countries:["TR",{display_name:"Türkiye"},42],adversary:{name:"Synthetic actor"}}));expect(parsed.tags).toEqual(["tag","object tag"]);expect(parsed.industries).toEqual(["Finance","Technology"]);expect(parsed.targeted_countries).toEqual(["TR","Türkiye"]);expect(parsed.adversary).toBe("Synthetic actor");expect(parsed.normalization.pulse_context_items_dropped).toBeGreaterThan(0)});
 it("supplies bounded defaults when optional context is absent",()=>expect(metadata({})).toMatchObject({name:"Unnamed OTX Pulse",description:"",tags:[],references:[],malware_families:[],attack_ids:[]}));
 it("deduplicates deterministically and drops unsafe references",()=>{const parsed=parseOtxPulse(pulse({malware_families:["Alpha",{name:"Alpha"},null],references:["https://example.com/a","https://example.com/a","javascript:alert(1)","https://u:p@example.com/"]}));expect(parsed.malware_families).toEqual(["Alpha"]);expect(parsed.references).toEqual(["https://example.com/a"]);expect(parsed.normalization.pulse_context_items_dropped).toBe(5)});
 it("drops malformed optional context without aborting indicators",()=>{const result=buildOtxResult([pulse({name:{raw:"secret Pulse"},description:Array(5000).fill("raw"),malware_families:{raw:"provider object"},attack_ids:[{raw:"unknown"}],references:["raw-body-marker"]})],null,{now:new Date("2026-08-01T12:00:00.000Z")});expect(result.status).toBe("SUCCEEDED");expect(result.items).toHaveLength(1);expect(result.diagnostics.pulse_context_fields_dropped).toMatchObject({name:1,description:1,malware_families:1});expect(JSON.stringify(result.diagnostics)).not.toContain("secret Pulse");expect(JSON.stringify(result.diagnostics)).not.toContain("raw-body-marker")});
 it("turns malformed indicators into skip markers",()=>{const result=buildOtxResult([{...pulse(),indicators:[{id:"bad",type:"domain"},indicator]}],null,{now:new Date("2026-08-01T12:00:00.000Z")});expect(result.items).toContainEqual({provider_skip_reason:"INVALID_PROVIDER_RECORD"});expect(result.items.some(item=>"normalized_value" in item&&item.normalized_value==="example.com")).toBe(true)});
 it.each([{...pulse(),id:"NOT-A-PULSE-ID"},{...pulse(),modified:"not-a-date"},{...pulse(),modified:undefined}])("fails invalid synchronization identity as OTX_INVALID_RESPONSE",raw=>{try{buildOtxResult([raw],null);throw new Error("expected controlled failure")}catch(error){expect(error).toBeInstanceOf(OtxError);expect((error as OtxError).code).toBe("OTX_INVALID_RESPONSE");expect(JSON.stringify(error)).not.toContain("NOT-A-PULSE-ID");expect(JSON.stringify(error)).not.toContain("not-a-date");expect((error as OtxError).diagnostics).toEqual({pulse_context_fields_dropped:{},pulse_context_items_dropped:0,invalid_identity_pulse_count:1})}});
 it("keeps continuation identity independent of optional context",()=>{const indicators=Array.from({length:1001},(_,index)=>({id:`i-${index}`,type:"domain",indicator:`i${index}.example.com`})),a=buildOtxResult([{...pulse({name:"One",malware_families:["Alpha"]}),indicators}],null,{now:new Date("2026-08-01T12:00:00.000Z")}),b=buildOtxResult([{...pulse({name:"Two",malware_families:[{display_name:"Beta"}],attack_ids:[{id:"T1001",name:"Technique"}]}),indicators}],null,{now:new Date("2026-08-01T12:00:00.000Z")});expect(a.nextCursor).toBe(b.nextCursor);expect(a.items).toHaveLength(1000);expect(b.items).toHaveLength(1000)});
});
