import {afterEach,describe,expect,it,vi} from "vitest";
import {fetchOtxPulse,searchOtxPulses} from "./client";
const id="0123456789abcdef01234567",pulse={id,name:"Search result",description:"bounded",modified:"2026-08-01T10:00:00Z",author_name:"analyst",TLP:"amber",indicator_count:1,tags:["tag"]};
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllGlobals()});
describe("OTX Pulse search transport",()=>{
 it("uses the fixed search endpoint and returns bounded summaries",async()=>{const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[pulse],count:1})));vi.stubGlobal("fetch",fetchMock);const result=await searchOtxPulses("owner-key","example threat");const [url,init]=fetchMock.mock.calls[0];expect(String(url)).toBe("https://otx.alienvault.com/api/v1/search/pulses?q=example+threat&page=1&limit=5");expect(init).toMatchObject({method:"GET",redirect:"error",headers:{"X-OTX-API-KEY":"owner-key"}});expect(result).toEqual([{id,name:"Search result",description:"bounded",modified:"2026-08-01T10:00:00.000Z",author_name:"analyst",tlp:"amber",indicator_count:1,tags:["tag"],reference_url:`https://otx.alienvault.com/pulse/${id}`}])});
 it.each(["","x","x".repeat(121)])("rejects invalid query %j without a request",async query=>{const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);await expect(searchOtxPulses("key",query)).rejects.toMatchObject({code:"OTX_QUERY_FAILED"});expect(fetchMock).not.toHaveBeenCalled()});
 it.each([[401,"OTX_SEARCH_AUTH_FAILED"],[403,"OTX_SEARCH_AUTH_FAILED"],[429,"OTX_SEARCH_RATE_LIMITED"],[500,"OTX_SEARCH_NETWORK_FAILURE"]] as const)("classifies HTTP %s",async(status,code)=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("controlled",{status})));await expect(searchOtxPulses("key","query")).rejects.toMatchObject({code})});
 it("rejects malformed and excessive search results",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValueOnce(new Response("not-json")));await expect(searchOtxPulses("key","query")).rejects.toMatchObject({code:"OTX_SEARCH_INVALID_RESPONSE"});vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({results:Array.from({length:26},()=>pulse)}))));await expect(searchOtxPulses("key","query")).rejects.toMatchObject({code:"OTX_SEARCH_INVALID_RESPONSE"})});
 it("does not expose the key or raw response in errors",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("raw-provider-body",{status:500})));try{await searchOtxPulses("owner-secret-key","query")}catch(error){expect(JSON.stringify(error)).not.toContain("owner-secret-key");expect(JSON.stringify(error)).not.toContain("raw-provider-body")}});
});
describe("selected Pulse refetch",()=>{
 it("rejects a tampered Pulse ID without a request",async()=>{const fetchMock=vi.fn();vi.stubGlobal("fetch",fetchMock);await expect(fetchOtxPulse("key","../../public")).rejects.toMatchObject({code:"OTX_INVALID_RESPONSE"});expect(fetchMock).not.toHaveBeenCalled()});
 it("refetches fixed Pulse detail and indicator endpoints",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(pulse))).mockResolvedValueOnce(new Response(JSON.stringify({results:[{id:"i",type:"domain",indicator:"example.com"}]})));vi.stubGlobal("fetch",fetchMock);const result=await fetchOtxPulse("key",id);expect(fetchMock.mock.calls.map(call=>String(call[0]))).toEqual([`https://otx.alienvault.com/api/v1/pulses/${id}`,`https://otx.alienvault.com/api/v1/pulses/${id}/indicators`]);expect(result).toMatchObject({id,indicators:[{indicator:"example.com"}]})});
});
describe("OTX search timeout boundary",()=>{
 it("allows search to complete after fifteen but before thirty seconds",async()=>{vi.useFakeTimers();vi.stubGlobal("fetch",vi.fn((_url,init)=>new Promise<Response>((resolve,reject)=>{const timer=setTimeout(()=>resolve(new Response(JSON.stringify({results:[pulse]}))),20_000);init?.signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(new DOMException("aborted","AbortError"))})})));let settled=false;const request=searchOtxPulses("key","  specific query  ").finally(()=>{settled=true});await vi.advanceTimersByTimeAsync(15_000);expect(settled).toBe(false);await vi.advanceTimersByTimeAsync(5_000);await expect(request).resolves.toHaveLength(1);expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("q=specific+query");vi.useRealTimers()});
 it("aborts search at thirty seconds without exposing secrets or bodies",async()=>{vi.useFakeTimers();vi.stubGlobal("fetch",vi.fn((_url,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("raw-provider-body","AbortError"))))));const assertion=expect(searchOtxPulses("owner-secret","specific query")).rejects.toMatchObject({code:"OTX_SEARCH_TIMEOUT"});await vi.advanceTimersByTimeAsync(29_999);expect(vi.mocked(fetch)).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);await assertion.catch(error=>{expect(JSON.stringify(error)).not.toContain("owner-secret");expect(JSON.stringify(error)).not.toContain("raw-provider-body")});vi.useRealTimers()});
});
describe("global pagination and exact lookup routing",()=>{
 it("requests only the selected bounded global page with five results",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[pulse]}))));await searchOtxPulses("key","campaign name",3);expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("/api/v1/search/pulses?q=campaign+name&page=3&limit=5");expect(vi.mocked(fetch)).toHaveBeenCalledTimes(1)});
 it.each([0,6])("rejects global page %s without provider access",async page=>{const request=vi.fn();vi.stubGlobal("fetch",request);await expect(searchOtxPulses("key","campaign",page)).rejects.toMatchObject({code:"OTX_QUERY_FAILED"});expect(request).not.toHaveBeenCalled()});
 it("uses indicator general lookup for an exact observable and never subscribed Pulses",async()=>{const body={reputation:2,references:["https://example.com/reference"],pulse_info:{pulses:[pulse]}};vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify(body))));const {lookupOtxIndicator}=await import("./client"),result=await lookupOtxIndicator("key","192.0.2.1");const url=String(vi.mocked(fetch).mock.calls[0][0]);expect(url).toContain("/api/v1/indicators/IPv4/192.0.2.1/general");expect(url).not.toContain("/pulses/subscribed");expect(result).toMatchObject({mode:"EXACT",observable_type:"IPv4",reputation:2,pulses:[{id}]})});
 it("uses global Pulse search for free text and never subscribed Pulses",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[]}))));await searchOtxPulses("key","malware campaign",1);const url=String(vi.mocked(fetch).mock.calls[0][0]);expect(url).toContain("/api/v1/search/pulses");expect(url).not.toContain("/pulses/subscribed")});
});
