"use server";
import {createHash} from "node:crypto";
import {revalidatePath} from "next/cache";
import {requireUser} from "@/lib/auth";
import {normalizeFeedUrl} from "@/lib/research-feeds/url";
import {ingestGlobalResearchFeed} from "@/lib/osint/orchestrator";
import {feedInputSchema,idSchema,linkSchema,triageSchema} from "@/lib/osint/schema";
import {archiveGlobalFeed,createGlobalFeed,editGlobalFeed,restoreGlobalFeed,setGlobalFeedState} from "@/lib/research-feeds/trusted-workflow-client";

export type OsintActionResult={success?:string;error?:string};
const refresh=()=>revalidatePath("/osint");
const hash=(url:string)=>createHash("sha256").update(url).digest("hex");
const safe=()=>({error:"The OSINT change could not be completed safely."});
export async function createOsintFeed(form:FormData):Promise<OsintActionResult>{try{const {user}=await requireUser();const parsed=feedInputSchema.safeParse({name:form.get("name"),description:form.get("description")??"",url:form.get("url"),enabled:form.get("enabled")!=="false",schedulerEnabled:form.get("scheduler_enabled")!=="false",interval:form.get("interval")});if(!parsed.success||!parsed.data.url)return{error:parsed.error?.issues[0]?.message??"A feed URL is required."};const url=normalizeFeedUrl(parsed.data.url).toString();const {error}=await createGlobalFeed({p_actor_id:user.id,p_name:parsed.data.name,p_description:parsed.data.description,p_configured_url:url,p_configured_url_hash:hash(url),p_enabled:parsed.data.enabled,p_scheduler_enabled:parsed.data.schedulerEnabled,p_interval:parsed.data.interval});if(error)return safe();refresh();return{success:"Feed created and scheduled."}}catch{return safe()}}
export async function updateOsintFeed(feedId:string,form:FormData):Promise<OsintActionResult>{try{const {user}=await requireUser();if(!idSchema.safeParse(feedId).success)return safe();const raw=String(form.get("url")??"").trim();const parsed=feedInputSchema.safeParse({name:form.get("name"),description:form.get("description")??"",url:raw||undefined,enabled:form.get("enabled")==="true",schedulerEnabled:form.get("scheduler_enabled")==="true",interval:form.get("interval")});if(!parsed.success)return{error:parsed.error.issues[0]?.message};const url=raw?normalizeFeedUrl(raw).toString():null;const {error}=await editGlobalFeed({p_actor_id:user.id,p_feed_source_id:feedId,p_name:parsed.data.name,p_description:parsed.data.description,p_configured_url:url,p_configured_url_hash:url?hash(url):null,p_enabled:parsed.data.enabled,p_scheduler_enabled:parsed.data.schedulerEnabled,p_interval:parsed.data.interval});if(error)return safe();refresh();return{success:"Feed settings saved."}}catch{return safe()}}
export async function changeOsintFeedState(feedId:string,enabled:boolean,schedulerEnabled:boolean,interval:number):Promise<OsintActionResult>{try{const {user}=await requireUser();if(!idSchema.safeParse(feedId).success)return safe();const {error}=await setGlobalFeedState({p_actor_id:user.id,p_feed_source_id:feedId,p_enabled:enabled,p_scheduler_enabled:schedulerEnabled,p_interval:interval});if(error)return safe();refresh();return{success:"Feed state updated."}}catch{return safe()}}
export async function archiveOsintFeed(feedId:string,restore=false):Promise<OsintActionResult>{try{const {user}=await requireUser();if(!idSchema.safeParse(feedId).success)return safe();const {error}=await (restore?restoreGlobalFeed:archiveGlobalFeed)({p_actor_id:user.id,p_feed_source_id:feedId});if(error)return safe();refresh();return{success:restore?"Feed restored in a paused state.":"Feed archived."}}catch{return safe()}}
export async function fetchOsintFeedNow(feedId:string):Promise<OsintActionResult>{if(!idSchema.safeParse(feedId).success)return safe();const result=await ingestGlobalResearchFeed(feedId,"MANUAL");refresh();return result}
export async function setOsintItemState(itemId:string,action:string):Promise<OsintActionResult>{try{const {user,supabase}=await requireUser();const parsed=triageSchema.safeParse({itemId,action});if(!parsed.success)return safe();const now=new Date().toISOString(),field=action==="read"||action==="unread"?"read_at":action==="save"||action==="unsave"?"saved_at":"dismissed_at",value=["unread","unsave","restore"].includes(action)?null:now;const {error}=await supabase.from("osint_item_states").upsert({owner_id:user.id,research_item_id:itemId,[field]:value,updated_at:now},{onConflict:"owner_id,research_item_id"});if(error)return safe();refresh();return{success:"Item state updated."}}catch{return safe()}}
export async function linkOsintItem(itemId:string,form:FormData):Promise<OsintActionResult>{try{const {user,supabase}=await requireUser();const parsed=linkSchema.safeParse({itemId,projectId:form.get("project_id"),note:form.get("note")??""});if(!parsed.success)return{error:parsed.error.issues[0]?.message};const {error}=await supabase.from("osint_investigation_links").insert({owner_id:user.id,created_by:user.id,research_item_id:itemId,project_id:parsed.data.projectId,analyst_note:parsed.data.note});if(error)return{error:error.code==="23505"?"This item is already linked to that Investigation.":"The item could not be linked."};refresh();revalidatePath(`/projects/${parsed.data.projectId}`);return{success:"Item linked to the Investigation."}}catch{return safe()}}
export async function unlinkOsintItem(linkId:string,projectId:string):Promise<OsintActionResult>{try{const {supabase}=await requireUser();if(!idSchema.safeParse(linkId).success||!idSchema.safeParse(projectId).success)return safe();const {error}=await supabase.from("osint_investigation_links").delete().eq("id",linkId).eq("project_id",projectId);if(error)return safe();revalidatePath(`/projects/${projectId}`);return{success:"OSINT link removed; the global item was preserved."}}catch{return safe()}}
