import {beforeEach,describe,expect,it,vi} from "vitest";
import {OtxError} from "@/lib/ioc-connectors/providers/otx/errors";
import {IocCredentialError} from "@/lib/ioc-connectors/credentials/errors";

const mocks=vi.hoisted(()=>({testConnection:vi.fn(),configure:vi.fn(),credentialExists:vi.fn(),encrypt:vi.fn(),revalidate:vi.fn(),requireUser:vi.fn()}));
vi.mock("next/cache",()=>({revalidatePath:mocks.revalidate}));
vi.mock("@/lib/auth",()=>({requireUser:mocks.requireUser}));
vi.mock("@/lib/ioc-connectors/registry",()=>({getProvider:(key:string)=>key==="ALIENVAULT_OTX"?{testConnection:mocks.testConnection}:undefined}));
vi.mock("@/lib/ioc-connectors/credentials/crypto",()=>({encryptCredential:mocks.encrypt}));
vi.mock("@/lib/ioc-connectors/trusted-workflow-client",()=>({configureOtxConnection:mocks.configure,otxCredentialExists:mocks.credentialExists,disconnectOtxCredential:vi.fn(),updateOtxSettings:vi.fn(),ensureSyntheticConnection:vi.fn(),setIocConnectionEnabled:vi.fn(),configureThreatFoxConnection:vi.fn(),disconnectThreatFoxCredential:vi.fn(),updateThreatFoxSettings:vi.fn()}));
import {reconnectOtx} from "./ioc-actions";

const owner="11111111-1111-4111-8111-111111111111",id="22222222-2222-4222-8222-222222222222";
type State={connection:null|Record<string,unknown>;setting:null|{bootstrap_lookback_days:number};tables:string[]};
type Query={select:()=>Query;eq:()=>Query;maybeSingle:()=>Promise<{data:unknown;error:null}>};
function userClient(state:State){return{from:(table:string)=>{state.tables.push(table);const query:Query={select:()=>query,eq:()=>query,maybeSingle:async()=>table==="otx_connection_settings"?{data:state.setting,error:null}:{data:state.connection,error:null}};return query}}}
const form=(key="valid-key",lookback?:number)=>{const value=new FormData();value.set("api_key",key);if(lookback!==undefined)value.set("bootstrap_lookback_days",String(lookback));return value};
function ready(lookback=1){const state:State={connection:{id,provider_key:"ALIENVAULT_OTX",enabled:false,archived_at:null},setting:{bootstrap_lookback_days:lookback},tables:[]};mocks.requireUser.mockResolvedValue({user:{id:owner},supabase:userClient(state)});mocks.encrypt.mockReturnValue({ciphertext_b64:"cipher",iv_b64:"iv-value-value-value",auth_tag_b64:"tag-value-value-value",key_version:1});mocks.configure.mockImplementation(async(parameters:Record<string,unknown>)=>{state.connection={id,provider_key:"ALIENVAULT_OTX",enabled:true,health_status:"HEALTHY",last_error_code:null,last_error_message:null};return{data:id,error:null,parameters}});mocks.credentialExists.mockResolvedValue({exists:true,error:null});return state}
beforeEach(()=>{vi.clearAllMocks();mocks.testConnection.mockResolvedValue(undefined)});
describe("reconnectOtx",()=>{
 it("rejects a malformed identifier before lookup",async()=>{expect(await reconnectOtx("bad",{},form())).toEqual({error:"The IOC Inbox action could not be completed safely."});expect(mocks.requireUser).not.toHaveBeenCalled()});
 it("rejects missing/cross-owner, non-OTX, archived, and enabled connections",async()=>{for(const connection of [null,{id,provider_key:"THREATFOX",enabled:false,archived_at:null},{id,provider_key:"ALIENVAULT_OTX",enabled:false,archived_at:"2026-01-01"},{id,provider_key:"ALIENVAULT_OTX",enabled:true,archived_at:null}]){const state:State={connection,setting:{bootstrap_lookback_days:1},tables:[]};mocks.requireUser.mockResolvedValue({user:{id:owner},supabase:userClient(state)});expect(await reconnectOtx(id,{},form())).toEqual({error:"The IOC Inbox action could not be completed safely."});expect(mocks.testConnection).not.toHaveBeenCalled();vi.clearAllMocks()}});
 it("preserves the stored one-day setting and existing connection ID by default",async()=>{const state=ready(1);const result=await reconnectOtx(id,{},form());expect(result.success).toMatch(/reconnected successfully/);expect(mocks.configure).toHaveBeenCalledWith(expect.objectContaining({p_connection_id:id,p_owner_id:owner,p_bootstrap_lookback_days:1}));expect(state.tables).toEqual(["ioc_provider_connections","otx_connection_settings","ioc_provider_connections"])});
 it("accepts an explicit supported setting and rejects unsupported settings",async()=>{ready();await reconnectOtx(id,{},form("valid-key",14));expect(mocks.configure).toHaveBeenCalledWith(expect.objectContaining({p_bootstrap_lookback_days:14}));vi.clearAllMocks();ready();expect(await reconnectOtx(id,{},form("valid-key",2))).toEqual({error:"Choose a supported AlienVault OTX bootstrap look-back."});expect(mocks.testConnection).not.toHaveBeenCalled()});
 it("tests before encrypting and never persists authentication failures",async()=>{ready();mocks.testConnection.mockRejectedValue(new OtxError("OTX_AUTH_FAILED"));expect(await reconnectOtx(id,{},form())).toEqual({error:"AlienVault OTX rejected this API key."});expect(mocks.encrypt).not.toHaveBeenCalled();expect(mocks.configure).not.toHaveBeenCalled()});
 it("classifies rate limits and transport failures safely",async()=>{for(const [error,message] of [[new OtxError("OTX_RATE_LIMITED"),"AlienVault OTX rate limited the credential test. Try again later."],[new OtxError("OTX_TIMEOUT"),"AlienVault OTX could not be reached during the credential test."]]){ready();mocks.testConnection.mockRejectedValueOnce(error);expect(await reconnectOtx(id,{},form())).toEqual({error:message});expect(mocks.configure).not.toHaveBeenCalled();vi.clearAllMocks()}});
 it("does not save when encryption configuration is unavailable",async()=>{ready();mocks.encrypt.mockImplementation(()=>{throw new IocCredentialError("IOC_CREDENTIAL_CONFIGURATION_INVALID")});expect(await reconnectOtx(id,{},form())).toEqual({error:"The server credential-encryption configuration is unavailable."});expect(mocks.configure).not.toHaveBeenCalled()});
 it("returns a controlled RPC error",async()=>{ready();mocks.configure.mockResolvedValue({data:null,error:{message:"raw database detail"}});const result=await reconnectOtx(id,{},form("secret-value"));expect(result).toEqual({error:"The AlienVault OTX credential was tested, but the connection could not be saved."});expect(JSON.stringify(result)).not.toContain("secret-value");expect(JSON.stringify(result)).not.toContain("raw database")});
 it("fails closed when post-write connection or credential verification fails",async()=>{ready();mocks.credentialExists.mockResolvedValue({exists:false,error:null});expect(await reconnectOtx(id,{},form())).toEqual({error:"The AlienVault OTX connection could not be verified after saving."})});
 it("clears connection error state, verifies credential presence, and does not touch history",async()=>{const state=ready(1);expect(await reconnectOtx(id,{},form())).toEqual({success:"AlienVault OTX reconnected successfully. Historical IOC data and Pulse provenance were preserved."});expect(state.connection).toMatchObject({id,enabled:true,health_status:"HEALTHY",last_error_code:null,last_error_message:null});expect(mocks.credentialExists).toHaveBeenCalledWith(owner,id);expect(state.tables).not.toContain("ioc_ingestion_runs");expect(state.tables).not.toContain("ioc_provider_cursors");expect(mocks.revalidate).toHaveBeenCalledWith("/osint")});
});
