import { describe, expect, it } from "vitest";
import { campaignSchema, cveSchema, indicatorSchema, malwareSchema, mitreSchema, parseRelationshipSelections, validateIndicator } from "@/lib/cti-schema";
const ids=["00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000002","00000000-0000-4000-8000-000000000003"];
describe("cti schema validation",()=>{
  it("preserves all repeated multi-select relationship IDs and deduplicates",()=>{const fd=new FormData(); ids.forEach(id=>fd.append("malware_ids",id)); fd.append("malware_ids",ids[1]); const parsed=parseRelationshipSelections(fd); expect(parsed.success&&parsed.data.malware_ids).toEqual(ids);});
  it("rejects invalid relationship IDs",()=>{const fd=new FormData(); fd.append("indicator_ids","not-a-uuid"); expect(parseRelationshipSelections(fd)).toEqual({success:false,error:"indicator ids contains an invalid ID."});});
  it("validates standards-compliant IPs and rejects malformed IPv6",()=>{expect(validateIndicator("2001:db8::1","IP")).toBeNull(); expect(validateIndicator("999.1.1.1","IP")).toMatch(/valid IPv4/); expect(validateIndicator(":::::","IP")).toMatch(/valid IPv4/);});
  it("normalizes hash indicators to lowercase",()=>{const r=indicatorSchema.parse({value:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",type:"HASH",confidence:"HIGH",tags:"",first_seen:"",last_seen:""}); expect(r.value).toBe("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");});
  it("keeps URL domain email CVE and MITRE validation",()=>{expect(indicatorSchema.safeParse({value:"https://example.com/a",type:"URL",confidence:"LOW"}).success).toBe(true); expect(indicatorSchema.safeParse({value:"bad scheme",type:"URL",confidence:"LOW"}).success).toBe(false); expect(indicatorSchema.safeParse({value:"user@example.com",type:"EMAIL",confidence:"LOW"}).success).toBe(true); expect(cveSchema.safeParse({cve_id:"CVE-2024-12345",severity:"CRITICAL",exploit_status:"POC"}).success).toBe(true); expect(mitreSchema.safeParse({technique_id:"T1059.001",technique_name:"PowerShell",tactic:"Execution"}).success).toBe(true);});
  it("validates date ordering before database calls",()=>{expect(campaignSchema.safeParse({name:"c",start_date:"2026-02-02",end_date:"2026-01-01"}).success).toBe(false); expect(indicatorSchema.safeParse({value:"example.com",type:"DOMAIN",confidence:"LOW",first_seen:"bad-date"}).success).toBe(false);});
  it("validates malware hashes as supported hash JSON object",()=>{expect(malwareSchema.parse({name:"m",hashes:'{"md5":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}'}).hashes).toEqual({md5:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}); expect(malwareSchema.safeParse({name:"m",hashes:'[]'}).success).toBe(false); expect(malwareSchema.safeParse({name:"m",hashes:'{"ssdeep":"abc"}'}).success).toBe(false);});
});
