import {describe,expect,it} from "vitest";
import {parseFeed} from "@/lib/research-feeds/parser";
const feed=(extra:Record<string,unknown>={})=>JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:"Threat feed",language:"en",items:[{id:"one",title:" Item ",url:"/post",summary:"Summary",content_html:"<script>bad()</script><style>x</style><b>Safe &amp; sound</b>",date_published:"2026-01-02T03:04:05Z",date_modified:"bad",tags:["cti","cti"],authors:[{name:"Analyst"}],...extra}]});
describe("strict JSON Feed",()=>{
 it("normalizes JSON Feed 1.1 without returning raw JSON",()=>{const result=parseFeed(feed(),"https://example.com/feed.json");expect(result.type).toBe("JSON_FEED");expect(result.items[0]).toMatchObject({externalId:"one",title:"Item",canonicalUrl:"https://example.com/post",summaryText:"Summary",contentText:"Safe & sound",authorName:"Analyst",publishedAt:"2026-01-02T03:04:05.000Z",sourceUpdatedAt:null,categories:["cti"],language:"en"});expect(result).not.toHaveProperty("raw");});
 it("accepts version 1 and legacy author",()=>expect(parseFeed(JSON.stringify({version:"https://jsonfeed.org/version/1",title:"x",items:[{id:"1",content_text:"body",author:{name:"Legacy"}}]}),"https://example.com").items[0]?.authorName).toBe("Legacy"));
 it("uses external_url only as fallback and item language first",()=>expect(parseFeed(feed({url:undefined,external_url:"https://other.example/x",language:"tr"}),"https://example.com").items[0]).toMatchObject({canonicalUrl:"https://other.example/x",language:"tr"}));
 it("skips malformed items",()=>expect(parseFeed(JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:"x",items:[{},null,{id:"ok",content_text:"yes"}]}),"https://example.com").items).toHaveLength(1));
 it.each(["{}",JSON.stringify({type:"bundle",objects:[]}),JSON.stringify({version:"https://jsonfeed.org/version/2",title:"x",items:[]}),JSON.stringify({version:"https://jsonfeed.org/version/1.1",items:[]}),"[]","bad"])('rejects malformed or generic JSON: %s',value=>expect(()=>parseFeed(value,"https://example.com")).toThrow());
 it("rejects excessive depth",()=>{let nested:unknown="x";for(let i=0;i<45;i++)nested={nested};expect(()=>parseFeed(JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:"x",items:[],nested}),"https://example.com")).toThrow();});
 it("bounds items at 500",()=>{const items=Array.from({length:501},(_,i)=>({id:String(i),title:String(i)}));expect(parseFeed(JSON.stringify({version:"https://jsonfeed.org/version/1.1",title:"x",items}),"https://example.com").items).toHaveLength(500);});
});
