import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { reconstructionSchema } from "@/lib/reconstruction/schema";
import { timelineSchema } from "@/lib/workspace/schema";
import { campaignInfrastructureEdges, visibleInfrastructureMembershipStatuses } from "@/lib/graph/service";
const fd=(x:Record<string,string>)=>x;
describe("Phase 2.1D analyst workflow",()=>{
 it("validates observed and inferred event semantics and ranges",()=>{const base={event_name:"Beacon",event_date:"2026-07-30T10:00",description:"",related_entity_type:"",related_entity_id:"",occurred_end_at:"",basis:"OBSERVED",activity_phase:"COMMAND_AND_CONTROL",assessment_status:"RECORDED",confidence:"MEDIUM",analyst_rationale:""};expect(timelineSchema.safeParse(base).success).toBe(true);expect(timelineSchema.safeParse({...base,basis:"INFERRED"}).success).toBe(false);expect(timelineSchema.safeParse({...base,basis:"INFERRED",analyst_rationale:"Timing and infrastructure overlap."}).success).toBe(true);expect(timelineSchema.safeParse({...base,occurred_end_at:"2026-07-30T09:00"}).success).toBe(false);});
 it("requires assessed reconstruction content and a valid observation range",()=>{const base=fd({reconstruction_status:"DRAFT",activity_status:"ACTIVE",confidence:"HIGH",operational_objective:"Collection",current_assessment:"",next_expected_activity:"",key_uncertainties:"",first_observed_at:"",last_observed_at:"",assessed_at:""});expect(reconstructionSchema.safeParse(base).success).toBe(true);expect(reconstructionSchema.safeParse({...base,reconstruction_status:"ASSESSED"}).success).toBe(false);expect(reconstructionSchema.safeParse({...base,reconstruction_status:"ASSESSED",current_assessment:"Coherent operation",assessed_at:"2026-07-30T12:00"}).success).toBe(true);});
 it("derives Campaign-to-cluster edges without Timeline nodes and gates history",()=>{const rows=[{id:"r",campaign_id:"c",infrastructure_cluster_id:"i",status:"CONFIRMED",confidence:"HIGH",rationale:"Shared operational infrastructure",first_observed_at:"2026-01-01",last_observed_at:"2026-02-01"}];const edges=campaignInfrastructureEdges(rows,"p",new Set(["campaign:c","infrastructure-cluster:i"]));expect(edges).toHaveLength(1);expect(edges[0].metadata).toMatchObject({status:"CONFIRMED",confidence:"HIGH"});expect(edges[0].source).not.toContain("TIMELINE");expect(visibleInfrastructureMembershipStatuses(false)).not.toContain("REJECTED");expect(visibleInfrastructureMembershipStatuses(true)).toContain("REMOVED");});
 it("migration defines composite ownership, exact-one, restricted history and RLS",()=>{const sql=readFileSync("supabase/migrations/202607300020_phase2_1d_campaign_reconstruction.sql","utf8");expect(sql).toContain("foreign key(project_id,timeline_event_id)");expect(sql).toContain("num_nonnulls(indicator_id,infrastructure_cluster_id,malware_id,cve_id,mitre_technique_id)=1");expect(sql).toContain("num_nonnulls(source_id,evidence_id,enrichment_result_id)=1");expect(sql).toContain("references public.timeline_events(project_id,id) on delete restrict");expect((sql.match(/enable row level security/g)||[])).toHaveLength(5);expect(sql).not.toMatch(/timeline_event.*graph_entity_type/i);});
});
