import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {buildReferencePath,compareReference,createVersionSchema,lifecycleStatuses,productTypes,referenceTypes} from "@/lib/reports/versioning";
const read=(p:string)=>readFileSync(p,"utf8");
describe("Phase 2.1F hardening",()=>{
 it("defines the complete bounded product/reference vocabulary",()=>{expect(productTypes).toHaveLength(8);expect(referenceTypes).toHaveLength(13);expect(lifecycleStatuses).toEqual(["DRAFT","IN_REVIEW","APPROVED","ARCHIVED"])});
 it("requires every analyst assessment field",()=>{expect(createVersionSchema.safeParse({}).success).toBe(false);expect(createVersionSchema.safeParse({changeSummary:"change",executiveSummary:"summary",keyJudgments:"judgment",confidence:"HIGH",intelligenceGaps:"gap",recommendations:"act"}).success).toBe(true)});
 it("computes all live-record comparison states",()=>{const snap={source_updated_at:"2026-01-02"};expect(compareReference(undefined,{})).toBe("NEW_DRAFT_REFERENCE");expect(compareReference(snap,undefined)).toBe("CURRENT_RECORD_UNAVAILABLE");expect(compareReference(snap,{updated_at:"2026-01-02"})).toBe("UNCHANGED");expect(compareReference(snap,{updated_at:"2026-01-03"})).toBe("CURRENT_RECORD_UPDATED_AFTER_VERSION");expect(compareReference(snap,{updated_at:"2026-01-03",archived_at:"2026-01-04"})).toBe("CURRENT_RECORD_ARCHIVED")});
 it("uses typed composite FKs, matching checks, and partial uniqueness",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");expect(sql).not.toContain("reference_id uuid");expect(sql).toContain("report_references_type_target_match");expect(sql).toContain("foreign key(project_id,campaign_id) references public.campaigns(project_id,id)");expect(sql.match(/create unique index report_references_/g)).toHaveLength(13)});
 it("creates versions and snapshots in one RPC",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");expect(sql).toContain("create function public.create_report_version");expect(sql).toContain("for ref in select * from public.report_references");const action=read("src/app/projects/[id]/reports/version-actions.ts");expect(action).toContain('.rpc("create_report_version"');expect(action).not.toContain('.from("report_versions").insert')});
 it("locks publication, lifecycle, deletion, and immutable rows",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");for(const token of ["report_version_updates_require_workflow","report_versions_are_permanent","authoritative_version_must_be_published","lifecycle_transition_requires_workflow","No authenticated INSERT/UPDATE/DELETE policies"])expect(sql).toContain(token)});
 it("renders selectors, unlink, awareness and authoritative joins",()=>{const ui=read("src/components/reports/analytical-references.tsx");for(const token of ["Select a record","Add reference","Unlink","REMOVED_FROM_CURRENT_DRAFT","compareReference"])expect(ui).toContain(token);const page=read("src/app/projects/[id]/reports/[reportId]/page.tsx");expect(page).toContain("authoritativeVersion=(versions??[]).find")});
 it("allowlists candidate columns and emits only minimal DTO fields",()=>{const page=read("src/app/projects/[id]/reports/[reportId]/page.tsx"),block=page.slice(page.indexOf("const candidateResults"),page.indexOf("const { count: relationshipCount"));expect(block).not.toContain('select("*")');for(const secret of ["storage_path","original_file_name","source_url","normalized_data","safe_raw_data","analyst_notes"])expect(block).not.toContain(secret);expect(block).toContain("routeContext")});
 it("builds precise safe internal routes for all reference types",()=>{const p="11111111-1111-4111-8111-111111111111",t="22222222-2222-4222-8222-222222222222",context={indicatorId:t,campaignId:t};for(const type of referenceTypes)expect(buildReferencePath(p,type,t,context),type).toMatch(/^\/projects\//);expect(buildReferencePath("bad","SOURCE",t)).toBeNull();expect(buildReferencePath(p,"ENRICHMENT_RESULT",t,{})).toBeNull();expect(buildReferencePath(p,"ATTRIBUTION_HYPOTHESIS",t,{})).toBeNull()});
 it("protects Report workflow fields and deterministic restore in RPCs",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");for(const token of ["report_workflow_fields_require_rpc","new.authoritative_version_id","new.published_at","new.current_version_number","update_report_product_metadata","new.lifecycle_status='PUBLISHED'","pre_archive_lifecycle_status"])expect(sql).toContain(token)});
 it("exports complete immutable assessment metadata",()=>{const route=read("src/app/api/projects/[id]/reports/[reportId]/export/[format]/route.ts");for(const token of ["Executive summary","Key judgments","Intelligence gaps","Recommendations","Change summary","Referenced-record appendix",'get("scope")==="authoritative"',"attributionDisclaimer","-v${String(record.version_number)}"])expect(route).toContain(token)});
});
