import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {compareReference,createVersionSchema,lifecycleStatuses,productTypes,referenceTypes} from "@/lib/reports/versioning";
const read=(p:string)=>readFileSync(p,"utf8");
describe("Phase 2.1F hardening",()=>{
 it("defines the complete bounded product/reference vocabulary",()=>{expect(productTypes).toHaveLength(8);expect(referenceTypes).toHaveLength(13);expect(lifecycleStatuses).toEqual(["DRAFT","IN_REVIEW","APPROVED","ARCHIVED"])});
 it("requires every analyst assessment field",()=>{expect(createVersionSchema.safeParse({}).success).toBe(false);expect(createVersionSchema.safeParse({changeSummary:"change",executiveSummary:"summary",keyJudgments:"judgment",confidence:"HIGH",intelligenceGaps:"gap",recommendations:"act"}).success).toBe(true)});
 it("computes all live-record comparison states",()=>{const snap={source_updated_at:"2026-01-02"};expect(compareReference(undefined,{})).toBe("NEW_DRAFT_REFERENCE");expect(compareReference(snap,undefined)).toBe("CURRENT_RECORD_UNAVAILABLE");expect(compareReference(snap,{updated_at:"2026-01-02"})).toBe("UNCHANGED");expect(compareReference(snap,{updated_at:"2026-01-03"})).toBe("CURRENT_RECORD_UPDATED_AFTER_VERSION");expect(compareReference(snap,{updated_at:"2026-01-03",archived_at:"2026-01-04"})).toBe("CURRENT_RECORD_ARCHIVED")});
 it("uses typed composite FKs, matching checks, and partial uniqueness",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");expect(sql).not.toContain("reference_id uuid");expect(sql).toContain("report_references_type_target_match");expect(sql).toContain("foreign key(project_id,campaign_id) references public.campaigns(project_id,id)");expect(sql.match(/create unique index report_references_/g)).toHaveLength(13)});
 it("creates versions and snapshots in one RPC",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");expect(sql).toContain("create function public.create_report_version");expect(sql).toContain("for ref in select * from public.report_references");const action=read("src/app/projects/[id]/reports/version-actions.ts");expect(action).toContain('.rpc("create_report_version"');expect(action).not.toContain('.from("report_versions").insert')});
 it("locks publication, lifecycle, deletion, and immutable rows",()=>{const sql=read("supabase/migrations/202607300022_phase2_1f_intelligence_products_versioning.sql");for(const token of ["report_version_updates_require_workflow","report_versions_are_permanent","authoritative_version_must_be_published","lifecycle_transition_requires_workflow","No authenticated INSERT/UPDATE/DELETE policies"])expect(sql).toContain(token)});
 it("renders selectors, unlink, awareness and authoritative joins",()=>{const ui=read("src/components/reports/analytical-references.tsx");for(const token of ["Select a record","Add reference","Unlink","REMOVED_FROM_CURRENT_DRAFT","compareReference"])expect(ui).toContain(token);const page=read("src/app/projects/[id]/reports/[reportId]/page.tsx");expect(page).toContain("authoritativeVersion=(versions??[]).find")});
 it("exports complete immutable assessment metadata",()=>{const route=read("src/app/api/projects/[id]/reports/[reportId]/export/[format]/route.ts");for(const token of ["Executive summary","Key judgments","Intelligence gaps","Recommendations","Change summary","Referenced-record appendix",'get("scope")==="authoritative"',"attributionDisclaimer","-v${String(record.version_number)}"])expect(route).toContain(token)});
});
