/* eslint-disable @typescript-eslint/no-explicit-any */
import {describe,expect,it,vi} from "vitest";
import {normalizeFeedUrl,normalizeItemUrl,redactUrl} from "@/lib/research-feeds/url";
import {isPublicAddress,resolvePublic,fetchFeed} from "@/lib/research-feeds/network";
import {parseFeed} from "@/lib/research-feeds/parser";
import {itemFingerprints} from "@/lib/research-feeds/fingerprint";
const rss=`<?xml version="1.0"?><rss version="2.0"><channel><title>x</title><item><guid>1</guid><title>Hello</title><link>/post#x</link><description><![CDATA[<script>bad()</script><b>Safe</b>]]></description><pubDate>bad</pubDate><category>A</category></item></channel></rss>`;
const atom=`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><title>x</title><entry><id>1</id><title>Atom</title><link rel="alternate" href="https://example.com/a"/><summary>Body</summary></entry></feed>`;
describe("feed URL validation",()=>{it.each(["http://example.com/feed","https://EXAMPLE.com/a/../feed?q=x"])("accepts %s",u=>expect(normalizeFeedUrl(u).hostname).toBe("example.com"));it.each(["ftp://example.com/x","https://u:p@example.com/x","https://example.com/x#f","http://localhost/x","http://internal/x","https://example.com:8443/x","not url","https://example.com/%0aevil"])("rejects %s",u=>expect(()=>normalizeFeedUrl(u)).toThrow());it("redacts query values",()=>expect(redactUrl("https://example.com/a?token=secret")).not.toContain("secret"));});
describe("address classification",()=>{it.each(["127.0.0.1","10.0.0.1","169.254.169.254","192.0.2.1","224.0.0.1","::1","fc00::1","fe80::1","2001:db8::1","::ffff:127.0.0.1"])("blocks %s",a=>expect(isPublicAddress(a)).toBe(false));it("allows global addresses",()=>expect(isPublicAddress("93.184.216.34")).toBe(true));it("rejects mixed DNS",async()=>await expect(resolvePublic("example.com",async()=>[{address:"93.184.216.34",family:4},{address:"10.0.0.1",family:4}])).rejects.toMatchObject({code:"DNS_BLOCKED"}));});
describe("protected transport",()=>{const resolver=async()=>[{address:"93.184.216.34",family:4}];it("pins the validated address and sends controlled headers",async()=>{const t=vi.fn(async(_u,_a,h)=>({status:304,headers:{},body:[] as Uint8Array[]}));await fetchFeed("https://example.com/feed",{}, {resolver,transport:t as any});expect(t.mock.calls[0]?.[1]).toEqual({address:"93.184.216.34",family:4});expect(t.mock.calls[0]?.[2]).not.toHaveProperty("authorization");expect(t.mock.calls[0]?.[2]).not.toHaveProperty("cookie");});it("blocks private redirect",async()=>{let n=0;await expect(fetchFeed("https://example.com/feed",{}, {resolver:async h=>h==="private.example"?[{address:"10.0.0.1",family:4}]:resolver(),transport:(async()=>({status:++n===1?302:200,headers:{location:"https://private.example/feed"},body:[]})) as any})).rejects.toMatchObject({code:"DNS_BLOCKED"});});it("rejects downgrade",async()=>await expect(fetchFeed("https://example.com",{}, {resolver,transport:(async()=>({status:302,headers:{location:"http://example.com/feed"},body:[]})) as any})).rejects.toMatchObject({code:"REDIRECT_BLOCKED"}));it("enforces content length",async()=>await expect(fetchFeed("https://example.com",{}, {resolver,transport:(async()=>({status:200,headers:{"content-type":"application/xml","content-length":"99999999"},body:[]})) as any})).rejects.toMatchObject({code:"RESPONSE_TOO_LARGE"}));it("rejects HTML",async()=>await expect(fetchFeed("https://example.com",{}, {resolver,transport:(async()=>({status:200,headers:{"content-type":"text/html"},body:[]})) as any})).rejects.toMatchObject({code:"CONTENT_TYPE_REJECTED"}));});
describe("feed parsing and normalization",()=>{it("parses safe RSS",()=>{const x=parseFeed(rss,"https://example.com/feed");expect(x.type).toBe("RSS");expect(x.items[0]).toMatchObject({title:"Hello",canonicalUrl:"https://example.com/post",summaryText:"Safe",publishedAt:null});});it("parses Atom alternate links",()=>expect(parseFeed(atom,"https://example.com").items[0]?.canonicalUrl).toBe("https://example.com/a"));it.each(["<!DOCTYPE rss><rss/>","<!ENTITY x SYSTEM 'file:///etc/passwd'><rss/>"])("rejects unsafe XML",x=>expect(()=>parseFeed(x,"https://example.com")).toThrow());it("rejects malformed XML",()=>expect(()=>parseFeed("<rss><channel>","https://example.com")).toThrow());it("rejects unsupported XML",()=>expect(()=>parseFeed("<html/>","https://example.com")).toThrow());it("enforces item limit",()=>{const xml=`<rss><channel>${Array.from({length:501},(_,i)=>`<item><title>${i}</title></item>`).join("")}</channel></rss>`;expect(parseFeed(xml,"https://example.com").items).toHaveLength(500)});it("skips unusable items",()=>expect(parseFeed("<rss><channel><item><guid>x</guid></item></channel></rss>","https://example.com").items).toHaveLength(0));it("normalizes item URLs",()=>expect(normalizeItemUrl("/a#b","https://example.com/feed")).toBe("https://example.com/a"));it("fingerprints deterministically",()=>{const item=parseFeed(atom,"https://example.com").items[0]!;expect(itemFingerprints(item)).toEqual(itemFingerprints(item));});});
