/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { aiWorkflowSchema, getAiConfig } from "@/lib/ai/config";
import { runEntityExtractionWorkflow, runReportDraftWorkflow, runStructuredWorkflow, runTranslationWorkflow, validateExtractedIndicator } from "@/lib/ai/workflows";
import { buildModelFacingReportSource, buildReportSourceAliases } from "@/lib/ai/provenance";
import { AiError } from "@/lib/ai/client";
import { safeAiErrorCode, safeAiErrorMessage } from "@/lib/ai/byok/errors";
import { byokChat } from "@/lib/ai/byok/client";
import { BYOK_COOKIE, decryptCredential } from "@/lib/ai/byok/vault";
import { cookies } from "next/headers";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const uuid = z.string().uuid();
const bodySchema = z.object({ workflow: aiWorkflowSchema, noteIds: z.array(uuid).max(10).optional(), evidenceIds: z.array(uuid).max(10).optional(), pastedText: z.string().max(20000).optional(), entityType: z.enum(["campaigns","malware"]).optional(), entityId: uuid.optional(), targetLanguage: z.enum(["Spanish","French","German","Arabic","Turkish","Ukrainian","Russian","Chinese","Japanese","Korean","Portuguese","Italian","English"]).optional(), selections: z.record(z.string(), z.array(uuid).max(20)).optional(), providerMode: z.enum(["ollama","byok"]).default("ollama"), byokConsent: z.boolean().optional() }).strict();
async function projectCtx(id: string) { const { supabase, user } = await requireUser(); const { data, error } = await supabase.from("projects").select("id,owner_id").eq("id", id).single(); if (error || !data || data.owner_id !== user.id) throw new Error("not_found"); return { supabase, user, projectId: id }; }
function safeError(e: unknown) { const code = e instanceof AiError ? e.code : safeAiErrorCode(e); const error = code === "disabled" ? "AI is disabled." : code === "configuration_required" ? "AI configuration is required." : code === "missing_model" ? "Configured Ollama model is missing." : code === "report_provenance_unreliable" ? "AI could not cite the selected sources reliably. Try generating again or select fewer sources." : code === "translation_invalid" ? "AI could not produce a valid translation while preserving protected values." : code === "rate_limited" ? "AI usage limit exceeded." : code === "malformed_output" ? "AI output did not match the required schema." : ["byok_required","byok_expired","byok_binding_mismatch","byok_consent_required","timeout","provider_rate_limited","provider_unreachable","nvidia_output_exhausted"].includes(code) ? safeAiErrorMessage(code) : "AI request could not be completed."; return NextResponse.json({ error, code }, { status: code === "rate_limited" || code === "provider_rate_limited" ? 429 : 400 }); }
async function reserve(supabase: any, projectId: string, workflow: string, inputChars: number) { const cfg = getAiConfig(); const { data, error } = await supabase.rpc("reserve_ai_usage_event", { p_project_id: projectId, p_workflow: workflow, p_input_chars: inputChars, p_window_minutes: cfg.rateLimitWindowMinutes, p_max_requests: cfg.rateLimitRequests, p_max_input_chars: cfg.rateLimitInputChars }); if (error || !data) throw new AiError("rate_limited"); return data as string; }
async function finish(supabase: any, eventId: string, status: string, output: unknown) { await supabase.rpc("complete_ai_usage_event", { p_event_id: eventId, p_status: status, p_output_chars: JSON.stringify(output ?? "").length }); }
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params; const parsed = bodySchema.parse(await req.json()); const ctx = await projectCtx(id);
    const source: Record<string, unknown> = { pastedText: parsed.pastedText?.slice(0, 20000) ?? "" };
    let reportAliases: ReturnType<typeof buildReportSourceAliases> = [];
    let modelSource: Record<string, unknown> | null = null;
    let translationSource: { id: string; text: string } | null = null;
    if (parsed.workflow !== "generate_report_draft") {
      if (parsed.noteIds?.length) { const { data, error } = await ctx.supabase.from("research_notes").select("id,title,content,tags").eq("project_id", id).in("id", parsed.noteIds); if (error) return NextResponse.json({ error: "Unable to load selected notes." }, { status: 400 }); source.notes = data ?? []; }
      if (parsed.evidenceIds?.length) { const { data, error } = await ctx.supabase.from("evidence").select("id,title,type,description,source_url,collection_date,tags").eq("project_id", id).in("id", parsed.evidenceIds); if (error) return NextResponse.json({ error: "Unable to load selected evidence." }, { status: 400 }); source.evidence = data ?? []; }
    }
    if (parsed.workflow === "translate_document") {
      if (((parsed.noteIds?.length ?? 0) + (parsed.evidenceIds?.length ?? 0)) !== 1 || !parsed.targetLanguage) return NextResponse.json({ error: "Select exactly one note or evidence source for translation." }, { status: 400 });
      const note = ((source.notes as any[]) ?? [])[0];
      const evidenceRow = ((source.evidence as any[]) ?? [])[0];
      if (note) translationSource = { id: note.id, text: String(note.content ?? "") };
      if (evidenceRow) translationSource = { id: evidenceRow.id, text: String(evidenceRow.description ?? "") };
      if (!translationSource) return NextResponse.json({ error: "Select exactly one note or evidence source for translation." }, { status: 400 });
      modelSource = { source_text: translationSource.text };
    }
    if (parsed.workflow === "suggest_mitre_mapping") { const table = parsed.entityType === "campaigns" ? "campaigns" : "malware"; const { data } = await ctx.supabase.from(table).select("id,name,description").eq("project_id", id).eq("id", parsed.entityId).single(); source.target = data; const { data: mitre } = await ctx.supabase.from("mitre_techniques").select("id,technique_id,technique_name,description").eq("project_id", id).limit(200); if (!data) return NextResponse.json({ error: "Selected Campaign or Malware was not found." }, { status: 400 }); if (mitre === null) source.available_mitre = []; else source.available_mitre = mitre; }
    if (parsed.workflow === "generate_report_draft") { if (!parsed.selections) return NextResponse.json({ error: "Select at least one available report source." }, { status: 400 }); let reportSourceCount = 0; const allowed: Record<string, string> = { research_notes: "id,title,content,tags", evidence: "id,title,type,description,source_url,collection_date,tags", timeline_events: "id,event_name,event_date,description,related_entity_type", project_tasks: "id,task_name,description,status,priority,deadline", threat_actors: "id,name,aliases,country,motivations,description,known_ttps,references", campaigns: "id,name,description,start_date,end_date,targets", indicators: "id,value,type,confidence,source,tags,first_seen,last_seen", malware: "id,name,family,hashes,description,behavior", cves: "id,cve_id,description,severity,affected_product,exploit_status,references", mitre_techniques: "id,technique_id,technique_name,tactic,description" }; for (const [table, ids] of Object.entries(parsed.selections)) { const columns = allowed[table]; if (!columns) continue; const { data, error } = await ctx.supabase.from(table).select(columns).eq("project_id", id).in("id", ids); if (error) return NextResponse.json({ error: "Unable to load selected report sources." }, { status: 400 }); source[table] = data ?? []; reportSourceCount += (data ?? []).length; } if (reportSourceCount === 0) return NextResponse.json({ error: "Select at least one available report source." }, { status: 400 }); reportAliases = buildReportSourceAliases(source); modelSource = buildModelFacingReportSource(source, reportAliases); }
    const inputChars = JSON.stringify(modelSource ?? source).length; if (inputChars > getAiConfig().maxInputChars) return NextResponse.json({ error: "Selected source data is too large. Select fewer sources and try again." }, { status: 400 });
    const eventId = await reserve(ctx.supabase, id, parsed.workflow, inputChars);
    try { const chat = parsed.providerMode === "byok" ? (() => { if (!parsed.byokConsent) throw new AiError("byok_consent_required"); return async (messages: any) => { const cookie = (await cookies()).get(BYOK_COOKIE)?.value; if (!cookie) throw new AiError("byok_required"); const cred = decryptCredential(cookie, { kind: "user", id: ctx.user.id }); return byokChat(cred.providerId, cred.model, cred.apiKey, messages, "generation"); }; })() : undefined; const result: any = parsed.workflow === "generate_report_draft" ? await runReportDraftWorkflow(modelSource ?? {}, reportAliases, chat) : parsed.workflow === "translate_document" ? await runTranslationWorkflow(parsed.targetLanguage!, translationSource!.id, translationSource!.text, chat) : parsed.workflow === "extract_entities" ? await runEntityExtractionWorkflow(source, chat) /* preserves legacy contract: runEntityExtractionWorkflow(source) */ : await runStructuredWorkflow(parsed.workflow, source, chat); if (parsed.workflow === "summarize_research") { const allowed = new Set(((source.notes as any[]) ?? []).map((n) => n.id)); result.cited_source_note_ids = result.cited_source_note_ids.filter((x: string) => allowed.has(x)); }

      if (parsed.workflow === "extract_entities") { const allowedRefs = new Set([ ...(((source.notes as any[]) ?? []).map((n) => `note:${n.id}`)), ...(((source.evidence as any[]) ?? []).map((e) => `evidence:${e.id}`)) ]); result.entities = result.entities.map((entity: any) => ({ ...entity, source_ref: entity.source_ref && allowedRefs.has(`${entity.source_ref.kind}:${entity.source_ref.id}`) ? entity.source_ref : null })); }
      if (parsed.workflow === "extract_indicators") { const values = result.indicators.map((x: any) => ({ ...x, validation: validateExtractedIndicator(x) })); const { data: existing } = await ctx.supabase.from("indicators").select("id,value,type").eq("project_id", id); result.indicators = values.map((x: any) => ({ ...x, duplicate_id: (existing ?? []).find((e: any) => e.type === x.type && e.value === x.validation.normalized)?.id ?? null })); }
      await finish(ctx.supabase, eventId, "SUCCEEDED", result); return NextResponse.json({ result, sourceRecordIds: parsed.workflow === "generate_report_draft" ? { report: reportAliases.map((a) => a.id) } : { notes: ((source.notes as any[]) ?? []).map((n) => n.id), evidence: ((source.evidence as any[]) ?? []).map((e) => e.id) }, disclaimer: "AI-generated suggestions require human review and explicit approval before saving." });
    } catch (e) { await finish(ctx.supabase, eventId, "FAILED", null); throw e; }
  } catch (e) { return safeError(e); }
}
