import Link from "next/link";
import { getNodeEntityGeography,getNodeEntityLineage,getNodeInfrastructureContext,getNodeRelatedRecords } from "@/lib/baykush-node/queries";
import { requireUser } from "@/lib/auth";

export default async function Page({params}:{params:Promise<{entityType:string;entityKey:string[]}>}){
  await requireUser();
  const resolved=await params;
  const entityType=resolved.entityType;
  const entityKey=resolved.entityKey.join('/');
  const [related,lineage,geography,infrastructure]=await Promise.allSettled([
    getNodeRelatedRecords(entityType,entityKey),getNodeEntityLineage(entityType,entityKey),getNodeEntityGeography(entityType,entityKey),
    entityType==='IP'?getNodeInfrastructureContext(entityType,entityKey):Promise.resolve(null),
  ]);
  return <section className="space-y-5">
    <header className="citem-page-header"><div><p className="citem-eyebrow">CİTEM / NODE-7 / exact canonical subject</p><h1 className="citem-title break-all">{entityKey}</h1><p className="citem-subtitle">{entityType} · evidence-backed discovery context. Relationships on this page do not constitute attribution, causation, exploitation or a threat score.</p></div><Link href="/techint/discovery" className="citem-button-ghost">Back to discovery</Link></header>
    <section className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Related records</p><h2 className="citem-section-title">Exact canonical overlap</h2></div>{related.status==='rejected'?<Unavailable text="Related records unavailable."/>:related.value.data.records.length?<div className="space-y-2">{related.value.data.records.map(record=><article key={record.id} className="rounded border border-stone-800 px-3 py-2"><p className="text-sm font-medium text-stone-200">{record.sourceKey} · {record.recordKind}</p><p className="mt-1 break-all text-xs text-stone-500">{record.sourceRecordId}</p><p className="mt-1 text-xs text-stone-600">{record.sourceClass} · upstream {record.upstreamOriginKey}</p></article>)}</div>:<Empty text="No exact canonical related records returned."/>}</section>
    <section className="grid gap-5 xl:grid-cols-2"><div className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Geography</p><h2 className="citem-section-title">Explicit assertions</h2></div>{geography.status==='rejected'?<Unavailable text="Geography unavailable."/>:geography.value.data.length?<div className="space-y-2">{geography.value.data.map(item=><article key={item.id} className="rounded border border-stone-800 px-3 py-2"><p className="text-xs uppercase tracking-[0.12em] text-amber-300">{item.geoClass}</p><p className="mt-1 text-sm text-stone-200">{item.countryName??item.countryCode??'Unknown location'} · {item.locationPrecision}</p><p className="mt-1 text-xs text-stone-500">{item.basisSourceKey} · {item.temporalPolicy} · {item.timePrecision}</p><p className="mt-1 text-xs text-stone-600">Infrastructure location is not attacker origin.</p></article>)}</div>:<Empty text="No geographic assertions available."/>}</div>
    <div className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Lineage</p><h2 className="citem-section-title">Bounded evidence graph</h2></div>{lineage.status==='rejected'?<Unavailable text="Lineage unavailable."/>:<><p className="text-sm text-stone-400">{lineage.value.data.nodes.length} nodes · {lineage.value.data.edges.length} edges{lineage.value.data.truncated?' · bounded result truncated':''}</p><div className="max-h-80 space-y-1 overflow-auto">{lineage.value.data.nodes.map(node=><div key={node.id} className="rounded border border-stone-800 px-2 py-2 text-xs"><span className="text-amber-300">{node.type}</span><span className="ml-2 break-all text-stone-500">{node.id}</span></div>)}</div></>}</div></section>
    {entityType==='IP'?<section className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Internet Infrastructure</p><h2 className="citem-section-title">RIPE routing context · last hour</h2><p className="mt-1 text-xs text-stone-500">Announcement is not attack. Withdrawal is not an outage verdict. No hijack inference is made.</p></div>{infrastructure.status==='rejected'||!infrastructure.value?<Unavailable text="Routing context unavailable."/>:infrastructure.value.data.length?<div className="space-y-2">{infrastructure.value.data.slice(0,50).map((item,index)=><article key={`${item.bucketStart}:${item.coveringPrefix}:${index}`} className="rounded border border-stone-800 px-3 py-2"><p className="text-sm text-stone-200">{item.coveringPrefix} · {item.activityTypes.join(' + ')}</p><p className="mt-1 text-xs text-stone-500">{new Date(item.bucketStart).toLocaleString()} · coverage {item.coverageStatus} · availability {item.dataAvailability}</p><p className="mt-1 text-xs text-stone-600">live {item.liveCollectionCoverage} · acquisition {item.acquisitionBasis}</p></article>)}</div>:<Empty text="No matching RIPE routing context returned for the last hour."/>}</section>:null}
  </section>;
}
function Empty({text}:{text:string}){return <p className="text-sm text-stone-500">{text}</p>}
function Unavailable({text}:{text:string}){return <p className="rounded border border-stone-800 px-3 py-2 text-sm text-stone-500">{text}</p>}
