import Link from "next/link";
import type { NodeCompositionFinding,NodeConvergenceFinding,NodeGeographyMap,NodeNewEntityFinding } from "@/lib/baykush-node/discovery-schema";
import type { GlobalRange } from "@/lib/baykush-node/range";

const findingLabels:Record<string,string>={SOURCE_SYSTEM_OVERLAP:'Source-system overlap',MULTI_ORIGIN_CONVERGENCE:'Multi-origin convergence',CROSS_CLASS_CONVERGENCE:'Cross-class convergence',CONCURRENT_MOVEMENT:'Concurrent technical movement'};
function entityHref(type:string,key:string){return `/techint/discovery/entity/${encodeURIComponent(type)}/${encodeURIComponent(key)}`;}
function formatTime(value:string|null|undefined){return value?new Date(value).toLocaleString():'—';}

export function DiscoveryWorkbench(input:{
  range:GlobalRange;
  convergence?:readonly NodeConvergenceFinding[];
  newEntities?:readonly NodeNewEntityFinding[];
  composition?:readonly NodeCompositionFinding[];
  topMovers?:readonly NodeCompositionFinding[];
  geography?:NodeGeographyMap;
  convergenceUnavailable?:boolean;newEntitiesUnavailable?:boolean;compositionUnavailable?:boolean;geographyUnavailable?:boolean;
}){
  return <section className="space-y-5">
    <header className="citem-page-header"><div><p className="citem-eyebrow">CİTEM / TechINT / NODE-7</p><h1 className="citem-title">Discovery Workbench</h1><p className="citem-subtitle">Cross-source movement around exact canonical technical subjects. Findings expose overlap, composition and provenance; they do not assert causation, exploitation, attribution or a threat score.</p></div></header>
    <RangeLinks range={input.range}/>
    <section className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Convergence</p><h2 className="citem-section-title">Multi-source movement</h2></div>{input.convergenceUnavailable?<Unavailable text="Convergence unavailable; other discovery surfaces remain independent."/>:input.convergence?.length?<div className="grid gap-3 xl:grid-cols-2">{input.convergence.map(item=><article key={item.id} className="rounded border border-stone-800 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.14em] text-amber-300">{findingLabels[item.findingType]??item.findingType}</p><Link className="mt-1 block break-all text-sm font-semibold text-stone-100 hover:text-amber-200" href={entityHref(item.entityType,item.entityKey)}>{item.entityKey}</Link></div><span className="text-xs text-stone-500">{item.entityType}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-stone-400"><Metric label="Sources" value={item.sourceDefinitionCount}/><Metric label="Origins" value={item.upstreamOriginCount}/><Metric label="Classes" value={item.sourceClassCount}/></div><p className="mt-3 text-xs text-stone-500">{formatTime(item.windowStart)} → {formatTime(item.windowEnd)} · precision {item.timePrecision}</p></article>)}</div>:<Empty text="No convergence findings published for this range."/>}</section>

    <section className="grid gap-5 xl:grid-cols-2"><div className="card panel-corners space-y-3"><div><p className="citem-eyebrow">New entities</p><h2 className="citem-section-title">Effective first seen</h2></div>{input.newEntitiesUnavailable?<Unavailable text="New-entity discovery unavailable."/>:input.newEntities?.length?<div className="space-y-2">{input.newEntities.map(item=><article className="rounded border border-stone-800 px-3 py-2" key={item.id}><Link className="break-all text-sm font-medium text-stone-200 hover:text-amber-200" href={entityHref(item.entityType,item.entityKey)}>{item.entityKey}</Link><p className="mt-1 text-xs text-stone-500">{item.entityType} · effective {item.effectiveFirstSeenTime?formatTime(item.effectiveFirstSeenTime):item.effectiveFirstSeenDate??'unknown'} · {item.acquisitionBasis??'basis unknown'}</p></article>)}</div>:<Empty text="No current new entities published for this range."/>}</div>
    <div className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Composition</p><h2 className="citem-section-title">Positive expansion</h2></div>{input.compositionUnavailable?<Unavailable text="Composition discovery unavailable."/>:input.composition?.length?<div className="space-y-2">{input.composition.map(item=><article className="rounded border border-stone-800 px-3 py-2" key={item.id}><Link className="break-all text-sm font-medium text-stone-200 hover:text-amber-200" href={entityHref(item.entityType,item.entityKey)}>{item.entityKey}</Link><p className="mt-1 text-xs text-stone-500">+{item.newUpstreamOriginCount} origins · +{item.newSourceClassCount} classes · +{item.newSourceDefinitionCount} source systems</p><p className="mt-1 text-xs text-stone-600">Absence is not interpreted as removal.</p></article>)}</div>:<Empty text="No positive composition expansion published for this range."/>}</div></section>

    <section className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Top movers</p><h2 className="citem-section-title">Explainable composition movement</h2><p className="mt-1 text-xs text-stone-500">Ordered by new upstream origins, source classes and source systems — not severity or risk.</p></div>{input.topMovers?.length?<div className="grid gap-3 lg:grid-cols-3">{input.topMovers.map(item=><article key={item.id} className="rounded border border-stone-800 p-3"><Link href={entityHref(item.entityType,item.entityKey)} className="break-all text-sm font-semibold text-stone-100 hover:text-amber-200">{item.entityKey}</Link><p className="mt-2 text-xs text-stone-500">+{item.newUpstreamOriginCount} origins · +{item.newSourceClassCount} classes · +{item.newSourceDefinitionCount} sources</p></article>)}</div>:<Empty text="No movers published for this range."/>}</section>

    <section className="card panel-corners space-y-3"><div><p className="citem-eyebrow">Geography</p><h2 className="citem-section-title">Observed infrastructure distribution</h2><p className="mt-1 text-xs text-stone-500">Country-level infrastructure context. This is not attacker origin. Current IPinfo snapshots are not backdated.</p></div>{input.geographyUnavailable?<Unavailable text="Geography unavailable; convergence and other discovery surfaces remain usable."/>:input.geography?.countries.length?<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{input.geography.countries.map(country=><article key={country.countryCode} className="rounded border border-stone-800 px-3 py-3"><p className="text-sm font-semibold text-stone-100">{country.countryName??country.countryCode}</p><p className="mt-1 text-xs text-stone-500">{country.countryCode} · {country.observedEntityCount} entities</p><p className="mt-1 text-xs text-stone-600">{country.sourceSystemCount} source systems · {country.upstreamOriginCount} origins</p></article>)}</div>:<Empty text="No country-level geographic assertions published for this range."/>}</section>
  </section>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded bg-black/20 px-2 py-2"><p className="text-[10px] uppercase tracking-[0.12em] text-stone-600">{label}</p><p className="mt-1 text-sm text-stone-200">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="text-sm text-stone-500">{text}</p>}
function Unavailable({text}:{text:string}){return <p className="rounded border border-stone-800 px-3 py-2 text-sm text-stone-500">{text}</p>}
function RangeLinks({range}:{range:GlobalRange}){return <nav className="flex gap-2" aria-label="Discovery history range">{(['24h','7d','30d'] as const).map(value=><Link key={value} href={`/techint/discovery?range=${value}`} className={value===range?'citem-button':'citem-button-ghost'}>{value.toUpperCase()}</Link>)}</nav>}
