import { redactUrl } from "./url";

export const FEED_VIEW_PROJECTION = "id,name,description,configured_url,detected_feed_type,enabled,health_status,last_checked_at,last_success_at,last_content_change_at,last_http_status,last_final_url,etag,last_modified,consecutive_failures,last_error_message,archived_at,research_feed_item_observations(count)";
export const FETCH_RUN_VIEW_PROJECTION = "id,feed_source_id,status,started_at,completed_at,duration_ms,http_status,response_bytes,items_seen,items_created,items_changed,items_deduplicated,items_skipped,error_message,created_at";

export type FeedViewModel = {id:string;name:string;description:string;display_url:string|null;enabled:boolean;archived_at:string|null;detected_feed_type:string;health_status:string;last_checked_at:string|null;last_success_at:string|null;last_content_change_at:string|null;last_http_status:number|null;last_final_url:string|null;has_etag:boolean;has_last_modified:boolean;consecutive_failures:number;last_error_message:string|null;recent_item_count:number};
export type FetchRunViewModel = {id:string;feed_source_id:string;status:string;started_at:string;completed_at:string|null;duration_ms:number|null;http_status:number|null;response_bytes:number|null;items_seen:number;items_created:number;items_changed:number;items_deduplicated:number;items_skipped:number;error_message:string|null;created_at:string};

type Row=Record<string,unknown>;
export function toFeedViewModel(row:Row):FeedViewModel {const observations=Array.isArray(row.research_feed_item_observations)?row.research_feed_item_observations:[];const count=observations[0] as {count?:number}|undefined;return{id:String(row.id),name:String(row.name),description:String(row.description??""),display_url:redactUrl(typeof row.configured_url==="string"?row.configured_url:null),enabled:Boolean(row.enabled),archived_at:typeof row.archived_at==="string"?row.archived_at:null,detected_feed_type:String(row.detected_feed_type),health_status:String(row.health_status),last_checked_at:typeof row.last_checked_at==="string"?row.last_checked_at:null,last_success_at:typeof row.last_success_at==="string"?row.last_success_at:null,last_content_change_at:typeof row.last_content_change_at==="string"?row.last_content_change_at:null,last_http_status:typeof row.last_http_status==="number"?row.last_http_status:null,last_final_url:redactUrl(typeof row.last_final_url==="string"?row.last_final_url:null),has_etag:Boolean(row.etag),has_last_modified:Boolean(row.last_modified),consecutive_failures:Number(row.consecutive_failures??0),last_error_message:typeof row.last_error_message==="string"?row.last_error_message:null,recent_item_count:Number(count?.count??0)};}
export function toFetchRunViewModel(row:Row):FetchRunViewModel{return{id:String(row.id),feed_source_id:String(row.feed_source_id),status:String(row.status),started_at:String(row.started_at),completed_at:typeof row.completed_at==="string"?row.completed_at:null,duration_ms:typeof row.duration_ms==="number"?row.duration_ms:null,http_status:typeof row.http_status==="number"?row.http_status:null,response_bytes:typeof row.response_bytes==="number"?row.response_bytes:null,items_seen:Number(row.items_seen??0),items_created:Number(row.items_created??0),items_changed:Number(row.items_changed??0),items_deduplicated:Number(row.items_deduplicated??0),items_skipped:Number(row.items_skipped??0),error_message:typeof row.error_message==="string"?row.error_message:null,created_at:String(row.created_at)};}
