import { NextResponse } from "next/server";
import { z } from "zod";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { indicatorSchema, actorSchema, campaignSchema, malwareSchema, cveSchema, validateIndicator, normalizeIndicatorValue } from "@/lib/cti-schema";
import { noteSchema } from "@/lib/workspace/schema";
import { reportMetaSchema, reportSchema } from "@/lib/reports/schema";
import { toTiptapDoc, reportDraftSchema, missingProtectedTokens } from "@/lib/ai/workflows";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const uuid = z.string().uuid();
const schema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("save_summary_note"), title: z.string().max(160), content: z.string().max(50000), sourceNoteIds: z.array(uuid).max(20) }).strict(),
  z.object({ kind: z.literal("add_indicator"), value: z.string().max(500), type: z.enum(["IP","DOMAIN","URL","HASH","EMAIL","FILE","REGISTRY"]), confidence: z.enum(["LOW","MEDIUM","HIGH"]), source: z.string().max(300).optional() }).strict(),
  z.object({ kind: z.literal("add_entity"), entityType: z.enum(["actors","malware","campaigns","cves"]), name: z.string().max(180), description: z.string().max(20000).optional() }).strict(),
  z.object({ kind: z.literal("link_mitre"), parentType: z.enum(["campaigns","malware"]), parentId: uuid, techniqueIds: z.array(uuid).max(20) }).strict(),
  z.object({ kind: z.literal("save_report_draft"), draft: reportDraftSchema }).strict(),
  z.object({ kind: z.literal("save_translation_note"), title: z.string().max(160), translatedText: z.string().max(50000), sourceText: z.string().max(50000) }).strict(),
]);
async function projectCtx(id: string) { const { supabase, user } = await requireUser(); const { data, error } = await supabase.from("projects").select("id,owner_id").eq("id", id).single(); if (error || !data || data.owner_id !== user.id) throw new Error("not_found"); return { supabase, user, projectId: id }; }
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try { const { id } = await params; const body = schema.parse(await req.json()); const { supabase, user } = await projectCtx(id);
    if (body.kind === "save_summary_note" || body.kind === "save_translation_note") { if (body.kind === "save_translation_note" && missingProtectedTokens(body.sourceText, body.translatedText).length) return NextResponse.json({ error: "Protected values must be preserved before saving." }, { status: 400 }); const p = noteSchema.parse({ title: body.title, content: body.kind === "save_summary_note" ? body.content : body.translatedText, tags: ["ai-generated"] }); const { data, error } = await supabase.from("research_notes").insert({ ...p, project_id: id, author_id: user.id }).select("id").single(); if (error) return NextResponse.json({ error: "Unable to save note." }, { status: 400 }); revalidatePath(`/projects/${id}`); return NextResponse.json({ ok: true, id: data.id }); }
    if (body.kind === "add_indicator") { const normalized = normalizeIndicatorValue(body.value, body.type); const invalid = validateIndicator(normalized, body.type); if (invalid) return NextResponse.json({ error: invalid }, { status: 400 }); const p = indicatorSchema.parse({ value: normalized, type: body.type, confidence: body.confidence, source: body.source ?? "AI-reviewed approval", tags: ["ai-generated"], first_seen: null, last_seen: null }); const { data: dup } = await supabase.from("indicators").select("id").eq("project_id", id).eq("type", p.type).eq("value", p.value).maybeSingle(); if (dup) return NextResponse.json({ ok: true, id: dup.id, duplicate: true }); const { data, error } = await supabase.from("indicators").insert({ ...p, project_id: id }).select("id").single(); if (error) return NextResponse.json({ error: "Unable to save indicator." }, { status: 400 }); revalidatePath(`/projects/${id}`); return NextResponse.json({ ok: true, id: data.id }); }
    if (body.kind === "add_entity") { const table = ({ actors:"threat_actors", malware:"malware", campaigns:"campaigns", cves:"cves" } as const)[body.entityType]; const payload = body.entityType === "actors" ? actorSchema.parse({ name: body.name, description: body.description ?? "", aliases: [], country: null, motivations: [], known_ttps: "", references: [] }) : body.entityType === "campaigns" ? campaignSchema.parse({ name: body.name, description: body.description ?? "", start_date: null, end_date: null, targets: [] }) : body.entityType === "malware" ? malwareSchema.parse({ name: body.name, description: body.description ?? "", aliases: [], malware_type: null, platforms: [], capabilities: [], references: [] }) : cveSchema.parse({ cve_id: body.name, description: body.description ?? "", severity: "LOW", cvss_score: null, affected_products: [], exploit_status: "NONE", references: [] }); const uniqueCol = body.entityType === "cves" ? "cve_id" : "name"; const { data: dup } = await supabase.from(table).select("id").eq("project_id", id).eq(uniqueCol, body.name).maybeSingle(); if (dup) return NextResponse.json({ ok: true, id: dup.id, duplicate: true }); const { data, error } = await supabase.from(table).insert({ ...payload, project_id: id }).select("id").single(); if (error) return NextResponse.json({ error: "Unable to save entity." }, { status: 400 }); revalidatePath(`/projects/${id}`); return NextResponse.json({ ok: true, id: data.id }); }
    if (body.kind === "link_mitre") { const table = body.parentType === "campaigns" ? "campaign_mitre_techniques" : "malware_mitre_techniques"; const parentTable = body.parentType === "campaigns" ? "campaigns" : "malware"; const parentCol = body.parentType === "campaigns" ? "campaign_id" : "malware_id"; const { data: parent } = await supabase.from(parentTable).select("id").eq("project_id", id).eq("id", body.parentId).single(); const { count } = await supabase.from("mitre_techniques").select("id", { count: "exact", head: true }).eq("project_id", id).in("id", body.techniqueIds); if (!parent || count !== body.techniqueIds.length) return NextResponse.json({ error: "Unable to link MITRE techniques." }, { status: 400 }); const rows = body.techniqueIds.map((tid) => ({ project_id: id, [parentCol]: body.parentId, mitre_technique_id: tid })); const { error } = await supabase.from(table).upsert(rows, { onConflict: `project_id,${parentCol},mitre_technique_id` }); if (error) return NextResponse.json({ error: "Unable to link MITRE techniques." }, { status: 400 }); revalidatePath(`/projects/${id}`); return NextResponse.json({ ok: true, count: rows.length }); }
    const doc = toTiptapDoc(body.draft); const report = reportSchema.parse({ title: body.draft.title, type: body.draft.report_type_suggestion, status: "DRAFT", content: doc }); reportMetaSchema.parse(report); const { data, error } = await supabase.from("reports").insert({ ...report, project_id: id, author_id: user.id }).select("id").single(); if (error) return NextResponse.json({ error: "Unable to save report." }, { status: 400 }); revalidatePath(`/projects/${id}`); return NextResponse.json({ ok: true, id: data.id });
  } catch { return NextResponse.json({ error: "Approval could not be completed." }, { status: 400 }); }
}
