import ipaddr from "ipaddr.js";
import {createHash} from "node:crypto";
import {domainToASCII} from "node:url";
import type {IocCandidateType,NormalizedCandidate} from "./types";

const MAX=8000, dot=/\[\.\]/gi;
function port(value:unknown){if(value==null)return null;const n=Number(value);if(!Number.isInteger(n)||n<1||n>65535)throw new Error("INVALID_CANDIDATE_VALUE");return n}
function ip(raw:string,type:"IPV4"|"IPV6"){if(raw.includes("%"))throw new Error("INVALID_CANDIDATE_VALUE");let value=raw.replace(dot,"."),p:number|null=null;if(type==="IPV4"){const m=/^(.+):(\d+)$/.exec(value);if(m){value=m[1];p=port(m[2])}}else if(value.startsWith("[")){const m=/^\[([^\]]+)\](?::(\d+))?$/.exec(value);if(!m)throw new Error("INVALID_CANDIDATE_VALUE");value=m[1];p=port(m[2])}const parsed=ipaddr.parse(value);if((type==="IPV4"&&parsed.kind()!=="ipv4")||(type==="IPV6"&&parsed.kind()!=="ipv6"))throw new Error("INVALID_CANDIDATE_VALUE");return{value:parsed.toString(),port:p}}
function cidr(raw:string){const [address,prefixText,...extra]=raw.replace(dot,".").split("/");if(extra.length||!prefixText||!/^[0-9]+$/.test(prefixText))throw new Error("INVALID_CANDIDATE_VALUE");const parsed=ipaddr.parse(address),prefix=Number(prefixText),max=parsed.kind()==="ipv4"?32:128;if(prefix<0||prefix>max)throw new Error("INVALID_CANDIDATE_VALUE");const bytes=parsed.toByteArray(),whole=Math.floor(prefix/8),bits=prefix%8;for(let i=whole;i<bytes.length;i++)bytes[i]=i===whole&&bits?bytes[i]&((0xff<<(8-bits))&0xff):0;const network=parsed.kind()==="ipv4"?new ipaddr.IPv4(bytes):new ipaddr.IPv6(Array.from({length:8},(_,i)=>(bytes[i*2]<<8)|bytes[i*2+1]));return`${network.toString()}/${prefix}`}
function domain(raw:string){let value=raw.replace(dot,".").toLowerCase();if(value.endsWith("."))value=value.slice(0,-1);if(value.startsWith("*.")||/[\s\/:?#@]/.test(value)||ipaddr.isValid(value))throw new Error("INVALID_CANDIDATE_VALUE");value=domainToASCII(value);if(!value||value.length>253||!value.includes(".")||value.split(".").some(x=>!x||x.length>63||! /^(?!-)[a-z0-9-]+(?<!-)$/.test(x)))throw new Error("INVALID_CANDIDATE_VALUE");return value}
export function normalizeCandidateValue(type:IocCandidateType,original:string,networkPort?:number|null){const raw=original.trim();if(!raw||raw.length>MAX||/\r|\n/.test(raw))throw new Error("INVALID_CANDIDATE_VALUE");if(type==="IPV4"||type==="IPV6"){const parsed=ip(raw,type);return{normalizedValue:parsed.value,networkPort:networkPort==null?parsed.port:port(networkPort)}}if(networkPort!=null)throw new Error("INVALID_CANDIDATE_VALUE");if(type==="CIDR")return{normalizedValue:cidr(raw),networkPort:null};if(type==="DOMAIN"||type==="HOSTNAME")return{normalizedValue:domain(raw),networkPort:null};if(type==="URL"){const refanged=raw.replace(/^hxxps:/i,"https:").replace(/^hxxp:/i,"http:").replace(dot,".");let u:URL;try{u=new URL(refanged)}catch{throw new Error("INVALID_CANDIDATE_VALUE")}if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw new Error("INVALID_CANDIDATE_VALUE");u.hash="";if((u.protocol==="http:"&&u.port==="80")||(u.protocol==="https:"&&u.port==="443"))u.port="";return{normalizedValue:u.toString(),networkPort:null}}if(type==="CVE"){const v=raw.toUpperCase();if(!/^CVE-\d{4}-\d{4,}$/.test(v))throw new Error("INVALID_CANDIDATE_VALUE");return{normalizedValue:v,networkPort:null}}const lengths={MD5:32,SHA1:40,SHA256:64} as const;if(!new RegExp(`^[a-fA-F0-9]{${lengths[type]}}$`).test(raw))throw new Error("INVALID_CANDIDATE_VALUE");return{normalizedValue:raw.toLowerCase(),networkPort:null}}
export function normalizeProviderItem(input:{providerKey:string;providerItemId:string;type:IocCandidateType;value:string;networkPort?:number|null}&Partial<Omit<NormalizedCandidate,"provider_item_id"|"candidate_type"|"normalized_value"|"original_value"|"network_port"|"source_fingerprint">>):NormalizedCandidate{const n=normalizeCandidateValue(input.type,input.value,input.networkPort);const fingerprint=createHash("sha256").update(`${input.providerKey}\0${input.providerItemId}\0${input.type}\0${n.normalizedValue}\0${n.networkPort??0}`).digest("hex");return{provider_item_id:input.providerItemId,candidate_type:input.type,normalized_value:n.normalizedValue,original_value:input.value,network_port:n.networkPort,provider_reference_url:input.provider_reference_url??null,threat_type:input.threat_type??null,malware_family:input.malware_family??null,confidence_score:input.confidence_score??null,first_seen_at:input.first_seen_at??null,last_seen_at:input.last_seen_at??null,tags:input.tags??[],metadata:input.metadata??{},source_fingerprint:fingerprint}}
export function defangCandidate(type:IocCandidateType,value:string){if(type==="URL")return value.replace(/^https:/,"hxxps:").replace(/^http:/,"hxxp:").replace(/\./g,"[.]");if(["IPV4","DOMAIN","HOSTNAME"].includes(type))return value.replace(/\./g,"[.]");if(type==="CIDR")return value.replace(/\./g,"[.]");return value}
