"use client";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { linkEventEntity, linkEventSupport, saveClusterMembership, saveEventMembership, saveReconstruction } from "@/app/projects/[id]/reconstruction-actions";
type Row=Record<string,unknown>; type State={error?:string;success?:string}; const s=(v:unknown)=>String(v??""); const dt=(v:unknown)=>s(v).slice(0,16);
function Submit(){const{pending}=useFormStatus();return <button disabled={pending} className="rounded bg-cyan-300 px-3 py-2 font-semibold text-slate-950">{pending?"Saving…":"Save"}</button>}
function Form({action,children}:{action:(state:State,fd:FormData)=>Promise<State>,children:React.ReactNode}){const[state,a]=useActionState(action,{});return <form action={a} className="mt-3 grid gap-3">{children}<Submit/>{state.error&&<p role="alert" className="text-red-300">{state.error}</p>}{state.success&&<p className="text-emerald-300">{state.success}</p>}</form>}
const statuses=["POSSIBLE","CONFIRMED","REJECTED","REMOVED"];
export function EventMembershipForm({projectId,eventId,campaigns}:{projectId:string,eventId:string,campaigns:Row[]}){return <Form action={saveEventMembership.bind(null,projectId,eventId)}><select className="field" name="campaign_id" required><option value="">Select existing Campaign</option>{campaigns.map(x=><option key={s(x.id)} value={s(x.id)}>{s(x.name)}</option>)}</select><div className="grid gap-2 md:grid-cols-3"><select className="field" name="status">{statuses.map(x=><option key={x}>{x}</option>)}</select><select className="field" name="confidence">{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select><input className="field" name="sequence_order" type="number" min="0" placeholder="Optional sequence order"/></div><textarea className="field" required name="rationale" placeholder="Why this event belongs—or does not belong—to the Campaign"/></Form>}
export function EntityLinkForm({projectId,eventId,options}:{projectId:string,eventId:string,options:Record<string,Row[]>}){return <Form action={linkEventEntity.bind(null,projectId,eventId)}><select className="field" name="entity_type">{Object.keys(options).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input className="field" required name="entity_id" placeholder="Existing entity UUID (shown in selectors below)"/><select className="field" name="role">{["SUBJECT","INFRASTRUCTURE","PAYLOAD","TECHNIQUE","VULNERABILITY","SUPPORTING_ARTIFACT","OTHER"].map(x=><option key={x}>{x}</option>)}</select><textarea className="field" name="analyst_note" placeholder="Optional analyst note"/><div className="text-xs text-stone-500">{Object.entries(options).map(([k,rows])=><p key={k}><strong>{k}:</strong> {rows.map(x=>`${s(x.name||x.value||x.cve_id||x.technique_id)} (${s(x.id)})`).join(" · ")||"none"}</p>)}</div></Form>}
export function SupportLinkForm({projectId,eventId,options}:{projectId:string,eventId:string,options:Record<string,Row[]>}){return <Form action={linkEventSupport.bind(null,projectId,eventId)}><select className="field" name="support_type">{Object.keys(options).map(x=><option key={x}>{x}</option>)}</select><input className="field" required name="support_id" placeholder="Existing supporting record UUID"/><textarea className="field" name="analyst_note" placeholder="Optional analyst note"/><div className="text-xs text-stone-500">{Object.entries(options).map(([k,rows])=><p key={k}><strong>{k}:</strong> {rows.map(x=>`${s(x.title||x.provider_label_snapshot||x.category)} (${s(x.id)})`).join(" · ")||"none"}</p>)}</div></Form>}
export function ReconstructionForm({projectId,campaignId,row={}}:{projectId:string,campaignId:string,row?:Row}){return <Form action={saveReconstruction.bind(null,projectId,campaignId)}><div className="grid gap-2 md:grid-cols-3"><select className="field" name="reconstruction_status" defaultValue={s(row.reconstruction_status)||"DRAFT"}><option>DRAFT</option><option>ASSESSED</option></select><select className="field" name="activity_status" defaultValue={s(row.activity_status)||"UNKNOWN"}>{["UNKNOWN","ACTIVE","DORMANT","CONCLUDED"].map(x=><option key={x}>{x}</option>)}</select><select className="field" name="confidence" defaultValue={s(row.confidence)||"MEDIUM"}>{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select></div><textarea className="field" name="operational_objective" defaultValue={s(row.operational_objective)} placeholder="Operational objective — what the Campaign appears intended to achieve"/><textarea className="field" name="current_assessment" defaultValue={s(row.current_assessment)} placeholder="Current analyst assessment"/><textarea className="field" name="next_expected_activity" defaultValue={s(row.next_expected_activity)} placeholder="Bounded near-term expectation, not certainty"/><textarea className="field" name="key_uncertainties" defaultValue={s(row.key_uncertainties)} placeholder="Missing, disputed, or insufficiently supported points"/><div className="grid gap-2 md:grid-cols-3"><input className="field" type="datetime-local" name="first_observed_at" defaultValue={dt(row.first_observed_at)}/><input className="field" type="datetime-local" name="last_observed_at" defaultValue={dt(row.last_observed_at)}/><input className="field" type="datetime-local" name="assessed_at" defaultValue={dt(row.assessed_at)}/></div></Form>}
export function ClusterMembershipForm({projectId,campaignId,clusters}:{projectId:string,campaignId:string,clusters:Row[]}){return <Form action={saveClusterMembership.bind(null,projectId,campaignId)}><select className="field" name="infrastructure_cluster_id" required><option value="">Select existing Infrastructure Cluster</option>{clusters.map(x=><option key={s(x.id)} value={s(x.id)}>{s(x.name)}</option>)}</select><div className="grid gap-2 md:grid-cols-2"><select className="field" name="status">{statuses.map(x=><option key={x}>{x}</option>)}</select><select className="field" name="confidence">{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select></div><textarea className="field" required name="rationale" placeholder="Campaign-specific rationale"/><div className="grid gap-2 md:grid-cols-2"><input className="field" name="first_observed_at" type="datetime-local"/><input className="field" name="last_observed_at" type="datetime-local"/></div></Form>}
