import React from "react";
import { NextResponse } from "next/server";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { requireUser } from "@/lib/auth";
import { parseJsonDoc, safeReportFilename, type ReportDoc } from "@/lib/reports/schema";
import { escapeHtml, standaloneHtml, tiptapToMarkdown, tiptapToPdfElements } from "@/lib/reports/render";
import { attributionDisclaimer } from "@/lib/reports/versioning";
export const runtime = "nodejs";
type Row=Record<string,unknown>;
const styles=StyleSheet.create({page:{padding:36,fontSize:11,lineHeight:1.4},title:{fontSize:22,marginBottom:8,fontWeight:700},meta:{fontSize:10,marginBottom:10,color:"#475569"},heading:{fontSize:14,marginTop:10,marginBottom:3,fontWeight:700},pageNo:{position:"absolute",bottom:18,right:36,fontSize:9,color:"#64748b"}});
const assessmentFields=[["Executive summary","executive_summary_snapshot"],["Key judgments","key_judgments_snapshot"],["Confidence","confidence_snapshot"],["Intelligence gaps","intelligence_gaps_snapshot"],["Recommendations","recommendations_snapshot"],["Change summary","change_summary"]] as const;
function appendix(v:Row){return (v.report_version_references as Row[]??[]).map(r=>`${String(r.reference_type)}: ${String(r.label_snapshot)} | state ${JSON.stringify(r.state_snapshot)} | source updated ${String(r.source_updated_at)}`)}
function versionMarkdown(v:Row,content:ReportDoc){const fields=assessmentFields.map(([label,key])=>`## ${label}\n\n${String(v[key])}`).join("\n\n");const disclaimer=v.product_type_snapshot==="ATTRIBUTION_ASSESSMENT"?`\n\n## Attribution disclaimer\n\n${attributionDisclaimer}`:"";return `# ${String(v.title_snapshot)}\n\n**Product type:** ${String(v.product_type_snapshot)}  \n**Version:** ${String(v.version_number)} (${String(v.version_status)})  \n**Created:** ${String(v.created_at)}  \n**Issued:** ${String(v.published_at??"Not issued")}  \n**Author:** Analyst ${String(v.created_by)}\n\n${fields}\n\n## Frozen report content\n\n${tiptapToMarkdown(content)}\n\n## Referenced-record appendix\n\n${appendix(v).map(x=>`- ${x}`).join("\n")||"No references."}${disclaimer}\n`;}
function versionHtml(v:Row,content:Parameters<typeof standaloneHtml>[0]){const body=assessmentFields.map(([label,key])=>`<h2>${escapeHtml(label)}</h2><p>${escapeHtml(String(v[key]))}</p>`).join("")+`<h2>Frozen report content</h2>`+standaloneHtml(content,{title:String(v.title_snapshot),type:String(v.product_type_snapshot),status:`Version ${String(v.version_number)} · ${String(v.version_status)}`,updated_at:String(v.created_at)}).match(/<body>([\s\S]*)<\/body>/)?.[1]+`<h2>Referenced-record appendix</h2><ul>${appendix(v).map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`+(v.product_type_snapshot==="ATTRIBUTION_ASSESSMENT"?`<h2>Attribution disclaimer</h2><p>${escapeHtml(attributionDisclaimer)}</p>`:"");return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(String(v.title_snapshot))} v${String(v.version_number)}</title><style>body{font-family:Arial,sans-serif;line-height:1.55;max-width:900px;margin:40px auto;color:#111827}table{border-collapse:collapse;width:100%}td,th{border:1px solid #cbd5e1;padding:6px}</style></head><body><h1>${escapeHtml(String(v.title_snapshot))}</h1><p><strong>${escapeHtml(String(v.product_type_snapshot))}</strong> · Version ${String(v.version_number)} · ${escapeHtml(String(v.version_status))}<br>Created ${escapeHtml(String(v.created_at))} · Issued ${escapeHtml(String(v.published_at??"Not issued"))} · Analyst ${escapeHtml(String(v.created_by))}</p>${body}</body></html>`;}
function PdfDoc({record,content,versioned}:{record:Row;content:unknown;versioned:boolean}){return React.createElement(Document,null,React.createElement(Page,{size:"A4",style:styles.page,wrap:true},React.createElement(Text,{style:styles.title},String(record.title_snapshot??record.title)),React.createElement(Text,{style:styles.meta},versioned?`${String(record.product_type_snapshot)} · Version ${String(record.version_number)} · ${String(record.version_status)} · Created ${String(record.created_at)} · Issued ${String(record.published_at??"Not issued")} · Analyst ${String(record.created_by)}`:`${String(record.type)} · ${String(record.status)} · Working draft · ${String(record.updated_at??"")}`),...(versioned?assessmentFields.flatMap(([label,key])=>[React.createElement(Text,{key:`${key}-h`,style:styles.heading},label),React.createElement(Text,{key},String(record[key]))]):[]),React.createElement(Text,{style:styles.heading},versioned?"Frozen report content":"Report content"),React.createElement(View,null,tiptapToPdfElements(content)),...(versioned?[React.createElement(Text,{key:"appendix-h",style:styles.heading},"Referenced-record appendix"),...appendix(record).map((x,i)=>React.createElement(Text,{key:`ref-${i}`},`• ${x}`)),...(record.product_type_snapshot==="ATTRIBUTION_ASSESSMENT"?[React.createElement(Text,{key:"disclaimer-h",style:styles.heading},"Attribution disclaimer"),React.createElement(Text,{key:"disclaimer"},attributionDisclaimer)]:[])]:[]),React.createElement(Text,{fixed:true,render:({pageNumber,totalPages})=>`${pageNumber} / ${totalPages}`,style:styles.pageNo})));}
export async function GET(request:Request,{params}:{params:Promise<{id:string;reportId:string;format:string}>}){const {id,reportId,format}=await params;const {supabase,user}=await requireUser();const {data:project}=await supabase.from("projects").select("owner_id").eq("id",id).single();if(!project||project.owner_id!==user.id)return NextResponse.json({error:"Not found"},{status:404});const {data:report}=await supabase.from("reports").select("*").eq("project_id",id).eq("id",reportId).single();if(!report)return NextResponse.json({error:"Not found"},{status:404});
 const url=new URL(request.url),versionId=url.searchParams.get("versionId"),authoritative=url.searchParams.get("scope")==="authoritative";let record:Row=report,versioned=false;if(versionId||authoritative){let q=supabase.from("report_versions").select("*,report_version_references(*)").eq("project_id",id).eq("report_id",reportId);q=versionId?q.eq("id",versionId):q.eq("id",report.authoritative_version_id??"");const {data:v}=await q.single();if(!v)return NextResponse.json({error:"Not found"},{status:404});record=v;versioned=true;}
 const parsed=parseJsonDoc(versioned?record.content_snapshot:record.content);if(!parsed.success)return NextResponse.json({error:"Report content is invalid."},{status:422});const ext=format==="md"?"md":format==="html"?"html":format==="pdf"?"pdf":"";if(!ext)return NextResponse.json({error:"Unsupported export format."},{status:400});const stem=versioned?`${String(record.title_snapshot)}-v${String(record.version_number)}`:String(record.title);const headers={"Content-Disposition":`attachment; filename="${safeReportFilename(stem,ext)}"`};if(format==="md")return new NextResponse(versioned?versionMarkdown(record,parsed.data):tiptapToMarkdown(parsed.data,String(report.title)),{headers:{...headers,"Content-Type":"text/markdown; charset=utf-8"}});if(format==="html")return new NextResponse(versioned?versionHtml(record,parsed.data):standaloneHtml(parsed.data,{title:String(report.title),type:String(report.type),status:String(report.status),updated_at:String(report.updated_at??"")}),{headers:{...headers,"Content-Type":"text/html; charset=utf-8"}});try{const buf=await renderToBuffer(React.createElement(PdfDoc,{record,content:parsed.data,versioned}) as React.ReactElement<React.ComponentProps<typeof Document>>);if(!buf.subarray(0,4).equals(Buffer.from("%PDF"))||!buf.includes(Buffer.from("%%EOF")))throw new Error();return new NextResponse(new Uint8Array(buf),{headers:{...headers,"Content-Type":"application/pdf"}});}catch{return NextResponse.json({error:"Unable to generate PDF export."},{status:500});}}
