"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { parseProjectForm } from "@/lib/projects/schema";
import { requireUser } from "@/lib/auth";

type State = { error?: string; success?: string; fields?: Record<string,string> };
function safeReturn(path: string | null) { return path?.startsWith("/") && !path.startsWith("//") ? path : "/dashboard"; }
export async function signIn(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const password = String(formData.get("password")||""); const { error } = await s.auth.signInWithPassword({ email, password }); if (error) return { error: error.message }; redirect(safeReturn(String(formData.get("returnTo")||"/dashboard"))); }
export async function signUp(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const password = String(formData.get("password")||""); const display_name = String(formData.get("display_name")||""); const { error } = await s.auth.signUp({ email, password, options: { data: { display_name } } }); if (error) return { error: error.message }; return { success: "Check your email to confirm your account, then sign in." }; }
export async function signOut() { const s = await createClient(); await s.auth.signOut(); redirect("/auth/sign-in"); }
export async function forgotPassword(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const { error } = await s.auth.resetPasswordForEmail(email, { redirectTo: `${process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"}/auth/update-password` }); if (error) return { error: error.message }; return { success: "If email recovery is enabled in Supabase, a reset link has been sent." }; }
export async function updatePassword(_: State, formData: FormData): Promise<State> { const s = await createClient(); const password = String(formData.get("password")||""); if (password.length < 8) return { error: "Password must be at least 8 characters." }; const { error } = await s.auth.updateUser({ password }); if (error) return { error: error.message }; return { success: "Password updated. You can continue to the dashboard." }; }
export async function createProject(_: State, formData: FormData): Promise<State> { const { supabase, user } = await requireUser(); const parsed = parseProjectForm(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid project" }; const { data, error } = await supabase.from("projects").insert({ ...parsed.data, owner_id: user.id }).select("id").single(); if (error) return { error: error.code === "23505" ? "A project with this name already exists." : error.message }; revalidatePath("/projects"); redirect(`/projects/${data.id}`); }
export async function updateProject(id: string, _: State, formData: FormData): Promise<State> { const { supabase } = await requireUser(); const parsed = parseProjectForm(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid project" }; const { error } = await supabase.from("projects").update(parsed.data).eq("id", id); if (error) return { error: error.message }; revalidatePath(`/projects/${id}`); revalidatePath("/projects"); return { success: "Project updated." }; }
export async function deleteProject(id: string, name: string, formData: FormData) { const confirm = String(formData.get("confirm")||""); if (confirm !== name) return; const { supabase } = await requireUser(); await supabase.from("projects").delete().eq("id", id); revalidatePath("/projects"); redirect("/projects"); }
