"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { parseProjectForm } from "@/lib/projects/schema";
import { requireUser } from "@/lib/auth";
import { buildEvidencePath, evidenceFinalizeSchema, evidenceMetadataSchema, evidenceUrlOnlySchema, formObject, noteSchema, taskSchema, timelineSchema, uploadAuthorizeSchema, validateUpload } from "@/lib/workspace/schema";

type State = { error?: string; success?: string; fields?: Record<string,string> };
function safeReturn(path: string | null) { return path?.startsWith("/") && !path.startsWith("//") ? path : "/dashboard"; }
export async function signIn(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const password = String(formData.get("password")||""); const { error } = await s.auth.signInWithPassword({ email, password }); if (error) return { error: error.message }; redirect(safeReturn(String(formData.get("returnTo")||"/dashboard"))); }
export async function signUp(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const password = String(formData.get("password")||""); const display_name = String(formData.get("display_name")||""); const { error } = await s.auth.signUp({ email, password, options: { data: { display_name } } }); if (error) return { error: error.message }; return { success: "Check your email to confirm your account, then sign in." }; }
export async function signOut() { const s = await createClient(); await s.auth.signOut(); redirect("/auth/sign-in"); }
export async function forgotPassword(_: State, formData: FormData): Promise<State> { const s = await createClient(); const email = String(formData.get("email")||""); const { error } = await s.auth.resetPasswordForEmail(email, { redirectTo: `${process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"}/auth/update-password` }); if (error) return { error: error.message }; return { success: "If email recovery is enabled in Supabase, a reset link has been sent." }; }
export async function updatePassword(_: State, formData: FormData): Promise<State> { const s = await createClient(); const password = String(formData.get("password")||""); if (password.length < 8) return { error: "Password must be at least 8 characters." }; const { error } = await s.auth.updateUser({ password }); if (error) return { error: error.message }; return { success: "Password updated. You can continue to the dashboard." }; }
export async function createProject(_: State, formData: FormData): Promise<State> { const { supabase, user } = await requireUser(); const parsed = parseProjectForm(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid project" }; const { data, error } = await supabase.from("projects").insert({ ...parsed.data, owner_id: user.id }).select("id").single(); if (error) return { error: error.code === "23505" ? "A project with this name already exists." : error.message }; revalidatePath("/projects"); redirect(`/projects/${data.id}`); }
export async function updateProject(id: string, _: State, formData: FormData): Promise<State> { const { supabase } = await requireUser(); const parsed = parseProjectForm(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Invalid project" }; const { error } = await supabase.from("projects").update(parsed.data).eq("id", id); if (error) return { error: error.message }; revalidatePath(`/projects/${id}`); revalidatePath("/projects"); return { success: "Project updated." }; }
export async function deleteProject(id: string, name: string, formData: FormData) { const confirm = String(formData.get("confirm")||""); if (confirm !== name) return; const { supabase } = await requireUser(); await supabase.from("projects").delete().eq("id", id); revalidatePath("/projects"); redirect("/projects"); }

async function assertProject(projectId:string){const ctx=await requireUser(); const {data,error}=await ctx.supabase.from("projects").select("id,owner_id").eq("id",projectId).single(); if(error||!data||data.owner_id!==ctx.user.id) throw new Error("Project not found"); return ctx;}
async function assertChild(projectId:string, table:"research_notes"|"evidence"|"timeline_events"|"project_tasks", id:string){const {supabase,user}=await assertProject(projectId); const {data,error}=await supabase.from(table).select("id,project_id").eq("project_id",projectId).eq("id",id).single(); if(error||!data) throw new Error("Record not found"); return {supabase,user};}
const msg=(p:{success:boolean; error?:{issues:{message:string}[]}})=>p.error?.issues[0]?.message??"Invalid input";

export async function createNote(projectId:string,_:State,fd:FormData):Promise<State>{const {supabase,user}=await assertProject(projectId);const p=noteSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("research_notes").insert({...p.data,project_id:projectId,author_id:user.id});if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Note created."};}
export async function updateNote(projectId:string,id:string,_:State,fd:FormData):Promise<State>{const {supabase}=await assertChild(projectId,"research_notes",id);const p=noteSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("research_notes").update(p.data).eq("project_id",projectId).eq("id",id);if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Note updated."};}
export async function deleteNote(projectId:string,id:string){const {supabase}=await assertChild(projectId,"research_notes",id);await supabase.from("research_notes").delete().eq("project_id",projectId).eq("id",id);revalidatePath(`/projects/${projectId}`);}

export async function createUrlEvidence(projectId:string,_:State,fd:FormData):Promise<State>{const {supabase,user}=await assertProject(projectId);const p=evidenceUrlOnlySchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("evidence").insert({...p.data,project_id:projectId,collected_by:user.id});if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Evidence saved."};}
export async function authorizeEvidenceUpload(projectId:string,input:unknown){const {supabase,user}=await assertProject(projectId);const p=uploadAuthorizeSchema.safeParse(input);if(!p.success)return{error:msg(p)};const bad=validateUpload({name:p.data.file_name,type:p.data.mime_type,size:p.data.file_size});if(bad)return{error:bad};const storage_path=buildEvidencePath(user.id,projectId,p.data.file_name);const {data,error}=await supabase.storage.from("evidence").createSignedUploadUrl(storage_path);if(error)return{error:error.message};return{success:"Upload authorized.",path:storage_path,token:data.token,metadata:p.data};}
export async function finalizeEvidenceUpload(projectId:string,input:unknown):Promise<State>{const {supabase,user}=await assertProject(projectId);const p=evidenceFinalizeSchema.safeParse(input);if(!p.success){const path=typeof input==="object"&&input&&"storage_path" in input?String(input.storage_path):null;if(path)await supabase.storage.from("evidence").remove([path]);return{error:msg(p)}}if(!p.data.storage_path.startsWith(`${user.id}/${projectId}/`)){await supabase.storage.from("evidence").remove([p.data.storage_path]);return{error:"Invalid evidence path."}}const {error}=await supabase.from("evidence").insert({...p.data,project_id:projectId,collected_by:user.id});if(error){await supabase.storage.from("evidence").remove([p.data.storage_path]);return{error:error.message}}revalidatePath(`/projects/${projectId}`);return{success:"Evidence saved."};}
export async function updateEvidence(projectId:string,id:string,_:State,fd:FormData):Promise<State>{const {supabase}=await assertChild(projectId,"evidence",id);const p=evidenceMetadataSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("evidence").update(p.data).eq("project_id",projectId).eq("id",id);if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Evidence updated."};}
export async function replaceEvidenceFile(projectId:string,id:string,input:unknown):Promise<State>{const {supabase,user}=await assertChild(projectId,"evidence",id);const p=evidenceFinalizeSchema.pick({storage_path:true,original_file_name:true,mime_type:true,file_size:true}).safeParse(input);if(!p.success)return{error:msg(p)};if(!p.data.storage_path.startsWith(`${user.id}/${projectId}/`)){await supabase.storage.from("evidence").remove([p.data.storage_path]);return{error:"Invalid evidence path."}}const {data:old}=await supabase.from("evidence").select("storage_path").eq("project_id",projectId).eq("id",id).single();const {error}=await supabase.from("evidence").update(p.data).eq("project_id",projectId).eq("id",id);if(error){await supabase.storage.from("evidence").remove([p.data.storage_path]);return{error:error.message}}if(old?.storage_path)await supabase.storage.from("evidence").remove([old.storage_path]);revalidatePath(`/projects/${projectId}`);return{success:"Evidence file replaced."};}
export async function getEvidenceDownloadUrl(projectId:string,id:string){const {supabase}=await assertChild(projectId,"evidence",id);const {data:ev,error}=await supabase.from("evidence").select("storage_path,source_url").eq("project_id",projectId).eq("id",id).single();if(error||!ev)return{error:"Evidence not found."};if(ev.source_url&&!ev.storage_path)return{url:ev.source_url};const {data,error:signError}=await supabase.storage.from("evidence").createSignedUrl(String(ev.storage_path),60);if(signError)return{error:signError.message};return{url:data.signedUrl};}
export async function deleteEvidence(projectId:string,id:string){const {supabase}=await assertChild(projectId,"evidence",id);const {data}=await supabase.from("evidence").select("storage_path").eq("project_id",projectId).eq("id",id).single();await supabase.from("evidence").delete().eq("project_id",projectId).eq("id",id); if(data?.storage_path) await supabase.storage.from("evidence").remove([data.storage_path]); revalidatePath(`/projects/${projectId}`);}

export async function createTimelineEvent(projectId:string,_:State,fd:FormData):Promise<State>{const {supabase}=await assertProject(projectId);const p=timelineSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("timeline_events").insert({...p.data,project_id:projectId});if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Event created."};}
export async function updateTimelineEvent(projectId:string,id:string,_:State,fd:FormData):Promise<State>{const {supabase}=await assertChild(projectId,"timeline_events",id);const p=timelineSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const {error}=await supabase.from("timeline_events").update(p.data).eq("project_id",projectId).eq("id",id);if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Event updated."};}
export async function deleteTimelineEvent(projectId:string,id:string){const {supabase}=await assertChild(projectId,"timeline_events",id);await supabase.from("timeline_events").delete().eq("project_id",projectId).eq("id",id);revalidatePath(`/projects/${projectId}`);}

export async function createTask(projectId:string,_:State,fd:FormData):Promise<State>{const {supabase,user}=await assertProject(projectId);const p=taskSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const assigned_user_id=p.data.assigned_user_id??user.id;if(assigned_user_id!==user.id)return{error:"Tasks can only be assigned to the project owner in Phase 2."};const {error}=await supabase.from("project_tasks").insert({...p.data,assigned_user_id,project_id:projectId});if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Task created."};}
export async function updateTask(projectId:string,id:string,_:State,fd:FormData):Promise<State>{const {supabase,user}=await assertChild(projectId,"project_tasks",id);const p=taskSchema.safeParse(formObject(fd));if(!p.success)return{error:msg(p)};const assigned_user_id=p.data.assigned_user_id??user.id;if(assigned_user_id!==user.id)return{error:"Tasks can only be assigned to the project owner in Phase 2."};const {error}=await supabase.from("project_tasks").update({...p.data,assigned_user_id}).eq("project_id",projectId).eq("id",id);if(error)return{error:error.message};revalidatePath(`/projects/${projectId}`);return{success:"Task updated."};}
export async function updateTaskStatus(projectId:string,id:string,status:"TODO"|"IN_PROGRESS"|"COMPLETED"){const {supabase}=await assertChild(projectId,"project_tasks",id);await supabase.from("project_tasks").update({status}).eq("project_id",projectId).eq("id",id);revalidatePath(`/projects/${projectId}`);}
export async function deleteTask(projectId:string,id:string){const {supabase}=await assertChild(projectId,"project_tasks",id);await supabase.from("project_tasks").delete().eq("project_id",projectId).eq("id",id);revalidatePath(`/projects/${projectId}`);}
