import "server-only";
import {requireUser} from "@/lib/auth";
import {FeedError,safeFeedMessage} from "@/lib/research-feeds/errors";
import {itemFingerprints} from "@/lib/research-feeds/fingerprint";
import {fetchFeed} from "@/lib/research-feeds/network";
import {parseFeed} from "@/lib/research-feeds/parser";
import {claimGlobalFeed,completeGlobalFeed,failGlobalFeed,type GlobalClaim} from "@/lib/research-feeds/trusted-workflow-client";

export async function ingestGlobalResearchFeed(feedId:string,trigger:"MANUAL"|"SCHEDULED") {const {user}=await requireUser();const {data,error}=await claimGlobalFeed({p_actor_id:user.id,p_feed_source_id:feedId,p_trigger_type:trigger});const claim=data?.[0];if(error||!claim)return{error:"Feed not found or unavailable."};return ingestClaimedGlobalFeed(claim);}
export async function ingestClaimedGlobalFeed(run:GlobalClaim){try{const response=await fetchFeed(run.configured_url,{etag:run.etag,lastModified:run.last_modified},{diagnostic:{feedSourceId:run.feed_source_id,fetchRunId:run.run_id}});let type:"UNKNOWN"|"RSS"|"ATOM"="UNKNOWN";let items:Record<string,unknown>[]=[];if(response.status===200){const parsed=parseFeed(response.body,response.finalUrl);type=parsed.type;items=parsed.items.map(i=>{const f=itemFingerprints(i);return{external_id:i.externalId,title:i.title,canonical_url:i.canonicalUrl,summary_text:i.summaryText,content_text:i.contentText,author_name:i.authorName,published_at:i.publishedAt,source_updated_at:i.sourceUpdatedAt,language:i.language,categories:i.categories,url_hash:f.url,content_hash:f.content};});}const {error}=await completeGlobalFeed({p_owner_id:run.owner_id,p_feed_source_id:run.feed_source_id,p_run_id:run.run_id,p_lease_token:run.lease_token,p_request_url_hash:run.request_url_hash,p_status:response.status===304?"NOT_MODIFIED":"SUCCEEDED",p_feed_type:type,p_final_url:response.finalUrl,p_http_status:response.status,p_response_bytes:response.bytes,p_etag:String(response.headers.etag??"")||null,p_last_modified:String(response.headers["last-modified"]??"")||null,p_items:items});if(error)throw new FeedError("INTERNAL_ERROR");return{success:response.status===304?"Feed checked; content was not modified.":`Feed fetched; ${items.length} items processed.`};}catch(error){const code=error instanceof FeedError?error.code:"INTERNAL_ERROR";await failGlobalFeed({p_owner_id:run.owner_id,p_feed_source_id:run.feed_source_id,p_run_id:run.run_id,p_lease_token:run.lease_token,p_request_url_hash:run.request_url_hash,p_error_code:code,p_error_message:safeFeedMessage(code)});return{error:safeFeedMessage(code)};}}
