import "server-only";
import {timingSafeEqual} from "node:crypto";
import {ingestStoredResearchFeed} from "@/lib/research-feeds/orchestrator";
import {claimDueOsintFeeds} from "@/lib/research-feeds/trusted-workflow-client";

export type SchedulerConfig={enabled:boolean;batchSize:number;concurrency:number;budgetMs:number;secret:string};
function integer(value:string|undefined,fallback:number,min:number,max:number){if(value===undefined)return fallback;if(!/^\d+$/.test(value))throw new Error("INVALID_OSINT_SCHEDULER_CONFIGURATION");const result=Number(value);if(result<min||result>max)throw new Error("INVALID_OSINT_SCHEDULER_CONFIGURATION");return result;}
export function schedulerConfig(env:NodeJS.ProcessEnv=process.env):SchedulerConfig {const enabled=env.OSINT_SCHEDULER_ENABLED==="true";if(env.OSINT_SCHEDULER_ENABLED&&!['true','false'].includes(env.OSINT_SCHEDULER_ENABLED))throw new Error("INVALID_OSINT_SCHEDULER_CONFIGURATION");return{enabled,secret:env.CRON_SECRET??"",batchSize:integer(env.OSINT_FETCH_BATCH_SIZE,20,1,20),concurrency:integer(env.OSINT_FETCH_CONCURRENCY,3,1,3),budgetMs:integer(env.OSINT_SCHEDULER_TIME_BUDGET_MS,45000,5000,45000)}}
export function authorizeCron(header:string|null,secret:string){if(!header?.startsWith("Bearer ")||header.includes(","))return false;const supplied=header.slice(7);if(!secret||!supplied)return false;const a=Buffer.from(supplied),b=Buffer.from(secret);return a.length===b.length&&timingSafeEqual(a,b);}
type Due={feed_source_id:string;owner_id:string;project_id:string|null};
export async function runScheduler(config:SchedulerConfig){if(!config.enabled)return{claimed:0,succeeded:0,failed:0,skipped:0,disabled:true};const started=Date.now();const {data,error}=await claimDueOsintFeeds({p_limit:config.batchSize});if(error)throw new Error("SCHEDULER_CLAIM_FAILED");const due=data??[];let cursor=0,succeeded=0,failed=0,skipped=0;async function worker(){while(cursor<due.length){if(Date.now()-started>=config.budgetMs){skipped+=due.length-cursor;cursor=due.length;return}const feed=due[cursor++];if(!feed.project_id){failed++;continue}const result=await ingestStoredResearchFeed(feed.project_id,feed.feed_source_id);if("success" in result)succeeded++;else failed++;}}await Promise.all(Array.from({length:Math.min(config.concurrency,due.length)},worker));return{claimed:due.length,succeeded,failed,skipped,disabled:false};}
