import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { advisoryCanonicalKey, attackCanonicalKey, indicatorCanonicalKey, normalizeCve, reportCanonicalKey, validateCanonicalKey, vulnerabilityCanonicalKey } from "./canonical-key";
import { canonicalSnapshotFingerprint, deterministicFingerprint, sourceObservationKey } from "./fingerprints";
import { recordTechnicalSignalResultSchema, recordTechnicalSignalSchema } from "./schema";
import { signalTypes } from "./types";

const input = { actorId: "10000000-0000-4000-8000-000000000001", signal: { signalType: "VULNERABILITY_CHANGE", canonicalKey: "cve:CVE-2026-1234", title: "Changed", summary: "", lifecycle: "ACTIVE", severity: "HIGH", confidence: 80, facts: {}, publishedAt: null, observedAt: null, effectiveAt: "2026-08-05T00:00:00Z" }, observation: { sourceFamily: "MANUAL_TEST", sourceSystem: "synthetic", sourceRecordKey: "one", sourceRevisionKey: null, sourceUrl: "https://example.test/Case?Q=UP", sourceTitle: null, sourcePublishedAt: null, sourceModifiedAt: null, sourceObservedAt: null, receivedAt: "2026-08-05T00:01:00Z", effectiveAt: "2026-08-05T00:00:00Z", sourceSnapshot: {} }, entityAssertions: [] } as const;
describe("provider-independent Technical Signal helpers", () => {
 it("normalizes CVEs and stable canonical identities", () => { expect(normalizeCve("cve2026-1234")).toBe("CVE-2026-1234"); expect(vulnerabilityCanonicalKey("CVE-2026-1234")).toBe("cve:CVE-2026-1234"); expect(attackCanonicalKey("t1059.001")).toBe("attack:T1059.001"); expect(reportCanonicalKey(" Vendor ", "Case/UP")).toBe("report:vendor:Case/UP"); expect(advisoryCanonicalKey("Vendor", "ADV-1")).toBe("advisory:vendor:ADV-1"); });
 it("validates Indicator subtypes without changing URL path/query case", () => { expect(indicatorCanonicalKey("DOMAIN", "EXAMPLE.COM")).toBe("indicator:DOMAIN:example.com"); expect(indicatorCanonicalKey("URL", "https://Example.com/Case?Q=UP")).toContain("/Case?Q=UP"); expect(() => indicatorCanonicalKey("IP", "not-ip")).toThrow(); });
 it("fingerprints canonical JSON independent of key order", () => { expect(deterministicFingerprint({ b: 2, a: 1 })).toBe(deterministicFingerprint({ a: 1, b: 2 })); expect(sourceObservationKey({ ownerId: input.actorId, signalType: "VULNERABILITY_CHANGE", canonicalKey: "cve:CVE-2026-1234", sourceFamily: "MANUAL_TEST", sourceSystem: "TEST", sourceRecordKey: "1", sourceFingerprint: "abc" })).toBe(sourceObservationKey({ ownerId: input.actorId, signalType: "VULNERABILITY_CHANGE", canonicalKey: "cve:CVE-2026-1234", sourceFamily: "MANUAL_TEST", sourceSystem: "test", sourceRecordKey: "1", sourceFingerprint: "abc" })); });
 it("strictly bounds trusted inputs and rejects credential URLs/reserved bases", () => { expect(recordTechnicalSignalSchema.safeParse(input).success).toBe(true); expect(recordTechnicalSignalSchema.safeParse({ ...input, extra: true }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, signal: { ...input.signal, facts: { x: "x".repeat(66_000) } } }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, observation: { ...input.observation, sourceUrl: "https://u:p@example.test/x" } }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, entityAssertions: Array.from({ length: 101 }, () => ({})) }).success).toBe(false); });

 it("enforces canonical families and source-scoped observation identity", () => { expect(validateCanonicalKey("VULNERABILITY_CHANGE", "cve:CVE-2026-1234")).toBeTruthy(); expect(validateCanonicalKey("TTP_UPDATE", "attack:T1059.001")).toBeTruthy(); expect(() => validateCanonicalKey("VULNERABILITY_CHANGE", "cve:cve-2026-1234")).toThrow(); const base={ownerId:input.actorId,signalType:"VULNERABILITY_CHANGE" as const,canonicalKey:"cve:CVE-2026-1234",sourceFamily:"MANUAL_TEST",sourceSystem:"TEST",sourceRecordKey:"one",sourceFingerprint:"a".repeat(64)}; expect(sourceObservationKey(base)).not.toBe(sourceObservationKey({...base,canonicalKey:"cve:CVE-2026-9999"})); });
 it("uses the fixed canonical fingerprint contract", () => { expect(canonicalSnapshotFingerprint({lifecycle:"ACTIVE",title:"Fixture",summary:"Summary",severity:"HIGH",confidence:80,facts:{b:"two",a:1},publishedAt:"2026-08-05T12:00:00+02:00",observedAt:"2026-08-05T10:30:00Z",supersededBySignalId:null})).toBe("9fd4ffd3ccc6d2254828a8f02e48fe1639ebeb9ba05fb4c7924cecdd7cb7a5f9"); });
 it("rejects effective-time mismatch and malformed RPC results", () => { expect(recordTechnicalSignalSchema.safeParse({...input,observation:{...input.observation,effectiveAt:"2026-08-05T00:00:01Z"}}).success).toBe(false); expect(recordTechnicalSignalResultSchema.safeParse({signal_id:"bad"}).success).toBe(false); });
 it("contains only provider-independent signal types", () => { expect(signalTypes).toContain("TECHNICAL_REPORT"); expect(signalTypes.join(" ")).not.toMatch(/THREATFOX|OTX|NVD|KEV/); });
 it("keeps the trusted client server-only and free of provider/network/AI adapters", () => { const source = readFileSync("src/lib/techint/signals/trusted-signal-client.ts", "utf8"); expect(source).toMatch(/^import "server-only";/); expect(source).not.toMatch(/fetch\(|ThreatFox|OTX|openai|anthropic/i); });
});
