import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { advisoryCanonicalKey, attackCanonicalKey, indicatorCanonicalKey, normalizeCve, reportCanonicalKey, vulnerabilityCanonicalKey } from "./canonical-key";
import { deterministicFingerprint, sourceObservationKey } from "./fingerprints";
import { recordTechnicalSignalSchema } from "./schema";
import { signalTypes } from "./types";

const input = { actorId: "10000000-0000-4000-8000-000000000001", signal: { signalType: "VULNERABILITY_CHANGE", canonicalKey: "cve:CVE-2026-1234", title: "Changed", summary: "", lifecycle: "ACTIVE", severity: "HIGH", confidence: 80, facts: {}, publishedAt: null, observedAt: null, effectiveAt: "2026-08-05T00:00:00Z" }, observation: { sourceFamily: "MANUAL_TEST", sourceSystem: "synthetic", sourceRecordKey: "one", sourceRevisionKey: null, sourceUrl: "https://example.test/Case?Q=UP", sourceTitle: null, sourcePublishedAt: null, sourceModifiedAt: null, sourceObservedAt: null, receivedAt: "2026-08-05T00:01:00Z", effectiveAt: "2026-08-05T00:00:00Z", sourceSnapshot: {} }, entityAssertions: [] } as const;
describe("provider-independent Technical Signal helpers", () => {
 it("normalizes CVEs and stable canonical identities", () => { expect(normalizeCve("cve2026-1234")).toBe("CVE-2026-1234"); expect(vulnerabilityCanonicalKey("CVE-2026-1234")).toBe("cve:CVE-2026-1234"); expect(attackCanonicalKey("t1059.001")).toBe("attack:T1059.001"); expect(reportCanonicalKey(" Vendor ", "Case/UP")).toBe("report:vendor:Case/UP"); expect(advisoryCanonicalKey("Vendor", "ADV-1")).toBe("advisory:vendor:ADV-1"); });
 it("validates Indicator subtypes without changing URL path/query case", () => { expect(indicatorCanonicalKey("DOMAIN", "EXAMPLE.COM")).toBe("indicator:DOMAIN:example.com"); expect(indicatorCanonicalKey("URL", "https://Example.com/Case?Q=UP")).toContain("/Case?Q=UP"); expect(() => indicatorCanonicalKey("IP", "not-ip")).toThrow(); });
 it("fingerprints canonical JSON independent of key order", () => { expect(deterministicFingerprint({ b: 2, a: 1 })).toBe(deterministicFingerprint({ a: 1, b: 2 })); expect(sourceObservationKey({ sourceSystem: "TEST", sourceRecordKey: "1", sourceFingerprint: "abc" })).toBe(sourceObservationKey({ sourceSystem: "test", sourceRecordKey: "1", sourceFingerprint: "abc" })); });
 it("strictly bounds trusted inputs and rejects credential URLs/reserved bases", () => { expect(recordTechnicalSignalSchema.safeParse(input).success).toBe(true); expect(recordTechnicalSignalSchema.safeParse({ ...input, extra: true }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, signal: { ...input.signal, facts: { x: "x".repeat(66_000) } } }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, observation: { ...input.observation, sourceUrl: "https://u:p@example.test/x" } }).success).toBe(false); expect(recordTechnicalSignalSchema.safeParse({ ...input, entityAssertions: Array.from({ length: 101 }, () => ({})) }).success).toBe(false); });
 it("contains only provider-independent signal types", () => { expect(signalTypes).toContain("TECHNICAL_REPORT"); expect(signalTypes.join(" ")).not.toMatch(/THREATFOX|OTX|NVD|KEV/); });
 it("keeps the trusted client server-only and free of provider/network/AI adapters", () => { const source = readFileSync("src/lib/techint/signals/trusted-signal-client.ts", "utf8"); expect(source).toMatch(/^import "server-only";/); expect(source).not.toMatch(/fetch\(|ThreatFox|OTX|openai|anthropic/i); });
});
