import "server-only";
import { cookies } from "next/headers";
import { createAdminClient } from "@/lib/supabase/admin";
import { GUEST_COOKIE } from "./vault";
import { hmac, randomToken } from "./security";
export async function verifyTurnstile(token: string) { if (process.env.NODE_ENV !== "production" && token === "CIP_DEV_TURNSTILE_BYPASS") return true; const secret = process.env.TURNSTILE_SECRET_KEY; if (!secret) return false; const form = new FormData(); form.append("secret", secret); form.append("response", token); const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", { method:"POST", body: form, cache:"no-store" }); const body = await res.json().catch(()=>({ success:false })) as { success?: boolean }; return body.success === true; }
export async function createGuestSession(ip?: string) { const token = randomToken(); const tokenHash = hmac(token); const ipHash = ip ? hmac(ip) : null; const supabase = createAdminClient(); const expires = new Date(Date.now()+8*3600*1000).toISOString(); const { data, error } = await supabase.from("guest_ai_sessions").insert({ token_hash: tokenHash, ip_hash: ipHash, expires_at: expires }).select("id,expires_at").single(); if (error) throw new Error("guest_session_failed"); (await cookies()).set(GUEST_COOKIE, token, { httpOnly:true, sameSite:"strict", secure:process.env.NODE_ENV==="production", path:"/", maxAge:8*3600 }); return { id: data.id as string, expiresAt: data.expires_at as string }; }
export async function requireGuestSession() { const token = (await cookies()).get(GUEST_COOKIE)?.value; if (!token) throw new Error("guest_session_required"); const tokenHash = hmac(token); const supabase = createAdminClient(); const { data, error } = await supabase.from("guest_ai_sessions").select("id,status,expires_at,revoked_at").eq("token_hash", tokenHash).single(); if (error || !data || data.status !== "ACTIVE" || data.revoked_at || new Date(data.expires_at).getTime() <= Date.now()) throw new Error("guest_session_expired"); return { id: data.id as string, tokenHash, supabase }; }
export async function reserveGuestUsage(args:{guestSessionId:string; provider:string; model:string; workflow:string; inputChars:number}) { const supabase = createAdminClient(); const { data, error } = await supabase.rpc("reserve_guest_ai_usage_event", { p_guest_session_id: args.guestSessionId, p_provider: args.provider, p_model: args.model, p_workflow: args.workflow, p_input_chars: args.inputChars, p_max_requests_hour: Number(process.env.GUEST_AI_MAX_REQUESTS_PER_HOUR ?? 5), p_max_requests_day: Number(process.env.GUEST_AI_MAX_REQUESTS_PER_DAY ?? 20), p_max_input_chars: Number(process.env.GUEST_AI_MAX_INPUT_CHARS ?? 12000) }); if (error || !data) throw new Error("guest_limit_reached"); return data as string; }
export async function completeGuestUsage(eventId:string,status:"SUCCEEDED"|"FAILED"|"CANCELLED",outputChars=0){ await createAdminClient().rpc("complete_guest_ai_usage_event",{p_event_id:eventId,p_status:status,p_output_chars:outputChars}); }
