import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { listGlobalTechnicalAgenda } from "@/lib/techint/queries";

type AgendaRow={id:string;priority:string;reason_codes:string[];source_systems:string[];technical_signals:{title:string;signal_type:string;lifecycle:string;first_seen_at:string}|null};
export default async function Page(){
 const {supabase}=await requireUser();const {data,count}=await listGlobalTechnicalAgenda(supabase);const agenda=(data??[]) as unknown as AgendaRow[];
 return <section className="space-y-5"><header className="citem-page-header"><div><p className="citem-eyebrow">CİTEM / TechINT / Global View</p><h1 className="citem-title">Global View</h1><p className="citem-subtitle">Profile-independent, deterministic global technical agenda. Priority is not organizational or business risk.</p></div><div className="flex gap-2"><Link className="citem-button" href="/techint/entities">Entity normalization</Link><Link className="citem-button-ghost" href="/techint/sources">Collection operations</Link></div></header>
 <div className="card"><div className="flex justify-between"><h2 className="citem-section-title">Global technical agenda</h2><span className="text-sm text-stone-500">{count??0} evaluated</span></div><div className="mt-3 space-y-3">{agenda.map(row=><article key={row.id} className="rounded border border-stone-800 p-3"><p className="citem-eyebrow">{row.priority} · {row.technical_signals?.lifecycle}</p><h3 className="font-semibold">{row.technical_signals?.title}</h3><p className="text-xs text-stone-500">{row.technical_signals?.signal_type} · first observed {row.technical_signals&&new Date(row.technical_signals.first_seen_at).toLocaleString()} · {row.source_systems.length} source system(s)</p><p className="mt-2 text-sm">Why: {row.reason_codes.join(" · ")||"Baseline technical context"}</p></article>)}{!agenda.length&&<p className="text-sm text-stone-500">No evaluated signals yet. Collection workflows populate this projection without AI.</p>}</div></div></section>;
}
