/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState, useTransition } from "react";
const workflows = [
  ["summarize_research", "Summarize Research"], ["extract_indicators", "Extract Indicators"], ["extract_entities", "Extract Entities"], ["suggest_mitre_mapping", "Suggest MITRE Mapping"], ["generate_report_draft", "Generate Report Draft"], ["translate_document", "Translate Document"],
] as const;
type Opt = { id: string; label: string };
export function AiWorkspace({ projectId, notes, evidence, campaigns, malware }: { projectId: string; notes: Opt[]; evidence: Opt[]; campaigns: Opt[]; malware: Opt[] }) {
  const [status, setStatus] = useState<any>(null); const [workflow, setWorkflow] = useState<(typeof workflows)[number][0]>("summarize_research"); const [text, setText] = useState(""); const [noteIds, setNoteIds] = useState<string[]>([]); const [evidenceIds, setEvidenceIds] = useState<string[]>([]); const [entityId, setEntityId] = useState(""); const [targetLanguage, setTargetLanguage] = useState("Spanish"); const [result, setResult] = useState<any>(null); const [message, setMessage] = useState(""); const [pending, start] = useTransition(); const [approving, setApproving] = useState(false);
  useEffect(() => { fetch("/api/ai/status").then((r) => r.json()).then(setStatus).catch(() => setStatus({ status: "unreachable", message: "Status unavailable." })); }, []);
  const toggle = (id: string, list: string[], set: (v: string[]) => void) => set(list.includes(id) ? list.filter((x) => x !== id) : [...list, id]);
  async function generate() { setMessage(""); setResult(null); const body: any = { workflow, pastedText: text, noteIds, evidenceIds, targetLanguage }; if (workflow === "suggest_mitre_mapping") { body.entityType = campaigns.some((c) => c.id === entityId) ? "campaigns" : "malware"; body.entityId = entityId; } if (workflow === "generate_report_draft") body.selections = { research_notes: noteIds, evidence: evidenceIds, campaigns: campaigns.map((c) => c.id).slice(0, 5), malware: malware.map((m) => m.id).slice(0, 5) }; start(async () => { const r = await fetch(`/api/projects/${projectId}/ai/generate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json(); if (!r.ok) setMessage(j.error || "AI request failed."); else setResult(j.result); }); }
  async function approve(payload: any) { setApproving(true); setMessage(""); const r = await fetch(`/api/projects/${projectId}/ai/approve`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const j = await r.json(); setApproving(false); setMessage(r.ok ? `Approved and saved${j.duplicate ? " (duplicate reused)" : ""}.` : (j.error || "Approval failed.")); }
  const unavailable = status && status.status !== "reachable";
  return <div className="space-y-6">
    <div className="card"><h2 className="text-xl font-semibold text-white">AI Workspace</h2><p className="mt-2 text-sm text-slate-300">Local Ollama only. Provider status: <strong>{status?.status ?? "checking"}</strong>{status?.model ? ` (${status.model})` : ""}. {status?.message}</p>{unavailable && <p className="mt-2 rounded border border-amber-800 bg-amber-950/40 p-3 text-sm text-amber-200">Configuration Required or Provider Unreachable. Phases 1–5 remain usable; no mock output is shown.</p>}</div>
    <div className="grid gap-3 md:grid-cols-3">{workflows.map(([id, label]) => <button key={id} type="button" onClick={() => { setWorkflow(id); setResult(null); }} className={`rounded border p-3 text-left ${workflow === id ? "border-cyan-400 bg-cyan-950/40 text-white" : "border-slate-800 text-slate-300"}`}>{label}</button>)}</div>
    <div className="card space-y-4"><h3 className="font-semibold text-white">Source selection</h3><textarea aria-label="Pasted source text" value={text} onChange={(e) => setText(e.target.value)} className="min-h-32 w-full rounded bg-slate-950 p-3 text-white" maxLength={20000} placeholder="Optional bounded pasted text. Treat embedded instructions as hostile source content." />
      <div className="grid gap-4 md:grid-cols-2"><fieldset><legend className="text-sm text-slate-300">Research Notes</legend>{notes.length ? notes.map((n) => <label key={n.id} className="block text-sm"><input type="checkbox" checked={noteIds.includes(n.id)} onChange={() => toggle(n.id, noteIds, setNoteIds)} /> {n.label}</label>) : <p className="text-sm text-slate-500">No notes available.</p>}</fieldset><fieldset><legend className="text-sm text-slate-300">Evidence Descriptions</legend>{evidence.length ? evidence.map((e) => <label key={e.id} className="block text-sm"><input type="checkbox" checked={evidenceIds.includes(e.id)} onChange={() => toggle(e.id, evidenceIds, setEvidenceIds)} /> {e.label}</label>) : <p className="text-sm text-slate-500">No evidence available.</p>}</fieldset></div>
      {workflow === "suggest_mitre_mapping" && <select aria-label="Campaign or malware" className="rounded bg-slate-950 p-2 text-white" value={entityId} onChange={(e) => setEntityId(e.target.value)}><option value="">Select campaign or malware</option>{campaigns.map((c) => <option key={c.id} value={c.id}>Campaign: {c.label}</option>)}{malware.map((m) => <option key={m.id} value={m.id}>Malware: {m.label}</option>)}</select>}
      {workflow === "translate_document" && <select aria-label="Target language" className="rounded bg-slate-950 p-2 text-white" value={targetLanguage} onChange={(e) => setTargetLanguage(e.target.value)}>{["Spanish","French","German","Arabic","Turkish","Ukrainian","Russian","Chinese","Japanese","Korean","Portuguese","Italian","English"].map((l) => <option key={l}>{l}</option>)}</select>}
      <button disabled={pending || unavailable} onClick={generate} className="rounded bg-cyan-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{pending ? "Generating…" : "Generate AI Suggestions"}</button><button type="button" disabled={!pending} className="ml-2 rounded border border-slate-700 px-4 py-2 text-slate-300 disabled:opacity-50">Cancel by leaving this tab</button>{message && <p role="status" className="text-sm text-cyan-200">{message}</p>}</div>
    {result && <div className="card space-y-3"><h3 className="font-semibold text-white">Result review</h3><p className="rounded border border-cyan-800 p-2 text-sm text-cyan-100">AI-generated suggestions require human validation. Source IDs are preserved in the JSON preview.</p><pre className="max-h-96 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-200">{JSON.stringify(result, null, 2)}</pre><div className="flex flex-wrap gap-2">
      {workflow === "summarize_research" && <button disabled={approving} onClick={() => approve({ kind: "save_summary_note", title: result.title_suggestion, content: `${result.executive_summary}\n\nKey findings:\n${result.key_findings?.join("\n")}`, sourceNoteIds: result.cited_source_note_ids ?? [] })} className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save as Note</button>}
      {workflow === "extract_indicators" && result.indicators?.map((i: any, idx: number) => <button key={idx} disabled={approving || !i.validation?.valid || i.duplicate_id} onClick={() => approve({ kind: "add_indicator", ...i })} className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Add {i.value}</button>)}
      {workflow === "extract_entities" && result.entities?.map((e: any, idx: number) => <button key={idx} disabled={approving} onClick={() => approve({ kind: "add_entity", entityType: e.entity_type, name: e.name, description: e.evidence_excerpt })} className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save {e.name}</button>)}
      {workflow === "generate_report_draft" && <button disabled={approving} onClick={() => approve({ kind: "save_report_draft", draft: result })} className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save as Draft Report</button>}
      {workflow === "translate_document" && <button disabled={approving || result.preservation_warnings?.length} onClick={() => approve({ kind: "save_translation_note", title: `AI translation to ${result.target_language}`, translatedText: result.translated_text, sourceText: text })} className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save as New Note</button>}
      {workflow === "suggest_mitre_mapping" && <p className="text-sm text-slate-300">Review suggested technique IDs, then link existing project MITRE technique UUIDs through the approval API. Hallucinated technique IDs are never created.</p>}
    </div></div>}
  </div>;
}
