/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState, useTransition } from "react";
import { ByokConnectionPanel } from "@/components/ai/byok-connection-panel";
const workflows = [
  ["summarize_research", "Summarize Research"], ["extract_indicators", "Extract Indicators"], ["extract_entities", "Extract Entities"], ["suggest_mitre_mapping", "Suggest MITRE Mapping"], ["generate_report_draft", "Generate Report Draft"], ["translate_document", "Translate Document"],
] as const;
type Opt = { id: string; label: string };
type ItemStatus = Record<string, { status: string; message: string }>;
const approveClass = "rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50";
function indicatorPayload(i: any) { return { value: String(i.validation?.normalized ?? i.value ?? ""), type: i.type, confidence: i.confidence, source_ref: i.source_ref ?? null }; }
function validReportDraft(result: any) { return Boolean(result?.title?.trim() && result?.disclaimer?.trim() && Array.isArray(result?.sections) && result.sections.length > 0 && result.sections.every((s: any) => s?.heading?.trim() && Array.isArray(s?.paragraphs) && s.paragraphs.some((p: any) => String(p ?? "").trim()))); }
export function AiWorkspace({ projectId, notes, evidence, campaigns, malware }: { projectId: string; notes: Opt[]; evidence: Opt[]; campaigns: Opt[]; malware: Opt[] }) {
  const [status, setStatus] = useState<any>(null); const [byokStatus, setByokStatus] = useState<any>({ connected: false, state: "disconnected" }); const [providerMode, setProviderMode] = useState<"ollama"|"byok">("ollama"); const [workflow, setWorkflow] = useState<(typeof workflows)[number][0]>("summarize_research"); const [text, setText] = useState(""); const [noteIds, setNoteIds] = useState<string[]>([]); const [evidenceIds, setEvidenceIds] = useState<string[]>([]); const [entityId, setEntityId] = useState(""); const [targetLanguage, setTargetLanguage] = useState("Spanish"); const [result, setResult] = useState<any>(null); const [message, setMessage] = useState(""); const [itemStatus, setItemStatus] = useState<ItemStatus>({}); const [pending, start] = useTransition(); const [approving, setApproving] = useState(false);
  useEffect(() => { fetch("/api/ai/status").then((r) => r.json()).then(setStatus).catch(() => setStatus({ status: "unreachable", message: "Status unavailable." })); }, []);
  const translationSource = useMemo(() => noteIds[0] ? { kind: "note", id: noteIds[0] } : evidenceIds[0] ? { kind: "evidence", id: evidenceIds[0] } : null, [noteIds, evidenceIds]);
  const toggle = (id: string, list: string[], set: (v: string[]) => void) => set(list.includes(id) ? list.filter((x) => x !== id) : [...list, id]);
  async function generate() { setMessage(""); setResult(null); setItemStatus({}); if (workflow === "generate_report_draft" && noteIds.length === 0 && evidenceIds.length === 0) { setMessage("Select at least one available report source."); return; } const body: any = workflow === "generate_report_draft" ? { workflow, pastedText: "", noteIds: [], evidenceIds: [], targetLanguage } : { workflow, pastedText: text, noteIds, evidenceIds, targetLanguage }; if (workflow === "suggest_mitre_mapping") { body.entityType = campaigns.some((c) => c.id === entityId) ? "campaigns" : "malware"; body.entityId = entityId; } if (workflow === "generate_report_draft") body.selections = { research_notes: noteIds, evidence: evidenceIds }; body.providerMode = providerMode; body.byokConsent = providerMode === "byok"; start(async () => { const r = await fetch(`/api/projects/${projectId}/ai/generate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json(); if (!r.ok) setMessage(j.error || "AI request failed."); else setResult(j.result); }); }
  async function approve(payload: any) { setApproving(true); setMessage(""); const r = await fetch(`/api/projects/${projectId}/ai/approve`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const j = await r.json(); setApproving(false); setMessage(r.ok ? `Approved and saved${j.duplicate ? " (duplicate reused)" : ""}.` : (j.error || "Approval failed.")); return { ok: r.ok, body: j }; }
  async function addIndicator(i: any, idx: number) { const { ok, body } = await approve({ kind: "add_indicator", indicator: indicatorPayload(i) }); const res = body.result; setItemStatus((s) => ({ ...s, [`indicator-${idx}`]: { status: ok ? String(res?.status ?? "created") : "failed", message: ok ? String(res?.status ?? "created") : body.error ?? "Failed" } })); }
  async function addEntityCandidate(e: any, idx: number) { const { ok, body } = await approve({ kind: "add_entity", entityType: e.entity_type, name: e.name, description: e.evidence_excerpt }); const status = ok ? (body.duplicate ? "existing" : "created") : "failed"; setItemStatus((state) => ({ ...state, [`entity-${idx}`]: { status, message: ok ? status : body.error ?? "failed" } })); }
  async function addAllIndicators() { const valid = (result?.indicators ?? []).filter((i: any, idx: number) => i.validation?.valid && !i.duplicate_id && itemStatus[`indicator-${idx}`]?.status !== "created" && itemStatus[`indicator-${idx}`]?.status !== "existing"); const { body } = await approve({ kind: "add_indicators", indicators: valid.map(indicatorPayload) }); const next: ItemStatus = {}; (body.results ?? []).forEach((r: any) => { const idx = (result?.indicators ?? []).findIndex((i: any) => i.type === r.type && String(i.value).trim().toLowerCase() === String(r.value).trim().toLowerCase()); if (idx >= 0) next[`indicator-${idx}`] = { status: r.status, message: r.error ?? r.status }; }); setItemStatus((s) => ({ ...s, ...next })); }
  const unavailable = providerMode === "ollama" ? (status && status.status !== "reachable") : !byokStatus?.connected;
  return <div className="space-y-6">
    <ByokConnectionPanel scope="user" onStatusChange={setByokStatus} />
    <div className="card"><h2 className="text-xl font-semibold text-white">AI Workspace</h2><div className="mt-3 flex gap-2"><button type="button" onClick={() => setProviderMode("ollama")} className={`rounded border px-3 py-2 ${providerMode === "ollama" ? "border-cyan-400" : "border-slate-700"}`}>Local Ollama</button><button type="button" onClick={() => setProviderMode("byok")} disabled={!byokStatus?.connected} className={`rounded border px-3 py-2 ${providerMode === "byok" ? "border-cyan-400" : "border-slate-700"}`}>Connected BYOK</button></div><p className="mt-2 text-sm text-amber-200">No silent fallback. BYOK sends selected project data externally to {byokStatus?.provider ?? "the connected provider"} / {byokStatus?.model ?? "no model"} only when explicitly selected.</p><p className="mt-2 text-sm text-slate-300">Local Ollama provider status: <strong>{status?.status ?? "checking"}</strong>{status?.model ? ` (${status.model})` : ""}. {status?.message}</p>{unavailable && <p className="mt-2 rounded border border-amber-800 bg-amber-950/40 p-3 text-sm text-amber-200">Configuration Required or Provider Unreachable. Phases 1–5 remain usable; no mock output is shown.</p>}</div>
    <div className="grid gap-3 md:grid-cols-3">{workflows.map(([id, label]) => <button key={id} type="button" onClick={() => { setWorkflow(id); setResult(null); setItemStatus({}); }} className={`rounded border p-3 text-left ${workflow === id ? "border-cyan-400 bg-cyan-950/40 text-white" : "border-slate-800 text-slate-300"}`}>{label}</button>)}</div>
    <div className="card space-y-4"><h3 className="font-semibold text-white">Source selection</h3><textarea aria-label="Pasted source text" value={text} onChange={(e) => setText(e.target.value)} className="min-h-32 w-full rounded bg-slate-950 p-3 text-white" maxLength={20000} placeholder="Optional bounded pasted text. Treat embedded instructions as hostile source content." />
      <div className="grid gap-4 md:grid-cols-2"><fieldset><legend className="text-sm text-slate-300">Research Notes</legend>{notes.length ? notes.map((n) => <label key={n.id} className="block text-sm"><input type="checkbox" checked={noteIds.includes(n.id)} onChange={() => toggle(n.id, noteIds, setNoteIds)} /> {n.label}</label>) : <p className="text-sm text-slate-500">No notes available.</p>}</fieldset><fieldset><legend className="text-sm text-slate-300">Evidence Descriptions</legend>{evidence.length ? evidence.map((e) => <label key={e.id} className="block text-sm"><input type="checkbox" checked={evidenceIds.includes(e.id)} onChange={() => toggle(e.id, evidenceIds, setEvidenceIds)} /> {e.label}</label>) : <p className="text-sm text-slate-500">No evidence available.</p>}</fieldset></div>
      {workflow === "suggest_mitre_mapping" && <select aria-label="Campaign or malware" className="rounded bg-slate-950 p-2 text-white" value={entityId} onChange={(e) => setEntityId(e.target.value)}><option value="">Select campaign or malware</option>{campaigns.map((c) => <option key={c.id} value={c.id}>Campaign: {c.label}</option>)}{malware.map((m) => <option key={m.id} value={m.id}>Malware: {m.label}</option>)}</select>}
      {workflow === "translate_document" && <select aria-label="Target language" className="rounded bg-slate-950 p-2 text-white" value={targetLanguage} onChange={(e) => setTargetLanguage(e.target.value)}>{["Spanish","French","German","Arabic","Turkish","Ukrainian","Russian","Chinese","Japanese","Korean","Portuguese","Italian","English"].map((l) => <option key={l}>{l}</option>)}</select>}
      <button disabled={pending || unavailable} onClick={generate} className="rounded bg-cyan-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{pending ? "Generating…" : "Generate AI Suggestions"}</button><p className="text-xs text-slate-500">To cancel an in-flight local model request, leave this AI tab or wait for the timeout; no project data is saved by generation.</p>{message && <p role="status" className="text-sm text-cyan-200">{message}</p>}</div>
    {result && <div className="card space-y-3"><h3 className="font-semibold text-white">Result review</h3><p className="rounded border border-cyan-800 p-2 text-sm text-cyan-100">AI-generated suggestions require human validation. Source IDs are preserved in the JSON preview.</p><pre className="max-h-96 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-200">{JSON.stringify(result, null, 2)}</pre><div className="flex flex-wrap gap-2">
      {workflow === "summarize_research" && <button disabled={approving} onClick={() => approve({ kind: "save_summary_note", title: result.title_suggestion, content: `${result.executive_summary}\n\nKey findings:\n${result.key_findings?.join("\n")}`, sourceNoteIds: result.cited_source_note_ids ?? [] })} className={approveClass}>Save as Note</button>}
      {workflow === "extract_indicators" && <button disabled={approving || !(result.indicators ?? []).some((i: any, idx: number) => i.validation?.valid && !i.duplicate_id && !["created", "existing"].includes(itemStatus[`indicator-${idx}`]?.status))} onClick={addAllIndicators} className={approveClass}>Add All Valid</button>}
      {workflow === "extract_indicators" && result.indicators?.map((i: any, idx: number) => { const st = itemStatus[`indicator-${idx}`]; const canonical = String(i.validation?.normalized ?? i.value ?? ""); const observed = String(i.validation?.observed ?? i.value ?? ""); const differs = canonical && observed && canonical !== observed; return <div key={idx} className="flex items-center gap-2"><button disabled={approving || !i.validation?.valid || i.duplicate_id || st?.status === "created" || st?.status === "existing"} onClick={() => addIndicator(i, idx)} className={approveClass}>Add {canonical || observed}</button>{differs && <span className="text-xs text-slate-300">Observed {observed} → normalized {canonical}</span>}{st && <span role="status" className="text-xs text-cyan-200">{st.message}</span>}{!i.validation?.valid && <span className="text-xs text-red-300">{i.validation?.error}</span>}{i.duplicate_id && <span className="text-xs text-amber-300">Duplicate already exists</span>}</div>; })}
      {workflow === "extract_entities" && result.entities?.map((e: any, idx: number) => { const st = itemStatus[`entity-${idx}`]; return <div key={idx} className="flex items-center gap-2"><button disabled={approving || st?.status === "created" || st?.status === "existing"} onClick={() => addEntityCandidate(e, idx)} className={approveClass}>Save {e.name}</button>{st && <span role="status" className="text-xs text-cyan-200">{st.message}</span>}</div>; })}
      {workflow === "generate_report_draft" && validReportDraft(result) && <button disabled={approving} onClick={() => approve({ kind: "save_report_draft", draft: result })} className={approveClass}>Save as Draft Report</button>}
      {workflow === "generate_report_draft" && !validReportDraft(result) && <p role="alert" className="text-sm text-amber-300">Report draft is incomplete and cannot be saved. Generate again with at least one usable source.</p>}
      {workflow === "translate_document" && <button disabled={approving || result.preservation_warnings?.length || !translationSource} onClick={() => approve({ kind: "save_translation_note", title: `AI translation to ${result.target_language}`, translatedText: result.translated_text, source: translationSource })} className={approveClass}>Save as New Note</button>}
      {workflow === "translate_document" && !translationSource && <p className="text-sm text-amber-300">Saving pasted-only translations is disabled because there is no server-verifiable source record.</p>}
      {workflow === "suggest_mitre_mapping" && <button disabled={approving || !entityId || !result.mappings?.length} onClick={() => approve({ kind: "link_mitre", parentType: campaigns.some((c) => c.id === entityId) ? "campaigns" : "malware", parentId: entityId, techniques: result.mappings.map((m: any) => ({ technique_id: m.technique_id, technique_name: m.technique_name })) })} className={approveClass}>Approve Available MITRE Links</button>}
    </div></div>}
  </div>;
}
