#!/usr/bin/env bash
set -euo pipefail
command -v psql >/dev/null||{ echo 'PostgreSQL 16+ psql is required';exit 2;}; major=$(psql --version|sed -E 's/.* ([0-9]+).*/\1/');((major>=16))||exit 2
DB="citem_phase2_2c_$$";tmp=$(mktemp);trap 'rm -f "$tmp";dropdb --if-exists "$DB" >/dev/null 2>&1||true' EXIT;createdb "$DB"
psql -v ON_ERROR_STOP=1 -d "$DB" <<'SQL' >/dev/null
do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role service_role;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;create schema extensions;create extension pgcrypto with schema extensions;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt()returns jsonb language sql stable as $$select '{}'::jsonb$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner uuid);create function storage.foldername(name text)returns text[] language sql immutable as $$select string_to_array(name,'/')$$;create function storage.filename(name text)returns text language sql immutable as $$select(string_to_array(name,'/'))[array_length(string_to_array(name,'/'),1)]$$;
SQL
find supabase/migrations -maxdepth 1 -name '*.sql'|sort|while read -r m;do printf "\\i '%s/%s'\n" "$PWD" "$m";done >"$tmp";psql -v ON_ERROR_STOP=1 -d "$DB" -f "$tmp" >/dev/null
psql -v ON_ERROR_STOP=1 -d "$DB" <<'SQL' >/dev/null
insert into auth.users(id)values('10000000-0000-4000-8000-000000000001'),('10000000-0000-4000-8000-000000000002');insert into projects(id,owner_id,name,research_type)values('20000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000001','One','CTI'),('20000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000002','Two','CTI');
do $$declare c ioc_provider_connections;run record;payload jsonb;candidate uuid;begin insert into ioc_provider_connections(owner_id,provider_key,display_name,created_by)values('10000000-0000-4000-8000-000000000001','TEST_SYNTHETIC','Deterministic Test IOC Provider','10000000-0000-4000-8000-000000000001')returning * into c;select * into run from claim_ioc_connection(c.owner_id,c.id,'TEST');payload:=jsonb_build_array(jsonb_build_object('provider_item_id','one','candidate_type','IPV4','normalized_value','192.0.2.44','original_value','192.0.2[.]44','source_fingerprint',repeat('a',64),'confidence_score',50,'tags',jsonb_build_array('TEST'),'metadata','{}'::jsonb));begin perform complete_ioc_ingestion(c.owner_id,c.id,run.run_id,gen_random_uuid(),'SUCCEEDED',run.cursor_version,'next',payload);raise exception 'wrong lease accepted';exception when others then if sqlerrm='wrong lease accepted'then raise;end if;end;perform complete_ioc_ingestion(c.owner_id,c.id,run.run_id,run.lease_token,'SUCCEEDED',run.cursor_version,'next',payload);select id into candidate from ioc_candidates where owner_id=c.owner_id;if candidate is null or(select count(*)from ioc_candidate_sources where candidate_id=candidate)<>1 then raise exception 'candidate persistence failed';end if;perform set_config('request.jwt.claim.sub',c.owner_id::text,true);perform triage_ioc_candidate(candidate,'REVIEW');select * into run from claim_ioc_connection(c.owner_id,c.id,'TEST');perform complete_ioc_ingestion(c.owner_id,c.id,run.run_id,run.lease_token,'SUCCEEDED',run.cursor_version,'next2',payload);if(select status from ioc_candidates where id=candidate)<>'REVIEWED'or(select observation_count from ioc_candidate_sources where candidate_id=candidate)<>2 then raise exception 'triage/dedup failed';end if;if not(accept_ioc_candidate(candidate,'20000000-0000-4000-8000-000000000001','accept',null)->>'ok')::boolean then raise exception 'accept failed';end if;if(select status from indicators where project_id='20000000-0000-4000-8000-000000000001')<>'UNVERIFIED'or not exists(select 1 from indicator_observations where origin_kind='IMPORT')then raise exception 'indicator acceptance failed';end if;perform accept_ioc_candidate(candidate,'20000000-0000-4000-8000-000000000001','again',null);if(select count(*)from ioc_candidate_acceptances where candidate_id=candidate)<>1 then raise exception 'acceptance not idempotent';end if;end$$;
do $$begin if not exists(select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='indicator_type'and e.enumlabel='CIDR')then raise exception 'CIDR missing';end if;if has_function_privilege('authenticated','public.complete_ioc_ingestion(uuid,uuid,uuid,uuid,public.ioc_ingestion_run_status,bigint,text,jsonb)','EXECUTE')then raise exception 'completion ACL';end if;if exists(select 1 from pg_class where relname like'ioc_%'and relkind='r'and not relrowsecurity)then raise exception 'RLS missing';end if;end$$;
SQL
printf 'PostgreSQL %s; migrations 001-027; CIDR, IOC schema, RLS/ACL, exact lease, deduplication, triage persistence and Indicator acceptance passed.\n' "$(psql -Atqc 'show server_version' -d "$DB")"
