#!/usr/bin/env bash
set -euo pipefail
command -v psql >/dev/null || { echo 'PostgreSQL 16+ psql is required'; exit 2; }
major=$(psql --version | sed -E 's/.* ([0-9]+).*/\1/'); ((major>=16)) || { echo 'PostgreSQL 16+ is required'; exit 2; }
DB_NAME="citem_phase2_2a_${$}"; sql_file=$(mktemp); cleanup(){ rm -f "$sql_file"; dropdb --if-exists "$DB_NAME" >/dev/null 2>&1||true;};trap cleanup EXIT
createdb "$DB_NAME"
psql -v ON_ERROR_STOP=1 -d "$DB_NAME" <<'SQL'
do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;create extension pgcrypto;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb not null default '{}');create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt()returns jsonb language sql stable as $$select '{}'::jsonb$$;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,owner uuid);create function storage.foldername(name text)returns text[] language sql immutable as $$select string_to_array(name,'/')$$;create function storage.filename(name text)returns text language sql immutable as $$select(string_to_array(name,'/'))[array_length(string_to_array(name,'/'),1)]$$;
SQL
{ echo BEGIN;for migration in supabase/migrations/*.sql;do printf "\\i '%s/%s'\n" "$PWD" "$migration";done;cat <<'SQL'
do $$declare u1 uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();p1 uuid:=gen_random_uuid();p2 uuid:=gen_random_uuid();f1 uuid;r record;i uuid;begin
 if(select count(*)from pg_class where oid in('public.research_feed_sources'::regclass,'public.research_feed_fetch_runs'::regclass,'public.research_items'::regclass,'public.research_item_fingerprints'::regclass,'public.research_feed_item_observations'::regclass)and relrowsecurity)<>5 then raise exception 'RLS missing';end if;if(select count(*)from pg_policies where tablename like 'research_%')<>7 then raise exception 'policy count';end if;
 insert into auth.users values(u1,'{}'),(u2,'{}');perform set_config('request.jwt.claim.sub',u1::text,true);insert into projects(id,owner_id,name,research_type)values(p1,u1,'One','CTI'),(p2,u2,'Two','CTI');insert into research_feed_sources(project_id,name,configured_url,configured_url_hash,created_by)values(p1,'Feed','https://example.com/feed',repeat('a',64),u1)returning id into f1;
 begin insert into research_feed_sources(project_id,name,configured_url,configured_url_hash,created_by)values(p1,'Duplicate','https://example.com/feed',repeat('a',64),u1);raise exception 'duplicate accepted';exception when unique_violation then null;end;
 r:=claim_research_feed_fetch(p1,f1);begin perform claim_research_feed_fetch(p1,f1);raise exception 'concurrent claim accepted';exception when raise_exception then null;end;
 perform complete_research_feed_fetch(p1,f1,r.id,'SUCCEEDED','RSS','https://example.com/feed',200,100,null,null,jsonb_build_array(jsonb_build_object('title','One','summary_text','Body','categories','[]'::jsonb,'url_hash',repeat('b',64),'content_hash',repeat('c',64))));if(select count(*)from research_items where project_id=p1)<>1 then raise exception 'finalization failed';end if;
 update research_feed_sources set next_eligible_fetch_at=null where id=f1;r:=claim_research_feed_fetch(p1,f1);perform complete_research_feed_fetch(p1,f1,r.id,'SUCCEEDED','RSS','https://example.com/feed',200,100,null,null,jsonb_build_array(jsonb_build_object('title','One','summary_text','Body','categories','[]'::jsonb,'url_hash',repeat('b',64),'content_hash',repeat('c',64))));if(select count(*)from research_items where project_id=p1)<>1 then raise exception 'URL reuse failed';end if;
 begin insert into research_items(project_id,title,created_by)values(p2,'Foreign',u2)returning id into i;insert into research_feed_item_observations(project_id,feed_source_id,research_item_id,fetch_run_id)values(p1,f1,i,r.id);raise exception 'cross Investigation accepted';exception when foreign_key_violation then null;end;
 update research_feed_sources set enabled=false,next_eligible_fetch_at=null where id=f1;begin perform claim_research_feed_fetch(p1,f1);raise exception 'paused accepted';exception when raise_exception then null;end;update research_feed_sources set enabled=true,archived_at=now()where id=f1;begin perform claim_research_feed_fetch(p1,f1);raise exception 'archived accepted';exception when raise_exception then null;end;
end$$;rollback;
SQL
} >"$sql_file";psql -v ON_ERROR_STOP=1 -d "$DB_NAME" -f "$sql_file" >/dev/null
echo "Phase 2.2A PostgreSQL $major migration assertions passed (not live Supabase validation)."
