"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireOwnedProject } from "@/lib/projects/ownership";
import { clusterSchema,memberSchema,objectFromForm,supportSchema } from "@/lib/infrastructure/schema";
const uuid=z.string().uuid();
async function context(projectId:string,clusterId?:string){const ctx=await requireOwnedProject(projectId);if(!clusterId)return ctx;if(!uuid.safeParse(clusterId).success)throw new Error("not_found");const {data}=await ctx.supabase.from("infrastructure_clusters").select("id").eq("project_id",ctx.projectId).eq("id",clusterId).single();if(!data)throw new Error("not_found");return ctx;}
const refresh=(p:string,c?:string)=>{revalidatePath(`/projects/${p}`);if(c)revalidatePath(`/projects/${p}/infrastructure/${c}`);};
export async function createCluster(projectId:string,fd:FormData){const ctx=await context(projectId);const parsed=clusterSchema.safeParse(objectFromForm(fd));if(!parsed.success)redirect(`/projects/${projectId}?tab=infrastructure&error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid cluster")}`);const archived=parsed.data.status==="ARCHIVED";const {data,error}=await ctx.supabase.from("infrastructure_clusters").insert({...parsed.data,project_id:ctx.projectId,created_by:ctx.user.id,archived_at:archived?new Date().toISOString():null}).select("id").single();if(error||!data)redirect(`/projects/${projectId}?tab=infrastructure&error=Cluster%20could%20not%20be%20created`);redirect(`/projects/${projectId}/infrastructure/${data.id}`);}
export async function updateCluster(projectId:string,clusterId:string,fd:FormData){const ctx=await context(projectId,clusterId);const parsed=clusterSchema.safeParse(objectFromForm(fd));if(!parsed.success)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid cluster")}`);const archived=parsed.data.status==="ARCHIVED";await ctx.supabase.from("infrastructure_clusters").update({...parsed.data,archived_at:archived?new Date().toISOString():null}).eq("project_id",ctx.projectId).eq("id",clusterId);refresh(projectId,clusterId);redirect(`/projects/${projectId}/infrastructure/${clusterId}`);}
export async function setClusterArchived(projectId:string,clusterId:string,archived:boolean){const ctx=await context(projectId,clusterId);const {error}=await ctx.supabase.from("infrastructure_clusters").update({status:archived?"ARCHIVED":"DRAFT",archived_at:archived?new Date().toISOString():null}).eq("project_id",ctx.projectId).eq("id",clusterId);if(error)throw new Error("Cluster archive state could not be changed.");refresh(projectId,clusterId);}
export async function saveMember(projectId:string,clusterId:string,memberId:string|null,fd:FormData){const ctx=await context(projectId,clusterId);const parsed=memberSchema.safeParse(objectFromForm(fd));if(!parsed.success)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=${encodeURIComponent(parsed.error.issues[0]?.message??"Invalid membership")}`);const {data:indicator}=await ctx.supabase.from("indicators").select("id").eq("project_id",ctx.projectId).eq("id",parsed.data.indicator_id).single();if(!indicator)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Indicator%20not%20available`);const query=memberId?ctx.supabase.from("infrastructure_cluster_members").update(parsed.data).eq("project_id",ctx.projectId).eq("cluster_id",clusterId).eq("id",memberId):ctx.supabase.from("infrastructure_cluster_members").insert({...parsed.data,project_id:ctx.projectId,cluster_id:clusterId,created_by:ctx.user.id});const {error}=await query;if(error)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Membership%20could%20not%20be%20saved`);refresh(projectId,clusterId);}
export async function attachSupport(projectId:string,clusterId:string,fd:FormData){const ctx=await context(projectId,clusterId);const parsed=supportSchema.safeParse(objectFromForm(fd));if(!parsed.success)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Invalid%20supporting%20material`);if(parsed.data.cluster_member_id){const {data}=await ctx.supabase.from("infrastructure_cluster_members").select("id").eq("project_id",ctx.projectId).eq("cluster_id",clusterId).eq("id",parsed.data.cluster_member_id).single();if(!data)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Membership%20not%20found`);}const table=parsed.data.kind==="source"?"sources":parsed.data.kind==="evidence"?"evidence":"enrichment_results";const {data:target}=await ctx.supabase.from(table).select("id").eq("project_id",ctx.projectId).eq("id",parsed.data.target_id).single();if(!target)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Supporting%20record%20not%20available`);const ids={source_id:null as string|null,evidence_id:null as string|null,enrichment_result_id:null as string|null};ids[parsed.data.kind==="source"?"source_id":parsed.data.kind==="evidence"?"evidence_id":"enrichment_result_id"]=parsed.data.target_id;const {error}=await ctx.supabase.from("infrastructure_cluster_support").insert({...ids,project_id:ctx.projectId,cluster_id:clusterId,cluster_member_id:parsed.data.cluster_member_id,note:parsed.data.note,created_by:ctx.user.id});if(error)redirect(`/projects/${projectId}/infrastructure/${clusterId}?error=Supporting%20material%20could%20not%20be%20attached`);refresh(projectId,clusterId);}
export async function unlinkSupport(projectId:string,clusterId:string,supportId:string){const ctx=await context(projectId,clusterId);if(!uuid.safeParse(supportId).success)return;await ctx.supabase.from("infrastructure_cluster_support").delete().eq("project_id",ctx.projectId).eq("cluster_id",clusterId).eq("id",supportId);refresh(projectId,clusterId);}
