"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth";
import { clusterMembershipSchema, entityLinkSchema, membershipSchema, reconstructionSchema, supportLinkSchema } from "@/lib/reconstruction/schema";
import { requiredUuidSchema } from "@/lib/workspace/schema";
type State={error?:string;success?:string};
const values=(fd:FormData)=>Object.fromEntries(fd.entries());
const message=(p:{error?:{issues:{message:string}[]}})=>p.error?.issues[0]?.message??"Invalid input.";
async function context(projectId:string){const id=requiredUuidSchema.safeParse(projectId);if(!id.success)throw new Error("Not found");const c=await requireUser();const {data}=await c.supabase.from("projects").select("id,owner_id").eq("id",id.data).single();if(!data||data.owner_id!==c.user.id)throw new Error("Not found");return{...c,projectId:id.data};}
async function owned(c:Awaited<ReturnType<typeof context>>,table:string,id:string){const parsed=requiredUuidSchema.safeParse(id);if(!parsed.success)return false;const {data}=await c.supabase.from(table).select("id").eq("project_id",c.projectId).eq("id",parsed.data).maybeSingle();return !!data;}
const refresh=(p:string,e?:string)=>{revalidatePath(`/projects/${p}`);if(e)revalidatePath(`/projects/${p}/timeline/${e}`);};
export async function saveReconstruction(projectId:string,campaignId:string,_:State,fd:FormData):Promise<State>{const c=await context(projectId);if(!await owned(c,"campaigns",campaignId))return{error:"Campaign not found."};const p=reconstructionSchema.safeParse(values(fd));if(!p.success)return{error:message(p)};const {error}=await c.supabase.from("campaign_reconstructions").upsert({...p.data,project_id:c.projectId,campaign_id:campaignId,created_by:c.user.id},{onConflict:"campaign_id"});if(error)return{error:"Unable to save reconstruction."};refresh(c.projectId);return{success:"Reconstruction saved."};}
export async function saveEventMembership(projectId:string,eventId:string,_:State,fd:FormData):Promise<State>{const c=await context(projectId);if(!await owned(c,"timeline_events",eventId))return{error:"Timeline event not found."};const p=membershipSchema.safeParse(values(fd));if(!p.success)return{error:message(p)};if(!await owned(c,"campaigns",p.data.campaign_id))return{error:"Campaign not found."};const {error}=await c.supabase.from("campaign_timeline_events").upsert({...p.data,sequence_order:p.data.sequence_order??null,project_id:c.projectId,timeline_event_id:eventId,created_by:c.user.id},{onConflict:"campaign_id,timeline_event_id"});if(error)return{error:"Unable to save Campaign membership."};refresh(c.projectId,eventId);return{success:"Campaign membership saved."};}
export async function saveClusterMembership(projectId:string,campaignId:string,_:State,fd:FormData):Promise<State>{const c=await context(projectId);const p=clusterMembershipSchema.safeParse(values(fd));if(!p.success)return{error:message(p)};if(!await owned(c,"campaigns",campaignId)||!await owned(c,"infrastructure_clusters",p.data.infrastructure_cluster_id))return{error:"Campaign or Infrastructure Cluster not found."};const {error}=await c.supabase.from("campaign_infrastructure_clusters").upsert({...p.data,project_id:c.projectId,campaign_id:campaignId,created_by:c.user.id},{onConflict:"campaign_id,infrastructure_cluster_id"});if(error)return{error:"Unable to save infrastructure relationship."};refresh(c.projectId);return{success:"Infrastructure relationship saved."};}
export async function linkEventEntity(projectId:string,eventId:string,_:State,fd:FormData):Promise<State>{const c=await context(projectId);const p=entityLinkSchema.safeParse(values(fd));if(!p.success)return{error:message(p)};const tables={indicator:"indicators",infrastructure_cluster:"infrastructure_clusters",malware:"malware",cve:"cves",mitre_technique:"mitre_techniques"} as const;if(!await owned(c,"timeline_events",eventId)||!await owned(c,tables[p.data.entity_type],p.data.entity_id))return{error:"Timeline event or entity not found."};const {error}=await c.supabase.from("timeline_event_entities").insert({project_id:c.projectId,timeline_event_id:eventId,[`${p.data.entity_type}_id`]:p.data.entity_id,role:p.data.role,analyst_note:p.data.analyst_note,created_by:c.user.id});if(error)return{error:"Unable to link technical entity."};refresh(c.projectId,eventId);return{success:"Technical entity linked."};}
export async function linkEventSupport(projectId:string,eventId:string,_:State,fd:FormData):Promise<State>{const c=await context(projectId);const p=supportLinkSchema.safeParse(values(fd));if(!p.success)return{error:message(p)};const tables={source:"sources",evidence:"evidence",enrichment_result:"enrichment_results"} as const;if(!await owned(c,"timeline_events",eventId)||!await owned(c,tables[p.data.support_type],p.data.support_id))return{error:"Timeline event or supporting record not found."};const {error}=await c.supabase.from("timeline_event_support").insert({project_id:c.projectId,timeline_event_id:eventId,[`${p.data.support_type}_id`]:p.data.support_id,analyst_note:p.data.analyst_note,created_by:c.user.id});if(error)return{error:"Unable to link supporting material."};refresh(c.projectId,eventId);return{success:"Supporting material linked."};}
export async function unlinkEventRecord(projectId:string,eventId:string,table:"timeline_event_entities"|"timeline_event_support",id:string){const c=await context(projectId);if(!await owned(c,"timeline_events",eventId))return;const parsed=requiredUuidSchema.safeParse(id);if(!parsed.success)return;const {error}=await c.supabase.from(table).delete().eq("project_id",c.projectId).eq("timeline_event_id",eventId).eq("id",parsed.data);if(error)throw new Error("Unable to unlink record.");refresh(c.projectId,eventId);}
