"use server";
import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { requireOwnedProject } from "@/lib/projects/ownership";
import { ingestStoredResearchFeed } from "@/lib/research-feeds/orchestrator";
import { feedFormSchema,idsSchema } from "@/lib/research-feeds/schema";
import { normalizeFeedUrl } from "@/lib/research-feeds/url";
export type FeedActionState={error?:string;success?:string}; const refresh=(id:string)=>revalidatePath(`/projects/${id}`);
export async function createResearchFeed(projectId:string,_s:FeedActionState,fd:FormData):Promise<FeedActionState>{try{const ctx=await requireOwnedProject(projectId);const parsed=feedFormSchema.safeParse({name:fd.get("name"),description:fd.get("description")??"",configured_url:fd.get("configured_url"),enabled:fd.get("enabled")==="on"});if(!parsed.success)return{error:parsed.error.issues[0]?.message};const {count}=await ctx.supabase.from("research_feed_sources").select("id",{count:"exact",head:true}).eq("project_id",projectId);if((count??0)>=100)return{error:"This Investigation has reached the 100-feed limit."};const normalized=normalizeFeedUrl(parsed.data.configured_url).toString();const {error}=await ctx.supabase.from("research_feed_sources").insert({...parsed.data,configured_url:normalized,configured_url_hash:createHash("sha256").update(normalized).digest("hex"),project_id:projectId,created_by:ctx.user.id});if(error)return{error:"Feed could not be created; the URL may already be configured."};refresh(projectId);return{success:"Feed created. It will not fetch until Fetch now is selected."};}catch{return{error:"Investigation not found."};}}
export async function updateResearchFeed(projectId:string,feedId:string,_s:FeedActionState,fd:FormData):Promise<FeedActionState>{try{if(!idsSchema.safeParse({projectId,feedId}).success)return{error:"Feed not found."};const ctx=await requireOwnedProject(projectId);const parsed=feedFormSchema.safeParse({name:fd.get("name"),description:fd.get("description")??"",configured_url:fd.get("configured_url"),enabled:fd.get("enabled")==="on"});if(!parsed.success)return{error:parsed.error.issues[0]?.message};const normalized=normalizeFeedUrl(parsed.data.configured_url).toString();const {data:old}=await ctx.supabase.from("research_feed_sources").select("configured_url").eq("project_id",projectId).eq("id",feedId).single();if(!old)return{error:"Feed not found."};const reset=old.configured_url!==normalized?{etag:null,last_modified:null,last_final_url:null,health_status:"NEVER_FETCHED",detected_feed_type:"UNKNOWN",last_error_code:null,last_error_message:null}:{};const {error}=await ctx.supabase.from("research_feed_sources").update({...parsed.data,configured_url:normalized,configured_url_hash:createHash("sha256").update(normalized).digest("hex"),...reset}).eq("project_id",projectId).eq("id",feedId);if(error)return{error:"Feed could not be updated."};refresh(projectId);return{success:"Feed updated."};}catch{return{error:"Investigation not found."};}}
export async function setResearchFeedEnabled(projectId:string,feedId:string,enabled:boolean){try{const ctx=await requireOwnedProject(projectId);const {data,error}=await ctx.supabase.from("research_feed_sources").update({enabled}).eq("project_id",projectId).eq("id",feedId).is("archived_at",null).select("id").single();if(error||!data)return{error:"Feed state could not be changed."};refresh(projectId);return{success:enabled?"Feed enabled.":"Feed paused."};}catch{return{error:"Feed not found."};}}
export async function archiveResearchFeed(projectId:string,feedId:string){try{const ctx=await requireOwnedProject(projectId);const {error}=await ctx.supabase.from("research_feed_sources").update({archived_at:new Date().toISOString(),enabled:false}).eq("project_id",projectId).eq("id",feedId);if(error)return{error:"Feed could not be archived."};refresh(projectId);return{success:"Feed archived; collected items and history were preserved."};}catch{return{error:"Feed not found."};}}
export async function fetchResearchFeedNow(projectId:string,feedId:string){if(!idsSchema.safeParse({projectId,feedId}).success)return{error:"Feed not found."};const result=await ingestStoredResearchFeed(projectId,feedId);refresh(projectId);return result;}
