do $$ begin create type public.intel_profile_kind as enum ('STANDALONE','INVESTIGATION'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_status as enum ('ACTIVE','PAUSED','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_priority as enum ('LOW','MEDIUM','HIGH','CRITICAL'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_item_origin as enum ('EXPLICIT','DERIVED','SUGGESTED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_item_state as enum ('PENDING','ACTIVE','EXCLUDED','REMOVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_item_kind as enum ('THREAT_ACTOR','MALWARE','CAMPAIGN','CVE','INDICATOR','INFRASTRUCTURE','ATTACK_TECHNIQUE','VENDOR','PRODUCT','SECTOR','COUNTRY','REGION','TAG','KEYWORD'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_semantic_role as enum ('TARGET','AFFECTED_REGION','INFRASTRUCTURE_LOCATION','ACTOR_ASSOCIATION','STRATEGIC_CONTEXT','GENERAL_CONTEXT'); exception when duplicate_object then null; end $$;
do $$ begin create type public.intel_profile_audit_action as enum ('PROFILE_CREATED','PROFILE_UPDATED','PROFILE_PAUSED','PROFILE_RESUMED','PROFILE_ARCHIVED','PROFILE_RESTORED','ITEM_ADDED','ITEM_ACCEPTED','ITEM_EXCLUDED','ITEM_REMOVED','ITEM_REACTIVATED','INVESTIGATION_REFRESHED'); exception when duplicate_object then null; end $$;

alter table public.projects add constraint projects_owner_id_id_unique unique(owner_id,id);

create table public.intel_profiles(
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, kind public.intel_profile_kind not null,
  project_id uuid null, name text not null check(char_length(trim(name)) between 2 and 160), description text not null default '' check(char_length(description)<=2000),
  intelligence_question text not null default '' check(char_length(intelligence_question)<=2000), priority public.intel_profile_priority not null default 'MEDIUM', status public.intel_profile_status not null default 'ACTIVE',
  time_horizon_days integer not null default 90 check(time_horizon_days between 1 and 730), minimum_confidence integer null check(minimum_confidence between 0 and 100), relationship_depth integer not null default 1 check(relationship_depth between 0 and 3),
  created_by uuid not null references auth.users(id), updated_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz,
  unique(owner_id,id), foreign key(owner_id,project_id) references public.projects(owner_id,id) on delete cascade,
  check((kind='STANDALONE' and project_id is null) or (kind='INVESTIGATION' and project_id is not null)), check((status='ARCHIVED')=(archived_at is not null))
);
create unique index intel_profiles_one_open_investigation_profile on public.intel_profiles(owner_id,project_id) where kind='INVESTIGATION' and archived_at is null;
create index intel_profiles_owner_kind_idx on public.intel_profiles(owner_id,kind,status,updated_at desc);
drop trigger if exists intel_profiles_set_updated_at on public.intel_profiles; create trigger intel_profiles_set_updated_at before update on public.intel_profiles for each row execute function public.set_updated_at();

create table public.intel_profile_items(
  id uuid primary key default gen_random_uuid(), profile_id uuid not null, owner_id uuid not null references auth.users(id) on delete cascade,
  kind public.intel_profile_item_kind not null, display_value text not null check(char_length(trim(display_value)) between 1 and 300), normalized_value text not null check(char_length(trim(normalized_value)) between 1 and 300), profile_local_key text not null check(char_length(profile_local_key)<=700),
  origin public.intel_profile_item_origin not null, state public.intel_profile_item_state not null, semantic_role public.intel_profile_semantic_role null, source_project_id uuid null, source_entity_type text null check(char_length(source_entity_type)<=80), source_entity_id uuid null, indicator_type public.indicator_type null,
  created_by uuid not null references auth.users(id), accepted_by uuid null references auth.users(id), updated_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), removed_at timestamptz,
  unique(owner_id,id), unique(owner_id,profile_id,profile_local_key), foreign key(owner_id,profile_id) references public.intel_profiles(owner_id,id) on delete cascade, foreign key(owner_id,source_project_id) references public.projects(owner_id,id) on delete cascade,
  check(origin <> 'SUGGESTED' or state='PENDING' or accepted_by is not null), check((kind='INDICATOR')=(indicator_type is not null)), check(kind not in ('COUNTRY','REGION') or state <> 'ACTIVE' or semantic_role is not null), check((state in ('REMOVED','EXCLUDED'))=(removed_at is not null))
);
create index intel_profile_items_profile_state_idx on public.intel_profile_items(owner_id,profile_id,state,updated_at desc);
drop trigger if exists intel_profile_items_set_updated_at on public.intel_profile_items; create trigger intel_profile_items_set_updated_at before update on public.intel_profile_items for each row execute function public.set_updated_at();

create table public.intel_profile_audit_events(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, profile_id uuid not null, item_id uuid null, actor_id uuid not null references auth.users(id), action public.intel_profile_audit_action not null, details jsonb not null default '{}' check(pg_column_size(details)<=4096), created_at timestamptz not null default now(),
 foreign key(owner_id,profile_id) references public.intel_profiles(owner_id,id) on delete cascade, foreign key(owner_id,item_id) references public.intel_profile_items(owner_id,id) on delete set null (item_id)
);
create index intel_profile_audit_events_profile_idx on public.intel_profile_audit_events(owner_id,profile_id,created_at desc);

alter table public.intel_profiles enable row level security; alter table public.intel_profile_items enable row level security; alter table public.intel_profile_audit_events enable row level security;
revoke all on public.intel_profiles, public.intel_profile_items, public.intel_profile_audit_events from anon, authenticated;
grant select on public.intel_profiles, public.intel_profile_items, public.intel_profile_audit_events to authenticated;
create policy intel_profiles_select_own on public.intel_profiles for select to authenticated using(auth.uid()=owner_id);
create policy intel_profile_items_select_own on public.intel_profile_items for select to authenticated using(auth.uid()=owner_id);
create policy intel_profile_audit_events_select_own on public.intel_profile_audit_events for select to authenticated using(auth.uid()=owner_id);

create function public.intel_profile_validate_indicator(p_value text,p_type public.indicator_type) returns text language plpgsql immutable as $$declare v text:=trim(p_value);host text;prefix int;begin
 if p_type='IP' then begin return host(inet(v));exception when others then raise exception 'INVALID_INDICATOR' using errcode='22023';end;end if;
 if p_type='CIDR' then begin prefix:=masklen(cidr(v));if prefix<0 then raise exception 'INVALID_INDICATOR' using errcode='22023';end if;return cidr(v)::text;exception when others then raise exception 'INVALID_INDICATOR' using errcode='22023';end;end if;
 if p_type='DOMAIN' then if v~*'^(?!-)([a-z0-9-]{1,63}\.)+[a-z]{2,63}$' then return lower(v);end if;raise exception 'INVALID_INDICATOR' using errcode='22023';end if;
 if p_type='HASH' then if v~*'^(?:[a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64})$' then return lower(v);end if;raise exception 'INVALID_INDICATOR' using errcode='22023';end if;
 if p_type='EMAIL' then if v~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then return lower(v);end if;raise exception 'INVALID_INDICATOR' using errcode='22023';end if;
 if p_type='URL' then if v!~*'^https?://[^[:space:]]+$' then raise exception 'INVALID_INDICATOR' using errcode='22023';end if;host:=substring(v from '^https?://([^/?#]+)');if host is null or host='' or host like '%@%' or host=':' or host!~*'^[^:]+(:[0-9]{1,5})?$' or (position(':' in host)>0 and split_part(host,':',2)::int not between 1 and 65535) then raise exception 'INVALID_INDICATOR' using errcode='22023';end if;return lower(substring(v from '^(https?://[^/?#]+)'))||substring(v from '^https?://[^/?#]+(.*)$');end if;
 raise exception 'INVALID_INDICATOR' using errcode='22023';
end$$;
create function public.intel_profile_detect_indicator_type(p_value text) returns public.indicator_type language plpgsql immutable as $$declare v text:=trim(p_value);begin
 if v~*'^(?:[a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64})$' then return 'HASH';end if;if v~*'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then return 'EMAIL';end if;if v~*'^https?://[^[:space:]]+$' then return 'URL';end if;if position('/' in v)>0 then perform public.intel_profile_validate_indicator(v,'CIDR');return 'CIDR';end if;begin perform public.intel_profile_validate_indicator(v,'IP');return 'IP';exception when others then null;end;if v~*'^(?!-)([a-z0-9-]{1,63}\.)+[a-z]{2,63}$' then return 'DOMAIN';end if;raise exception 'INVALID_INDICATOR' using errcode='22023';
end$$;
create function public.intel_profile_normalize_item_value(p_kind public.intel_profile_item_kind,p_value text,p_indicator_type public.indicator_type default null) returns text language plpgsql immutable as $$declare t public.indicator_type;begin
 if p_kind='CVE' then return regexp_replace(upper(trim(p_value)),'^CVE([0-9])','CVE-\1');end if;if p_kind='INDICATOR' then t:=coalesce(p_indicator_type,public.intel_profile_detect_indicator_type(p_value));return public.intel_profile_validate_indicator(p_value,t);end if;return regexp_replace(lower(trim(p_value)),'\s+',' ','g');
end$$;
create function public.intel_profile_local_key(p_kind public.intel_profile_item_kind,p_normalized text,p_role public.intel_profile_semantic_role) returns text language sql immutable as $$select lower(p_kind::text)||':'||lower(coalesce(p_role::text,''))||':'||p_normalized$$;
create function public.intel_profile_write_audit(p_owner uuid,p_profile uuid,p_item uuid,p_actor uuid,p_action public.intel_profile_audit_action,p_details jsonb default '{}') returns void language plpgsql security definer set search_path='' as $$begin
 if p_actor is null or p_owner is null or p_profile is null or p_details is null or pg_column_size(p_details)>4096 then raise exception 'INTEL_PROFILE_AUDIT_INVALID' using errcode='22023';end if;
 insert into public.intel_profile_audit_events(owner_id,profile_id,item_id,actor_id,action,details)values(p_owner,p_profile,p_item,p_actor,p_action,p_details);
end$$;
create function public.intel_profile_seed_from_project(p_actor uuid,p_profile uuid,p_project uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare p public.intel_profiles; r record; added int:=0; already int:=0; excl int:=0; rem int:=0; skipped int:=0; norm text; k text; item public.intel_profile_items; begin
 select * into p from public.intel_profiles where id=p_profile and owner_id=p_actor and kind='INVESTIGATION' and project_id=p_project and status<>'ARCHIVED' for update;if p.id is null or not exists(select 1 from public.projects where id=p_project and owner_id=p_actor)then raise exception 'not_found' using errcode='P0002';end if;
 for r in select 'THREAT_ACTOR'::public.intel_profile_item_kind kind,'threat_actors'::text src,id,name::text val,null::public.indicator_type indicator_type from public.threat_actors where project_id=p_project union all select 'CAMPAIGN','campaigns',id,name,null::public.indicator_type from public.campaigns where project_id=p_project union all select 'MALWARE','malware',id,name,null::public.indicator_type from public.malware where project_id=p_project union all select 'CVE','cves',id,cve_id,null::public.indicator_type from public.cves where project_id=p_project union all select 'INDICATOR','indicators',id,value,type from public.indicators where project_id=p_project union all select 'ATTACK_TECHNIQUE','mitre_techniques',id,technique_id,null::public.indicator_type from public.mitre_techniques where project_id=p_project loop
  if r.kind='INDICATOR' and r.indicator_type not in('IP','CIDR','DOMAIN','URL','HASH','EMAIL') then skipped:=skipped+1;continue;end if;
  begin
   norm:=public.intel_profile_normalize_item_value(r.kind,r.val,r.indicator_type);
  exception when invalid_parameter_value then
   if r.kind='INDICATOR' then skipped:=skipped+1;continue;end if;raise;
  end;
  k:=public.intel_profile_local_key(r.kind,norm,null);select * into item from public.intel_profile_items where owner_id=p_actor and profile_id=p_profile and profile_local_key=k for update;
  if item.id is null then insert into public.intel_profile_items(owner_id,profile_id,kind,display_value,normalized_value,profile_local_key,origin,state,source_project_id,source_entity_type,source_entity_id,indicator_type,created_by,updated_by)values(p_actor,p_profile,r.kind,r.val,norm,k,'DERIVED','ACTIVE',p_project,r.src,r.id,r.indicator_type,p_actor,p_actor);added:=added+1;
  elsif item.state='EXCLUDED' then excl:=excl+1; elsif item.state='REMOVED' then rem:=rem+1; else already:=already+1; end if;
 end loop;
 return jsonb_build_object('added',added,'already_present',already,'preserved_exclusions',excl,'preserved_removals',rem,'pending_suggestions',0,'skipped',skipped);
end$$;

create function public.create_standalone_intel_profile(p_actor uuid,p_name text,p_description text,p_intelligence_question text,p_priority public.intel_profile_priority,p_time_horizon_days integer,p_minimum_confidence integer,p_relationship_depth integer) returns uuid language plpgsql security definer set search_path='' as $$declare pid uuid;begin
 if p_actor is null or char_length(trim(p_name)) not between 2 and 160 then raise exception 'INVALID_PROFILE' using errcode='22023';end if;
 insert into public.intel_profiles(owner_id,kind,project_id,name,description,intelligence_question,priority,time_horizon_days,minimum_confidence,relationship_depth,created_by,updated_by)values(p_actor,'STANDALONE',null,trim(p_name),coalesce(p_description,''),coalesce(p_intelligence_question,''),p_priority,p_time_horizon_days,p_minimum_confidence,p_relationship_depth,p_actor,p_actor)returning id into pid;
 perform public.intel_profile_write_audit(p_actor,pid,null,p_actor,'PROFILE_CREATED','{}');return pid;end$$;
create function public.create_investigation_intel_profile(p_actor uuid,p_project_id uuid,p_name text,p_description text,p_intelligence_question text,p_priority public.intel_profile_priority,p_time_horizon_days integer,p_minimum_confidence integer,p_relationship_depth integer) returns jsonb language plpgsql security definer set search_path='' as $$declare pid uuid; counts jsonb;begin
 if not exists(select 1 from public.projects where id=p_project_id and owner_id=p_actor) then raise exception 'not_found' using errcode='P0002';end if;
 insert into public.intel_profiles(owner_id,kind,project_id,name,description,intelligence_question,priority,time_horizon_days,minimum_confidence,relationship_depth,created_by,updated_by)values(p_actor,'INVESTIGATION',p_project_id,trim(p_name),coalesce(p_description,''),coalesce(p_intelligence_question,''),p_priority,p_time_horizon_days,p_minimum_confidence,p_relationship_depth,p_actor,p_actor)returning id into pid;
 counts:=public.intel_profile_seed_from_project(p_actor,pid,p_project_id);perform public.intel_profile_write_audit(p_actor,pid,null,p_actor,'PROFILE_CREATED',jsonb_build_object('project_id',p_project_id,'seed',counts));return jsonb_build_object('profile_id',pid,'refresh',counts);end$$;
create function public.update_intel_profile_definition(p_actor uuid,p_profile_id uuid,p_name text,p_description text,p_intelligence_question text,p_priority public.intel_profile_priority,p_time_horizon_days integer,p_minimum_confidence integer,p_relationship_depth integer) returns uuid language plpgsql security definer set search_path='' as $$declare project uuid;begin
 if exists(select 1 from public.intel_profiles where id=p_profile_id and owner_id=p_actor and status='ARCHIVED') then raise exception 'PROFILE_ARCHIVED' using errcode='22023';end if;update public.intel_profiles set name=trim(p_name),description=coalesce(p_description,''),intelligence_question=coalesce(p_intelligence_question,''),priority=p_priority,time_horizon_days=p_time_horizon_days,minimum_confidence=p_minimum_confidence,relationship_depth=p_relationship_depth,updated_by=p_actor where id=p_profile_id and owner_id=p_actor returning project_id into project;if not found then raise exception 'not_found' using errcode='P0002';end if;perform public.intel_profile_write_audit(p_actor,p_profile_id,null,p_actor,'PROFILE_UPDATED','{}');return project;end$$;
create function public.set_intel_profile_status(p_actor uuid,p_profile_id uuid,p_status public.intel_profile_status,p_restore boolean default false) returns uuid language plpgsql security definer set search_path='' as $$declare p public.intel_profiles; new_status public.intel_profile_status; new_archived timestamptz; act public.intel_profile_audit_action;begin
 select * into p from public.intel_profiles where id=p_profile_id and owner_id=p_actor for update;if p.id is null then raise exception 'not_found' using errcode='P0002';end if;
 if p_restore then if p.status<>'ARCHIVED' then raise exception 'INVALID_PROFILE_TRANSITION' using errcode='22023';end if;new_status:='PAUSED';new_archived:=null;act:='PROFILE_RESTORED';
 elsif p.status='ACTIVE' and p_status='PAUSED' then new_status:='PAUSED';new_archived:=null;act:='PROFILE_PAUSED';
 elsif p.status='PAUSED' and p_status='ACTIVE' then new_status:='ACTIVE';new_archived:=null;act:='PROFILE_RESUMED';
 elsif p.status in('ACTIVE','PAUSED') and p_status='ARCHIVED' then new_status:='ARCHIVED';new_archived:=coalesce(p.archived_at,clock_timestamp());act:='PROFILE_ARCHIVED';
 else raise exception 'INVALID_PROFILE_TRANSITION' using errcode='22023';end if;
 update public.intel_profiles set status=new_status,archived_at=new_archived,updated_by=p_actor where id=p.id;perform public.intel_profile_write_audit(p_actor,p_profile_id,null,p_actor,act,jsonb_build_object('from',p.status,'to',new_status));return p.project_id;end$$;
create function public.add_explicit_intel_profile_item(p_actor uuid,p_profile_id uuid,p_kind public.intel_profile_item_kind,p_display_value text,p_semantic_role public.intel_profile_semantic_role default null,p_indicator_type public.indicator_type default null) returns uuid language plpgsql security definer set search_path='' as $$declare norm text;k text;i uuid;begin
 if not exists(select 1 from public.intel_profiles where id=p_profile_id and owner_id=p_actor and status<>'ARCHIVED') then raise exception 'not_found' using errcode='P0002';end if;if p_kind in('COUNTRY','REGION')and p_semantic_role is null then raise exception 'LOCATION_ROLE_REQUIRED' using errcode='22023';end if;if p_kind='INDICATOR' then p_indicator_type:=coalesce(p_indicator_type,public.intel_profile_detect_indicator_type(p_display_value));end if;norm:=public.intel_profile_normalize_item_value(p_kind,p_display_value,p_indicator_type);k:=public.intel_profile_local_key(p_kind,norm,p_semantic_role);
 insert into public.intel_profile_items(owner_id,profile_id,kind,display_value,normalized_value,profile_local_key,origin,state,semantic_role,indicator_type,created_by,updated_by,accepted_by)values(p_actor,p_profile_id,p_kind,trim(p_display_value),norm,k,'EXPLICIT','ACTIVE',p_semantic_role,p_indicator_type,p_actor,p_actor,p_actor)returning id into i;perform public.intel_profile_write_audit(p_actor,p_profile_id,i,p_actor,'ITEM_ADDED',jsonb_build_object('kind',p_kind));return i;end$$;
create function public.transition_intel_profile_item(p_actor uuid,p_profile_id uuid,p_item_id uuid,p_target_state public.intel_profile_item_state) returns uuid language plpgsql security definer set search_path='' as $$declare i public.intel_profile_items; project uuid; act public.intel_profile_audit_action;begin
 if exists(select 1 from public.intel_profiles where id=p_profile_id and owner_id=p_actor and status='ARCHIVED') then raise exception 'PROFILE_ARCHIVED' using errcode='22023';end if;select * into i from public.intel_profile_items where id=p_item_id and profile_id=p_profile_id and owner_id=p_actor for update;if i.id is null then raise exception 'not_found' using errcode='P0002';end if;select project_id into project from public.intel_profiles where id=p_profile_id and owner_id=p_actor;if project is null and not exists(select 1 from public.intel_profiles where id=p_profile_id and owner_id=p_actor)then raise exception 'not_found' using errcode='P0002';end if;
 if p_target_state='ACTIVE' then if i.state='ACTIVE' then raise exception 'INVALID_ITEM_TRANSITION' using errcode='22023';end if;if i.kind in('COUNTRY','REGION')and i.semantic_role is null then raise exception 'LOCATION_ROLE_REQUIRED' using errcode='22023';end if;update public.intel_profile_items set state='ACTIVE',removed_at=null,accepted_by=p_actor,updated_by=p_actor where id=i.id;act:=case when i.state='PENDING' then 'ITEM_ACCEPTED' else 'ITEM_REACTIVATED' end;
 elsif p_target_state in('EXCLUDED','REMOVED') then if i.state not in('ACTIVE','PENDING') then raise exception 'INVALID_ITEM_TRANSITION' using errcode='22023';end if;update public.intel_profile_items set state=p_target_state,removed_at=clock_timestamp(),updated_by=p_actor where id=i.id;act:=case when p_target_state='EXCLUDED' then 'ITEM_EXCLUDED' else 'ITEM_REMOVED' end;
 else raise exception 'INVALID_ITEM_TRANSITION' using errcode='22023';end if;perform public.intel_profile_write_audit(p_actor,p_profile_id,p_item_id,p_actor,act,jsonb_build_object('from',i.state,'to',p_target_state));return project;end$$;
create function public.refresh_investigation_intel_profile(p_actor uuid,p_profile_id uuid,p_project_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare counts jsonb;begin
 counts:=public.intel_profile_seed_from_project(p_actor,p_profile_id,p_project_id);perform public.intel_profile_write_audit(p_actor,p_profile_id,null,p_actor,'INVESTIGATION_REFRESHED',counts);return counts;end$$;

revoke all on function public.intel_profile_write_audit(uuid,uuid,uuid,uuid,public.intel_profile_audit_action,jsonb) from public, anon, authenticated;
revoke all on function public.intel_profile_seed_from_project(uuid,uuid,uuid) from public, anon, authenticated;
revoke all on function public.create_standalone_intel_profile(uuid,text,text,text,public.intel_profile_priority,integer,integer,integer) from public, anon, authenticated;
revoke all on function public.create_investigation_intel_profile(uuid,uuid,text,text,text,public.intel_profile_priority,integer,integer,integer) from public, anon, authenticated;
revoke all on function public.update_intel_profile_definition(uuid,uuid,text,text,text,public.intel_profile_priority,integer,integer,integer) from public, anon, authenticated;
revoke all on function public.set_intel_profile_status(uuid,uuid,public.intel_profile_status,boolean) from public, anon, authenticated;
revoke all on function public.add_explicit_intel_profile_item(uuid,uuid,public.intel_profile_item_kind,text,public.intel_profile_semantic_role,public.indicator_type) from public, anon, authenticated;
revoke all on function public.transition_intel_profile_item(uuid,uuid,uuid,public.intel_profile_item_state) from public, anon, authenticated;
revoke all on function public.refresh_investigation_intel_profile(uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.create_standalone_intel_profile(uuid,text,text,text,public.intel_profile_priority,integer,integer,integer), public.create_investigation_intel_profile(uuid,uuid,text,text,text,public.intel_profile_priority,integer,integer,integer), public.update_intel_profile_definition(uuid,uuid,text,text,text,public.intel_profile_priority,integer,integer,integer), public.set_intel_profile_status(uuid,uuid,public.intel_profile_status,boolean), public.add_explicit_intel_profile_item(uuid,uuid,public.intel_profile_item_kind,text,public.intel_profile_semantic_role,public.indicator_type), public.transition_intel_profile_item(uuid,uuid,uuid,public.intel_profile_item_state), public.refresh_investigation_intel_profile(uuid,uuid,uuid) to service_role;
do $$begin
 if has_table_privilege('authenticated','public.intel_profiles','INSERT') or has_table_privilege('authenticated','public.intel_profile_items','UPDATE') or has_table_privilege('authenticated','public.intel_profile_audit_events','INSERT') then raise exception 'TechINT table ACL too broad';end if;
 if has_function_privilege('authenticated','public.create_standalone_intel_profile(uuid,text,text,text,public.intel_profile_priority,integer,integer,integer)','EXECUTE') or not has_function_privilege('service_role','public.refresh_investigation_intel_profile(uuid,uuid,uuid)','EXECUTE') then raise exception 'TechINT trusted function ACL invalid';end if;
end$$;
