create type public.evidence_type as enum ('SCREENSHOT','PDF','ARTICLE','TWEET','FILE','LOG','PCAP');
create type public.task_status as enum ('TODO','IN_PROGRESS','COMPLETED');
create type public.task_priority as enum ('LOW','MEDIUM','HIGH');

create table public.research_notes (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, author_id uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(trim(title)) between 1 and 160), content text not null default '' check (char_length(content)<=50000), tags text[] not null default '{}' check (array_length(tags,1) is null or array_length(tags,1)<=20), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id));
create table public.evidence (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, collected_by uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(trim(title)) between 1 and 180), type public.evidence_type not null, description text not null default '' check (char_length(description)<=10000), source_url text check (source_url is null or source_url ~* '^https?://'), storage_path text, original_file_name text, mime_type text, file_size bigint check (file_size is null or file_size between 0 and 20971520), collection_date timestamptz not null default now(), tags text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id), check ((type in ('ARTICLE','TWEET') and source_url is not null) or storage_path is not null));
create table public.timeline_events (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, event_name text not null check (char_length(trim(event_name)) between 1 and 180), event_date timestamptz not null, description text not null default '' check (char_length(description)<=10000), related_entity_type text, related_entity_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id));
create table public.project_tasks (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, task_name text not null check (char_length(trim(task_name)) between 1 and 180), description text not null default '' check (char_length(description)<=10000), status public.task_status not null default 'TODO', priority public.task_priority not null default 'MEDIUM', assigned_user_id uuid references auth.users(id) on delete set null, deadline timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id));

create index research_notes_project_updated_idx on public.research_notes(project_id, updated_at desc); create index research_notes_tags_idx on public.research_notes using gin(tags);
create index evidence_project_collection_idx on public.evidence(project_id, collection_date desc); create index evidence_type_idx on public.evidence(type); create index evidence_tags_idx on public.evidence using gin(tags);
create index timeline_project_date_idx on public.timeline_events(project_id,event_date); create index tasks_project_status_idx on public.project_tasks(project_id,status); create index tasks_project_deadline_idx on public.project_tasks(project_id,deadline);

create trigger research_notes_set_updated_at before update on public.research_notes for each row execute function public.set_updated_at();
create trigger evidence_set_updated_at before update on public.evidence for each row execute function public.set_updated_at();
create trigger timeline_events_set_updated_at before update on public.timeline_events for each row execute function public.set_updated_at();
create trigger project_tasks_set_updated_at before update on public.project_tasks for each row execute function public.set_updated_at();

create function public.project_is_owned(pid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.projects p where p.id=pid and p.owner_id=auth.uid()) $$;
create function public.task_assignment_allowed(pid uuid, assigned uuid) returns boolean language sql stable security definer set search_path=public as $$ select assigned is null or exists(select 1 from public.projects p where p.id=pid and p.owner_id=auth.uid() and p.owner_id=assigned) $$;

alter table public.research_notes enable row level security; alter table public.evidence enable row level security; alter table public.timeline_events enable row level security; alter table public.project_tasks enable row level security;
create policy "notes owned project all" on public.research_notes for all to authenticated using (public.project_is_owned(project_id)) with check (public.project_is_owned(project_id) and author_id=auth.uid());
create policy "evidence owned project all" on public.evidence for all to authenticated using (public.project_is_owned(project_id)) with check (public.project_is_owned(project_id) and collected_by=auth.uid());
create policy "timeline owned project all" on public.timeline_events for all to authenticated using (public.project_is_owned(project_id)) with check (public.project_is_owned(project_id));
create policy "tasks owned project all" on public.project_tasks for all to authenticated using (public.project_is_owned(project_id)) with check (public.project_is_owned(project_id) and public.task_assignment_allowed(project_id,assigned_user_id));

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('evidence','evidence',false,20971520,array['image/png','image/jpeg','application/pdf','application/vnd.tcpdump.pcap','application/octet-stream','text/plain','text/x-log']) on conflict (id) do update set public=false,file_size_limit=20971520,allowed_mime_types=excluded.allowed_mime_types;
create policy "evidence storage read own" on storage.objects for select to authenticated using (bucket_id='evidence' and exists(select 1 from public.projects p where p.id=(split_part(name,'/',2))::uuid and p.owner_id=auth.uid() and split_part(name,'/',1)=auth.uid()::text));
create policy "evidence storage insert own" on storage.objects for insert to authenticated with check (bucket_id='evidence' and exists(select 1 from public.projects p where p.id=(split_part(name,'/',2))::uuid and p.owner_id=auth.uid() and split_part(name,'/',1)=auth.uid()::text));
create policy "evidence storage delete own" on storage.objects for delete to authenticated using (bucket_id='evidence' and exists(select 1 from public.projects p where p.id=(split_part(name,'/',2))::uuid and p.owner_id=auth.uid() and split_part(name,'/',1)=auth.uid()::text));
