-- Phase 2.2A: trusted, owner-scoped external research feed collection. Raw XML is never persisted.
create type public.research_feed_type as enum ('UNKNOWN','RSS','ATOM');
create type public.research_feed_health as enum ('NEVER_FETCHED','HEALTHY','DEGRADED','ERROR');
create type public.research_feed_run_status as enum ('RUNNING','SUCCEEDED','NOT_MODIFIED','FAILED');
create type public.research_fingerprint_type as enum ('URL','CONTENT');

create table public.research_feed_sources (
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade,
 name text not null check(char_length(name) between 1 and 240), description text not null default '' check(char_length(description)<=10000),
 configured_url text not null check(char_length(configured_url)<=4096), configured_url_hash text not null check(configured_url_hash~'^[0-9a-f]{64}$'),
 detected_feed_type public.research_feed_type not null default 'UNKNOWN', enabled boolean not null default true,
 health_status public.research_feed_health not null default 'NEVER_FETCHED', last_checked_at timestamptz,last_success_at timestamptz,last_content_change_at timestamptz,
 last_http_status integer check(last_http_status between 100 and 599),last_final_url text check(char_length(last_final_url)<=4096),
 etag text check(char_length(etag)<=512 and etag!~E'[\r\n]'),last_modified text check(char_length(last_modified)<=128 and last_modified!~E'[\r\n]'),
 consecutive_failures integer not null default 0 check(consecutive_failures>=0),next_eligible_fetch_at timestamptz,
 last_error_code text check(char_length(last_error_code)<=64),last_error_message text check(char_length(last_error_message)<=500),
 fetch_lease_token_hash text check(fetch_lease_token_hash~'^[0-9a-f]{64}$'),fetch_lease_run_id uuid,fetch_lease_url_hash text,fetch_lease_expires_at timestamptz,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,
 unique(project_id,id),unique(project_id,configured_url_hash),
 check((fetch_lease_token_hash is null)=(fetch_lease_expires_at is null) and (fetch_lease_token_hash is null)=(fetch_lease_run_id is null) and (fetch_lease_token_hash is null)=(fetch_lease_url_hash is null))
);
create table public.research_feed_fetch_runs (
 id uuid primary key default gen_random_uuid(),project_id uuid not null,feed_source_id uuid not null,status public.research_feed_run_status not null default 'RUNNING',
 started_at timestamptz not null default now(),completed_at timestamptz,duration_ms integer check(duration_ms>=0),request_url_hash text not null check(request_url_hash~'^[0-9a-f]{64}$'),
 lease_token_hash text not null check(lease_token_hash~'^[0-9a-f]{64}$'),lease_expires_at timestamptz not null,
 final_url text check(char_length(final_url)<=4096),http_status integer check(http_status between 100 and 599),response_bytes integer check(response_bytes between 0 and 5242880),
 items_seen integer not null default 0,items_created integer not null default 0,items_updated integer not null default 0,items_changed integer not null default 0,items_deduplicated integer not null default 0,items_skipped integer not null default 0,
 error_code text check(char_length(error_code)<=64),error_message text check(char_length(error_message)<=500),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),
 unique(project_id,id),foreign key(project_id,feed_source_id) references public.research_feed_sources(project_id,id) on delete cascade,check((status='RUNNING')=(completed_at is null))
);
alter table public.research_feed_sources add constraint research_feed_source_lease_run_fk foreign key(project_id,fetch_lease_run_id) references public.research_feed_fetch_runs(project_id,id) deferrable initially deferred;
create table public.research_items (
 id uuid primary key default gen_random_uuid(),project_id uuid not null references public.projects(id) on delete cascade,canonical_url text check(char_length(canonical_url)<=4096),
 title text check(char_length(title)<=500),summary_text text check(char_length(summary_text)<=20000),content_text text check(char_length(content_text)<=100000),author_name text check(char_length(author_name)<=500),
 published_at timestamptz,source_updated_at timestamptz,language text check(char_length(language)<=50),categories text[] not null default '{}',first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),content_changed_at timestamptz,
 created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,id),check(cardinality(categories)<=50),check(title is not null or summary_text is not null or content_text is not null)
);
create table public.research_item_fingerprints(id uuid primary key default gen_random_uuid(),project_id uuid not null,research_item_id uuid not null,fingerprint_type public.research_fingerprint_type not null,fingerprint_hash text not null check(fingerprint_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default now(),foreign key(project_id,research_item_id) references public.research_items(project_id,id) on delete cascade,unique(project_id,fingerprint_type,fingerprint_hash));
create table public.research_feed_item_observations(id uuid primary key default gen_random_uuid(),project_id uuid not null,feed_source_id uuid not null,research_item_id uuid not null,fetch_run_id uuid not null,external_item_id text check(char_length(external_item_id)<=1000),observed_url text check(char_length(observed_url)<=4096),source_published_at timestamptz,first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),observation_count integer not null default 1 check(observation_count>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(project_id,feed_source_id) references public.research_feed_sources(project_id,id),foreign key(project_id,research_item_id) references public.research_items(project_id,id),foreign key(project_id,fetch_run_id) references public.research_feed_fetch_runs(project_id,id),unique(project_id,feed_source_id,research_item_id));

create function public.research_actor_owns(p_actor_id uuid,p_project_id uuid) returns boolean language sql stable security definer set search_path='' as $$select p_actor_id is not null and exists(select 1 from public.projects where id=p_project_id and owner_id=p_actor_id)$$;
revoke all on function public.research_actor_owns(uuid,uuid) from public,anon,authenticated;

create function public.create_research_feed(p_actor_id uuid,p_project_id uuid,p_name text,p_description text,p_configured_url text,p_configured_url_hash text,p_enabled boolean) returns public.research_feed_sources language plpgsql security definer set search_path='' as $$declare r public.research_feed_sources;begin
 if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;
 if char_length(trim(p_name)) not between 1 and 240 or char_length(p_description)>10000 or p_configured_url is null or(p_configured_url is not null and(char_length(p_configured_url)>4096 or p_configured_url_hash!~'^[0-9a-f]{64}$'))then raise exception 'INVALID_FEED_INPUT' using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_project_id::text||':feed-limit',0));if(select count(*) from public.research_feed_sources where project_id=p_project_id)>=100 then raise exception 'FEED_LIMIT';end if;
 insert into public.research_feed_sources(project_id,name,description,configured_url,configured_url_hash,enabled,created_by)values(p_project_id,trim(p_name),p_description,p_configured_url,p_configured_url_hash,p_enabled,p_actor_id)returning * into r;return r;end$$;
create function public.edit_research_feed(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid,p_name text,p_description text,p_configured_url text,p_configured_url_hash text,p_enabled boolean) returns public.research_feed_sources language plpgsql security definer set search_path='' as $$declare r public.research_feed_sources;changed boolean;begin
 if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;select * into r from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;if r.id is null then raise exception 'not_found' using errcode='P0002';end if;if r.archived_at is not null then raise exception 'FEED_ARCHIVED';end if;if r.fetch_lease_expires_at>clock_timestamp() then raise exception 'FETCH_ALREADY_RUNNING';end if;
 if char_length(trim(p_name)) not between 1 and 240 or char_length(p_description)>10000 or(p_configured_url is not null and(char_length(p_configured_url)>4096 or p_configured_url_hash is null or p_configured_url_hash!~'^[0-9a-f]{64}$'))then raise exception 'INVALID_FEED_INPUT' using errcode='22023';end if;changed:=p_configured_url_hash is not null and r.configured_url_hash<>p_configured_url_hash;
 update public.research_feed_sources set name=trim(p_name),description=p_description,configured_url=coalesce(p_configured_url,configured_url),configured_url_hash=coalesce(p_configured_url_hash,configured_url_hash),enabled=p_enabled,detected_feed_type=case when changed then 'UNKNOWN' else detected_feed_type end,health_status=case when changed then 'NEVER_FETCHED' else health_status end,last_final_url=case when changed then null else last_final_url end,etag=case when changed then null else etag end,last_modified=case when changed then null else last_modified end,last_error_code=case when changed then null else last_error_code end,last_error_message=case when changed then null else last_error_message end,updated_at=clock_timestamp() where id=r.id returning * into r;return r;end$$;
create function public.set_research_feed_enabled(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid,p_enabled boolean) returns public.research_feed_sources language plpgsql security definer set search_path='' as $$declare r public.research_feed_sources;begin if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;update public.research_feed_sources set enabled=p_enabled,updated_at=clock_timestamp() where project_id=p_project_id and id=p_feed_source_id and archived_at is null returning * into r;if r.id is null then raise exception 'not_found' using errcode='P0002';end if;return r;end$$;
create function public.archive_research_feed(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid) returns public.research_feed_sources language plpgsql security definer set search_path='' as $$declare r public.research_feed_sources;begin if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;select * into r from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;if r.id is null then raise exception 'not_found' using errcode='P0002';end if;if r.fetch_lease_expires_at>clock_timestamp() then raise exception 'FETCH_ALREADY_RUNNING';end if;update public.research_feed_sources set enabled=false,archived_at=coalesce(archived_at,clock_timestamp()),updated_at=clock_timestamp() where id=r.id returning * into r;return r;end$$;
create function public.restore_research_feed(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid) returns public.research_feed_sources language plpgsql security definer set search_path='' as $$declare r public.research_feed_sources;begin if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;update public.research_feed_sources set enabled=false,archived_at=null,updated_at=clock_timestamp() where project_id=p_project_id and id=p_feed_source_id and archived_at is not null returning * into r;if r.id is null then raise exception 'not_found' using errcode='P0002';end if;return r;end$$;

create function public.claim_research_feed_fetch(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid) returns table(run_id uuid,lease_token uuid,request_url_hash text,lease_expires_at timestamptz,configured_url text,etag text,last_modified text) language plpgsql security definer set search_path='' as $$declare s public.research_feed_sources;t uuid:=gen_random_uuid();rid uuid:=gen_random_uuid();exp timestamptz:=clock_timestamp()+interval '2 minutes';begin
 if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;select * into s from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;if s.id is null then raise exception 'not_found' using errcode='P0002';end if;if s.archived_at is not null then raise exception 'FEED_ARCHIVED';end if;if not s.enabled then raise exception 'FEED_DISABLED';end if;if s.fetch_lease_expires_at>clock_timestamp() then raise exception 'FETCH_ALREADY_RUNNING';end if;if s.next_eligible_fetch_at>clock_timestamp() then raise exception 'FETCH_COOLDOWN';end if;
 if s.fetch_lease_run_id is not null then update public.research_feed_fetch_runs set status='FAILED',completed_at=clock_timestamp(),duration_ms=greatest(0,(extract(epoch from(clock_timestamp()-started_at))*1000)::int),error_code='LEASE_EXPIRED',error_message='The prior fetch lease expired.' where project_id=p_project_id and id=s.fetch_lease_run_id and status='RUNNING';update public.research_feed_sources set fetch_lease_token_hash=null,fetch_lease_run_id=null,fetch_lease_url_hash=null,fetch_lease_expires_at=null where id=s.id;end if;
 insert into public.research_feed_fetch_runs(id,project_id,feed_source_id,request_url_hash,lease_token_hash,lease_expires_at,created_by)values(rid,p_project_id,s.id,s.configured_url_hash,encode(public.digest(t::text,'sha256'),'hex'),exp,p_actor_id);
 update public.research_feed_sources set fetch_lease_token_hash=encode(public.digest(t::text,'sha256'),'hex'),fetch_lease_run_id=rid,fetch_lease_url_hash=s.configured_url_hash,fetch_lease_expires_at=exp where id=s.id;return query select rid,t,s.configured_url_hash,exp,s.configured_url,s.etag,s.last_modified;end$$;

create function public.complete_research_feed_fetch(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid,p_run_id uuid,p_lease_token uuid,p_request_url_hash text,p_status public.research_feed_run_status,p_feed_type public.research_feed_type,p_final_url text,p_http_status integer,p_response_bytes integer,p_etag text,p_last_modified text,p_items jsonb default '[]') returns public.research_feed_fetch_runs language plpgsql security definer set search_path='' as $$
declare s public.research_feed_sources;r public.research_feed_fetch_runs;j jsonb;u uuid;url_match uuid;content_match uuid;created_n int:=0;changed_n int:=0;dedup_n int:=0;skipped_n int:=0;seen_n int:=0;now_ts timestamptz:=clock_timestamp();cats text[];published timestamptz;source_updated timestamptz;begin
 if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;if p_lease_token is null or p_items is null or p_status not in ('SUCCEEDED','NOT_MODIFIED') or p_response_bytes not between 0 and 5242880 or p_final_url is null or char_length(p_final_url)>4096 or p_final_url!~'^https?://[^[:space:]]+$' or(p_status='SUCCEEDED' and(p_http_status<>200 or p_feed_type not in ('RSS','ATOM')))or(p_status='NOT_MODIFIED' and(p_http_status<>304 or p_response_bytes<>0)) or p_etag~E'[\r\n]' or char_length(p_etag)>512 or p_last_modified~E'[\r\n]' or char_length(p_last_modified)>128 or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)>500 or pg_column_size(p_items)>5242880 or(p_status='NOT_MODIFIED' and jsonb_array_length(p_items)<>0) then raise exception 'INVALID_COMPLETION_PAYLOAD' using errcode='22023';end if;
 select * into s from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;select * into r from public.research_feed_fetch_runs where project_id=p_project_id and feed_source_id=p_feed_source_id and id=p_run_id for update;
 if s.id is null or r.id is null or r.status<>'RUNNING' or s.fetch_lease_token_hash is distinct from encode(public.digest(p_lease_token::text,'sha256'),'hex') or s.fetch_lease_run_id is distinct from p_run_id or s.fetch_lease_expires_at<=now_ts or r.lease_expires_at<=now_ts or r.lease_token_hash<>encode(public.digest(p_lease_token::text,'sha256'),'hex') or s.fetch_lease_url_hash<>p_request_url_hash or s.configured_url_hash<>p_request_url_hash or r.request_url_hash<>p_request_url_hash then raise exception 'STALE_FETCH_LEASE';end if;
 if p_status='SUCCEEDED' then for j in select * from jsonb_array_elements(p_items) loop
  if(j->>'content_hash')!~'^[0-9a-f]{64}$' or(j->>'url_hash' is not null and(j->>'url_hash')!~'^[0-9a-f]{64}$')or char_length(j->>'title')>500 or char_length(j->>'summary_text')>20000 or char_length(j->>'content_text')>100000 or char_length(j->>'author_name')>500 or char_length(j->>'language')>50 or char_length(j->>'canonical_url')>4096 or jsonb_typeof(coalesce(j->'categories','[]'))<>'array' or jsonb_array_length(coalesce(j->'categories','[]'))>50 then raise exception 'INVALID_ITEM_PAYLOAD' using errcode='22023';end if;
  cats:=array(select value from jsonb_array_elements_text(coalesce(j->'categories','[]')) value);if exists(select 1 from unnest(cats)x where char_length(x)>100)then raise exception 'INVALID_ITEM_PAYLOAD' using errcode='22023';end if;begin published:=nullif(j->>'published_at','')::timestamptz;source_updated:=nullif(j->>'source_updated_at','')::timestamptz;exception when others then raise exception 'INVALID_ITEM_DATE' using errcode='22023';end;
  seen_n:=seen_n+1;perform pg_advisory_xact_lock(hashtextextended(p_project_id::text||':'||least(coalesce(j->>'url_hash',j->>'content_hash'),j->>'content_hash'),0));perform pg_advisory_xact_lock(hashtextextended(p_project_id::text||':'||greatest(coalesce(j->>'url_hash',j->>'content_hash'),j->>'content_hash'),0));
  url_match:=null;content_match:=null;select research_item_id into url_match from public.research_item_fingerprints where project_id=p_project_id and fingerprint_type='URL' and fingerprint_hash=j->>'url_hash';select research_item_id into content_match from public.research_item_fingerprints where project_id=p_project_id and fingerprint_type='CONTENT' and fingerprint_hash=j->>'content_hash';
  if url_match is not null and content_match is not null and url_match<>content_match then skipped_n:=skipped_n+1;continue;end if;u:=coalesce(url_match,content_match);
  if u is null then insert into public.research_items(project_id,canonical_url,title,summary_text,content_text,author_name,published_at,source_updated_at,language,categories,created_by)values(p_project_id,j->>'canonical_url',j->>'title',j->>'summary_text',j->>'content_text',j->>'author_name',published,source_updated,j->>'language',cats,p_actor_id)returning id into u;insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'CONTENT',j->>'content_hash');if j->>'url_hash' is not null then insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'URL',j->>'url_hash');end if;created_n:=created_n+1;
  else if url_match is not null and content_match is null then update public.research_items set title=j->>'title',summary_text=j->>'summary_text',content_text=j->>'content_text',author_name=j->>'author_name',published_at=published,source_updated_at=source_updated,language=j->>'language',categories=cats,last_seen_at=now_ts,content_changed_at=now_ts,updated_at=now_ts where project_id=p_project_id and id=u;insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'CONTENT',j->>'content_hash');changed_n:=changed_n+1;else update public.research_items set last_seen_at=now_ts,updated_at=now_ts where project_id=p_project_id and id=u;dedup_n:=dedup_n+1;if j->>'url_hash' is not null then insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'URL',j->>'url_hash')on conflict do nothing;end if;end if;end if;
  insert into public.research_feed_item_observations(project_id,feed_source_id,research_item_id,fetch_run_id,external_item_id,observed_url,source_published_at)values(p_project_id,p_feed_source_id,u,p_run_id,j->>'external_id',j->>'canonical_url',published)on conflict(project_id,feed_source_id,research_item_id)do update set fetch_run_id=excluded.fetch_run_id,last_seen_at=now_ts,observation_count=public.research_feed_item_observations.observation_count+1,updated_at=now_ts;
 end loop;end if;
 update public.research_feed_fetch_runs set status=p_status,completed_at=now_ts,duration_ms=greatest(0,(extract(epoch from(now_ts-started_at))*1000)::int),final_url=p_final_url,http_status=p_http_status,response_bytes=p_response_bytes,items_seen=seen_n,items_created=created_n,items_changed=changed_n,items_deduplicated=dedup_n,items_skipped=skipped_n where id=p_run_id returning * into r;
 update public.research_feed_sources set detected_feed_type=case when p_status='SUCCEEDED' then p_feed_type else detected_feed_type end,health_status='HEALTHY',last_checked_at=now_ts,last_success_at=now_ts,last_content_change_at=case when created_n+changed_n>0 then now_ts else last_content_change_at end,last_http_status=p_http_status,last_final_url=p_final_url,etag=case when p_status='SUCCEEDED' then nullif(p_etag,'') else etag end,last_modified=case when p_status='SUCCEEDED' then nullif(p_last_modified,'') else last_modified end,consecutive_failures=0,next_eligible_fetch_at=now_ts+interval '60 seconds',last_error_code=null,last_error_message=null,fetch_lease_token_hash=null,fetch_lease_run_id=null,fetch_lease_url_hash=null,fetch_lease_expires_at=null,updated_at=now_ts where id=p_feed_source_id and fetch_lease_token_hash=encode(public.digest(p_lease_token::text,'sha256'),'hex') and fetch_lease_run_id=p_run_id;return r;end$$;

create function public.fail_research_feed_fetch(p_actor_id uuid,p_project_id uuid,p_feed_source_id uuid,p_run_id uuid,p_lease_token uuid,p_request_url_hash text,p_error_code text,p_error_message text) returns void language plpgsql security definer set search_path='' as $$declare s public.research_feed_sources;r public.research_feed_fetch_runs;ts timestamptz:=clock_timestamp();begin
 if not public.research_actor_owns(p_actor_id,p_project_id) then raise exception 'not_found' using errcode='P0002';end if;if p_lease_token is null then raise exception 'STALE_FETCH_LEASE';end if;select * into s from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;select * into r from public.research_feed_fetch_runs where project_id=p_project_id and feed_source_id=p_feed_source_id and id=p_run_id for update;
 if s.id is null or r.id is null or r.status<>'RUNNING' or s.fetch_lease_token_hash is distinct from encode(public.digest(p_lease_token::text,'sha256'),'hex') or s.fetch_lease_run_id is distinct from p_run_id or s.fetch_lease_expires_at<=ts or r.lease_token_hash<>encode(public.digest(p_lease_token::text,'sha256'),'hex') or s.fetch_lease_url_hash<>p_request_url_hash or s.configured_url_hash<>p_request_url_hash or r.request_url_hash<>p_request_url_hash then raise exception 'STALE_FETCH_LEASE';end if;
 update public.research_feed_fetch_runs set status='FAILED',completed_at=ts,duration_ms=greatest(0,(extract(epoch from(ts-started_at))*1000)::int),error_code=left(p_error_code,64),error_message=left(p_error_message,500)where id=p_run_id;
 update public.research_feed_sources set last_checked_at=ts,consecutive_failures=consecutive_failures+1,health_status=case when consecutive_failures+1>=3 then 'ERROR'::public.research_feed_health else 'DEGRADED'::public.research_feed_health end,last_error_code=left(p_error_code,64),last_error_message=left(p_error_message,500),fetch_lease_token_hash=null,fetch_lease_run_id=null,fetch_lease_url_hash=null,fetch_lease_expires_at=null,next_eligible_fetch_at=ts+interval '60 seconds',updated_at=ts where id=p_feed_source_id and fetch_lease_token_hash=encode(public.digest(p_lease_token::text,'sha256'),'hex') and fetch_lease_run_id=p_run_id;end$$;

alter table public.research_feed_sources enable row level security;alter table public.research_feed_fetch_runs enable row level security;alter table public.research_items enable row level security;alter table public.research_item_fingerprints enable row level security;alter table public.research_feed_item_observations enable row level security;
do $$declare t text;begin foreach t in array array['research_feed_sources','research_feed_fetch_runs','research_items','research_item_fingerprints','research_feed_item_observations']loop execute format('create policy %I on public.%I for select to authenticated using(public.project_is_owned(project_id))',t||'_select',t);end loop;end$$;
-- Analyst clients can only read. All mutations cross the dedicated server-only service-role boundary.
revoke all on function public.create_research_feed(uuid,uuid,text,text,text,text,boolean),public.edit_research_feed(uuid,uuid,uuid,text,text,text,text,boolean),public.set_research_feed_enabled(uuid,uuid,uuid,boolean),public.archive_research_feed(uuid,uuid,uuid),public.restore_research_feed(uuid,uuid,uuid),public.claim_research_feed_fetch(uuid,uuid,uuid),public.complete_research_feed_fetch(uuid,uuid,uuid,uuid,uuid,text,public.research_feed_run_status,public.research_feed_type,text,integer,integer,text,text,jsonb),public.fail_research_feed_fetch(uuid,uuid,uuid,uuid,uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.create_research_feed(uuid,uuid,text,text,text,text,boolean),public.edit_research_feed(uuid,uuid,uuid,text,text,text,text,boolean),public.set_research_feed_enabled(uuid,uuid,uuid,boolean),public.archive_research_feed(uuid,uuid,uuid),public.restore_research_feed(uuid,uuid,uuid),public.claim_research_feed_fetch(uuid,uuid,uuid),public.complete_research_feed_fetch(uuid,uuid,uuid,uuid,uuid,text,public.research_feed_run_status,public.research_feed_type,text,integer,integer,text,text,jsonb),public.fail_research_feed_fetch(uuid,uuid,uuid,uuid,uuid,text,text,text) to service_role;
