create extension if not exists pgcrypto;

create type public.technical_signal_type as enum('VULNERABILITY_CHANGE','ACTIVE_EXPLOITATION','TECHNICAL_ADVISORY','IOC_OBSERVATION','MALWARE_ACTIVITY','CAMPAIGN_REPORT','INFRASTRUCTURE_CHANGE','TTP_UPDATE','PROVIDER_ALERT','TECHNICAL_REPORT');
create type public.technical_signal_lifecycle as enum('ACTIVE','RETRACTED','SUPERSEDED','ARCHIVED');
create type public.technical_signal_severity as enum('UNKNOWN','INFO','LOW','MEDIUM','HIGH','CRITICAL');
create type public.technical_signal_revision_change_kind as enum('CREATED','UPDATED','RETRACTED','REACTIVATED','SUPERSEDED');
create type public.technical_signal_source_family as enum('IOC_PROVIDER','FEED','VULNERABILITY','ADVISORY','STIX','MANUAL_TEST','OTHER');
create type public.technical_signal_observation_disposition as enum('CURRENT','SUPPORTING','STALE','CONFLICTING');
create type public.technical_signal_entity_kind as enum('CVE','INDICATOR','THREAT_ACTOR','MALWARE','CAMPAIGN','INFRASTRUCTURE','ATTACK_TECHNIQUE','VENDOR','PRODUCT','SECTOR','COUNTRY','REGION','TAG');
create type public.technical_signal_entity_role as enum('SUBJECT','AFFECTS','EXPLOITS','USES','ATTRIBUTED_TO','TARGETS','LOCATED_IN','RELATED_TO','MENTIONS');
create type public.technical_signal_assertion_basis as enum('PROVIDER_ASSERTED','SYSTEM_EXTRACTED','AI_SUGGESTED','ANALYST_CONFIRMED');

create function public.tech_signal_json_size_ok(p_json jsonb,p_limit integer) returns boolean language sql immutable as $$select p_json is not null and pg_column_size(p_json)<=p_limit$$;
create function public.tech_signal_snapshot_fingerprint(p_signal_type public.technical_signal_type,p_title text,p_summary text,p_lifecycle public.technical_signal_lifecycle,p_severity public.technical_signal_severity,p_confidence integer,p_facts jsonb,p_published_at timestamptz,p_observed_at timestamptz,p_effective_at timestamptz) returns text language sql immutable as $$select encode(extensions.digest(convert_to(jsonb_build_object('signal_type',p_signal_type::text,'title',trim(p_title),'summary',coalesce(p_summary,''),'lifecycle',p_lifecycle::text,'severity',p_severity::text,'confidence',p_confidence,'facts',p_facts,'published_at',p_published_at,'observed_at',p_observed_at,'effective_at',p_effective_at)::text,'utf8'),'sha256'),'hex')$$;
create function public.tech_signal_observation_key(p_source_system text,p_source_record_key text,p_source_revision_key text,p_fingerprint text) returns text language sql immutable as $$select encode(extensions.digest(convert_to(lower(trim(p_source_system))||':'||trim(p_source_record_key)||':'||coalesce(trim(p_source_revision_key),'')||':'||p_fingerprint,'utf8'),'sha256'),'hex')$$;
create function public.tech_signal_validate_url(p_url text) returns text language plpgsql immutable as $$declare v text:=trim(p_url);auth text;begin if p_url is null or v='' then return null;end if;if char_length(v)>2048 or v!~*'^https?://[^[:space:]]+$' then raise exception 'INVALID_SOURCE_URL' using errcode='22023';end if;auth:=substring(v from '^https?://([^/?#]+)');if auth is null or auth='' or auth like '%@%' then raise exception 'INVALID_SOURCE_URL' using errcode='22023';end if;return v;end$$;
create function public.tech_signal_normalize_cve(p_value text) returns text language plpgsql immutable as $$declare v text:=upper(trim(p_value));begin if v~'^CVE-[0-9]{4}-[0-9]{4,}$' then return v;end if;raise exception 'INVALID_CVE' using errcode='22023';end$$;
create function public.tech_signal_normalize_attack_id(p_value text) returns text language plpgsql immutable as $$declare v text:=upper(trim(p_value));begin if v~'^T[0-9]{4}(\.[0-9]{3})?$' then return v;end if;raise exception 'INVALID_ATTACK_ID' using errcode='22023';end$$;
create function public.tech_signal_reject_mutation() returns trigger language plpgsql security definer set search_path='' as $$begin raise exception 'TECH_SIGNAL_APPEND_ONLY' using errcode='42501';end$$;

create table public.technical_signals(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id), signal_type public.technical_signal_type not null, canonical_key text not null check(char_length(canonical_key) between 3 and 300), title text not null check(char_length(trim(title)) between 1 and 300), summary text not null default '' check(char_length(summary)<=5000), lifecycle public.technical_signal_lifecycle not null default 'ACTIVE', severity public.technical_signal_severity not null default 'UNKNOWN', confidence integer check(confidence between 0 and 100), facts jsonb not null default '{}' check(public.tech_signal_json_size_ok(facts,65536)), published_at timestamptz, observed_at timestamptz, effective_at timestamptz not null, first_seen_at timestamptz not null, last_seen_at timestamptz not null, current_revision_number integer not null default 0 check(current_revision_number>=0), current_revision_id uuid, current_snapshot_fingerprint text, superseded_by_signal_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,signal_type,canonical_key), unique(owner_id,id), check(first_seen_at<=last_seen_at), check(superseded_by_signal_id is null or superseded_by_signal_id<>id));

create table public.technical_signal_observations(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null, signal_id uuid not null, source_family public.technical_signal_source_family not null, source_system text not null check(char_length(trim(source_system)) between 2 and 80 and source_system~'^[A-Za-z0-9_.:-]+$'), source_record_key text not null check(char_length(trim(source_record_key)) between 1 and 300), source_revision_key text check(char_length(source_revision_key)<=300), observation_key text not null check(observation_key~'^[0-9a-f]{64}$'), source_url text check(source_url is null or char_length(source_url)<=2048), source_title text check(source_title is null or char_length(source_title)<=300), source_published_at timestamptz, source_modified_at timestamptz, source_observed_at timestamptz, received_at timestamptz not null, effective_at timestamptz not null, disposition public.technical_signal_observation_disposition not null, source_snapshot jsonb not null default '{}' check(public.tech_signal_json_size_ok(source_snapshot,65536)), source_fingerprint text not null check(source_fingerprint~'^[0-9a-f]{64}$'), created_at timestamptz not null default now(), unique(owner_id,observation_key), unique(owner_id,id), unique(owner_id,signal_id,id), foreign key(owner_id,signal_id) references public.technical_signals(owner_id,id) on delete restrict);

create table public.technical_signal_revisions(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null, signal_id uuid not null, revision_number integer not null check(revision_number>0), change_kind public.technical_signal_revision_change_kind not null, lifecycle public.technical_signal_lifecycle not null, title text not null check(char_length(trim(title)) between 1 and 300), summary text not null default '' check(char_length(summary)<=5000), severity public.technical_signal_severity not null, confidence integer check(confidence between 0 and 100), facts jsonb not null default '{}' check(public.tech_signal_json_size_ok(facts,65536)), published_at timestamptz, observed_at timestamptz, effective_at timestamptz not null, snapshot_fingerprint text not null check(snapshot_fingerprint~'^[0-9a-f]{64}$'), source_observation_id uuid not null, created_at timestamptz not null default now(), unique(owner_id,signal_id,revision_number), unique(owner_id,signal_id,snapshot_fingerprint), unique(owner_id,id), unique(owner_id,signal_id,id), foreign key(owner_id,signal_id) references public.technical_signals(owner_id,id) on delete restrict, foreign key(owner_id,signal_id,source_observation_id) references public.technical_signal_observations(owner_id,signal_id,id) on delete restrict);

alter table public.technical_signals add constraint technical_signals_current_revision_fk foreign key(owner_id,id,current_revision_id) references public.technical_signal_revisions(owner_id,signal_id,id) deferrable initially deferred;
alter table public.technical_signals add constraint technical_signals_superseded_fk foreign key(owner_id,superseded_by_signal_id) references public.technical_signals(owner_id,id) on delete restrict;
create trigger technical_signals_set_updated_at before update on public.technical_signals for each row execute function public.set_updated_at();

create table public.technical_signal_entity_assertions(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null, signal_id uuid not null, source_observation_id uuid not null, entity_kind public.technical_signal_entity_kind not null, display_value text not null check(char_length(trim(display_value)) between 1 and 300), normalized_value text not null check(char_length(trim(normalized_value)) between 1 and 300), semantic_role public.technical_signal_entity_role not null, assertion_basis public.technical_signal_assertion_basis not null, confidence integer check(confidence between 0 and 100), indicator_type public.indicator_type, existing_entity_type text check(existing_entity_type is null or char_length(existing_entity_type)<=80), existing_entity_id uuid, created_at timestamptz not null default now(), unique(owner_id,source_observation_id,entity_kind,normalized_value,semantic_role,assertion_basis), foreign key(owner_id,signal_id,source_observation_id) references public.technical_signal_observations(owner_id,signal_id,id) on delete restrict, check((entity_kind='INDICATOR')=(indicator_type is not null)));

create trigger technical_signal_observations_append_only before update or delete on public.technical_signal_observations for each row execute function public.tech_signal_reject_mutation();
create trigger technical_signal_revisions_append_only before update or delete on public.technical_signal_revisions for each row execute function public.tech_signal_reject_mutation();
create trigger technical_signal_entity_assertions_append_only before update or delete on public.technical_signal_entity_assertions for each row execute function public.tech_signal_reject_mutation();

create or replace function public.record_technical_signal(p_owner_id uuid,p_signal jsonb,p_observation jsonb,p_entity_assertions jsonb default '[]') returns jsonb language plpgsql security definer set search_path='' as $$declare
 sig public.technical_signals; obs public.technical_signal_observations; rev_id uuid; sfp text; ofp text; okey text; disp public.technical_signal_observation_disposition; rn int; created_sig bool:=false; created_obs bool:=false; created_rev bool:=false; ent_count int:=0; item jsonb; st public.technical_signal_type; lc public.technical_signal_lifecycle; sev public.technical_signal_severity; ef timestamptz; rec timestamptz; ck public.technical_signal_revision_change_kind;
begin
 if p_owner_id is null or not exists(select 1 from auth.users where id=p_owner_id) then raise exception 'not_found' using errcode='P0002';end if;
 if p_signal is null or p_observation is null or p_entity_assertions is null or jsonb_typeof(p_signal)<>'object' or jsonb_typeof(p_observation)<>'object' or jsonb_typeof(p_entity_assertions)<>'array' or jsonb_array_length(p_entity_assertions)>50 then raise exception 'INVALID_SIGNAL_PAYLOAD' using errcode='22023';end if;
 if pg_column_size(coalesce(p_signal->'facts','{}'::jsonb))>65536 or pg_column_size(coalesce(p_observation->'source_snapshot','{}'::jsonb))>65536 then raise exception 'PAYLOAD_TOO_LARGE' using errcode='22023';end if;
 begin st:=(p_signal->>'signal_type')::public.technical_signal_type; lc:=coalesce(p_signal->>'lifecycle','ACTIVE')::public.technical_signal_lifecycle; sev:=coalesce(p_signal->>'severity','UNKNOWN')::public.technical_signal_severity; ef:=(p_signal->>'effective_at')::timestamptz; rec:=coalesce(nullif(p_observation->>'received_at','')::timestamptz,clock_timestamp()); exception when others then raise exception 'INVALID_SIGNAL_PAYLOAD' using errcode='22023';end;
 if char_length(trim(p_signal->>'canonical_key')) not between 3 and 300 or char_length(trim(p_signal->>'title')) not between 1 and 300 or char_length(coalesce(p_signal->>'summary',''))>5000 or (p_signal?'confidence' and (p_signal->>'confidence')::int not between 0 and 100) then raise exception 'INVALID_SIGNAL_PAYLOAD' using errcode='22023';end if;
 if char_length(trim(p_observation->>'source_system')) not between 2 and 80 or (p_observation->>'source_system')!~'^[A-Za-z0-9_.:-]+$' or char_length(trim(p_observation->>'source_record_key')) not between 1 and 300 or char_length(coalesce(p_observation->>'source_revision_key',''))>300 then raise exception 'INVALID_OBSERVATION_PAYLOAD' using errcode='22023';end if;
 sfp:=public.tech_signal_snapshot_fingerprint(st,p_signal->>'title',coalesce(p_signal->>'summary',''),lc,sev,nullif(p_signal->>'confidence','')::int,coalesce(p_signal->'facts','{}'::jsonb),nullif(p_signal->>'published_at','')::timestamptz,nullif(p_signal->>'observed_at','')::timestamptz,ef);
 ofp:=encode(extensions.digest(convert_to(jsonb_build_object('source_family',p_observation->>'source_family','source_system',lower(trim(p_observation->>'source_system')),'source_record_key',p_observation->>'source_record_key','source_revision_key',p_observation->>'source_revision_key','snapshot',coalesce(p_observation->'source_snapshot','{}'::jsonb),'snapshot_fingerprint',sfp)::text,'utf8'),'sha256'),'hex');
 okey:=public.tech_signal_observation_key(p_observation->>'source_system',p_observation->>'source_record_key',p_observation->>'source_revision_key',ofp);
 select * into obs from public.technical_signal_observations where owner_id=p_owner_id and observation_key=okey;
 if obs.id is not null then return jsonb_build_object('signal_id',obs.signal_id,'observation_id',obs.id,'revision_id',null,'signal_created',false,'observation_created',false,'revision_created',false,'duplicate_observation',true,'disposition',obs.disposition,'current_revision_number',(select current_revision_number from public.technical_signals where owner_id=p_owner_id and id=obs.signal_id),'entity_assertions_created',0);end if;
 select * into sig from public.technical_signals where owner_id=p_owner_id and signal_type=st and canonical_key=trim(p_signal->>'canonical_key') for update;
 if sig.id is null then insert into public.technical_signals(owner_id,signal_type,canonical_key,title,summary,lifecycle,severity,confidence,facts,published_at,observed_at,effective_at,first_seen_at,last_seen_at,current_snapshot_fingerprint) values(p_owner_id,st,trim(p_signal->>'canonical_key'),trim(p_signal->>'title'),coalesce(p_signal->>'summary',''),lc,sev,nullif(p_signal->>'confidence','')::int,coalesce(p_signal->'facts','{}'::jsonb),nullif(p_signal->>'published_at','')::timestamptz,nullif(p_signal->>'observed_at','')::timestamptz,ef,rec,rec,sfp) returning * into sig; created_sig:=true; disp:='CURRENT'; ck:='CREATED'; else if ef<sig.effective_at then disp:='STALE'; elsif ef=sig.effective_at and sfp<>sig.current_snapshot_fingerprint then disp:='CONFLICTING'; elsif sfp=sig.current_snapshot_fingerprint then disp:='SUPPORTING'; else disp:='CURRENT'; ck:=case when sig.lifecycle='RETRACTED' and lc='ACTIVE' then 'REACTIVATED' when lc='RETRACTED' then 'RETRACTED' when lc='SUPERSEDED' then 'SUPERSEDED' else 'UPDATED' end; end if; end if;
 insert into public.technical_signal_observations(owner_id,signal_id,source_family,source_system,source_record_key,source_revision_key,observation_key,source_url,source_title,source_published_at,source_modified_at,source_observed_at,received_at,effective_at,disposition,source_snapshot,source_fingerprint) values(p_owner_id,sig.id,(p_observation->>'source_family')::public.technical_signal_source_family,trim(p_observation->>'source_system'),trim(p_observation->>'source_record_key'),nullif(trim(coalesce(p_observation->>'source_revision_key','')),''),okey,public.tech_signal_validate_url(p_observation->>'source_url'),nullif(p_observation->>'source_title',''),nullif(p_observation->>'source_published_at','')::timestamptz,nullif(p_observation->>'source_modified_at','')::timestamptz,nullif(p_observation->>'source_observed_at','')::timestamptz,rec,coalesce(nullif(p_observation->>'effective_at','')::timestamptz,ef),disp,coalesce(p_observation->'source_snapshot','{}'::jsonb),ofp) returning * into obs; created_obs:=true;
 if disp='CURRENT' then rn:=sig.current_revision_number+1; insert into public.technical_signal_revisions(owner_id,signal_id,revision_number,change_kind,lifecycle,title,summary,severity,confidence,facts,published_at,observed_at,effective_at,snapshot_fingerprint,source_observation_id) values(p_owner_id,sig.id,rn,ck,lc,trim(p_signal->>'title'),coalesce(p_signal->>'summary',''),sev,nullif(p_signal->>'confidence','')::int,coalesce(p_signal->'facts','{}'::jsonb),nullif(p_signal->>'published_at','')::timestamptz,nullif(p_signal->>'observed_at','')::timestamptz,ef,sfp,obs.id) returning id into rev_id; created_rev:=true; update public.technical_signals set title=trim(p_signal->>'title'),summary=coalesce(p_signal->>'summary',''),lifecycle=lc,severity=sev,confidence=nullif(p_signal->>'confidence','')::int,facts=coalesce(p_signal->'facts','{}'::jsonb),published_at=nullif(p_signal->>'published_at','')::timestamptz,observed_at=nullif(p_signal->>'observed_at','')::timestamptz,effective_at=ef,last_seen_at=greatest(last_seen_at,rec),first_seen_at=least(first_seen_at,rec),current_revision_number=rn,current_revision_id=rev_id,current_snapshot_fingerprint=sfp where id=sig.id returning * into sig; elsif disp='SUPPORTING' then update public.technical_signals set first_seen_at=least(first_seen_at,rec),last_seen_at=greatest(last_seen_at,rec) where id=sig.id returning * into sig; end if;
 for item in select * from jsonb_array_elements(p_entity_assertions) loop
  if (item->>'assertion_basis') not in('PROVIDER_ASSERTED','SYSTEM_EXTRACTED') then raise exception 'INVALID_ASSERTION_BASIS' using errcode='22023';end if;
  if (item->>'entity_kind')='CVE' then item:=jsonb_set(item,'{normalized_value}',to_jsonb(public.tech_signal_normalize_cve(item->>'display_value'))); elsif (item->>'entity_kind')='ATTACK_TECHNIQUE' then item:=jsonb_set(item,'{normalized_value}',to_jsonb(public.tech_signal_normalize_attack_id(item->>'display_value'))); elsif (item->>'entity_kind')='INDICATOR' then item:=jsonb_set(item,'{normalized_value}',to_jsonb(public.intel_profile_validate_indicator(item->>'display_value',(item->>'indicator_type')::public.indicator_type))); else item:=jsonb_set(item,'{normalized_value}',to_jsonb(regexp_replace(trim(coalesce(item->>'normalized_value',item->>'display_value')),'\s+',' ','g'))); end if;
  insert into public.technical_signal_entity_assertions(owner_id,signal_id,source_observation_id,entity_kind,display_value,normalized_value,semantic_role,assertion_basis,confidence,indicator_type,existing_entity_type,existing_entity_id) values(p_owner_id,sig.id,obs.id,(item->>'entity_kind')::public.technical_signal_entity_kind,trim(item->>'display_value'),item->>'normalized_value',(item->>'semantic_role')::public.technical_signal_entity_role,(item->>'assertion_basis')::public.technical_signal_assertion_basis,nullif(item->>'confidence','')::int,nullif(item->>'indicator_type','')::public.indicator_type,nullif(item->>'existing_entity_type',''),nullif(item->>'existing_entity_id','')::uuid) on conflict do nothing; if found then ent_count:=ent_count+1;end if;
 end loop;
 return jsonb_build_object('signal_id',sig.id,'observation_id',obs.id,'revision_id',rev_id,'signal_created',created_sig,'observation_created',created_obs,'revision_created',created_rev,'duplicate_observation',false,'disposition',disp,'current_revision_number',sig.current_revision_number,'entity_assertions_created',ent_count);
end$$;

alter table public.technical_signals enable row level security; alter table public.technical_signal_observations enable row level security; alter table public.technical_signal_revisions enable row level security; alter table public.technical_signal_entity_assertions enable row level security;
create policy technical_signals_owner_select on public.technical_signals for select to authenticated using(owner_id=auth.uid());
create policy technical_signal_observations_owner_select on public.technical_signal_observations for select to authenticated using(owner_id=auth.uid());
create policy technical_signal_revisions_owner_select on public.technical_signal_revisions for select to authenticated using(owner_id=auth.uid());
create policy technical_signal_entity_assertions_owner_select on public.technical_signal_entity_assertions for select to authenticated using(owner_id=auth.uid());
revoke all on public.technical_signals,public.technical_signal_observations,public.technical_signal_revisions,public.technical_signal_entity_assertions from public,anon,authenticated;
grant select on public.technical_signals,public.technical_signal_observations,public.technical_signal_revisions,public.technical_signal_entity_assertions to authenticated;
revoke all on function public.record_technical_signal(uuid,jsonb,jsonb,jsonb) from public,anon,authenticated; grant execute on function public.record_technical_signal(uuid,jsonb,jsonb,jsonb) to service_role;
do $$begin if has_function_privilege('authenticated','public.record_technical_signal(uuid,jsonb,jsonb,jsonb)','EXECUTE') or not has_function_privilege('service_role','public.record_technical_signal(uuid,jsonb,jsonb,jsonb)','EXECUTE') then raise exception 'technical signal RPC ACL invalid';end if;if has_table_privilege('authenticated','public.technical_signal_observations','INSERT') or has_table_privilege('authenticated','public.technical_signal_revisions','UPDATE') or has_table_privilege('authenticated','public.technical_signal_entity_assertions','DELETE') then raise exception 'technical signal table ACL too broad';end if;end$$;
