-- Phase 2.2C.3: manual, read-only AlienVault OTX subscribed-Pulse connector.
begin;
alter table public.ioc_provider_credentials drop constraint ioc_provider_credentials_provider_key_check;
alter table public.ioc_provider_credentials add constraint ioc_provider_credentials_provider_key_check check(provider_key in('THREATFOX','ALIENVAULT_OTX'));
create table public.otx_connection_settings(
 owner_id uuid not null,provider_connection_id uuid not null,bootstrap_lookback_days integer not null default 30 check(bootstrap_lookback_days in(30,90,180,365)),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,provider_connection_id),
 foreign key(owner_id,provider_connection_id) references public.ioc_provider_connections(owner_id,id) on delete cascade
);
create function public.configure_otx_connection(p_owner_id uuid,p_connection_id uuid,p_ciphertext_b64 text,p_iv_b64 text,p_auth_tag_b64 text,p_key_version smallint,p_bootstrap_lookback_days integer)
returns uuid language plpgsql security definer set search_path='' as $$begin
 if p_bootstrap_lookback_days not in(30,90,180,365)or char_length(p_ciphertext_b64)not between 4 and 2048 or char_length(p_iv_b64)not between 16 and 32 or char_length(p_auth_tag_b64)not between 20 and 32 or p_key_version not between 1 and 32767 or not exists(select 1 from auth.users where id=p_owner_id)then raise exception 'OTX_CONFIGURATION_INVALID';end if;
 if exists(select 1 from public.ioc_provider_connections where id=p_connection_id and(owner_id<>p_owner_id or provider_key<>'ALIENVAULT_OTX' or archived_at is not null))then raise exception 'CONNECTION_UNAVAILABLE';end if;
 insert into public.ioc_provider_connections(id,owner_id,provider_key,display_name,enabled,scheduler_enabled,sync_interval_minutes,next_scheduled_sync_at,created_by,last_checked_at,health_status)values(p_connection_id,p_owner_id,'ALIENVAULT_OTX','AlienVault OTX',true,false,15,null,p_owner_id,now(),'HEALTHY')on conflict(owner_id,provider_key)do update set enabled=true,scheduler_enabled=false,next_scheduled_sync_at=null,last_checked_at=now(),health_status='HEALTHY',last_error_code=null,last_error_message=null,updated_at=now()returning id into p_connection_id;
 insert into public.ioc_provider_credentials(owner_id,provider_connection_id,provider_key,ciphertext_b64,iv_b64,auth_tag_b64,key_version)values(p_owner_id,p_connection_id,'ALIENVAULT_OTX',p_ciphertext_b64,p_iv_b64,p_auth_tag_b64,p_key_version)on conflict(owner_id,provider_connection_id)do update set provider_key='ALIENVAULT_OTX',ciphertext_b64=excluded.ciphertext_b64,iv_b64=excluded.iv_b64,auth_tag_b64=excluded.auth_tag_b64,key_version=excluded.key_version,updated_at=now(),rotated_at=now();
 insert into public.otx_connection_settings(owner_id,provider_connection_id,bootstrap_lookback_days)values(p_owner_id,p_connection_id,p_bootstrap_lookback_days)on conflict(owner_id,provider_connection_id)do update set bootstrap_lookback_days=excluded.bootstrap_lookback_days,updated_at=now();return p_connection_id;end$$;
create function public.disconnect_otx_credential(p_owner_id uuid,p_connection_id uuid)returns boolean language plpgsql security definer set search_path='' as $$begin
 if not exists(select 1 from public.ioc_provider_connections where owner_id=p_owner_id and id=p_connection_id and provider_key='ALIENVAULT_OTX'and archived_at is null)then raise exception 'CONNECTION_UNAVAILABLE';end if;
 delete from public.ioc_provider_credentials where owner_id=p_owner_id and provider_connection_id=p_connection_id and provider_key='ALIENVAULT_OTX';update public.ioc_provider_connections set enabled=false,scheduler_enabled=false,next_scheduled_sync_at=null,health_status='UNKNOWN',updated_at=now()where owner_id=p_owner_id and id=p_connection_id;return true;end$$;
create function public.update_otx_settings(p_owner_id uuid,p_connection_id uuid,p_bootstrap_lookback_days integer)returns boolean language plpgsql security definer set search_path='' as $$begin
 if p_bootstrap_lookback_days not in(30,90,180,365)or not exists(select 1 from public.ioc_provider_connections where owner_id=p_owner_id and id=p_connection_id and provider_key='ALIENVAULT_OTX'and archived_at is null)then raise exception 'OTX_CONFIGURATION_INVALID';end if;
 update public.otx_connection_settings set bootstrap_lookback_days=p_bootstrap_lookback_days,updated_at=now()where owner_id=p_owner_id and provider_connection_id=p_connection_id;update public.ioc_provider_connections set scheduler_enabled=false,next_scheduled_sync_at=null,updated_at=now()where owner_id=p_owner_id and id=p_connection_id;return true;end$$;
create or replace function public.fail_ioc_ingestion(p_owner_id uuid,p_connection_id uuid,p_run_id uuid,p_lease_token uuid,p_error_code text,p_error_message text)returns public.ioc_ingestion_runs language plpgsql security definer set search_path='' as $$declare r public.ioc_ingestion_runs;c public.ioc_provider_connections;delay_minutes integer;begin
 update public.ioc_ingestion_runs ir set status='FAILED',completed_at=now(),error_code=left(p_error_code,100),error_message=left(p_error_message,500)where id=p_run_id and owner_id=p_owner_id and provider_connection_id=p_connection_id and status='RUNNING'and lease_token_hash=encode(public.digest(p_lease_token::text,'sha256'),'hex')returning * into r;if r.id is null then raise exception 'STALE_INGESTION_LEASE';end if;
 select * into c from public.ioc_provider_connections where id=p_connection_id and owner_id=p_owner_id for update;delay_minutes:=least(1440,case when p_error_code in('THREATFOX_RATE_LIMITED','OTX_RATE_LIMITED')then 30 else greatest(30,power(2,least(c.consecutive_failures,10))::integer*15)end);
 update public.ioc_provider_connections set lease_token_hash=null,lease_run_id=null,lease_expires_at=null,health_status=case when p_error_code in('THREATFOX_AUTH_FAILED','OTX_AUTH_FAILED')then'FAILED'::public.ioc_connection_health else'DEGRADED'::public.ioc_connection_health end,consecutive_failures=consecutive_failures+1,last_error_code=r.error_code,last_error_message=r.error_message,scheduler_enabled=case when provider_key='ALIENVAULT_OTX'or p_error_code in('THREATFOX_AUTH_FAILED','OTX_AUTH_FAILED')then false else scheduler_enabled end,next_scheduled_sync_at=case when provider_key='ALIENVAULT_OTX'or p_error_code in('THREATFOX_AUTH_FAILED','OTX_AUTH_FAILED')then null else now()+make_interval(mins=>delay_minutes)end,updated_at=now()where id=p_connection_id and owner_id=p_owner_id and lease_run_id=p_run_id and lease_token_hash=r.lease_token_hash;if not found then raise exception 'STALE_INGESTION_LEASE';end if;return r;end$$;
alter table public.otx_connection_settings enable row level security;
create policy otx_settings_read on public.otx_connection_settings for select to authenticated using(owner_id=auth.uid());
grant select on public.otx_connection_settings to authenticated,service_role;revoke insert,update,delete on public.otx_connection_settings from public,anon,authenticated;
revoke all on function public.configure_otx_connection(uuid,uuid,text,text,text,smallint,integer),public.disconnect_otx_credential(uuid,uuid),public.update_otx_settings(uuid,uuid,integer)from public,anon,authenticated;
grant execute on function public.configure_otx_connection(uuid,uuid,text,text,text,smallint,integer),public.disconnect_otx_credential(uuid,uuid),public.update_otx_settings(uuid,uuid,integer)to service_role;
do $$declare definition text;begin
 select pg_get_constraintdef(oid)into definition from pg_constraint where conrelid='public.ioc_provider_credentials'::regclass and conname='ioc_provider_credentials_provider_key_check';
 if definition is null or definition not like '%THREATFOX%'or definition not like '%ALIENVAULT_OTX%'then raise exception 'credential provider constraint missing';end if;
 if has_table_privilege('authenticated','public.ioc_provider_credentials','SELECT')or has_table_privilege('authenticated','public.ioc_provider_credentials','INSERT')or has_table_privilege('authenticated','public.ioc_provider_credentials','UPDATE')or has_table_privilege('authenticated','public.ioc_provider_credentials','DELETE')then raise exception 'credential ACL broadened';end if;
 if has_function_privilege('authenticated','public.configure_otx_connection(uuid,uuid,text,text,text,smallint,integer)','EXECUTE')or has_function_privilege('authenticated','public.disconnect_otx_credential(uuid,uuid)','EXECUTE')or has_function_privilege('authenticated','public.update_otx_settings(uuid,uuid,integer)','EXECUTE')then raise exception 'trusted OTX ACL broadened';end if;
 if not has_function_privilege('service_role','public.configure_otx_connection(uuid,uuid,text,text,text,smallint,integer)','EXECUTE')or not has_function_privilege('service_role','public.disconnect_otx_credential(uuid,uuid)','EXECUTE')or not has_function_privilege('service_role','public.update_otx_settings(uuid,uuid,integer)','EXECUTE')then raise exception 'service role OTX ACL missing';end if;
 if not(select relrowsecurity from pg_class where oid='public.otx_connection_settings'::regclass)or(select count(*)from pg_policies where schemaname='public'and tablename='otx_connection_settings'and policyname='otx_settings_read')<>1 then raise exception 'OTX settings RLS missing';end if;
end$$;
commit;
