do $$ begin create type public.technical_signal_type as enum ('VULNERABILITY_CHANGE','ACTIVE_EXPLOITATION','TECHNICAL_ADVISORY','IOC_OBSERVATION','MALWARE_ACTIVITY','CAMPAIGN_REPORT','INFRASTRUCTURE_CHANGE','TTP_UPDATE','PROVIDER_ALERT','TECHNICAL_REPORT'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_lifecycle as enum ('ACTIVE','RETRACTED','SUPERSEDED','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_severity as enum ('UNKNOWN','INFO','LOW','MEDIUM','HIGH','CRITICAL'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_change_kind as enum ('CREATED','UPDATED','RETRACTED','REACTIVATED','SUPERSEDED'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_source_family as enum ('IOC_PROVIDER','FEED','VULNERABILITY','ADVISORY','STIX','MANUAL_TEST','OTHER'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_disposition as enum ('CURRENT','SUPPORTING','STALE','CONFLICTING'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_entity_kind as enum ('CVE','INDICATOR','THREAT_ACTOR','MALWARE','CAMPAIGN','INFRASTRUCTURE','ATTACK_TECHNIQUE','VENDOR','PRODUCT','SECTOR','COUNTRY','REGION','TAG'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_entity_role as enum ('SUBJECT','AFFECTS','EXPLOITS','USES','ATTRIBUTED_TO','TARGETS','LOCATED_IN','RELATED_TO','MENTIONS'); exception when duplicate_object then null; end $$;
do $$ begin create type public.technical_signal_assertion_basis as enum ('PROVIDER_ASSERTED','SYSTEM_EXTRACTED','AI_SUGGESTED','ANALYST_CONFIRMED'); exception when duplicate_object then null; end $$;

create table public.technical_signals(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade,
 signal_type public.technical_signal_type not null, canonical_key text not null check(char_length(trim(canonical_key)) between 1 and 700), title text not null check(char_length(trim(title)) between 1 and 500), summary text not null default '' check(char_length(summary)<=4000), lifecycle public.technical_signal_lifecycle not null, severity public.technical_signal_severity not null, confidence smallint check(confidence between 0 and 100), facts jsonb not null default '{}' check(jsonb_typeof(facts)='object' and pg_column_size(facts)<=65536),
 published_at timestamptz, observed_at timestamptz, effective_at timestamptz not null, first_seen_at timestamptz not null, last_seen_at timestamptz not null, current_revision_number integer not null check(current_revision_number>0), superseded_by_signal_id uuid,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(owner_id,id), unique(owner_id,signal_type,canonical_key), check(first_seen_at<=last_seen_at), check(superseded_by_signal_id is null or superseded_by_signal_id<>id), foreign key(owner_id,superseded_by_signal_id) references public.technical_signals(owner_id,id)
);
create trigger technical_signals_set_updated_at before update on public.technical_signals for each row execute function public.set_updated_at();

create table public.technical_signal_observations(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, signal_id uuid not null,
 source_family public.technical_signal_source_family not null, source_system text not null check(char_length(trim(source_system)) between 1 and 200), source_record_key text not null check(char_length(trim(source_record_key)) between 1 and 200), source_revision_key text check(char_length(trim(source_revision_key)) between 1 and 200), observation_key text not null check(observation_key~'^[a-f0-9]{64}$'), source_url text check(char_length(source_url)<=2048 and source_url~*'^https?://[^[:space:]]+$' and substring(source_url from '^https?://([^/?#]+)') not like '%@%'), source_title text check(char_length(source_title)<=500), source_published_at timestamptz, source_modified_at timestamptz, source_observed_at timestamptz, received_at timestamptz not null, effective_at timestamptz not null, disposition public.technical_signal_disposition not null, source_snapshot jsonb not null check(jsonb_typeof(source_snapshot)='object' and pg_column_size(source_snapshot)<=65536), source_fingerprint text not null check(source_fingerprint~'^[a-f0-9]{64}$'), created_at timestamptz not null default now(),
 unique(owner_id,id), unique(owner_id,observation_key), foreign key(owner_id,signal_id) references public.technical_signals(owner_id,id) on delete cascade
);
create table public.technical_signal_revisions(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, signal_id uuid not null, revision_number integer not null check(revision_number>0), change_kind public.technical_signal_change_kind not null, lifecycle public.technical_signal_lifecycle not null, title text not null check(char_length(title) between 1 and 500), summary text not null check(char_length(summary)<=4000), severity public.technical_signal_severity not null, confidence smallint check(confidence between 0 and 100), facts jsonb not null check(jsonb_typeof(facts)='object' and pg_column_size(facts)<=65536), published_at timestamptz, observed_at timestamptz, effective_at timestamptz not null, snapshot_fingerprint text not null check(snapshot_fingerprint~'^[a-f0-9]{64}$'), source_observation_id uuid not null, created_at timestamptz not null default now(),
 unique(owner_id,id), unique(owner_id,signal_id,revision_number), foreign key(owner_id,signal_id) references public.technical_signals(owner_id,id) on delete cascade, foreign key(owner_id,source_observation_id) references public.technical_signal_observations(owner_id,id)
);
create table public.technical_signal_entity_assertions(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, signal_id uuid not null, source_observation_id uuid not null, entity_kind public.technical_signal_entity_kind not null, display_value text not null check(char_length(trim(display_value)) between 1 and 500), normalized_value text not null check(char_length(trim(normalized_value)) between 1 and 500), semantic_role public.technical_signal_entity_role not null, assertion_basis public.technical_signal_assertion_basis not null, confidence smallint check(confidence between 0 and 100), indicator_type public.indicator_type, source_entity_type text check(char_length(source_entity_type)<=80), source_entity_id uuid, created_at timestamptz not null default now(),
 unique(owner_id,id), foreign key(owner_id,signal_id) references public.technical_signals(owner_id,id) on delete cascade, foreign key(owner_id,source_observation_id) references public.technical_signal_observations(owner_id,id), check((entity_kind='INDICATOR')=(indicator_type is not null))
);
create index technical_signals_owner_updated_idx on public.technical_signals(owner_id,updated_at desc);
create index technical_signal_observations_signal_idx on public.technical_signal_observations(owner_id,signal_id,effective_at desc);
create index technical_signal_revisions_signal_idx on public.technical_signal_revisions(owner_id,signal_id,revision_number desc);
create index technical_signal_assertions_signal_idx on public.technical_signal_entity_assertions(owner_id,signal_id);

create function public.technical_signal_reject_change() returns trigger language plpgsql set search_path='' as $$begin raise exception 'APPEND_ONLY' using errcode='55000';end$$;
create trigger technical_signal_observations_append_only before update or delete on public.technical_signal_observations for each row execute function public.technical_signal_reject_change();
create trigger technical_signal_revisions_append_only before update or delete on public.technical_signal_revisions for each row execute function public.technical_signal_reject_change();
create trigger technical_signal_assertions_append_only before update or delete on public.technical_signal_entity_assertions for each row execute function public.technical_signal_reject_change();

alter table public.technical_signals enable row level security; alter table public.technical_signal_observations enable row level security; alter table public.technical_signal_revisions enable row level security; alter table public.technical_signal_entity_assertions enable row level security;
revoke all on public.technical_signals,public.technical_signal_observations,public.technical_signal_revisions,public.technical_signal_entity_assertions from anon,authenticated;
grant select on public.technical_signals,public.technical_signal_observations,public.technical_signal_revisions,public.technical_signal_entity_assertions to authenticated;
create policy technical_signals_select_own on public.technical_signals for select to authenticated using(auth.uid()=owner_id);
create policy technical_signal_observations_select_own on public.technical_signal_observations for select to authenticated using(auth.uid()=owner_id);
create policy technical_signal_revisions_select_own on public.technical_signal_revisions for select to authenticated using(auth.uid()=owner_id);
create policy technical_signal_assertions_select_own on public.technical_signal_entity_assertions for select to authenticated using(auth.uid()=owner_id);

create function public.record_technical_signal(p_actor uuid,p_signal jsonb,p_observation jsonb,p_entity_assertions jsonb default '[]') returns jsonb language plpgsql security definer set search_path='' as $$
declare s public.technical_signals; o public.technical_signal_observations; rid uuid; sf text; ofp text; okey text; disp public.technical_signal_disposition; rev int; ck public.technical_signal_change_kind; created_signal boolean:=false; created_obs boolean:=false; created_rev boolean:=false; assertion_count int:=0; a jsonb; norm text; it public.indicator_type;
begin
 if p_actor is null or not exists(select 1 from auth.users where id=p_actor) or jsonb_typeof(p_signal)<>'object' or jsonb_typeof(p_observation)<>'object' or jsonb_typeof(p_entity_assertions)<>'array' or jsonb_array_length(p_entity_assertions)>100 then raise exception 'INVALID_TECHNICAL_SIGNAL' using errcode='22023';end if;
 if char_length(trim(p_signal->>'canonicalKey')) not between 1 and 700 or char_length(trim(p_signal->>'title')) not between 1 and 500 or char_length(coalesce(p_signal->>'summary',''))>4000 or pg_column_size(coalesce(p_signal->'facts','{}'))>65536 then raise exception 'INVALID_TECHNICAL_SIGNAL' using errcode='22023';end if;
 if char_length(trim(p_observation->>'sourceSystem')) not between 1 and 200 or char_length(trim(p_observation->>'sourceRecordKey')) not between 1 and 200 or pg_column_size(coalesce(p_observation->'sourceSnapshot','{}'))>65536 then raise exception 'INVALID_OBSERVATION' using errcode='22023';end if;
 if p_observation->>'sourceUrl' is not null and ((p_observation->>'sourceUrl')!~*'^https?://[^[:space:]]+$' or substring(p_observation->>'sourceUrl' from '^https?://([^/?#]+)') like '%@%' or char_length(p_observation->>'sourceUrl')>2048) then raise exception 'INVALID_SOURCE_URL' using errcode='22023';end if;
 sf:=encode(extensions.digest(jsonb_build_object('lifecycle',p_signal->>'lifecycle','title',trim(p_signal->>'title'),'summary',coalesce(p_signal->>'summary',''),'severity',p_signal->>'severity','confidence',p_signal->'confidence','facts',coalesce(p_signal->'facts','{}'))::text,'sha256'),'hex');
 ofp:=encode(extensions.digest(coalesce(p_observation->'sourceSnapshot','{}')::text,'sha256'),'hex');
 okey:=encode(extensions.digest(jsonb_build_object('source_system',lower(trim(p_observation->>'sourceSystem')),'record_key',trim(p_observation->>'sourceRecordKey'),'revision_key',nullif(trim(coalesce(p_observation->>'sourceRevisionKey','')),''),'fingerprint',ofp)::text,'sha256'),'hex');
 select * into o from public.technical_signal_observations where owner_id=p_actor and observation_key=okey;
 if o.id is not null then select * into s from public.technical_signals where owner_id=p_actor and id=o.signal_id; return jsonb_build_object('signal_id',s.id,'observation_id',o.id,'revision_id',null,'signal_created',false,'observation_created',false,'revision_created',false,'duplicate_observation',true,'disposition',o.disposition,'current_revision_number',s.current_revision_number,'entity_assertions_created',0);end if;
 select * into s from public.technical_signals where owner_id=p_actor and signal_type=(p_signal->>'signalType')::public.technical_signal_type and canonical_key=trim(p_signal->>'canonicalKey') for update;
 if s.id is null then
  insert into public.technical_signals(owner_id,signal_type,canonical_key,title,summary,lifecycle,severity,confidence,facts,published_at,observed_at,effective_at,first_seen_at,last_seen_at,current_revision_number,superseded_by_signal_id) values(p_actor,(p_signal->>'signalType')::public.technical_signal_type,trim(p_signal->>'canonicalKey'),trim(p_signal->>'title'),coalesce(p_signal->>'summary',''),(p_signal->>'lifecycle')::public.technical_signal_lifecycle,(p_signal->>'severity')::public.technical_signal_severity,(p_signal->>'confidence')::smallint,coalesce(p_signal->'facts','{}'),(p_signal->>'publishedAt')::timestamptz,(p_signal->>'observedAt')::timestamptz,(p_signal->>'effectiveAt')::timestamptz,(p_observation->>'receivedAt')::timestamptz,(p_observation->>'receivedAt')::timestamptz,1,(p_signal->>'supersededBySignalId')::uuid) returning * into s; created_signal:=true;disp:='CURRENT';rev:=1;ck:='CREATED';
 else
  select snapshot_fingerprint into ofp from public.technical_signal_revisions where owner_id=p_actor and signal_id=s.id and revision_number=s.current_revision_number;
  if (p_observation->>'effectiveAt')::timestamptz<s.effective_at then disp:='STALE';elsif (p_observation->>'effectiveAt')::timestamptz=s.effective_at and sf<>ofp then disp:='CONFLICTING';elsif sf=ofp then disp:='SUPPORTING';else disp:='CURRENT';rev:=s.current_revision_number+1;ck:=case when (p_signal->>'lifecycle')='RETRACTED' then 'RETRACTED'::public.technical_signal_change_kind when s.lifecycle='RETRACTED' and (p_signal->>'lifecycle')='ACTIVE' then 'REACTIVATED'::public.technical_signal_change_kind when (p_signal->>'lifecycle')='SUPERSEDED' then 'SUPERSEDED'::public.technical_signal_change_kind else 'UPDATED'::public.technical_signal_change_kind end;end if;
 end if;
 insert into public.technical_signal_observations(owner_id,signal_id,source_family,source_system,source_record_key,source_revision_key,observation_key,source_url,source_title,source_published_at,source_modified_at,source_observed_at,received_at,effective_at,disposition,source_snapshot,source_fingerprint) values(p_actor,s.id,(p_observation->>'sourceFamily')::public.technical_signal_source_family,trim(p_observation->>'sourceSystem'),trim(p_observation->>'sourceRecordKey'),nullif(trim(coalesce(p_observation->>'sourceRevisionKey','')),''),okey,p_observation->>'sourceUrl',p_observation->>'sourceTitle',(p_observation->>'sourcePublishedAt')::timestamptz,(p_observation->>'sourceModifiedAt')::timestamptz,(p_observation->>'sourceObservedAt')::timestamptz,(p_observation->>'receivedAt')::timestamptz,(p_observation->>'effectiveAt')::timestamptz,disp,coalesce(p_observation->'sourceSnapshot','{}'),case when created_signal then ofp else encode(extensions.digest(coalesce(p_observation->'sourceSnapshot','{}')::text,'sha256'),'hex') end) returning * into o;created_obs:=true;
 if disp='CURRENT' then
  if not created_signal then update public.technical_signals set title=trim(p_signal->>'title'),summary=coalesce(p_signal->>'summary',''),lifecycle=(p_signal->>'lifecycle')::public.technical_signal_lifecycle,severity=(p_signal->>'severity')::public.technical_signal_severity,confidence=(p_signal->>'confidence')::smallint,facts=coalesce(p_signal->'facts','{}'),published_at=(p_signal->>'publishedAt')::timestamptz,observed_at=(p_signal->>'observedAt')::timestamptz,effective_at=(p_signal->>'effectiveAt')::timestamptz,last_seen_at=greatest(last_seen_at,(p_observation->>'receivedAt')::timestamptz),first_seen_at=least(first_seen_at,(p_observation->>'receivedAt')::timestamptz),current_revision_number=rev,superseded_by_signal_id=(p_signal->>'supersededBySignalId')::uuid where id=s.id returning * into s;end if;
  insert into public.technical_signal_revisions(owner_id,signal_id,revision_number,change_kind,lifecycle,title,summary,severity,confidence,facts,published_at,observed_at,effective_at,snapshot_fingerprint,source_observation_id) values(p_actor,s.id,rev,ck,s.lifecycle,s.title,s.summary,s.severity,s.confidence,s.facts,s.published_at,s.observed_at,s.effective_at,sf,o.id) returning id into rid;created_rev:=true;
 elsif disp='SUPPORTING' then update public.technical_signals set first_seen_at=least(first_seen_at,(p_observation->>'receivedAt')::timestamptz),last_seen_at=greatest(last_seen_at,(p_observation->>'receivedAt')::timestamptz) where id=s.id returning * into s;
 end if;
 for a in select value from jsonb_array_elements(p_entity_assertions) loop
  if (a->>'assertionBasis') not in('PROVIDER_ASSERTED','SYSTEM_EXTRACTED') or char_length(trim(a->>'displayValue')) not between 1 and 500 or char_length(trim(a->>'normalizedValue')) not between 1 and 500 then raise exception 'INVALID_ENTITY_ASSERTION' using errcode='22023';end if;
  it:=(a->>'indicatorType')::public.indicator_type;norm:=trim(a->>'normalizedValue');if (a->>'entityKind')='INDICATOR' then norm:=public.intel_profile_validate_indicator(norm,it);elsif it is not null then raise exception 'INVALID_ENTITY_ASSERTION' using errcode='22023';end if;
  insert into public.technical_signal_entity_assertions(owner_id,signal_id,source_observation_id,entity_kind,display_value,normalized_value,semantic_role,assertion_basis,confidence,indicator_type,source_entity_type,source_entity_id) values(p_actor,s.id,o.id,(a->>'entityKind')::public.technical_signal_entity_kind,trim(a->>'displayValue'),norm,(a->>'semanticRole')::public.technical_signal_entity_role,(a->>'assertionBasis')::public.technical_signal_assertion_basis,(a->>'confidence')::smallint,it,a->>'sourceEntityType',(a->>'sourceEntityId')::uuid);assertion_count:=assertion_count+1;
 end loop;
 return jsonb_build_object('signal_id',s.id,'observation_id',o.id,'revision_id',rid,'signal_created',created_signal,'observation_created',created_obs,'revision_created',created_rev,'duplicate_observation',false,'disposition',disp,'current_revision_number',s.current_revision_number,'entity_assertions_created',assertion_count);
exception when invalid_text_representation or check_violation or string_data_right_truncation or not_null_violation then raise exception 'INVALID_TECHNICAL_SIGNAL' using errcode='22023';end$$;

revoke all on function public.technical_signal_reject_change() from public,anon,authenticated,service_role;
revoke all on function public.record_technical_signal(uuid,jsonb,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.record_technical_signal(uuid,jsonb,jsonb,jsonb) to service_role;
do $$begin if has_table_privilege('authenticated','public.technical_signals','INSERT') or has_table_privilege('authenticated','public.technical_signal_observations','UPDATE') then raise exception 'Technical Signal ACL too broad';end if;if has_function_privilege('authenticated','public.record_technical_signal(uuid,jsonb,jsonb,jsonb)','EXECUTE') or not has_function_privilege('service_role','public.record_technical_signal(uuid,jsonb,jsonb,jsonb)','EXECUTE') then raise exception 'Technical Signal RPC ACL invalid';end if;end$$;
