-- Phase 2.2A: owner-scoped external research feed collection. Raw XML is never persisted.
create type public.research_feed_type as enum ('UNKNOWN','RSS','ATOM');
create type public.research_feed_health as enum ('NEVER_FETCHED','HEALTHY','DEGRADED','ERROR');
create type public.research_feed_run_status as enum ('RUNNING','SUCCEEDED','NOT_MODIFIED','FAILED');
create type public.research_fingerprint_type as enum ('URL','CONTENT');

create table public.research_feed_sources (
 id uuid primary key default gen_random_uuid(), project_id uuid not null, name text not null check(char_length(name) between 1 and 240), description text not null default '' check(char_length(description)<=10000), configured_url text not null check(char_length(configured_url)<=4096), configured_url_hash text not null check(configured_url_hash~'^[0-9a-f]{64}$'), detected_feed_type public.research_feed_type not null default 'UNKNOWN', enabled boolean not null default true, health_status public.research_feed_health not null default 'NEVER_FETCHED', last_checked_at timestamptz,last_success_at timestamptz,last_content_change_at timestamptz,last_http_status integer check(last_http_status between 100 and 599),last_final_url text check(char_length(last_final_url)<=4096),etag text check(char_length(etag)<=512 and etag!~E'[\r\n]'),last_modified text check(char_length(last_modified)<=128 and last_modified!~E'[\r\n]'),consecutive_failures integer not null default 0 check(consecutive_failures>=0),next_eligible_fetch_at timestamptz,last_error_code text check(char_length(last_error_code)<=64),last_error_message text check(char_length(last_error_message)<=500),fetch_lease_token uuid,fetch_lease_expires_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,
 foreign key(project_id) references public.projects(id) on delete cascade, unique(project_id,id), unique(project_id,configured_url_hash), check((fetch_lease_token is null)=(fetch_lease_expires_at is null))
);
create table public.research_feed_fetch_runs (
 id uuid primary key default gen_random_uuid(),project_id uuid not null,feed_source_id uuid not null,status public.research_feed_run_status not null default 'RUNNING',started_at timestamptz not null default now(),completed_at timestamptz,duration_ms integer check(duration_ms>=0),request_url_hash text not null check(request_url_hash~'^[0-9a-f]{64}$'),final_url text check(char_length(final_url)<=4096),http_status integer check(http_status between 100 and 599),response_bytes integer check(response_bytes>=0),items_seen integer not null default 0,items_created integer not null default 0,items_updated integer not null default 0,items_deduplicated integer not null default 0,items_skipped integer not null default 0,error_code text check(char_length(error_code)<=64),error_message text check(char_length(error_message)<=500),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(project_id,id),foreign key(project_id,feed_source_id) references public.research_feed_sources(project_id,id) on delete cascade,check((status='RUNNING')=(completed_at is null))
);
create table public.research_items (
 id uuid primary key default gen_random_uuid(),project_id uuid not null,canonical_url text check(char_length(canonical_url)<=4096),title text check(char_length(title)<=500),summary_text text check(char_length(summary_text)<=20000),content_text text check(char_length(content_text)<=100000),author_name text check(char_length(author_name)<=500),published_at timestamptz,source_updated_at timestamptz,language text check(char_length(language)<=50),categories text[] not null default '{}',first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),content_changed_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,id),foreign key(project_id) references public.projects(id) on delete cascade,check(cardinality(categories)<=50),check(title is not null or summary_text is not null or content_text is not null)
);
create table public.research_item_fingerprints(id uuid primary key default gen_random_uuid(),project_id uuid not null,research_item_id uuid not null,fingerprint_type public.research_fingerprint_type not null,fingerprint_hash text not null check(fingerprint_hash~'^[0-9a-f]{64}$'),created_at timestamptz not null default now(),foreign key(project_id,research_item_id) references public.research_items(project_id,id) on delete cascade,unique(project_id,fingerprint_type,fingerprint_hash));
create table public.research_feed_item_observations(id uuid primary key default gen_random_uuid(),project_id uuid not null,feed_source_id uuid not null,research_item_id uuid not null,fetch_run_id uuid not null,external_item_id text check(char_length(external_item_id)<=1000),observed_url text check(char_length(observed_url)<=4096),source_published_at timestamptz,first_seen_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),observation_count integer not null default 1 check(observation_count>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(project_id,feed_source_id) references public.research_feed_sources(project_id,id),foreign key(project_id,research_item_id) references public.research_items(project_id,id),foreign key(project_id,fetch_run_id) references public.research_feed_fetch_runs(project_id,id),unique(project_id,feed_source_id,research_item_id));

create function public.claim_research_feed_fetch(p_project_id uuid,p_feed_source_id uuid) returns public.research_feed_fetch_runs language plpgsql security definer set search_path='' as $$ declare s public.research_feed_sources;r public.research_feed_fetch_runs;t uuid:=gen_random_uuid();begin
 if auth.uid() is null or not exists(select 1 from public.projects where id=p_project_id and owner_id=auth.uid()) then raise exception 'not_found' using errcode='P0002';end if;
 select * into s from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;if s.id is null then raise exception 'not_found' using errcode='P0002';end if;if s.archived_at is not null then raise exception 'FEED_ARCHIVED';end if;if not s.enabled then raise exception 'FEED_DISABLED';end if;if s.fetch_lease_expires_at>clock_timestamp() then raise exception 'FETCH_ALREADY_RUNNING';end if;if s.next_eligible_fetch_at>clock_timestamp() then raise exception 'FETCH_COOLDOWN';end if;
 update public.research_feed_sources set fetch_lease_token=t,fetch_lease_expires_at=clock_timestamp()+interval '2 minutes' where id=s.id;
 insert into public.research_feed_fetch_runs(project_id,feed_source_id,request_url_hash,created_by)values(p_project_id,s.id,s.configured_url_hash,auth.uid())returning * into r;return r;end$$;
create function public.complete_research_feed_fetch(p_project_id uuid,p_feed_source_id uuid,p_run_id uuid,p_status public.research_feed_run_status,p_feed_type public.research_feed_type,p_final_url text,p_http_status integer,p_response_bytes integer,p_etag text,p_last_modified text,p_items jsonb default '[]') returns public.research_feed_fetch_runs language plpgsql security definer set search_path='' as $$declare s public.research_feed_sources;r public.research_feed_fetch_runs;j jsonb;u uuid;c uuid;url_match uuid;content_match uuid;created_n int:=0;updated_n int:=0;dedup_n int:=0;skipped_n int:=0;seen_n int:=0;now_ts timestamptz:=clock_timestamp();begin
 if auth.uid() is null or not exists(select 1 from public.projects where id=p_project_id and owner_id=auth.uid()) then raise exception 'not_found' using errcode='P0002';end if;select * into s from public.research_feed_sources where project_id=p_project_id and id=p_feed_source_id for update;select * into r from public.research_feed_fetch_runs where project_id=p_project_id and feed_source_id=p_feed_source_id and id=p_run_id and status='RUNNING' for update;if s.id is null or r.id is null or s.fetch_lease_expires_at is null then raise exception 'FETCH_ALREADY_RUNNING';end if;
 if p_status='SUCCEEDED' then for j in select * from jsonb_array_elements(p_items) loop seen_n:=seen_n+1;url_match:=null;content_match:=null;select research_item_id into url_match from public.research_item_fingerprints where project_id=p_project_id and fingerprint_type='URL' and fingerprint_hash=j->>'url_hash';select research_item_id into content_match from public.research_item_fingerprints where project_id=p_project_id and fingerprint_type='CONTENT' and fingerprint_hash=j->>'content_hash';if url_match is not null and content_match is not null and url_match<>content_match then skipped_n:=skipped_n+1;continue;end if;u:=coalesce(url_match,content_match);if u is null then insert into public.research_items(project_id,canonical_url,title,summary_text,content_text,author_name,published_at,source_updated_at,language,categories,created_by)values(p_project_id,j->>'canonical_url',j->>'title',j->>'summary_text',j->>'content_text',j->>'author_name',(j->>'published_at')::timestamptz,(j->>'source_updated_at')::timestamptz,j->>'language',coalesce(array(select jsonb_array_elements_text(j->'categories')),'{}'),auth.uid())returning id into u;created_n:=created_n+1;else update public.research_items set last_seen_at=now_ts,updated_at=now_ts,canonical_url=coalesce(j->>'canonical_url',canonical_url),title=coalesce(j->>'title',title),summary_text=coalesce(j->>'summary_text',summary_text),content_text=coalesce(j->>'content_text',content_text),content_changed_at=case when content_match is null then now_ts else content_changed_at end where id=u and project_id=p_project_id;updated_n:=updated_n+1;dedup_n:=dedup_n+1;end if;
 if j->>'url_hash' is not null then insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'URL',j->>'url_hash')on conflict do nothing;end if;insert into public.research_item_fingerprints(project_id,research_item_id,fingerprint_type,fingerprint_hash)values(p_project_id,u,'CONTENT',j->>'content_hash')on conflict do nothing;
 insert into public.research_feed_item_observations(project_id,feed_source_id,research_item_id,fetch_run_id,external_item_id,observed_url,source_published_at)values(p_project_id,p_feed_source_id,u,p_run_id,j->>'external_id',j->>'canonical_url',(j->>'published_at')::timestamptz)on conflict(project_id,feed_source_id,research_item_id)do update set fetch_run_id=excluded.fetch_run_id,last_seen_at=now_ts,observation_count=public.research_feed_item_observations.observation_count+1,updated_at=now_ts;end loop;end if;
 update public.research_feed_fetch_runs set status=p_status,completed_at=now_ts,duration_ms=greatest(0,(extract(epoch from(now_ts-started_at))*1000)::int),final_url=left(p_final_url,4096),http_status=p_http_status,response_bytes=p_response_bytes,items_seen=seen_n,items_created=created_n,items_updated=updated_n,items_deduplicated=dedup_n,items_skipped=skipped_n where id=p_run_id returning * into r;
 update public.research_feed_sources set detected_feed_type=case when p_status='SUCCEEDED' then p_feed_type else detected_feed_type end,health_status='HEALTHY',last_checked_at=now_ts,last_success_at=now_ts,last_content_change_at=case when created_n+updated_n>0 then now_ts else last_content_change_at end,last_http_status=p_http_status,last_final_url=left(p_final_url,4096),etag=case when p_status='SUCCEEDED' then left(p_etag,512) else etag end,last_modified=case when p_status='SUCCEEDED' then left(p_last_modified,128) else last_modified end,consecutive_failures=0,next_eligible_fetch_at=now_ts+interval '60 seconds',last_error_code=null,last_error_message=null,fetch_lease_token=null,fetch_lease_expires_at=null,updated_at=now_ts where id=p_feed_source_id;return r;end$$;
create function public.fail_research_feed_fetch(p_project_id uuid,p_feed_source_id uuid,p_run_id uuid,p_error_code text,p_error_message text) returns void language plpgsql security definer set search_path='' as $$declare n int;begin if auth.uid() is null or not exists(select 1 from public.projects where id=p_project_id and owner_id=auth.uid()) then raise exception 'not_found' using errcode='P0002';end if;update public.research_feed_fetch_runs set status='FAILED',completed_at=clock_timestamp(),duration_ms=greatest(0,(extract(epoch from(clock_timestamp()-started_at))*1000)::int),error_code=left(p_error_code,64),error_message=left(p_error_message,500)where project_id=p_project_id and feed_source_id=p_feed_source_id and id=p_run_id and status='RUNNING';update public.research_feed_sources set last_checked_at=clock_timestamp(),consecutive_failures=consecutive_failures+1,health_status=case when consecutive_failures+1>=3 then 'ERROR'::public.research_feed_health else 'DEGRADED'::public.research_feed_health end,last_error_code=left(p_error_code,64),last_error_message=left(p_error_message,500),fetch_lease_token=null,fetch_lease_expires_at=null,next_eligible_fetch_at=clock_timestamp()+interval '60 seconds' where project_id=p_project_id and id=p_feed_source_id;end$$;

alter table public.research_feed_sources enable row level security;alter table public.research_feed_fetch_runs enable row level security;alter table public.research_items enable row level security;alter table public.research_item_fingerprints enable row level security;alter table public.research_feed_item_observations enable row level security;
do $$declare t text;begin foreach t in array array['research_feed_sources','research_feed_fetch_runs','research_items','research_item_fingerprints','research_feed_item_observations'] loop execute format('create policy %I on public.%I for select to authenticated using(public.project_is_owned(project_id))',t||'_select',t);end loop;end$$;
create policy research_feed_sources_insert on public.research_feed_sources for insert to authenticated with check(public.project_is_owned(project_id) and created_by=auth.uid());create policy research_feed_sources_update on public.research_feed_sources for update to authenticated using(public.project_is_owned(project_id)) with check(public.project_is_owned(project_id) and created_by=auth.uid());
revoke all on function public.claim_research_feed_fetch(uuid,uuid) from public,anon;revoke all on function public.complete_research_feed_fetch(uuid,uuid,uuid,public.research_feed_run_status,public.research_feed_type,text,integer,integer,text,text,jsonb) from public,anon;revoke all on function public.fail_research_feed_fetch(uuid,uuid,uuid,text,text) from public,anon;grant execute on function public.claim_research_feed_fetch(uuid,uuid),public.complete_research_feed_fetch(uuid,uuid,uuid,public.research_feed_run_status,public.research_feed_type,text,integer,integer,text,text,jsonb),public.fail_research_feed_fetch(uuid,uuid,uuid,text,text) to authenticated;
