-- Phase 2.2C.1: fixed ThreatFox connector and encrypted persistent credentials.
begin;
create table public.ioc_provider_credentials(
 id uuid primary key default gen_random_uuid(), owner_id uuid not null, provider_connection_id uuid not null,
 provider_key text not null check(provider_key='THREATFOX'), ciphertext_b64 text not null check(char_length(ciphertext_b64) between 4 and 2048),
 iv_b64 text not null check(char_length(iv_b64) between 16 and 32), auth_tag_b64 text not null check(char_length(auth_tag_b64) between 20 and 32),
 key_version smallint not null default 1 check(key_version between 1 and 32767), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), rotated_at timestamptz,
 unique(owner_id,provider_connection_id), foreign key(owner_id,provider_connection_id) references public.ioc_provider_connections(owner_id,id) on delete cascade
);
create table public.threatfox_connection_settings(
 owner_id uuid not null, provider_connection_id uuid not null, lookback_days integer not null default 1 check(lookback_days between 1 and 7),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,provider_connection_id),
 foreign key(owner_id,provider_connection_id) references public.ioc_provider_connections(owner_id,id) on delete cascade
);
create function public.configure_threatfox_connection(p_owner_id uuid,p_connection_id uuid,p_ciphertext_b64 text,p_iv_b64 text,p_auth_tag_b64 text,p_key_version smallint,p_lookback_days integer,p_scheduler_enabled boolean,p_sync_interval_minutes integer)
returns uuid language plpgsql security definer set search_path='' as $$begin
 if p_lookback_days not between 1 and 7 or p_sync_interval_minutes not between 30 and 1440 or char_length(p_ciphertext_b64)not between 4 and 2048 or char_length(p_iv_b64)not between 16 and 32 or char_length(p_auth_tag_b64)not between 20 and 32 or p_key_version not between 1 and 32767 or not exists(select 1 from auth.users where id=p_owner_id)then raise exception 'THREATFOX_CONFIGURATION_INVALID';end if;
 insert into public.ioc_provider_connections(id,owner_id,provider_key,display_name,enabled,scheduler_enabled,sync_interval_minutes,next_scheduled_sync_at,created_by,last_checked_at,health_status) values(p_connection_id,p_owner_id,'THREATFOX','ThreatFox Community API',true,p_scheduler_enabled,p_sync_interval_minutes,case when p_scheduler_enabled then now()+make_interval(mins=>p_sync_interval_minutes)end,p_owner_id,now(),'HEALTHY') on conflict(owner_id,provider_key)do update set enabled=true,scheduler_enabled=p_scheduler_enabled,sync_interval_minutes=p_sync_interval_minutes,next_scheduled_sync_at=case when p_scheduler_enabled then now()+make_interval(mins=>p_sync_interval_minutes)end,last_checked_at=now(),health_status='HEALTHY',last_error_code=null,last_error_message=null,updated_at=now() returning id into p_connection_id;
 if exists(select 1 from public.ioc_provider_connections where id=p_connection_id and(owner_id<>p_owner_id or provider_key<>'THREATFOX' or archived_at is not null))then raise exception 'CONNECTION_UNAVAILABLE';end if;
 insert into public.ioc_provider_credentials(owner_id,provider_connection_id,provider_key,ciphertext_b64,iv_b64,auth_tag_b64,key_version)values(p_owner_id,p_connection_id,'THREATFOX',p_ciphertext_b64,p_iv_b64,p_auth_tag_b64,p_key_version)on conflict(owner_id,provider_connection_id)do update set ciphertext_b64=excluded.ciphertext_b64,iv_b64=excluded.iv_b64,auth_tag_b64=excluded.auth_tag_b64,key_version=excluded.key_version,updated_at=now(),rotated_at=now();
 insert into public.threatfox_connection_settings(owner_id,provider_connection_id,lookback_days)values(p_owner_id,p_connection_id,p_lookback_days)on conflict(owner_id,provider_connection_id)do update set lookback_days=excluded.lookback_days,updated_at=now();return p_connection_id;end$$;
create function public.disconnect_threatfox_credential(p_owner_id uuid,p_connection_id uuid)returns boolean language plpgsql security definer set search_path='' as $$begin
 if not exists(select 1 from public.ioc_provider_connections where owner_id=p_owner_id and id=p_connection_id and provider_key='THREATFOX' and archived_at is null)then raise exception 'CONNECTION_UNAVAILABLE';end if;
 delete from public.ioc_provider_credentials where owner_id=p_owner_id and provider_connection_id=p_connection_id and provider_key='THREATFOX';update public.ioc_provider_connections set enabled=false,scheduler_enabled=false,next_scheduled_sync_at=null,health_status='UNKNOWN',updated_at=now()where owner_id=p_owner_id and id=p_connection_id;return true;end$$;
create function public.update_threatfox_settings(p_owner_id uuid,p_connection_id uuid,p_lookback_days integer,p_scheduler_enabled boolean,p_sync_interval_minutes integer)returns boolean language plpgsql security definer set search_path='' as $$begin
 if p_lookback_days not between 1 and 7 or p_sync_interval_minutes not between 30 and 1440 or not exists(select 1 from public.ioc_provider_connections where owner_id=p_owner_id and id=p_connection_id and provider_key='THREATFOX'and archived_at is null)then raise exception 'THREATFOX_CONFIGURATION_INVALID';end if;
 update public.threatfox_connection_settings set lookback_days=p_lookback_days,updated_at=now()where owner_id=p_owner_id and provider_connection_id=p_connection_id;update public.ioc_provider_connections set scheduler_enabled=p_scheduler_enabled,sync_interval_minutes=p_sync_interval_minutes,next_scheduled_sync_at=case when p_scheduler_enabled then now()+make_interval(mins=>p_sync_interval_minutes)end,updated_at=now()where owner_id=p_owner_id and id=p_connection_id;return true;end$$;
create or replace function public.fail_ioc_ingestion(p_owner_id uuid,p_connection_id uuid,p_run_id uuid,p_lease_token uuid,p_error_code text,p_error_message text)returns public.ioc_ingestion_runs language plpgsql security definer set search_path='' as $$declare r public.ioc_ingestion_runs;c public.ioc_provider_connections;delay_minutes integer;begin
 update public.ioc_ingestion_runs ir set status='FAILED',completed_at=now(),error_code=left(p_error_code,100),error_message=left(p_error_message,500)where id=p_run_id and owner_id=p_owner_id and provider_connection_id=p_connection_id and status='RUNNING'and lease_token_hash=encode(public.digest(p_lease_token::text,'sha256'),'hex')returning * into r;if r.id is null then raise exception 'STALE_INGESTION_LEASE';end if;
 select * into c from public.ioc_provider_connections where id=p_connection_id and owner_id=p_owner_id for update;delay_minutes:=least(1440,case when p_error_code='THREATFOX_RATE_LIMITED'then 30 else greatest(30,power(2,least(c.consecutive_failures,10))::integer*15)end);
 update public.ioc_provider_connections set lease_token_hash=null,lease_run_id=null,lease_expires_at=null,health_status=case when p_error_code='THREATFOX_AUTH_FAILED'then'FAILED'::public.ioc_connection_health else'DEGRADED'::public.ioc_connection_health end,consecutive_failures=consecutive_failures+1,last_error_code=r.error_code,last_error_message=r.error_message,scheduler_enabled=case when p_error_code='THREATFOX_AUTH_FAILED'then false else scheduler_enabled end,next_scheduled_sync_at=case when p_error_code='THREATFOX_AUTH_FAILED'then null else now()+make_interval(mins=>delay_minutes)end,updated_at=now()where id=p_connection_id and owner_id=p_owner_id and lease_run_id=p_run_id and lease_token_hash=r.lease_token_hash;if not found then raise exception 'STALE_INGESTION_LEASE';end if;return r;end$$;
alter table public.ioc_provider_credentials enable row level security;alter table public.threatfox_connection_settings enable row level security;
create policy threatfox_settings_read on public.threatfox_connection_settings for select to authenticated using(owner_id=auth.uid());
revoke all on table public.ioc_provider_credentials from public,anon,authenticated;grant select,insert,update,delete on table public.ioc_provider_credentials to service_role;
revoke all on function public.configure_threatfox_connection(uuid,uuid,text,text,text,smallint,integer,boolean,integer),public.disconnect_threatfox_credential(uuid,uuid),public.update_threatfox_settings(uuid,uuid,integer,boolean,integer)from public,anon,authenticated;
grant execute on function public.configure_threatfox_connection(uuid,uuid,text,text,text,smallint,integer,boolean,integer),public.disconnect_threatfox_credential(uuid,uuid),public.update_threatfox_settings(uuid,uuid,integer,boolean,integer)to service_role;
do $$begin
 if has_table_privilege('authenticated','public.ioc_provider_credentials','SELECT')or has_table_privilege('authenticated','public.ioc_provider_credentials','INSERT')or has_table_privilege('authenticated','public.ioc_provider_credentials','UPDATE')or has_table_privilege('authenticated','public.ioc_provider_credentials','DELETE')then raise exception 'credential ACL broadened';end if;
 if has_function_privilege('authenticated','public.configure_threatfox_connection(uuid,uuid,text,text,text,smallint,integer,boolean,integer)','EXECUTE')then raise exception 'trusted ThreatFox ACL broadened';end if;
end$$;
commit;
