-- Phase 3 CTI entities and explicit relationships
create type public.indicator_type as enum ('IP','DOMAIN','URL','HASH','EMAIL','FILE','REGISTRY');
create type public.confidence_level as enum ('LOW','MEDIUM','HIGH');
create type public.cve_severity as enum ('LOW','MEDIUM','HIGH','CRITICAL');
create type public.exploit_status as enum ('NONE','POC','WEAPONIZED','ACTIVE_EXPLOITATION');

create or replace function public.normalize_indicator_value(v text, t public.indicator_type) returns text language sql immutable as $$
  select case when t in ('DOMAIN','EMAIL') then lower(trim(v)) when t='URL' then trim(v) else trim(v) end;
$$;

create table public.threat_actors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, aliases text[] not null default '{}', country text, motivations text[] not null default '{}', description text not null default '', known_ttps text not null default '', references text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id), unique(project_id, name));
create table public.campaigns (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, description text not null default '', start_date date, end_date date, targets text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint campaigns_date_order check (start_date is null or end_date is null or end_date >= start_date), unique(project_id,id), unique(project_id,name));
create table public.indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, value text not null, normalized_value text generated always as (public.normalize_indicator_value(value,type)) stored, type public.indicator_type not null, confidence public.confidence_level not null default 'MEDIUM', source text, tags text[] not null default '{}', first_seen timestamptz, last_seen timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint indicators_seen_order check (first_seen is null or last_seen is null or last_seen >= first_seen), unique(project_id,id), unique(project_id,type,normalized_value));
create table public.malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, family text, hashes jsonb not null default '{}'::jsonb, description text not null default '', behavior text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id), unique(project_id,name));
create table public.cves (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, cve_id text not null, severity public.cve_severity not null, description text not null default '', affected_product text not null default '', exploit_status public.exploit_status not null default 'NONE', references text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint cves_identifier check (cve_id ~ '^CVE-[0-9]{4}-[0-9]{4,}$'), unique(project_id,id), unique(project_id,cve_id));
create table public.mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, technique_id text not null, technique_name text not null, tactic text not null, description text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint mitre_technique_identifier check (technique_id ~ '^T[0-9]{4}(\.[0-9]{3})?$'), unique(project_id,id), unique(project_id,technique_id));

create index on public.threat_actors(project_id, name); create index on public.threat_actors using gin(aliases); create index on public.threat_actors using gin(motivations); create index on public.campaigns(project_id, start_date, end_date); create index on public.indicators(project_id,type,confidence); create index on public.indicators using gin(tags); create index on public.malware(project_id,family,name); create index on public.cves(project_id,severity,exploit_status); create index on public.mitre_techniques(project_id,tactic,technique_id);

create table public.campaign_threat_actors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, threat_actor_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,threat_actor_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade);
create table public.threat_actor_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,malware_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.threat_actor_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,indicator_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.campaign_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,malware_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.campaign_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,indicator_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.malware_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, malware_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,malware_id,indicator_id), foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.cve_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, cve_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,cve_id,malware_id), foreign key(project_id,cve_id) references public.cves(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.threat_actor_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,mitre_technique_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);
create table public.campaign_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,mitre_technique_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);
create table public.malware_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, malware_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,malware_id,mitre_technique_id), foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['threat_actors','campaigns','indicators','malware','cves','mitre_techniques'] LOOP EXECUTE format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); END LOOP; FOREACH t IN ARRAY ARRAY['threat_actors','campaigns','indicators','malware','cves','mitre_techniques','campaign_threat_actors','threat_actor_malware','threat_actor_indicators','campaign_malware','campaign_indicators','malware_indicators','cve_malware','threat_actor_mitre_techniques','campaign_mitre_techniques','malware_mitre_techniques'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('create policy %I_select on public.%I for select using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_insert on public.%I for insert with check (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_update on public.%I for update using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())) with check (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_delete on public.%I for delete using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); END LOOP; END $$;
