-- Phase 3 CTI entities, explicit relationships, and atomic relationship replacement
create type public.indicator_type as enum ('IP','DOMAIN','URL','HASH','EMAIL','FILE','REGISTRY');
create type public.confidence_level as enum ('LOW','MEDIUM','HIGH');
create type public.cve_severity as enum ('LOW','MEDIUM','HIGH','CRITICAL');
create type public.exploit_status as enum ('NONE','POC','WEAPONIZED','ACTIVE_EXPLOITATION');

create or replace function public.normalize_indicator_value(v text, t public.indicator_type) returns text
language sql immutable set search_path = public as $$
  select case when t in ('DOMAIN','EMAIL','HASH') then lower(trim(v)) when t='URL' then trim(v) else trim(v) end;
$$;
revoke all on function public.normalize_indicator_value(text, public.indicator_type) from public, anon;
grant execute on function public.normalize_indicator_value(text, public.indicator_type) to authenticated;

create table public.threat_actors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, aliases text[] not null default '{}', country text, motivations text[] not null default '{}', description text not null default '', known_ttps text not null default '', "references" text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id), unique(project_id, name));
create table public.campaigns (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, description text not null default '', start_date date, end_date date, targets text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint campaigns_date_order check (start_date is null or end_date is null or end_date >= start_date), unique(project_id,id), unique(project_id,name));
create table public.indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, value text not null, normalized_value text generated always as (public.normalize_indicator_value(value,type)) stored, type public.indicator_type not null, confidence public.confidence_level not null default 'MEDIUM', source text, tags text[] not null default '{}', first_seen timestamptz, last_seen timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint indicators_seen_order check (first_seen is null or last_seen is null or last_seen >= first_seen), unique(project_id,id), unique(project_id,type,normalized_value));
create table public.malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, name text not null, family text, hashes jsonb not null default '{}'::jsonb, description text not null default '', behavior text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,id), unique(project_id,name));
create table public.cves (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, cve_id text not null, severity public.cve_severity not null, description text not null default '', affected_product text not null default '', exploit_status public.exploit_status not null default 'NONE', "references" text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint cves_identifier check (cve_id ~ '^CVE-[0-9]{4}-[0-9]{4,}$'), unique(project_id,id), unique(project_id,cve_id));
create table public.mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, technique_id text not null, technique_name text not null, tactic text not null, description text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint mitre_technique_identifier check (technique_id ~ '^T[0-9]{4}(\.[0-9]{3})?$'), unique(project_id,id), unique(project_id,technique_id));

create index threat_actors_project_name_idx on public.threat_actors(project_id, name, id); create index threat_actors_aliases_idx on public.threat_actors using gin(aliases); create index threat_actors_motivations_idx on public.threat_actors using gin(motivations);
create index campaigns_project_dates_idx on public.campaigns(project_id, start_date, end_date, id); create index indicators_project_type_confidence_idx on public.indicators(project_id,type,confidence,id); create index indicators_tags_idx on public.indicators using gin(tags); create index malware_project_family_name_idx on public.malware(project_id,family,name,id); create index cves_project_severity_exploit_idx on public.cves(project_id,severity,exploit_status,id); create index mitre_project_tactic_technique_idx on public.mitre_techniques(project_id,tactic,technique_id,id);

create table public.campaign_threat_actors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, threat_actor_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,threat_actor_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade);
create table public.threat_actor_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,malware_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.threat_actor_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,indicator_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.campaign_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,malware_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.campaign_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,indicator_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.malware_indicators (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, malware_id uuid not null, indicator_id uuid not null, created_at timestamptz not null default now(), unique(project_id,malware_id,indicator_id), foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade, foreign key(project_id,indicator_id) references public.indicators(project_id,id) on delete cascade);
create table public.cve_malware (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, cve_id uuid not null, malware_id uuid not null, created_at timestamptz not null default now(), unique(project_id,cve_id,malware_id), foreign key(project_id,cve_id) references public.cves(project_id,id) on delete cascade, foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade);
create table public.threat_actor_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, threat_actor_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,threat_actor_id,mitre_technique_id), foreign key(project_id,threat_actor_id) references public.threat_actors(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);
create table public.campaign_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, campaign_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,campaign_id,mitre_technique_id), foreign key(project_id,campaign_id) references public.campaigns(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);
create table public.malware_mitre_techniques (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, malware_id uuid not null, mitre_technique_id uuid not null, created_at timestamptz not null default now(), unique(project_id,malware_id,mitre_technique_id), foreign key(project_id,malware_id) references public.malware(project_id,id) on delete cascade, foreign key(project_id,mitre_technique_id) references public.mitre_techniques(project_id,id) on delete cascade);

create index campaign_threat_actors_actor_idx on public.campaign_threat_actors(project_id, threat_actor_id, campaign_id); create index threat_actor_malware_malware_idx on public.threat_actor_malware(project_id, malware_id, threat_actor_id); create index threat_actor_indicators_indicator_idx on public.threat_actor_indicators(project_id, indicator_id, threat_actor_id); create index campaign_malware_malware_idx on public.campaign_malware(project_id, malware_id, campaign_id); create index campaign_indicators_indicator_idx on public.campaign_indicators(project_id, indicator_id, campaign_id); create index malware_indicators_indicator_idx on public.malware_indicators(project_id, indicator_id, malware_id); create index cve_malware_malware_idx on public.cve_malware(project_id, malware_id, cve_id); create index threat_actor_mitre_techniques_mitre_idx on public.threat_actor_mitre_techniques(project_id, mitre_technique_id, threat_actor_id); create index campaign_mitre_techniques_mitre_idx on public.campaign_mitre_techniques(project_id, mitre_technique_id, campaign_id); create index malware_mitre_techniques_mitre_idx on public.malware_mitre_techniques(project_id, mitre_technique_id, malware_id);

create or replace function public.replace_cti_relationships(p_project_id uuid, p_entity_type text, p_entity_id uuid, p_threat_actor_ids uuid[] default '{}', p_campaign_ids uuid[] default '{}', p_indicator_ids uuid[] default '{}', p_malware_ids uuid[] default '{}', p_cve_ids uuid[] default '{}', p_mitre_technique_ids uuid[] default '{}') returns jsonb
language plpgsql security invoker set search_path = public as $$
declare ok boolean; begin
  if auth.uid() is null then return jsonb_build_object('ok', false, 'error', 'not_authorized'); end if;
  if not exists (select 1 from public.projects p where p.id = p_project_id and p.owner_id = auth.uid()) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  if p_entity_type not in ('actors','campaigns','indicators','malware','cves','mitre') then return jsonb_build_object('ok', false, 'error', 'invalid_type'); end if;
  if p_entity_type='actors' then
    if not exists(select 1 from public.threat_actors where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_malware_ids) x where not exists(select 1 from public.malware where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_indicator_ids) x where not exists(select 1 from public.indicators where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_mitre_technique_ids) x where not exists(select 1 from public.mitre_techniques where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.threat_actor_malware where project_id=p_project_id and threat_actor_id=p_entity_id; insert into public.threat_actor_malware(project_id, threat_actor_id, malware_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_malware_ids) x) s;
    delete from public.threat_actor_indicators where project_id=p_project_id and threat_actor_id=p_entity_id; insert into public.threat_actor_indicators(project_id, threat_actor_id, indicator_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_indicator_ids) x) s;
    delete from public.threat_actor_mitre_techniques where project_id=p_project_id and threat_actor_id=p_entity_id; insert into public.threat_actor_mitre_techniques(project_id, threat_actor_id, mitre_technique_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_mitre_technique_ids) x) s;
  elsif p_entity_type='campaigns' then
    if not exists(select 1 from public.campaigns where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_threat_actor_ids) x where not exists(select 1 from public.threat_actors where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_malware_ids) x where not exists(select 1 from public.malware where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_indicator_ids) x where not exists(select 1 from public.indicators where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_mitre_technique_ids) x where not exists(select 1 from public.mitre_techniques where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.campaign_threat_actors where project_id=p_project_id and campaign_id=p_entity_id; insert into public.campaign_threat_actors(project_id,campaign_id,threat_actor_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_threat_actor_ids) x) s;
    delete from public.campaign_malware where project_id=p_project_id and campaign_id=p_entity_id; insert into public.campaign_malware(project_id,campaign_id,malware_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_malware_ids) x) s;
    delete from public.campaign_indicators where project_id=p_project_id and campaign_id=p_entity_id; insert into public.campaign_indicators(project_id,campaign_id,indicator_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_indicator_ids) x) s;
    delete from public.campaign_mitre_techniques where project_id=p_project_id and campaign_id=p_entity_id; insert into public.campaign_mitre_techniques(project_id,campaign_id,mitre_technique_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_mitre_technique_ids) x) s;
  elsif p_entity_type='indicators' then
    if not exists(select 1 from public.indicators where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_threat_actor_ids) x where not exists(select 1 from public.threat_actors where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_campaign_ids) x where not exists(select 1 from public.campaigns where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_malware_ids) x where not exists(select 1 from public.malware where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.threat_actor_indicators where project_id=p_project_id and indicator_id=p_entity_id; insert into public.threat_actor_indicators(project_id,indicator_id,threat_actor_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_threat_actor_ids) x) s;
    delete from public.campaign_indicators where project_id=p_project_id and indicator_id=p_entity_id; insert into public.campaign_indicators(project_id,indicator_id,campaign_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_campaign_ids) x) s;
    delete from public.malware_indicators where project_id=p_project_id and indicator_id=p_entity_id; insert into public.malware_indicators(project_id,indicator_id,malware_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_malware_ids) x) s;
  elsif p_entity_type='malware' then
    if not exists(select 1 from public.malware where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_threat_actor_ids) x where not exists(select 1 from public.threat_actors where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_campaign_ids) x where not exists(select 1 from public.campaigns where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_indicator_ids) x where not exists(select 1 from public.indicators where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_cve_ids) x where not exists(select 1 from public.cves where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_mitre_technique_ids) x where not exists(select 1 from public.mitre_techniques where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.threat_actor_malware where project_id=p_project_id and malware_id=p_entity_id; insert into public.threat_actor_malware(project_id,malware_id,threat_actor_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_threat_actor_ids) x) s;
    delete from public.campaign_malware where project_id=p_project_id and malware_id=p_entity_id; insert into public.campaign_malware(project_id,malware_id,campaign_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_campaign_ids) x) s;
    delete from public.malware_indicators where project_id=p_project_id and malware_id=p_entity_id; insert into public.malware_indicators(project_id,malware_id,indicator_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_indicator_ids) x) s;
    delete from public.cve_malware where project_id=p_project_id and malware_id=p_entity_id; insert into public.cve_malware(project_id,malware_id,cve_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_cve_ids) x) s;
    delete from public.malware_mitre_techniques where project_id=p_project_id and malware_id=p_entity_id; insert into public.malware_mitre_techniques(project_id,malware_id,mitre_technique_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_mitre_technique_ids) x) s;
  elsif p_entity_type='cves' then
    if not exists(select 1 from public.cves where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_malware_ids) x where not exists(select 1 from public.malware where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.cve_malware where project_id=p_project_id and cve_id=p_entity_id; insert into public.cve_malware(project_id,cve_id,malware_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_malware_ids) x) s;
  else
    if not exists(select 1 from public.mitre_techniques where project_id=p_project_id and id=p_entity_id) then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
    if exists(select 1 from unnest(p_threat_actor_ids) x where not exists(select 1 from public.threat_actors where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_campaign_ids) x where not exists(select 1 from public.campaigns where project_id=p_project_id and id=x)) or exists(select 1 from unnest(p_malware_ids) x where not exists(select 1 from public.malware where project_id=p_project_id and id=x)) then return jsonb_build_object('ok', false, 'error', 'invalid_relationship'); end if;
    delete from public.threat_actor_mitre_techniques where project_id=p_project_id and mitre_technique_id=p_entity_id; insert into public.threat_actor_mitre_techniques(project_id,mitre_technique_id,threat_actor_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_threat_actor_ids) x) s;
    delete from public.campaign_mitre_techniques where project_id=p_project_id and mitre_technique_id=p_entity_id; insert into public.campaign_mitre_techniques(project_id,mitre_technique_id,campaign_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_campaign_ids) x) s;
    delete from public.malware_mitre_techniques where project_id=p_project_id and mitre_technique_id=p_entity_id; insert into public.malware_mitre_techniques(project_id,mitre_technique_id,malware_id) select p_project_id,p_entity_id,x from (select distinct unnest(p_malware_ids) x) s;
  end if;
  return jsonb_build_object('ok', true);
exception when others then
  raise;
end $$;
revoke all on function public.replace_cti_relationships(uuid,text,uuid,uuid[],uuid[],uuid[],uuid[],uuid[],uuid[]) from public, anon;
grant execute on function public.replace_cti_relationships(uuid,text,uuid,uuid[],uuid[],uuid[],uuid[],uuid[],uuid[]) to authenticated;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['threat_actors','campaigns','indicators','malware','cves','mitre_techniques'] LOOP EXECUTE format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); END LOOP; FOREACH t IN ARRAY ARRAY['threat_actors','campaigns','indicators','malware','cves','mitre_techniques','campaign_threat_actors','threat_actor_malware','threat_actor_indicators','campaign_malware','campaign_indicators','malware_indicators','cve_malware','threat_actor_mitre_techniques','campaign_mitre_techniques','malware_mitre_techniques'] LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('create policy %I_select on public.%I for select to authenticated using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_insert on public.%I for insert to authenticated with check (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_update on public.%I for update to authenticated using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid())) with check (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); EXECUTE format('create policy %I_delete on public.%I for delete to authenticated using (exists (select 1 from public.projects p where p.id = project_id and p.owner_id = auth.uid()))',t,t); END LOOP; END $$;
