import type { SupabaseClient } from "@supabase/supabase-js";
export async function listStandaloneIntelProfiles(supabase:SupabaseClient){return supabase.from("intel_profiles").select("*, intel_profile_items(count)").eq("kind","STANDALONE").order("updated_at",{ascending:false});}
export async function listInvestigationIntelProfiles(supabase:SupabaseClient){return supabase.from("intel_profiles").select("*, projects(name), intel_profile_items(count)").eq("kind","INVESTIGATION").order("updated_at",{ascending:false});}
export async function getIntelProfile(supabase:SupabaseClient,id:string){return supabase.from("intel_profiles").select("*, projects(name)").eq("id",id).maybeSingle();}
export async function getInvestigationIntelProfile(supabase:SupabaseClient,projectId:string){return supabase.from("intel_profiles").select("*, projects(name)").eq("kind","INVESTIGATION").eq("project_id",projectId).maybeSingle();}
export async function listIntelProfileItems(supabase:SupabaseClient,profileId:string){return supabase.from("intel_profile_items").select("*").eq("profile_id",profileId).order("updated_at",{ascending:false});}
export async function listIntelProfileAudit(supabase:SupabaseClient,profileId:string){return supabase.from("intel_profile_audit_events").select("*").eq("profile_id",profileId).order("created_at",{ascending:false}).limit(50);}
export async function listGlobalTechnicalAgenda(supabase:SupabaseClient,page=0){return supabase.from("technical_signal_global_priorities").select("*, technical_signals(title,signal_type,lifecycle,first_seen_at,last_seen_at,severity)",{count:"exact"}).order("internal_score",{ascending:false}).order("evaluated_at",{ascending:false}).range(page*25,page*25+24);}
export async function listIntelProfileMatches(supabase:SupabaseClient,profileId:string,page=0){return supabase.from("technical_signal_profile_matches").select("*, technical_signals(title,signal_type,first_seen_at,last_seen_at), technical_signal_global_priorities(priority,reason_codes,source_systems)",{count:"exact"}).eq("profile_id",profileId).eq("is_active",true).order("internal_score",{ascending:false}).order("last_matched_at",{ascending:false}).range(page*25,page*25+24);}
